// GCP instance prices for region key: europe_southwest1 (updated 2026-08-30)
// Auto-generated by tools/split-data.js — do not edit by hand
// Specs for these types live in js/gcp/gcp-data.js as GCP_SPECS.compute
window.europe_southwest1 = {
  "a2-highgpu-1g": {
    hourlyPrice: 0.87258286,
    windowsHourlyPrice: 1.42458286,
  },
  "a2-highgpu-2g": {
    hourlyPrice: 1.74516572,
    windowsHourlyPrice: 2.84916572,
  },
  "a2-highgpu-4g": {
    hourlyPrice: 3.49033144,
    windowsHourlyPrice: 5.69833144,
  },
  "a2-highgpu-8g": {
    hourlyPrice: 6.98066288,
    windowsHourlyPrice: 11.39666288,
  },
  "a2-megagpu-16g": {
    hourlyPrice: 10.38043168,
    windowsHourlyPrice: 14.79643168,
  },
  "a2-ultragpu-1g": {
    hourlyPrice: 1.29755396,
    windowsHourlyPrice: 1.84955396,
  },
  "a2-ultragpu-2g": {
    hourlyPrice: 2.59510792,
    windowsHourlyPrice: 3.69910792,
  },
  "a2-ultragpu-4g": {
    hourlyPrice: 5.19021584,
    windowsHourlyPrice: 7.39821584,
  },
  "a2-ultragpu-8g": {
    hourlyPrice: 10.38043168,
    windowsHourlyPrice: 14.79643168,
  },
  "a3-edgegpu-8g": {
    hourlyPrice: 11.16286912,
    windowsHourlyPrice: 20.73086912,
  },
  "a3-edgegpu-8g-nolssd": {
    hourlyPrice: 11.16286912,
    windowsHourlyPrice: 20.73086912,
  },
  "a3-highgpu-1g": {
    hourlyPrice: 1.39535864,
    windowsHourlyPrice: 2.59135864,
  },
  "a3-highgpu-2g": {
    hourlyPrice: 2.79071728,
    windowsHourlyPrice: 5.18271728,
  },
  "a3-highgpu-4g": {
    hourlyPrice: 5.58143456,
    windowsHourlyPrice: 10.36543456,
  },
  "a3-highgpu-8g": {
    hourlyPrice: 11.16286912,
    windowsHourlyPrice: 20.73086912,
  },
  "a3-megagpu-8g": {
    hourlyPrice: 11.16286912,
    windowsHourlyPrice: 20.73086912,
  },
  "a3-ultragpu-8g": {
    hourlyPrice: 14.47387136,
    windowsHourlyPrice: 24.77787136,
  },
  "a3-ultragpu-8g-nolssd": {
    hourlyPrice: 14.47387136,
    windowsHourlyPrice: 24.77787136,
  },
  "c2-standard-16": {
    hourlyPrice: 0.98557376,
    windowsHourlyPrice: 1.72157376,
  },
  "c2-standard-30": {
    hourlyPrice: 1.8479508,
    windowsHourlyPrice: 3.2279508,
  },
  "c2-standard-4": {
    hourlyPrice: 0.24639344,
    windowsHourlyPrice: 0.43039344,
  },
  "c2-standard-60": {
    hourlyPrice: 3.6959016,
    windowsHourlyPrice: 6.4559016,
  },
  "c2-standard-8": {
    hourlyPrice: 0.49278688,
    windowsHourlyPrice: 0.86078688,
  },
  "c2d-highcpu-112": {
    hourlyPrice: 4.95348896,
    windowsHourlyPrice: 10.10548896,
  },
  "c2d-highcpu-16": {
    hourlyPrice: 0.70764128,
    windowsHourlyPrice: 1.44364128,
  },
  "c2d-highcpu-2": {
    hourlyPrice: 0.08845516,
    windowsHourlyPrice: 0.18045516,
  },
  "c2d-highcpu-32": {
    hourlyPrice: 1.41528256,
    windowsHourlyPrice: 2.88728256,
  },
  "c2d-highcpu-4": {
    hourlyPrice: 0.17691032,
    windowsHourlyPrice: 0.36091032,
  },
  "c2d-highcpu-56": {
    hourlyPrice: 2.47674448,
    windowsHourlyPrice: 5.05274448,
  },
  "c2d-highcpu-8": {
    hourlyPrice: 0.35382064,
    windowsHourlyPrice: 0.72182064,
  },
  "c2d-highmem-112": {
    hourlyPrice: 8.0928176,
    windowsHourlyPrice: 13.2448176,
  },
  "c2d-highmem-16": {
    hourlyPrice: 1.1561168,
    windowsHourlyPrice: 1.8921168,
  },
  "c2d-highmem-2": {
    hourlyPrice: 0.1445146,
    windowsHourlyPrice: 0.2365146,
  },
  "c2d-highmem-32": {
    hourlyPrice: 2.3122336,
    windowsHourlyPrice: 3.7842336,
  },
  "c2d-highmem-4": {
    hourlyPrice: 0.2890292,
    windowsHourlyPrice: 0.4730292,
  },
  "c2d-highmem-56": {
    hourlyPrice: 4.0464088,
    windowsHourlyPrice: 6.6224088,
  },
  "c2d-highmem-8": {
    hourlyPrice: 0.5780584,
    windowsHourlyPrice: 0.9460584,
  },
  "c2d-standard-112": {
    hourlyPrice: 5.99993184,
    windowsHourlyPrice: 11.15193184,
  },
  "c2d-standard-16": {
    hourlyPrice: 0.85713312,
    windowsHourlyPrice: 1.59313312,
  },
  "c2d-standard-2": {
    hourlyPrice: 0.10714164,
    windowsHourlyPrice: 0.19914164,
  },
  "c2d-standard-32": {
    hourlyPrice: 1.71426624,
    windowsHourlyPrice: 3.18626624,
  },
  "c2d-standard-4": {
    hourlyPrice: 0.21428328,
    windowsHourlyPrice: 0.39828328,
  },
  "c2d-standard-56": {
    hourlyPrice: 2.99996592,
    windowsHourlyPrice: 5.57596592,
  },
  "c2d-standard-8": {
    hourlyPrice: 0.42856656,
    windowsHourlyPrice: 0.79656656,
  },
  "c3-highcpu-176": {
    hourlyPrice: 8.83179968,
    windowsHourlyPrice: 16.92779968,
  },
  "c3-highcpu-192-metal": {
    hourlyPrice: 10.22948608,
    windowsHourlyPrice: 19.06148608,
  },
  "c3-highcpu-22": {
    hourlyPrice: 1.10397496,
    windowsHourlyPrice: 2.11597496,
  },
  "c3-highcpu-4": {
    hourlyPrice: 0.20072272,
    windowsHourlyPrice: 0.38472272,
  },
  "c3-highcpu-44": {
    hourlyPrice: 2.20794992,
    windowsHourlyPrice: 4.23194992,
  },
  "c3-highcpu-8": {
    hourlyPrice: 0.40144544,
    windowsHourlyPrice: 0.76944544,
  },
  "c3-highcpu-88": {
    hourlyPrice: 4.41589984,
    windowsHourlyPrice: 8.46389984,
  },
  "c3-highmem-176": {
    hourlyPrice: 13.73886272,
    windowsHourlyPrice: 21.83486272,
  },
  "c3-highmem-192-metal": {
    hourlyPrice: 14.98785024,
    windowsHourlyPrice: 23.81985024,
  },
  "c3-highmem-22": {
    hourlyPrice: 1.71735784,
    windowsHourlyPrice: 2.72935784,
  },
  "c3-highmem-4": {
    hourlyPrice: 0.31224688,
    windowsHourlyPrice: 0.49624688,
  },
  "c3-highmem-44": {
    hourlyPrice: 3.43471568,
    windowsHourlyPrice: 5.45871568,
  },
  "c3-highmem-8": {
    hourlyPrice: 0.62449376,
    windowsHourlyPrice: 0.99249376,
  },
  "c3-highmem-88": {
    hourlyPrice: 6.86943136,
    windowsHourlyPrice: 10.91743136,
  },
  "c3-standard-176": {
    hourlyPrice: 10.46748736,
    windowsHourlyPrice: 18.56348736,
  },
  "c3-standard-176-lssd": {
    hourlyPrice: 10.46748736,
    windowsHourlyPrice: 18.56348736,
  },
  "c3-standard-192-metal": {
    hourlyPrice: 11.41907712,
    windowsHourlyPrice: 20.25107712,
  },
  "c3-standard-22": {
    hourlyPrice: 1.30843592,
    windowsHourlyPrice: 2.32043592,
  },
  "c3-standard-22-lssd": {
    hourlyPrice: 1.30843592,
    windowsHourlyPrice: 2.32043592,
  },
  "c3-standard-4": {
    hourlyPrice: 0.23789744,
    windowsHourlyPrice: 0.42189744,
  },
  "c3-standard-4-lssd": {
    hourlyPrice: 0.23789744,
    windowsHourlyPrice: 0.42189744,
  },
  "c3-standard-44": {
    hourlyPrice: 2.61687184,
    windowsHourlyPrice: 4.64087184,
  },
  "c3-standard-44-lssd": {
    hourlyPrice: 2.61687184,
    windowsHourlyPrice: 4.64087184,
  },
  "c3-standard-8": {
    hourlyPrice: 0.47579488,
    windowsHourlyPrice: 0.84379488,
  },
  "c3-standard-8-lssd": {
    hourlyPrice: 0.47579488,
    windowsHourlyPrice: 0.84379488,
  },
  "c3-standard-88": {
    hourlyPrice: 5.23374368,
    windowsHourlyPrice: 9.28174368,
  },
  "c3-standard-88-lssd": {
    hourlyPrice: 5.23374368,
    windowsHourlyPrice: 9.28174368,
  },
  "c3d-highcpu-16": {
    hourlyPrice: 0.70764128,
    windowsHourlyPrice: 1.44364128,
  },
  "c3d-highcpu-180": {
    hourlyPrice: 7.93293468,
    windowsHourlyPrice: 16.21293468,
  },
  "c3d-highcpu-30": {
    hourlyPrice: 1.32215578,
    windowsHourlyPrice: 2.70215578,
  },
  "c3d-highcpu-360": {
    hourlyPrice: 15.86586936,
    windowsHourlyPrice: 32.42586936,
  },
  "c3d-highcpu-4": {
    hourlyPrice: 0.17691032,
    windowsHourlyPrice: 0.36091032,
  },
  "c3d-highcpu-60": {
    hourlyPrice: 2.64431156,
    windowsHourlyPrice: 5.40431156,
  },
  "c3d-highcpu-8": {
    hourlyPrice: 0.35382064,
    windowsHourlyPrice: 0.72182064,
  },
  "c3d-highcpu-90": {
    hourlyPrice: 3.96646734,
    windowsHourlyPrice: 8.10646734,
  },
  "c3d-highmem-16": {
    hourlyPrice: 1.1561168,
    windowsHourlyPrice: 1.8921168,
  },
  "c3d-highmem-16-lssd": {
    hourlyPrice: 1.1561168,
    windowsHourlyPrice: 1.8921168,
  },
  "c3d-highmem-180": {
    hourlyPrice: 13.006314,
    windowsHourlyPrice: 21.286314,
  },
  "c3d-highmem-180-lssd": {
    hourlyPrice: 13.006314,
    windowsHourlyPrice: 21.286314,
  },
  "c3d-highmem-30": {
    hourlyPrice: 2.167719,
    windowsHourlyPrice: 3.547719,
  },
  "c3d-highmem-30-lssd": {
    hourlyPrice: 2.167719,
    windowsHourlyPrice: 3.547719,
  },
  "c3d-highmem-360": {
    hourlyPrice: 26.012628,
    windowsHourlyPrice: 42.572628,
  },
  "c3d-highmem-360-lssd": {
    hourlyPrice: 26.012628,
    windowsHourlyPrice: 42.572628,
  },
  "c3d-highmem-4": {
    hourlyPrice: 0.2890292,
    windowsHourlyPrice: 0.4730292,
  },
  "c3d-highmem-60": {
    hourlyPrice: 4.335438,
    windowsHourlyPrice: 7.095438,
  },
  "c3d-highmem-60-lssd": {
    hourlyPrice: 4.335438,
    windowsHourlyPrice: 7.095438,
  },
  "c3d-highmem-8": {
    hourlyPrice: 0.5780584,
    windowsHourlyPrice: 0.9460584,
  },
  "c3d-highmem-8-lssd": {
    hourlyPrice: 0.5780584,
    windowsHourlyPrice: 0.9460584,
  },
  "c3d-highmem-90": {
    hourlyPrice: 6.503157,
    windowsHourlyPrice: 10.643157,
  },
  "c3d-highmem-90-lssd": {
    hourlyPrice: 6.503157,
    windowsHourlyPrice: 10.643157,
  },
  "c3d-standard-16": {
    hourlyPrice: 0.85713312,
    windowsHourlyPrice: 1.59313312,
  },
  "c3d-standard-16-lssd": {
    hourlyPrice: 0.85713312,
    windowsHourlyPrice: 1.59313312,
  },
  "c3d-standard-180": {
    hourlyPrice: 9.6427476,
    windowsHourlyPrice: 17.9227476,
  },
  "c3d-standard-180-lssd": {
    hourlyPrice: 9.6427476,
    windowsHourlyPrice: 17.9227476,
  },
  "c3d-standard-30": {
    hourlyPrice: 1.6071246,
    windowsHourlyPrice: 2.9871246,
  },
  "c3d-standard-30-lssd": {
    hourlyPrice: 1.6071246,
    windowsHourlyPrice: 2.9871246,
  },
  "c3d-standard-360": {
    hourlyPrice: 19.2854952,
    windowsHourlyPrice: 35.8454952,
  },
  "c3d-standard-360-lssd": {
    hourlyPrice: 19.2854952,
    windowsHourlyPrice: 35.8454952,
  },
  "c3d-standard-4": {
    hourlyPrice: 0.21428328,
    windowsHourlyPrice: 0.39828328,
  },
  "c3d-standard-60": {
    hourlyPrice: 3.2142492,
    windowsHourlyPrice: 5.9742492,
  },
  "c3d-standard-60-lssd": {
    hourlyPrice: 3.2142492,
    windowsHourlyPrice: 5.9742492,
  },
  "c3d-standard-8": {
    hourlyPrice: 0.42856656,
    windowsHourlyPrice: 0.79656656,
  },
  "c3d-standard-8-lssd": {
    hourlyPrice: 0.42856656,
    windowsHourlyPrice: 0.79656656,
  },
  "c3d-standard-90": {
    hourlyPrice: 4.8213738,
    windowsHourlyPrice: 8.9613738,
  },
  "c3d-standard-90-lssd": {
    hourlyPrice: 4.8213738,
    windowsHourlyPrice: 8.9613738,
  },
  "c4-highcpu-144": {
    hourlyPrice: 7.22601792,
    windowsHourlyPrice: 13.85001792,
  },
  "c4-highcpu-16": {
    hourlyPrice: 0.80289088,
    windowsHourlyPrice: 1.53889088,
  },
  "c4-highcpu-192": {
    hourlyPrice: 9.63469056,
    windowsHourlyPrice: 18.46669056,
  },
  "c4-highcpu-2": {
    hourlyPrice: 0.10036136,
    windowsHourlyPrice: 0.19236136,
  },
  "c4-highcpu-24": {
    hourlyPrice: 1.20433632,
    windowsHourlyPrice: 2.30833632,
  },
  "c4-highcpu-288": {
    hourlyPrice: 14.45203584,
    windowsHourlyPrice: 27.70003584,
  },
  "c4-highcpu-32": {
    hourlyPrice: 1.60578176,
    windowsHourlyPrice: 3.07778176,
  },
  "c4-highcpu-4": {
    hourlyPrice: 0.20072272,
    windowsHourlyPrice: 0.38472272,
  },
  "c4-highcpu-48": {
    hourlyPrice: 2.40867264,
    windowsHourlyPrice: 4.61667264,
  },
  "c4-highcpu-8": {
    hourlyPrice: 0.40144544,
    windowsHourlyPrice: 0.76944544,
  },
  "c4-highcpu-96": {
    hourlyPrice: 4.81734528,
    windowsHourlyPrice: 9.23334528,
  },
  "c4-highmem-144": {
    hourlyPrice: 11.07360144,
    windowsHourlyPrice: 17.69760144,
  },
  "c4-highmem-144-lssd": {
    hourlyPrice: 11.07360144,
    windowsHourlyPrice: 17.69760144,
  },
  "c4-highmem-16": {
    hourlyPrice: 1.23040016,
    windowsHourlyPrice: 1.96640016,
  },
  "c4-highmem-16-lssd": {
    hourlyPrice: 1.23040016,
    windowsHourlyPrice: 1.96640016,
  },
  "c4-highmem-192": {
    hourlyPrice: 14.76480192,
    windowsHourlyPrice: 23.59680192,
  },
  "c4-highmem-192-lssd": {
    hourlyPrice: 14.76480192,
    windowsHourlyPrice: 23.59680192,
  },
  "c4-highmem-2": {
    hourlyPrice: 0.1514766,
    windowsHourlyPrice: 0.2434766,
  },
  "c4-highmem-24": {
    hourlyPrice: 1.84560024,
    windowsHourlyPrice: 2.94960024,
  },
  "c4-highmem-24-lssd": {
    hourlyPrice: 1.84560024,
    windowsHourlyPrice: 2.94960024,
  },
  "c4-highmem-288": {
    hourlyPrice: 22.14720288,
    windowsHourlyPrice: 35.39520288,
  },
  "c4-highmem-288-lssd": {
    hourlyPrice: 22.14720288,
    windowsHourlyPrice: 35.39520288,
  },
  "c4-highmem-288-lssd-metal": {
    hourlyPrice: 22.14720288,
    windowsHourlyPrice: 35.39520288,
  },
  "c4-highmem-288-metal": {
    hourlyPrice: 22.14720288,
    windowsHourlyPrice: 35.39520288,
  },
  "c4-highmem-32": {
    hourlyPrice: 2.46080032,
    windowsHourlyPrice: 3.93280032,
  },
  "c4-highmem-32-lssd": {
    hourlyPrice: 2.46080032,
    windowsHourlyPrice: 3.93280032,
  },
  "c4-highmem-4": {
    hourlyPrice: 0.30760004,
    windowsHourlyPrice: 0.49160004,
  },
  "c4-highmem-4-lssd": {
    hourlyPrice: 0.30760004,
    windowsHourlyPrice: 0.49160004,
  },
  "c4-highmem-48": {
    hourlyPrice: 3.69120048,
    windowsHourlyPrice: 5.89920048,
  },
  "c4-highmem-48-lssd": {
    hourlyPrice: 3.69120048,
    windowsHourlyPrice: 5.89920048,
  },
  "c4-highmem-8": {
    hourlyPrice: 0.61520008,
    windowsHourlyPrice: 0.98320008,
  },
  "c4-highmem-8-lssd": {
    hourlyPrice: 0.61520008,
    windowsHourlyPrice: 0.98320008,
  },
  "c4-highmem-96": {
    hourlyPrice: 7.38240096,
    windowsHourlyPrice: 11.79840096,
  },
  "c4-highmem-96-lssd": {
    hourlyPrice: 7.38240096,
    windowsHourlyPrice: 11.79840096,
  },
  "c4-standard-144": {
    hourlyPrice: 8.3970216,
    windowsHourlyPrice: 15.0210216,
  },
  "c4-standard-144-lssd": {
    hourlyPrice: 8.3970216,
    windowsHourlyPrice: 15.0210216,
  },
  "c4-standard-16": {
    hourlyPrice: 0.9330024,
    windowsHourlyPrice: 1.6690024,
  },
  "c4-standard-16-lssd": {
    hourlyPrice: 0.9330024,
    windowsHourlyPrice: 1.6690024,
  },
  "c4-standard-192": {
    hourlyPrice: 11.1960288,
    windowsHourlyPrice: 20.0280288,
  },
  "c4-standard-192-lssd": {
    hourlyPrice: 11.1960288,
    windowsHourlyPrice: 20.0280288,
  },
  "c4-standard-2": {
    hourlyPrice: 0.11430188,
    windowsHourlyPrice: 0.20630188,
  },
  "c4-standard-24": {
    hourlyPrice: 1.3995036,
    windowsHourlyPrice: 2.5035036,
  },
  "c4-standard-24-lssd": {
    hourlyPrice: 1.3995036,
    windowsHourlyPrice: 2.5035036,
  },
  "c4-standard-288": {
    hourlyPrice: 16.7940432,
    windowsHourlyPrice: 30.0420432,
  },
  "c4-standard-288-lssd": {
    hourlyPrice: 16.7940432,
    windowsHourlyPrice: 30.0420432,
  },
  "c4-standard-288-lssd-metal": {
    hourlyPrice: 16.7940432,
    windowsHourlyPrice: 30.0420432,
  },
  "c4-standard-288-metal": {
    hourlyPrice: 16.7940432,
    windowsHourlyPrice: 30.0420432,
  },
  "c4-standard-32": {
    hourlyPrice: 1.8660048,
    windowsHourlyPrice: 3.3380048,
  },
  "c4-standard-32-lssd": {
    hourlyPrice: 1.8660048,
    windowsHourlyPrice: 3.3380048,
  },
  "c4-standard-4": {
    hourlyPrice: 0.2332506,
    windowsHourlyPrice: 0.4172506,
  },
  "c4-standard-4-lssd": {
    hourlyPrice: 0.2332506,
    windowsHourlyPrice: 0.4172506,
  },
  "c4-standard-48": {
    hourlyPrice: 2.7990072,
    windowsHourlyPrice: 5.0070072,
  },
  "c4-standard-48-lssd": {
    hourlyPrice: 2.7990072,
    windowsHourlyPrice: 5.0070072,
  },
  "c4-standard-8": {
    hourlyPrice: 0.4665012,
    windowsHourlyPrice: 0.8345012,
  },
  "c4-standard-8-lssd": {
    hourlyPrice: 0.4665012,
    windowsHourlyPrice: 0.8345012,
  },
  "c4-standard-96": {
    hourlyPrice: 5.5980144,
    windowsHourlyPrice: 10.0140144,
  },
  "c4-standard-96-lssd": {
    hourlyPrice: 5.5980144,
    windowsHourlyPrice: 10.0140144,
  },
  "c4a-highcpu-1": {
    hourlyPrice: 0.044699,
    windowsHourlyPrice: 0.090699,
  },
  "c4a-highcpu-16": {
    hourlyPrice: 0.715184,
    windowsHourlyPrice: 1.451184,
  },
  "c4a-highcpu-2": {
    hourlyPrice: 0.089398,
    windowsHourlyPrice: 0.181398,
  },
  "c4a-highcpu-32": {
    hourlyPrice: 1.430368,
    windowsHourlyPrice: 2.902368,
  },
  "c4a-highcpu-4": {
    hourlyPrice: 0.178796,
    windowsHourlyPrice: 0.362796,
  },
  "c4a-highcpu-48": {
    hourlyPrice: 2.145552,
    windowsHourlyPrice: 4.353552,
  },
  "c4a-highcpu-64": {
    hourlyPrice: 2.860736,
    windowsHourlyPrice: 5.804736,
  },
  "c4a-highcpu-72": {
    hourlyPrice: 3.218328,
    windowsHourlyPrice: 6.530328,
  },
  "c4a-highcpu-8": {
    hourlyPrice: 0.357592,
    windowsHourlyPrice: 0.725592,
  },
  "c4a-highmem-1": {
    hourlyPrice: 0.069551,
    windowsHourlyPrice: 0.115551,
  },
  "c4a-highmem-16": {
    hourlyPrice: 1.112816,
    windowsHourlyPrice: 1.848816,
  },
  "c4a-highmem-16-lssd": {
    hourlyPrice: 1.4037749,
    windowsHourlyPrice: 2.1397749,
  },
  "c4a-highmem-2": {
    hourlyPrice: 0.139102,
    windowsHourlyPrice: 0.231102,
  },
  "c4a-highmem-32": {
    hourlyPrice: 2.225632,
    windowsHourlyPrice: 3.697632,
  },
  "c4a-highmem-32-lssd": {
    hourlyPrice: 2.66207036,
    windowsHourlyPrice: 4.13407036,
  },
  "c4a-highmem-4": {
    hourlyPrice: 0.278204,
    windowsHourlyPrice: 0.462204,
  },
  "c4a-highmem-4-lssd": {
    hourlyPrice: 0.35094373,
    windowsHourlyPrice: 0.53494373,
  },
  "c4a-highmem-48": {
    hourlyPrice: 3.338448,
    windowsHourlyPrice: 5.546448,
  },
  "c4a-highmem-48-lssd": {
    hourlyPrice: 4.06584526,
    windowsHourlyPrice: 6.27384526,
  },
  "c4a-highmem-64": {
    hourlyPrice: 4.451264,
    windowsHourlyPrice: 7.395264,
  },
  "c4a-highmem-64-lssd": {
    hourlyPrice: 5.46962016,
    windowsHourlyPrice: 8.41362016,
  },
  "c4a-highmem-72": {
    hourlyPrice: 5.007672,
    windowsHourlyPrice: 8.319672,
  },
  "c4a-highmem-72-lssd": {
    hourlyPrice: 6.17150762,
    windowsHourlyPrice: 9.48350762,
  },
  "c4a-highmem-8": {
    hourlyPrice: 0.556408,
    windowsHourlyPrice: 0.924408,
  },
  "c4a-highmem-8-lssd": {
    hourlyPrice: 0.70188745,
    windowsHourlyPrice: 1.06988745,
  },
  "c4a-highmem-96-metal": {
    hourlyPrice: 6.676896,
    windowsHourlyPrice: 11.092896,
  },
  "c4a-standard-1": {
    hourlyPrice: 0.052983,
    windowsHourlyPrice: 0.098983,
  },
  "c4a-standard-16": {
    hourlyPrice: 0.847728,
    windowsHourlyPrice: 1.583728,
  },
  "c4a-standard-16-lssd": {
    hourlyPrice: 1.1386869,
    windowsHourlyPrice: 1.8746869,
  },
  "c4a-standard-2": {
    hourlyPrice: 0.105966,
    windowsHourlyPrice: 0.197966,
  },
  "c4a-standard-32": {
    hourlyPrice: 1.695456,
    windowsHourlyPrice: 3.167456,
  },
  "c4a-standard-32-lssd": {
    hourlyPrice: 2.13189436,
    windowsHourlyPrice: 3.60389436,
  },
  "c4a-standard-4": {
    hourlyPrice: 0.211932,
    windowsHourlyPrice: 0.395932,
  },
  "c4a-standard-4-lssd": {
    hourlyPrice: 0.28467173,
    windowsHourlyPrice: 0.46867173,
  },
  "c4a-standard-48": {
    hourlyPrice: 2.543184,
    windowsHourlyPrice: 4.751184,
  },
  "c4a-standard-48-lssd": {
    hourlyPrice: 3.27058126,
    windowsHourlyPrice: 5.47858126,
  },
  "c4a-standard-64": {
    hourlyPrice: 3.390912,
    windowsHourlyPrice: 6.334912,
  },
  "c4a-standard-64-lssd": {
    hourlyPrice: 4.40926816,
    windowsHourlyPrice: 7.35326816,
  },
  "c4a-standard-72": {
    hourlyPrice: 3.814776,
    windowsHourlyPrice: 7.126776,
  },
  "c4a-standard-72-lssd": {
    hourlyPrice: 4.97861162,
    windowsHourlyPrice: 8.29061162,
  },
  "c4a-standard-8": {
    hourlyPrice: 0.423864,
    windowsHourlyPrice: 0.791864,
  },
  "c4a-standard-8-lssd": {
    hourlyPrice: 0.56934345,
    windowsHourlyPrice: 0.93734345,
  },
  "c4d-highcpu-16": {
    hourlyPrice: 0.75031013,
    windowsHourlyPrice: 1.48631013,
  },
  "c4d-highcpu-192": {
    hourlyPrice: 9.00372154,
    windowsHourlyPrice: 17.83572154,
  },
  "c4d-highcpu-2": {
    hourlyPrice: 0.09046705,
    windowsHourlyPrice: 0.18246705,
  },
  "c4d-highcpu-32": {
    hourlyPrice: 1.50062026,
    windowsHourlyPrice: 2.97262026,
  },
  "c4d-highcpu-384": {
    hourlyPrice: 18.00744308,
    windowsHourlyPrice: 35.67144308,
  },
  "c4d-highcpu-384-metal": {
    hourlyPrice: 18.22003273,
    windowsHourlyPrice: 35.88403273,
  },
  "c4d-highcpu-4": {
    hourlyPrice: 0.18536306,
    windowsHourlyPrice: 0.36936306,
  },
  "c4d-highcpu-48": {
    hourlyPrice: 2.25093039,
    windowsHourlyPrice: 4.45893039,
  },
  "c4d-highcpu-64": {
    hourlyPrice: 3.00124051,
    windowsHourlyPrice: 5.94524051,
  },
  "c4d-highcpu-8": {
    hourlyPrice: 0.37515506,
    windowsHourlyPrice: 0.74315506,
  },
  "c4d-highcpu-96": {
    hourlyPrice: 4.50186077,
    windowsHourlyPrice: 8.91786077,
  },
  "c4d-highmem-16": {
    hourlyPrice: 1.17548942,
    windowsHourlyPrice: 1.91148942,
  },
  "c4d-highmem-16-lssd": {
    hourlyPrice: 1.27247572,
    windowsHourlyPrice: 2.00847572,
  },
  "c4d-highmem-192": {
    hourlyPrice: 14.10587303,
    windowsHourlyPrice: 22.93787303,
  },
  "c4d-highmem-192-lssd": {
    hourlyPrice: 15.65765386,
    windowsHourlyPrice: 24.48965386,
  },
  "c4d-highmem-2": {
    hourlyPrice: 0.14361446,
    windowsHourlyPrice: 0.23561446,
  },
  "c4d-highmem-32": {
    hourlyPrice: 2.35097884,
    windowsHourlyPrice: 3.82297884,
  },
  "c4d-highmem-32-lssd": {
    hourlyPrice: 2.54495144,
    windowsHourlyPrice: 4.01695144,
  },
  "c4d-highmem-384": {
    hourlyPrice: 28.21174607,
    windowsHourlyPrice: 45.87574607,
  },
  "c4d-highmem-384-lssd": {
    hourlyPrice: 31.31530771,
    windowsHourlyPrice: 48.97930771,
  },
  "c4d-highmem-384-metal": {
    hourlyPrice: 28.42433571,
    windowsHourlyPrice: 46.08833571,
  },
  "c4d-highmem-4": {
    hourlyPrice: 0.29165788,
    windowsHourlyPrice: 0.47565788,
  },
  "c4d-highmem-48": {
    hourlyPrice: 3.52646826,
    windowsHourlyPrice: 5.73446826,
  },
  "c4d-highmem-48-lssd": {
    hourlyPrice: 3.91441346,
    windowsHourlyPrice: 6.12241346,
  },
  "c4d-highmem-64": {
    hourlyPrice: 4.70195768,
    windowsHourlyPrice: 7.64595768,
  },
  "c4d-highmem-64-lssd": {
    hourlyPrice: 5.28387549,
    windowsHourlyPrice: 8.22787549,
  },
  "c4d-highmem-8": {
    hourlyPrice: 0.58774471,
    windowsHourlyPrice: 0.95574471,
  },
  "c4d-highmem-8-lssd": {
    hourlyPrice: 0.68473101,
    windowsHourlyPrice: 1.05273101,
  },
  "c4d-highmem-96": {
    hourlyPrice: 7.05293652,
    windowsHourlyPrice: 11.46893652,
  },
  "c4d-highmem-96-lssd": {
    hourlyPrice: 7.82882693,
    windowsHourlyPrice: 12.24482693,
  },
  "c4d-standard-16": {
    hourlyPrice: 0.89203656,
    windowsHourlyPrice: 1.62803656,
  },
  "c4d-standard-16-lssd": {
    hourlyPrice: 0.98902286,
    windowsHourlyPrice: 1.72502286,
  },
  "c4d-standard-192": {
    hourlyPrice: 10.70443871,
    windowsHourlyPrice: 19.53643871,
  },
  "c4d-standard-192-lssd": {
    hourlyPrice: 12.25621953,
    windowsHourlyPrice: 21.08821953,
  },
  "c4d-standard-2": {
    hourlyPrice: 0.10818286,
    windowsHourlyPrice: 0.20018286,
  },
  "c4d-standard-32": {
    hourlyPrice: 1.78407312,
    windowsHourlyPrice: 3.25607312,
  },
  "c4d-standard-32-lssd": {
    hourlyPrice: 1.97804572,
    windowsHourlyPrice: 3.45004572,
  },
  "c4d-standard-384": {
    hourlyPrice: 21.40887741,
    windowsHourlyPrice: 39.07287741,
  },
  "c4d-standard-384-lssd": {
    hourlyPrice: 24.51243905,
    windowsHourlyPrice: 42.17643905,
  },
  "c4d-standard-384-metal": {
    hourlyPrice: 21.62146706,
    windowsHourlyPrice: 39.28546706,
  },
  "c4d-standard-4": {
    hourlyPrice: 0.22079466,
    windowsHourlyPrice: 0.40479466,
  },
  "c4d-standard-48": {
    hourlyPrice: 2.67610968,
    windowsHourlyPrice: 4.88410968,
  },
  "c4d-standard-48-lssd": {
    hourlyPrice: 3.06405488,
    windowsHourlyPrice: 5.27205488,
  },
  "c4d-standard-64": {
    hourlyPrice: 3.56814624,
    windowsHourlyPrice: 6.51214624,
  },
  "c4d-standard-64-lssd": {
    hourlyPrice: 4.15006404,
    windowsHourlyPrice: 7.09406404,
  },
  "c4d-standard-8": {
    hourlyPrice: 0.44601828,
    windowsHourlyPrice: 0.81401828,
  },
  "c4d-standard-8-lssd": {
    hourlyPrice: 0.54300458,
    windowsHourlyPrice: 0.91100458,
  },
  "c4d-standard-96": {
    hourlyPrice: 5.35221935,
    windowsHourlyPrice: 9.76821935,
  },
  "c4d-standard-96-lssd": {
    hourlyPrice: 6.12810976,
    windowsHourlyPrice: 10.54410976,
  },
  "e2-highcpu-16": {
    hourlyPrice: 0.467008,
    windowsHourlyPrice: 1.203008,
  },
  "e2-highcpu-2": {
    hourlyPrice: 0.058376,
    windowsHourlyPrice: 0.150376,
  },
  "e2-highcpu-32": {
    hourlyPrice: 0.934016,
    windowsHourlyPrice: 2.406016,
  },
  "e2-highcpu-4": {
    hourlyPrice: 0.116752,
    windowsHourlyPrice: 0.300752,
  },
  "e2-highcpu-8": {
    hourlyPrice: 0.233504,
    windowsHourlyPrice: 0.601504,
  },
  "e2-highmem-16": {
    hourlyPrice: 0.853408,
    windowsHourlyPrice: 1.589408,
  },
  "e2-highmem-2": {
    hourlyPrice: 0.106676,
    windowsHourlyPrice: 0.198676,
  },
  "e2-highmem-4": {
    hourlyPrice: 0.213352,
    windowsHourlyPrice: 0.397352,
  },
  "e2-highmem-8": {
    hourlyPrice: 0.426704,
    windowsHourlyPrice: 0.794704,
  },
  "e2-medium": {
    hourlyPrice: 0.065276,
    windowsHourlyPrice: 0.157276,
  },
  "e2-micro": {
    hourlyPrice: 0.054926,
    windowsHourlyPrice: 0.146926,
  },
  "e2-small": {
    hourlyPrice: 0.058376,
    windowsHourlyPrice: 0.150376,
  },
  "e2-standard-16": {
    hourlyPrice: 0.632608,
    windowsHourlyPrice: 1.368608,
  },
  "e2-standard-2": {
    hourlyPrice: 0.079076,
    windowsHourlyPrice: 0.171076,
  },
  "e2-standard-32": {
    hourlyPrice: 1.265216,
    windowsHourlyPrice: 2.737216,
  },
  "e2-standard-4": {
    hourlyPrice: 0.158152,
    windowsHourlyPrice: 0.342152,
  },
  "e2-standard-8": {
    hourlyPrice: 0.316304,
    windowsHourlyPrice: 0.684304,
  },
  "g2-standard-12": {
    hourlyPrice: 0.5196438,
    windowsHourlyPrice: 1.0716438,
  },
  "g2-standard-16": {
    hourlyPrice: 0.6928584,
    windowsHourlyPrice: 1.4288584,
  },
  "g2-standard-24": {
    hourlyPrice: 1.0392876,
    windowsHourlyPrice: 2.1432876,
  },
  "g2-standard-32": {
    hourlyPrice: 1.3857168,
    windowsHourlyPrice: 2.8577168,
  },
  "g2-standard-4": {
    hourlyPrice: 0.1732146,
    windowsHourlyPrice: 0.3572146,
  },
  "g2-standard-48": {
    hourlyPrice: 2.0785752,
    windowsHourlyPrice: 4.2865752,
  },
  "g2-standard-8": {
    hourlyPrice: 0.3464292,
    windowsHourlyPrice: 0.7144292,
  },
  "g2-standard-96": {
    hourlyPrice: 4.1571504,
    windowsHourlyPrice: 8.5731504,
  },
  "h3-standard-88": {
    hourlyPrice: 5.809848,
    windowsHourlyPrice: 9.857848,
  },
  "m1-megamem-96": {
    hourlyPrice: 12.56954645,
    windowsHourlyPrice: 16.98554645,
  },
  "m1-ultramem-160": {
    hourlyPrice: 29.703432,
    windowsHourlyPrice: 37.063432,
  },
  "m1-ultramem-40": {
    hourlyPrice: 7.425858,
    windowsHourlyPrice: 9.265858,
  },
  "m1-ultramem-80": {
    hourlyPrice: 14.851716,
    windowsHourlyPrice: 18.531716,
  },
  "m2-hypermem-416": {
    hourlyPrice: 79.363968,
    windowsHourlyPrice: 98.499968,
  },
  "m2-megamem-416": {
    hourlyPrice: 59.34376704,
    windowsHourlyPrice: 78.47976704,
  },
  "m2-ultramem-208": {
    hourlyPrice: 49.69208448,
    windowsHourlyPrice: 59.26008448,
  },
  "m2-ultramem-416": {
    hourlyPrice: 99.38416896,
    windowsHourlyPrice: 118.52016896,
  },
  "m2-ultramem2x-96": {
    hourlyPrice: 12.95504772,
    windowsHourlyPrice: 17.37104772,
  },
  "m2-ultramemx-96": {
    hourlyPrice: 8.53482672,
    windowsHourlyPrice: 12.95082672,
  },
  "m3-megamem-128": {
    hourlyPrice: 17.003328,
    windowsHourlyPrice: 22.891328,
  },
  "m3-megamem-64": {
    hourlyPrice: 8.501664,
    windowsHourlyPrice: 11.445664,
  },
  "m3-ultramem-128": {
    hourlyPrice: 28.750464,
    windowsHourlyPrice: 34.638464,
  },
  "m3-ultramem-32": {
    hourlyPrice: 7.187616,
    windowsHourlyPrice: 8.659616,
  },
  "m3-ultramem-64": {
    hourlyPrice: 14.375232,
    windowsHourlyPrice: 17.319232,
  },
  "m4-hypermem-16": {
    hourlyPrice: 1.7109776,
    windowsHourlyPrice: 2.4469776,
  },
  "m4-hypermem-32": {
    hourlyPrice: 3.4219552,
    windowsHourlyPrice: 4.8939552,
  },
  "m4-hypermem-64": {
    hourlyPrice: 6.8439104,
    windowsHourlyPrice: 9.7879104,
  },
  "m4-megamem-112": {
    hourlyPrice: 10.6168112,
    windowsHourlyPrice: 15.7688112,
  },
  "m4-megamem-224": {
    hourlyPrice: 21.2336224,
    windowsHourlyPrice: 31.5376224,
  },
  "m4-megamem-28": {
    hourlyPrice: 2.6542028,
    windowsHourlyPrice: 3.9422028,
  },
  "m4-megamem-56": {
    hourlyPrice: 5.3084056,
    windowsHourlyPrice: 7.8844056,
  },
  "m4-ultramem-112": {
    hourlyPrice: 18.7770032,
    windowsHourlyPrice: 23.9290032,
  },
  "m4-ultramem-224": {
    hourlyPrice: 37.5540064,
    windowsHourlyPrice: 47.8580064,
  },
  "m4-ultramem-56": {
    hourlyPrice: 9.3885016,
    windowsHourlyPrice: 11.9645016,
  },
  "m4n-hypermem-16": {
    hourlyPrice: 3.0285088,
    windowsHourlyPrice: 3.7645088,
  },
  "m4n-hypermem-32": {
    hourlyPrice: 6.0570176,
    windowsHourlyPrice: 7.5290176,
  },
  "m4n-hypermem-64": {
    hourlyPrice: 12.1140352,
    windowsHourlyPrice: 15.0580352,
  },
  "m4n-megamem-112": {
    hourlyPrice: 18.7922256,
    windowsHourlyPrice: 23.9442256,
  },
  "m4n-megamem-224": {
    hourlyPrice: 37.5844512,
    windowsHourlyPrice: 47.8884512,
  },
  "m4n-megamem-28": {
    hourlyPrice: 4.6980564,
    windowsHourlyPrice: 5.9860564,
  },
  "m4n-megamem-56": {
    hourlyPrice: 9.3961128,
    windowsHourlyPrice: 11.9721128,
  },
  "m4n-ultramem-112": {
    hourlyPrice: 33.2362416,
    windowsHourlyPrice: 38.3882416,
  },
  "m4n-ultramem-224": {
    hourlyPrice: 66.4724832,
    windowsHourlyPrice: 76.7764832,
  },
  "m4n-ultramem-56": {
    hourlyPrice: 16.6181208,
    windowsHourlyPrice: 19.1941208,
  },
  "n1-highcpu-16": {
    hourlyPrice: 0.66881274,
    windowsHourlyPrice: 1.40481274,
  },
  "n1-highcpu-2": {
    hourlyPrice: 0.08360037,
    windowsHourlyPrice: 0.17560037,
  },
  "n1-highcpu-32": {
    hourlyPrice: 1.33762059,
    windowsHourlyPrice: 2.80962059,
  },
  "n1-highcpu-4": {
    hourlyPrice: 0.16720074,
    windowsHourlyPrice: 0.35120074,
  },
  "n1-highcpu-64": {
    hourlyPrice: 2.67524118,
    windowsHourlyPrice: 5.61924118,
  },
  "n1-highcpu-8": {
    hourlyPrice: 0.33440637,
    windowsHourlyPrice: 0.70240637,
  },
  "n1-highcpu-96": {
    hourlyPrice: 4.01286666,
    windowsHourlyPrice: 8.42886666,
  },
  "n1-highmem-16": {
    hourlyPrice: 1.11678032,
    windowsHourlyPrice: 1.85278032,
  },
  "n1-highmem-2": {
    hourlyPrice: 0.13959754,
    windowsHourlyPrice: 0.23159754,
  },
  "n1-highmem-32": {
    hourlyPrice: 2.23356064,
    windowsHourlyPrice: 3.70556064,
  },
  "n1-highmem-4": {
    hourlyPrice: 0.27919508,
    windowsHourlyPrice: 0.46319508,
  },
  "n1-highmem-64": {
    hourlyPrice: 4.46712128,
    windowsHourlyPrice: 7.41112128,
  },
  "n1-highmem-8": {
    hourlyPrice: 0.55839016,
    windowsHourlyPrice: 0.92639016,
  },
  "n1-highmem-96": {
    hourlyPrice: 6.70068192,
    windowsHourlyPrice: 11.11668192,
  },
  "n1-megamem-96": {
    hourlyPrice: 10.7484047,
    windowsHourlyPrice: 15.1644047,
  },
  "n1-standard-1": {
    hourlyPrice: 0.05604971,
    windowsHourlyPrice: 0.1020497,
  },
  "n1-standard-16": {
    hourlyPrice: 0.89679528,
    windowsHourlyPrice: 1.63279528,
  },
  "n1-standard-2": {
    hourlyPrice: 0.11209941,
    windowsHourlyPrice: 0.20409941,
  },
  "n1-standard-32": {
    hourlyPrice: 1.79359056,
    windowsHourlyPrice: 3.26559056,
  },
  "n1-standard-4": {
    hourlyPrice: 0.22419882,
    windowsHourlyPrice: 0.40819882,
  },
  "n1-standard-64": {
    hourlyPrice: 3.58718112,
    windowsHourlyPrice: 6.53118112,
  },
  "n1-standard-8": {
    hourlyPrice: 0.44839764,
    windowsHourlyPrice: 0.81639764,
  },
  "n1-standard-96": {
    hourlyPrice: 5.38077168,
    windowsHourlyPrice: 9.79677168,
  },
  "n1-ultramem-160": {
    hourlyPrice: 25.18684984,
    windowsHourlyPrice: 32.54684984,
  },
  "n1-ultramem-40": {
    hourlyPrice: 6.29671246,
    windowsHourlyPrice: 8.13671246,
  },
  "n1-ultramem-80": {
    hourlyPrice: 12.59342492,
    windowsHourlyPrice: 16.27342492,
  },
  "n2-highcpu-16": {
    hourlyPrice: 0.67681024,
    windowsHourlyPrice: 1.41281024,
  },
  "n2-highcpu-2": {
    hourlyPrice: 0.08460128,
    windowsHourlyPrice: 0.17660128,
  },
  "n2-highcpu-32": {
    hourlyPrice: 1.35362048,
    windowsHourlyPrice: 2.82562048,
  },
  "n2-highcpu-4": {
    hourlyPrice: 0.16920256,
    windowsHourlyPrice: 0.35320256,
  },
  "n2-highcpu-48": {
    hourlyPrice: 2.03043072,
    windowsHourlyPrice: 4.23843072,
  },
  "n2-highcpu-64": {
    hourlyPrice: 2.70724096,
    windowsHourlyPrice: 5.65124096,
  },
  "n2-highcpu-8": {
    hourlyPrice: 0.33840512,
    windowsHourlyPrice: 0.70640512,
  },
  "n2-highcpu-80": {
    hourlyPrice: 3.3840512,
    windowsHourlyPrice: 7.0640512,
  },
  "n2-highcpu-96": {
    hourlyPrice: 4.06086144,
    windowsHourlyPrice: 8.47686144,
  },
  "n2-highmem-128": {
    hourlyPrice: 9.09423168,
    windowsHourlyPrice: 14.98223168,
  },
  "n2-highmem-16": {
    hourlyPrice: 1.23677216,
    windowsHourlyPrice: 1.97277216,
  },
  "n2-highmem-2": {
    hourlyPrice: 0.15459652,
    windowsHourlyPrice: 0.24659652,
  },
  "n2-highmem-32": {
    hourlyPrice: 2.47354432,
    windowsHourlyPrice: 3.94554432,
  },
  "n2-highmem-4": {
    hourlyPrice: 0.30919304,
    windowsHourlyPrice: 0.49319304,
  },
  "n2-highmem-48": {
    hourlyPrice: 3.71031648,
    windowsHourlyPrice: 5.91831648,
  },
  "n2-highmem-64": {
    hourlyPrice: 4.94708864,
    windowsHourlyPrice: 7.89108864,
  },
  "n2-highmem-8": {
    hourlyPrice: 0.61838608,
    windowsHourlyPrice: 0.98638608,
  },
  "n2-highmem-80": {
    hourlyPrice: 6.1838608,
    windowsHourlyPrice: 9.8638608,
  },
  "n2-highmem-96": {
    hourlyPrice: 7.42063296,
    windowsHourlyPrice: 11.83663296,
  },
  "n2-standard-128": {
    hourlyPrice: 7.33435136,
    windowsHourlyPrice: 13.22235136,
  },
  "n2-standard-16": {
    hourlyPrice: 0.91679392,
    windowsHourlyPrice: 1.65279392,
  },
  "n2-standard-2": {
    hourlyPrice: 0.11459924,
    windowsHourlyPrice: 0.20659924,
  },
  "n2-standard-32": {
    hourlyPrice: 1.83358784,
    windowsHourlyPrice: 3.30558784,
  },
  "n2-standard-4": {
    hourlyPrice: 0.22919848,
    windowsHourlyPrice: 0.41319848,
  },
  "n2-standard-48": {
    hourlyPrice: 2.75038176,
    windowsHourlyPrice: 4.95838176,
  },
  "n2-standard-64": {
    hourlyPrice: 3.66717568,
    windowsHourlyPrice: 6.61117568,
  },
  "n2-standard-8": {
    hourlyPrice: 0.45839696,
    windowsHourlyPrice: 0.82639696,
  },
  "n2-standard-80": {
    hourlyPrice: 4.5839696,
    windowsHourlyPrice: 8.2639696,
  },
  "n2-standard-96": {
    hourlyPrice: 5.50076352,
    windowsHourlyPrice: 9.91676352,
  },
  "n2d-highcpu-128": {
    hourlyPrice: 4.71063552,
    windowsHourlyPrice: 10.59863552,
  },
  "n2d-highcpu-16": {
    hourlyPrice: 0.58882944,
    windowsHourlyPrice: 1.32482944,
  },
  "n2d-highcpu-2": {
    hourlyPrice: 0.07360368,
    windowsHourlyPrice: 0.16560368,
  },
  "n2d-highcpu-224": {
    hourlyPrice: 8.24361216,
    windowsHourlyPrice: 18.54761216,
  },
  "n2d-highcpu-32": {
    hourlyPrice: 1.17765888,
    windowsHourlyPrice: 2.64965888,
  },
  "n2d-highcpu-4": {
    hourlyPrice: 0.14720736,
    windowsHourlyPrice: 0.33120736,
  },
  "n2d-highcpu-48": {
    hourlyPrice: 1.76648832,
    windowsHourlyPrice: 3.97448832,
  },
  "n2d-highcpu-64": {
    hourlyPrice: 2.35531776,
    windowsHourlyPrice: 5.29931776,
  },
  "n2d-highcpu-8": {
    hourlyPrice: 0.29441472,
    windowsHourlyPrice: 0.66241472,
  },
  "n2d-highcpu-80": {
    hourlyPrice: 2.9441472,
    windowsHourlyPrice: 6.6241472,
  },
  "n2d-highcpu-96": {
    hourlyPrice: 3.53297664,
    windowsHourlyPrice: 7.94897664,
  },
  "n2d-highmem-16": {
    hourlyPrice: 1.0759712,
    windowsHourlyPrice: 1.8119712,
  },
  "n2d-highmem-2": {
    hourlyPrice: 0.1344964,
    windowsHourlyPrice: 0.2264964,
  },
  "n2d-highmem-32": {
    hourlyPrice: 2.1519424,
    windowsHourlyPrice: 3.6239424,
  },
  "n2d-highmem-4": {
    hourlyPrice: 0.2689928,
    windowsHourlyPrice: 0.4529928,
  },
  "n2d-highmem-48": {
    hourlyPrice: 3.2279136,
    windowsHourlyPrice: 5.4359136,
  },
  "n2d-highmem-64": {
    hourlyPrice: 4.3038848,
    windowsHourlyPrice: 7.2478848,
  },
  "n2d-highmem-8": {
    hourlyPrice: 0.5379856,
    windowsHourlyPrice: 0.9059856,
  },
  "n2d-highmem-80": {
    hourlyPrice: 5.379856,
    windowsHourlyPrice: 9.059856,
  },
  "n2d-highmem-96": {
    hourlyPrice: 6.4558272,
    windowsHourlyPrice: 10.8718272,
  },
  "n2d-standard-128": {
    hourlyPrice: 6.38083584,
    windowsHourlyPrice: 12.26883584,
  },
  "n2d-standard-16": {
    hourlyPrice: 0.79760448,
    windowsHourlyPrice: 1.53360448,
  },
  "n2d-standard-2": {
    hourlyPrice: 0.09970056,
    windowsHourlyPrice: 0.19170056,
  },
  "n2d-standard-224": {
    hourlyPrice: 11.16646272,
    windowsHourlyPrice: 21.47046272,
  },
  "n2d-standard-32": {
    hourlyPrice: 1.59520896,
    windowsHourlyPrice: 3.06720896,
  },
  "n2d-standard-4": {
    hourlyPrice: 0.19940112,
    windowsHourlyPrice: 0.38340112,
  },
  "n2d-standard-48": {
    hourlyPrice: 2.39281344,
    windowsHourlyPrice: 4.60081344,
  },
  "n2d-standard-64": {
    hourlyPrice: 3.19041792,
    windowsHourlyPrice: 6.13441792,
  },
  "n2d-standard-8": {
    hourlyPrice: 0.39880224,
    windowsHourlyPrice: 0.76680224,
  },
  "n2d-standard-80": {
    hourlyPrice: 3.9880224,
    windowsHourlyPrice: 7.6680224,
  },
  "n2d-standard-96": {
    hourlyPrice: 4.78562688,
    windowsHourlyPrice: 9.20162688,
  },
  "n4-highcpu-16": {
    hourlyPrice: 0.7225376,
    windowsHourlyPrice: 1.4585376,
  },
  "n4-highcpu-2": {
    hourlyPrice: 0.0903172,
    windowsHourlyPrice: 0.1823172,
  },
  "n4-highcpu-32": {
    hourlyPrice: 1.4450752,
    windowsHourlyPrice: 2.9170752,
  },
  "n4-highcpu-4": {
    hourlyPrice: 0.1806344,
    windowsHourlyPrice: 0.3646344,
  },
  "n4-highcpu-48": {
    hourlyPrice: 2.1676128,
    windowsHourlyPrice: 4.3756128,
  },
  "n4-highcpu-64": {
    hourlyPrice: 2.8901504,
    windowsHourlyPrice: 5.8341504,
  },
  "n4-highcpu-8": {
    hourlyPrice: 0.3612688,
    windowsHourlyPrice: 0.7292688,
  },
  "n4-highcpu-80": {
    hourlyPrice: 3.612688,
    windowsHourlyPrice: 7.292688,
  },
  "n4-highmem-16": {
    hourlyPrice: 1.1235488,
    windowsHourlyPrice: 1.8595488,
  },
  "n4-highmem-2": {
    hourlyPrice: 0.1404436,
    windowsHourlyPrice: 0.2324436,
  },
  "n4-highmem-32": {
    hourlyPrice: 2.2470976,
    windowsHourlyPrice: 3.7190976,
  },
  "n4-highmem-4": {
    hourlyPrice: 0.2808872,
    windowsHourlyPrice: 0.4648872,
  },
  "n4-highmem-48": {
    hourlyPrice: 3.3706464,
    windowsHourlyPrice: 5.5786464,
  },
  "n4-highmem-64": {
    hourlyPrice: 4.4941952,
    windowsHourlyPrice: 7.4381952,
  },
  "n4-highmem-8": {
    hourlyPrice: 0.5617744,
    windowsHourlyPrice: 0.9297744,
  },
  "n4-highmem-80": {
    hourlyPrice: 5.617744,
    windowsHourlyPrice: 9.297744,
  },
  "n4-standard-16": {
    hourlyPrice: 0.856208,
    windowsHourlyPrice: 1.592208,
  },
  "n4-standard-2": {
    hourlyPrice: 0.107026,
    windowsHourlyPrice: 0.199026,
  },
  "n4-standard-32": {
    hourlyPrice: 1.712416,
    windowsHourlyPrice: 3.184416,
  },
  "n4-standard-4": {
    hourlyPrice: 0.214052,
    windowsHourlyPrice: 0.398052,
  },
  "n4-standard-48": {
    hourlyPrice: 2.568624,
    windowsHourlyPrice: 4.776624,
  },
  "n4-standard-64": {
    hourlyPrice: 3.424832,
    windowsHourlyPrice: 6.368832,
  },
  "n4-standard-8": {
    hourlyPrice: 0.428104,
    windowsHourlyPrice: 0.796104,
  },
  "n4-standard-80": {
    hourlyPrice: 4.28104,
    windowsHourlyPrice: 7.96104,
  },
  "n4d-highcpu-16": {
    hourlyPrice: 0.628816,
    windowsHourlyPrice: 1.364816,
  },
  "n4d-highcpu-2": {
    hourlyPrice: 0.078602,
    windowsHourlyPrice: 0.170602,
  },
  "n4d-highcpu-32": {
    hourlyPrice: 1.257632,
    windowsHourlyPrice: 2.729632,
  },
  "n4d-highcpu-4": {
    hourlyPrice: 0.157204,
    windowsHourlyPrice: 0.341204,
  },
  "n4d-highcpu-48": {
    hourlyPrice: 1.886448,
    windowsHourlyPrice: 4.094448,
  },
  "n4d-highcpu-64": {
    hourlyPrice: 2.515264,
    windowsHourlyPrice: 5.459264,
  },
  "n4d-highcpu-8": {
    hourlyPrice: 0.314408,
    windowsHourlyPrice: 0.682408,
  },
  "n4d-highcpu-80": {
    hourlyPrice: 3.14408,
    windowsHourlyPrice: 6.82408,
  },
  "n4d-highcpu-96": {
    hourlyPrice: 3.772896,
    windowsHourlyPrice: 8.188896,
  },
  "n4d-highmem-16": {
    hourlyPrice: 0.978256,
    windowsHourlyPrice: 1.714256,
  },
  "n4d-highmem-2": {
    hourlyPrice: 0.122282,
    windowsHourlyPrice: 0.214282,
  },
  "n4d-highmem-32": {
    hourlyPrice: 1.956512,
    windowsHourlyPrice: 3.428512,
  },
  "n4d-highmem-4": {
    hourlyPrice: 0.244564,
    windowsHourlyPrice: 0.428564,
  },
  "n4d-highmem-48": {
    hourlyPrice: 2.934768,
    windowsHourlyPrice: 5.142768,
  },
  "n4d-highmem-64": {
    hourlyPrice: 3.913024,
    windowsHourlyPrice: 6.857024,
  },
  "n4d-highmem-8": {
    hourlyPrice: 0.489128,
    windowsHourlyPrice: 0.857128,
  },
  "n4d-highmem-80": {
    hourlyPrice: 4.89128,
    windowsHourlyPrice: 8.57128,
  },
  "n4d-highmem-96": {
    hourlyPrice: 5.869536,
    windowsHourlyPrice: 10.285536,
  },
  "n4d-standard-16": {
    hourlyPrice: 0.745296,
    windowsHourlyPrice: 1.481296,
  },
  "n4d-standard-2": {
    hourlyPrice: 0.093162,
    windowsHourlyPrice: 0.185162,
  },
  "n4d-standard-32": {
    hourlyPrice: 1.490592,
    windowsHourlyPrice: 2.962592,
  },
  "n4d-standard-4": {
    hourlyPrice: 0.186324,
    windowsHourlyPrice: 0.370324,
  },
  "n4d-standard-48": {
    hourlyPrice: 2.235888,
    windowsHourlyPrice: 4.443888,
  },
  "n4d-standard-64": {
    hourlyPrice: 2.981184,
    windowsHourlyPrice: 5.925184,
  },
  "n4d-standard-8": {
    hourlyPrice: 0.372648,
    windowsHourlyPrice: 0.740648,
  },
  "n4d-standard-80": {
    hourlyPrice: 3.72648,
    windowsHourlyPrice: 7.40648,
  },
  "n4d-standard-96": {
    hourlyPrice: 4.471776,
    windowsHourlyPrice: 8.887776,
  },
  "t2d-standard-1": {
    hourlyPrice: 0.04985028,
    windowsHourlyPrice: 0.09585028,
  },
  "t2d-standard-16": {
    hourlyPrice: 0.79760448,
    windowsHourlyPrice: 1.53360448,
  },
  "t2d-standard-2": {
    hourlyPrice: 0.09970056,
    windowsHourlyPrice: 0.19170056,
  },
  "t2d-standard-32": {
    hourlyPrice: 1.59520896,
    windowsHourlyPrice: 3.06720896,
  },
  "t2d-standard-4": {
    hourlyPrice: 0.19940112,
    windowsHourlyPrice: 0.38340112,
  },
  "t2d-standard-48": {
    hourlyPrice: 2.39281344,
    windowsHourlyPrice: 4.60081344,
  },
  "t2d-standard-60": {
    hourlyPrice: 2.9910168,
    windowsHourlyPrice: 5.7510168,
  },
  "t2d-standard-8": {
    hourlyPrice: 0.39880224,
    windowsHourlyPrice: 0.76680224,
  },
  "z3-highmem-14-standardlssd": {
    hourlyPrice: 1.69983324,
    windowsHourlyPrice: 2.34383324,
  },
  "z3-highmem-16-highlssd": {
    hourlyPrice: 1.94266656,
    windowsHourlyPrice: 2.67866656,
  },
  "z3-highmem-176": {
    hourlyPrice: 21.36933216,
    windowsHourlyPrice: 29.46533216,
  },
  "z3-highmem-176-standardlssd": {
    hourlyPrice: 21.36933216,
    windowsHourlyPrice: 29.46533216,
  },
  "z3-highmem-192-highlssd-metal": {
    hourlyPrice: 23.31199872,
    windowsHourlyPrice: 32.14399872,
  },
  "z3-highmem-22-highlssd": {
    hourlyPrice: 2.67116652,
    windowsHourlyPrice: 3.68316652,
  },
  "z3-highmem-22-standardlssd": {
    hourlyPrice: 2.67116652,
    windowsHourlyPrice: 3.68316652,
  },
  "z3-highmem-32-highlssd": {
    hourlyPrice: 3.88533312,
    windowsHourlyPrice: 5.35733312,
  },
  "z3-highmem-44-highlssd": {
    hourlyPrice: 5.34233304,
    windowsHourlyPrice: 7.36633304,
  },
  "z3-highmem-44-standardlssd": {
    hourlyPrice: 5.34233304,
    windowsHourlyPrice: 7.36633304,
  },
  "z3-highmem-8-highlssd": {
    hourlyPrice: 0.97133328,
    windowsHourlyPrice: 1.33933328,
  },
  "z3-highmem-88": {
    hourlyPrice: 10.68466608,
    windowsHourlyPrice: 14.73266608,
  },
  "z3-highmem-88-highlssd": {
    hourlyPrice: 10.68466608,
    windowsHourlyPrice: 14.73266608,
  },
  "z3-highmem-88-standardlssd": {
    hourlyPrice: 10.68466608,
    windowsHourlyPrice: 14.73266608,
  },
};
