// GCP instance prices for region key: me_central2 (updated 2026-08-30)
// Auto-generated by tools/split-data.js — do not edit by hand
// Specs for these types live in js/gcp/gcp-data.js as GCP_SPECS.compute
window.me_central2 = {
  "a2-highgpu-1g": {
    hourlyPrice: 1.1831632,
    windowsHourlyPrice: 1.7351632,
  },
  "a2-highgpu-2g": {
    hourlyPrice: 2.3663264,
    windowsHourlyPrice: 3.4703264,
  },
  "a2-highgpu-4g": {
    hourlyPrice: 4.7326528,
    windowsHourlyPrice: 6.9406528,
  },
  "a2-highgpu-8g": {
    hourlyPrice: 9.4653056,
    windowsHourlyPrice: 13.8813056,
  },
  "a2-megagpu-16g": {
    hourlyPrice: 14.0751616,
    windowsHourlyPrice: 18.4911616,
  },
  "a2-ultragpu-1g": {
    hourlyPrice: 1.7593952,
    windowsHourlyPrice: 2.3113952,
  },
  "a2-ultragpu-2g": {
    hourlyPrice: 3.5187904,
    windowsHourlyPrice: 4.6227904,
  },
  "a2-ultragpu-4g": {
    hourlyPrice: 7.0375808,
    windowsHourlyPrice: 9.2455808,
  },
  "a2-ultragpu-8g": {
    hourlyPrice: 14.0751616,
    windowsHourlyPrice: 18.4911616,
  },
  "a3-edgegpu-8g": {
    hourlyPrice: 15.13609136,
    windowsHourlyPrice: 24.70409136,
  },
  "a3-edgegpu-8g-nolssd": {
    hourlyPrice: 15.13609136,
    windowsHourlyPrice: 24.70409136,
  },
  "a3-highgpu-1g": {
    hourlyPrice: 1.89201142,
    windowsHourlyPrice: 3.08801142,
  },
  "a3-highgpu-2g": {
    hourlyPrice: 3.78402284,
    windowsHourlyPrice: 6.17602284,
  },
  "a3-highgpu-4g": {
    hourlyPrice: 7.56804568,
    windowsHourlyPrice: 12.35204568,
  },
  "a3-highgpu-8g": {
    hourlyPrice: 15.13609136,
    windowsHourlyPrice: 24.70409136,
  },
  "a3-megagpu-8g": {
    hourlyPrice: 15.13609136,
    windowsHourlyPrice: 24.70409136,
  },
  "a3-ultragpu-8g": {
    hourlyPrice: 19.62558352,
    windowsHourlyPrice: 29.92958352,
  },
  "a3-ultragpu-8g-nolssd": {
    hourlyPrice: 19.62558352,
    windowsHourlyPrice: 29.92958352,
  },
  "c2-standard-16": {
    hourlyPrice: 1.3363712,
    windowsHourlyPrice: 2.0723712,
  },
  "c2-standard-30": {
    hourlyPrice: 2.505696,
    windowsHourlyPrice: 3.885696,
  },
  "c2-standard-4": {
    hourlyPrice: 0.3340928,
    windowsHourlyPrice: 0.5180928,
  },
  "c2-standard-60": {
    hourlyPrice: 5.011392,
    windowsHourlyPrice: 7.771392,
  },
  "c2-standard-8": {
    hourlyPrice: 0.6681856,
    windowsHourlyPrice: 1.0361856,
  },
  "c2d-highcpu-112": {
    hourlyPrice: 6.7165952,
    windowsHourlyPrice: 11.8685952,
  },
  "c2d-highcpu-16": {
    hourlyPrice: 0.9595136,
    windowsHourlyPrice: 1.6955136,
  },
  "c2d-highcpu-2": {
    hourlyPrice: 0.1199392,
    windowsHourlyPrice: 0.2119392,
  },
  "c2d-highcpu-32": {
    hourlyPrice: 1.9190272,
    windowsHourlyPrice: 3.3910272,
  },
  "c2d-highcpu-4": {
    hourlyPrice: 0.2398784,
    windowsHourlyPrice: 0.4238784,
  },
  "c2d-highcpu-56": {
    hourlyPrice: 3.3582976,
    windowsHourlyPrice: 5.9342976,
  },
  "c2d-highcpu-8": {
    hourlyPrice: 0.4797568,
    windowsHourlyPrice: 0.8477568,
  },
  "c2d-highmem-112": {
    hourlyPrice: 10.973312,
    windowsHourlyPrice: 16.125312,
  },
  "c2d-highmem-16": {
    hourlyPrice: 1.567616,
    windowsHourlyPrice: 2.303616,
  },
  "c2d-highmem-2": {
    hourlyPrice: 0.195952,
    windowsHourlyPrice: 0.287952,
  },
  "c2d-highmem-32": {
    hourlyPrice: 3.135232,
    windowsHourlyPrice: 4.607232,
  },
  "c2d-highmem-4": {
    hourlyPrice: 0.391904,
    windowsHourlyPrice: 0.575904,
  },
  "c2d-highmem-56": {
    hourlyPrice: 5.486656,
    windowsHourlyPrice: 8.062656,
  },
  "c2d-highmem-8": {
    hourlyPrice: 0.783808,
    windowsHourlyPrice: 1.151808,
  },
  "c2d-standard-112": {
    hourlyPrice: 8.1355008,
    windowsHourlyPrice: 13.2875008,
  },
  "c2d-standard-16": {
    hourlyPrice: 1.1622144,
    windowsHourlyPrice: 1.8982144,
  },
  "c2d-standard-2": {
    hourlyPrice: 0.1452768,
    windowsHourlyPrice: 0.2372768,
  },
  "c2d-standard-32": {
    hourlyPrice: 2.3244288,
    windowsHourlyPrice: 3.7964288,
  },
  "c2d-standard-4": {
    hourlyPrice: 0.2905536,
    windowsHourlyPrice: 0.4745536,
  },
  "c2d-standard-56": {
    hourlyPrice: 4.0677504,
    windowsHourlyPrice: 6.6437504,
  },
  "c2d-standard-8": {
    hourlyPrice: 0.5811072,
    windowsHourlyPrice: 0.9491072,
  },
  "c3-highcpu-176": {
    hourlyPrice: 11.9753216,
    windowsHourlyPrice: 20.0713216,
  },
  "c3-highcpu-192-metal": {
    hourlyPrice: 13.8704896,
    windowsHourlyPrice: 22.7024896,
  },
  "c3-highcpu-22": {
    hourlyPrice: 1.4969152,
    windowsHourlyPrice: 2.5089152,
  },
  "c3-highcpu-4": {
    hourlyPrice: 0.2721664,
    windowsHourlyPrice: 0.4561664,
  },
  "c3-highcpu-44": {
    hourlyPrice: 2.9938304,
    windowsHourlyPrice: 5.0178304,
  },
  "c3-highcpu-8": {
    hourlyPrice: 0.5443328,
    windowsHourlyPrice: 0.9123328,
  },
  "c3-highcpu-88": {
    hourlyPrice: 5.9876608,
    windowsHourlyPrice: 10.0356608,
  },
  "c3-highmem-176": {
    hourlyPrice: 18.6289664,
    windowsHourlyPrice: 26.7249664,
  },
  "c3-highmem-192-metal": {
    hourlyPrice: 20.3225088,
    windowsHourlyPrice: 29.1545088,
  },
  "c3-highmem-22": {
    hourlyPrice: 2.3286208,
    windowsHourlyPrice: 3.3406208,
  },
  "c3-highmem-4": {
    hourlyPrice: 0.4233856,
    windowsHourlyPrice: 0.6073856,
  },
  "c3-highmem-44": {
    hourlyPrice: 4.6572416,
    windowsHourlyPrice: 6.6812416,
  },
  "c3-highmem-8": {
    hourlyPrice: 0.8467712,
    windowsHourlyPrice: 1.2147712,
  },
  "c3-highmem-88": {
    hourlyPrice: 9.3144832,
    windowsHourlyPrice: 13.3624832,
  },
  "c3-standard-176": {
    hourlyPrice: 14.1932032,
    windowsHourlyPrice: 22.2892032,
  },
  "c3-standard-176-lssd": {
    hourlyPrice: 14.1932032,
    windowsHourlyPrice: 22.2892032,
  },
  "c3-standard-192-metal": {
    hourlyPrice: 15.4834944,
    windowsHourlyPrice: 24.3154944,
  },
  "c3-standard-22": {
    hourlyPrice: 1.7741504,
    windowsHourlyPrice: 2.7861504,
  },
  "c3-standard-22-lssd": {
    hourlyPrice: 1.7741504,
    windowsHourlyPrice: 2.7861504,
  },
  "c3-standard-4": {
    hourlyPrice: 0.3225728,
    windowsHourlyPrice: 0.5065728,
  },
  "c3-standard-4-lssd": {
    hourlyPrice: 0.3225728,
    windowsHourlyPrice: 0.5065728,
  },
  "c3-standard-44": {
    hourlyPrice: 3.5483008,
    windowsHourlyPrice: 5.5723008,
  },
  "c3-standard-44-lssd": {
    hourlyPrice: 3.5483008,
    windowsHourlyPrice: 5.5723008,
  },
  "c3-standard-8": {
    hourlyPrice: 0.6451456,
    windowsHourlyPrice: 1.0131456,
  },
  "c3-standard-8-lssd": {
    hourlyPrice: 0.6451456,
    windowsHourlyPrice: 1.0131456,
  },
  "c3-standard-88": {
    hourlyPrice: 7.0966016,
    windowsHourlyPrice: 11.1446016,
  },
  "c3-standard-88-lssd": {
    hourlyPrice: 7.0966016,
    windowsHourlyPrice: 11.1446016,
  },
  "c3d-highcpu-16": {
    hourlyPrice: 0.9595136,
    windowsHourlyPrice: 1.6955136,
  },
  "c3d-highcpu-180": {
    hourlyPrice: 10.7565216,
    windowsHourlyPrice: 19.0365216,
  },
  "c3d-highcpu-30": {
    hourlyPrice: 1.7927536,
    windowsHourlyPrice: 3.1727536,
  },
  "c3d-highcpu-360": {
    hourlyPrice: 21.5130432,
    windowsHourlyPrice: 38.0730432,
  },
  "c3d-highcpu-4": {
    hourlyPrice: 0.2398784,
    windowsHourlyPrice: 0.4238784,
  },
  "c3d-highcpu-60": {
    hourlyPrice: 3.5855072,
    windowsHourlyPrice: 6.3455072,
  },
  "c3d-highcpu-8": {
    hourlyPrice: 0.4797568,
    windowsHourlyPrice: 0.8477568,
  },
  "c3d-highcpu-90": {
    hourlyPrice: 5.3782608,
    windowsHourlyPrice: 9.5182608,
  },
  "c3d-highmem-16": {
    hourlyPrice: 1.567616,
    windowsHourlyPrice: 2.303616,
  },
  "c3d-highmem-16-lssd": {
    hourlyPrice: 1.567616,
    windowsHourlyPrice: 2.303616,
  },
  "c3d-highmem-180": {
    hourlyPrice: 17.63568,
    windowsHourlyPrice: 25.91568,
  },
  "c3d-highmem-180-lssd": {
    hourlyPrice: 17.63568,
    windowsHourlyPrice: 25.91568,
  },
  "c3d-highmem-30": {
    hourlyPrice: 2.93928,
    windowsHourlyPrice: 4.31928,
  },
  "c3d-highmem-30-lssd": {
    hourlyPrice: 2.93928,
    windowsHourlyPrice: 4.31928,
  },
  "c3d-highmem-360": {
    hourlyPrice: 35.27136,
    windowsHourlyPrice: 51.83136,
  },
  "c3d-highmem-360-lssd": {
    hourlyPrice: 35.27136,
    windowsHourlyPrice: 51.83136,
  },
  "c3d-highmem-4": {
    hourlyPrice: 0.391904,
    windowsHourlyPrice: 0.575904,
  },
  "c3d-highmem-60": {
    hourlyPrice: 5.87856,
    windowsHourlyPrice: 8.63856,
  },
  "c3d-highmem-60-lssd": {
    hourlyPrice: 5.87856,
    windowsHourlyPrice: 8.63856,
  },
  "c3d-highmem-8": {
    hourlyPrice: 0.783808,
    windowsHourlyPrice: 1.151808,
  },
  "c3d-highmem-8-lssd": {
    hourlyPrice: 0.783808,
    windowsHourlyPrice: 1.151808,
  },
  "c3d-highmem-90": {
    hourlyPrice: 8.81784,
    windowsHourlyPrice: 12.95784,
  },
  "c3d-highmem-90-lssd": {
    hourlyPrice: 8.81784,
    windowsHourlyPrice: 12.95784,
  },
  "c3d-standard-16": {
    hourlyPrice: 1.1622144,
    windowsHourlyPrice: 1.8982144,
  },
  "c3d-standard-16-lssd": {
    hourlyPrice: 1.1622144,
    windowsHourlyPrice: 1.8982144,
  },
  "c3d-standard-180": {
    hourlyPrice: 13.074912,
    windowsHourlyPrice: 21.354912,
  },
  "c3d-standard-180-lssd": {
    hourlyPrice: 13.074912,
    windowsHourlyPrice: 21.354912,
  },
  "c3d-standard-30": {
    hourlyPrice: 2.179152,
    windowsHourlyPrice: 3.559152,
  },
  "c3d-standard-30-lssd": {
    hourlyPrice: 2.179152,
    windowsHourlyPrice: 3.559152,
  },
  "c3d-standard-360": {
    hourlyPrice: 26.149824,
    windowsHourlyPrice: 42.709824,
  },
  "c3d-standard-360-lssd": {
    hourlyPrice: 26.149824,
    windowsHourlyPrice: 42.709824,
  },
  "c3d-standard-4": {
    hourlyPrice: 0.2905536,
    windowsHourlyPrice: 0.4745536,
  },
  "c3d-standard-60": {
    hourlyPrice: 4.358304,
    windowsHourlyPrice: 7.118304,
  },
  "c3d-standard-60-lssd": {
    hourlyPrice: 4.358304,
    windowsHourlyPrice: 7.118304,
  },
  "c3d-standard-8": {
    hourlyPrice: 0.5811072,
    windowsHourlyPrice: 0.9491072,
  },
  "c3d-standard-8-lssd": {
    hourlyPrice: 0.5811072,
    windowsHourlyPrice: 0.9491072,
  },
  "c3d-standard-90": {
    hourlyPrice: 6.537456,
    windowsHourlyPrice: 10.677456,
  },
  "c3d-standard-90-lssd": {
    hourlyPrice: 6.537456,
    windowsHourlyPrice: 10.677456,
  },
  "c4-highcpu-144": {
    hourlyPrice: 9.7979904,
    windowsHourlyPrice: 16.4219904,
  },
  "c4-highcpu-16": {
    hourlyPrice: 1.0886656,
    windowsHourlyPrice: 1.8246656,
  },
  "c4-highcpu-192": {
    hourlyPrice: 13.0639872,
    windowsHourlyPrice: 21.8959872,
  },
  "c4-highcpu-2": {
    hourlyPrice: 0.1360832,
    windowsHourlyPrice: 0.2280832,
  },
  "c4-highcpu-24": {
    hourlyPrice: 1.6329984,
    windowsHourlyPrice: 2.7369984,
  },
  "c4-highcpu-288": {
    hourlyPrice: 19.5959808,
    windowsHourlyPrice: 32.8439808,
  },
  "c4-highcpu-32": {
    hourlyPrice: 2.1773312,
    windowsHourlyPrice: 3.6493312,
  },
  "c4-highcpu-4": {
    hourlyPrice: 0.2721664,
    windowsHourlyPrice: 0.4561664,
  },
  "c4-highcpu-48": {
    hourlyPrice: 3.2659968,
    windowsHourlyPrice: 5.4739968,
  },
  "c4-highcpu-8": {
    hourlyPrice: 0.5443328,
    windowsHourlyPrice: 0.9123328,
  },
  "c4-highcpu-96": {
    hourlyPrice: 6.5319936,
    windowsHourlyPrice: 10.9479936,
  },
  "c4-highmem-144": {
    hourlyPrice: 15.0150528,
    windowsHourlyPrice: 21.6390528,
  },
  "c4-highmem-144-lssd": {
    hourlyPrice: 15.0150528,
    windowsHourlyPrice: 21.6390528,
  },
  "c4-highmem-16": {
    hourlyPrice: 1.6683392,
    windowsHourlyPrice: 2.4043392,
  },
  "c4-highmem-16-lssd": {
    hourlyPrice: 1.6683392,
    windowsHourlyPrice: 2.4043392,
  },
  "c4-highmem-192": {
    hourlyPrice: 20.0200704,
    windowsHourlyPrice: 28.8520704,
  },
  "c4-highmem-192-lssd": {
    hourlyPrice: 20.0200704,
    windowsHourlyPrice: 28.8520704,
  },
  "c4-highmem-2": {
    hourlyPrice: 0.205392,
    windowsHourlyPrice: 0.297392,
  },
  "c4-highmem-24": {
    hourlyPrice: 2.5025088,
    windowsHourlyPrice: 3.6065088,
  },
  "c4-highmem-24-lssd": {
    hourlyPrice: 2.5025088,
    windowsHourlyPrice: 3.6065088,
  },
  "c4-highmem-288": {
    hourlyPrice: 30.0301056,
    windowsHourlyPrice: 43.2781056,
  },
  "c4-highmem-288-lssd": {
    hourlyPrice: 30.0301056,
    windowsHourlyPrice: 43.2781056,
  },
  "c4-highmem-288-lssd-metal": {
    hourlyPrice: 30.0301056,
    windowsHourlyPrice: 43.2781056,
  },
  "c4-highmem-288-metal": {
    hourlyPrice: 30.0301056,
    windowsHourlyPrice: 43.2781056,
  },
  "c4-highmem-32": {
    hourlyPrice: 3.3366784,
    windowsHourlyPrice: 4.8086784,
  },
  "c4-highmem-32-lssd": {
    hourlyPrice: 3.3366784,
    windowsHourlyPrice: 4.8086784,
  },
  "c4-highmem-4": {
    hourlyPrice: 0.4170848,
    windowsHourlyPrice: 0.6010848,
  },
  "c4-highmem-4-lssd": {
    hourlyPrice: 0.4170848,
    windowsHourlyPrice: 0.6010848,
  },
  "c4-highmem-48": {
    hourlyPrice: 5.0050176,
    windowsHourlyPrice: 7.2130176,
  },
  "c4-highmem-48-lssd": {
    hourlyPrice: 5.0050176,
    windowsHourlyPrice: 7.2130176,
  },
  "c4-highmem-8": {
    hourlyPrice: 0.8341696,
    windowsHourlyPrice: 1.2021696,
  },
  "c4-highmem-8-lssd": {
    hourlyPrice: 0.8341696,
    windowsHourlyPrice: 1.2021696,
  },
  "c4-highmem-96": {
    hourlyPrice: 10.0100352,
    windowsHourlyPrice: 14.4260352,
  },
  "c4-highmem-96-lssd": {
    hourlyPrice: 10.0100352,
    windowsHourlyPrice: 14.4260352,
  },
  "c4-standard-144": {
    hourlyPrice: 11.385792,
    windowsHourlyPrice: 18.009792,
  },
  "c4-standard-144-lssd": {
    hourlyPrice: 11.385792,
    windowsHourlyPrice: 18.009792,
  },
  "c4-standard-16": {
    hourlyPrice: 1.265088,
    windowsHourlyPrice: 2.001088,
  },
  "c4-standard-16-lssd": {
    hourlyPrice: 1.265088,
    windowsHourlyPrice: 2.001088,
  },
  "c4-standard-192": {
    hourlyPrice: 15.181056,
    windowsHourlyPrice: 24.013056,
  },
  "c4-standard-192-lssd": {
    hourlyPrice: 15.181056,
    windowsHourlyPrice: 24.013056,
  },
  "c4-standard-2": {
    hourlyPrice: 0.1549856,
    windowsHourlyPrice: 0.2469856,
  },
  "c4-standard-24": {
    hourlyPrice: 1.897632,
    windowsHourlyPrice: 3.001632,
  },
  "c4-standard-24-lssd": {
    hourlyPrice: 1.897632,
    windowsHourlyPrice: 3.001632,
  },
  "c4-standard-288": {
    hourlyPrice: 22.771584,
    windowsHourlyPrice: 36.019584,
  },
  "c4-standard-288-lssd": {
    hourlyPrice: 22.771584,
    windowsHourlyPrice: 36.019584,
  },
  "c4-standard-288-lssd-metal": {
    hourlyPrice: 22.771584,
    windowsHourlyPrice: 36.019584,
  },
  "c4-standard-288-metal": {
    hourlyPrice: 22.771584,
    windowsHourlyPrice: 36.019584,
  },
  "c4-standard-32": {
    hourlyPrice: 2.530176,
    windowsHourlyPrice: 4.002176,
  },
  "c4-standard-32-lssd": {
    hourlyPrice: 2.530176,
    windowsHourlyPrice: 4.002176,
  },
  "c4-standard-4": {
    hourlyPrice: 0.316272,
    windowsHourlyPrice: 0.500272,
  },
  "c4-standard-4-lssd": {
    hourlyPrice: 0.316272,
    windowsHourlyPrice: 0.500272,
  },
  "c4-standard-48": {
    hourlyPrice: 3.795264,
    windowsHourlyPrice: 6.003264,
  },
  "c4-standard-48-lssd": {
    hourlyPrice: 3.795264,
    windowsHourlyPrice: 6.003264,
  },
  "c4-standard-8": {
    hourlyPrice: 0.632544,
    windowsHourlyPrice: 1.000544,
  },
  "c4-standard-8-lssd": {
    hourlyPrice: 0.632544,
    windowsHourlyPrice: 1.000544,
  },
  "c4-standard-96": {
    hourlyPrice: 7.590528,
    windowsHourlyPrice: 12.006528,
  },
  "c4-standard-96-lssd": {
    hourlyPrice: 7.590528,
    windowsHourlyPrice: 12.006528,
  },
  "c4a-highcpu-1": {
    hourlyPrice: 0.06062,
    windowsHourlyPrice: 0.10662,
  },
  "c4a-highcpu-16": {
    hourlyPrice: 0.96992,
    windowsHourlyPrice: 1.70592,
  },
  "c4a-highcpu-2": {
    hourlyPrice: 0.12124,
    windowsHourlyPrice: 0.21324,
  },
  "c4a-highcpu-32": {
    hourlyPrice: 1.93984,
    windowsHourlyPrice: 3.41184,
  },
  "c4a-highcpu-4": {
    hourlyPrice: 0.24248,
    windowsHourlyPrice: 0.42648,
  },
  "c4a-highcpu-48": {
    hourlyPrice: 2.90976,
    windowsHourlyPrice: 5.11776,
  },
  "c4a-highcpu-64": {
    hourlyPrice: 3.87968,
    windowsHourlyPrice: 6.82368,
  },
  "c4a-highcpu-72": {
    hourlyPrice: 4.36464,
    windowsHourlyPrice: 7.67664,
  },
  "c4a-highcpu-8": {
    hourlyPrice: 0.48496,
    windowsHourlyPrice: 0.85296,
  },
  "c4a-highmem-1": {
    hourlyPrice: 0.09434,
    windowsHourlyPrice: 0.14034,
  },
  "c4a-highmem-16": {
    hourlyPrice: 1.50944,
    windowsHourlyPrice: 2.24544,
  },
  "c4a-highmem-16-lssd": {
    hourlyPrice: 1.90396055,
    windowsHourlyPrice: 2.63996055,
  },
  "c4a-highmem-2": {
    hourlyPrice: 0.18868,
    windowsHourlyPrice: 0.28068,
  },
  "c4a-highmem-32": {
    hourlyPrice: 3.01888,
    windowsHourlyPrice: 4.49088,
  },
  "c4a-highmem-32-lssd": {
    hourlyPrice: 3.61066082,
    windowsHourlyPrice: 5.08266082,
  },
  "c4a-highmem-4": {
    hourlyPrice: 0.37736,
    windowsHourlyPrice: 0.56136,
  },
  "c4a-highmem-4-lssd": {
    hourlyPrice: 0.47599014,
    windowsHourlyPrice: 0.65999014,
  },
  "c4a-highmem-48": {
    hourlyPrice: 4.52832,
    windowsHourlyPrice: 6.73632,
  },
  "c4a-highmem-48-lssd": {
    hourlyPrice: 5.51462137,
    windowsHourlyPrice: 7.72262137,
  },
  "c4a-highmem-64": {
    hourlyPrice: 6.03776,
    windowsHourlyPrice: 8.98176,
  },
  "c4a-highmem-64-lssd": {
    hourlyPrice: 7.41858192,
    windowsHourlyPrice: 10.36258192,
  },
  "c4a-highmem-72": {
    hourlyPrice: 6.79248,
    windowsHourlyPrice: 10.10448,
  },
  "c4a-highmem-72-lssd": {
    hourlyPrice: 8.37056219,
    windowsHourlyPrice: 11.68256219,
  },
  "c4a-highmem-8": {
    hourlyPrice: 0.75472,
    windowsHourlyPrice: 1.12272,
  },
  "c4a-highmem-8-lssd": {
    hourlyPrice: 0.95198027,
    windowsHourlyPrice: 1.31998027,
  },
  "c4a-highmem-96-metal": {
    hourlyPrice: 9.05664,
    windowsHourlyPrice: 13.47264,
  },
  "c4a-standard-1": {
    hourlyPrice: 0.07186,
    windowsHourlyPrice: 0.11786,
  },
  "c4a-standard-16": {
    hourlyPrice: 1.14976,
    windowsHourlyPrice: 1.88576,
  },
  "c4a-standard-16-lssd": {
    hourlyPrice: 1.54428055,
    windowsHourlyPrice: 2.28028055,
  },
  "c4a-standard-2": {
    hourlyPrice: 0.14372,
    windowsHourlyPrice: 0.23572,
  },
  "c4a-standard-32": {
    hourlyPrice: 2.29952,
    windowsHourlyPrice: 3.77152,
  },
  "c4a-standard-32-lssd": {
    hourlyPrice: 2.89130082,
    windowsHourlyPrice: 4.36330082,
  },
  "c4a-standard-4": {
    hourlyPrice: 0.28744,
    windowsHourlyPrice: 0.47144,
  },
  "c4a-standard-4-lssd": {
    hourlyPrice: 0.38607014,
    windowsHourlyPrice: 0.57007014,
  },
  "c4a-standard-48": {
    hourlyPrice: 3.44928,
    windowsHourlyPrice: 5.65728,
  },
  "c4a-standard-48-lssd": {
    hourlyPrice: 4.43558137,
    windowsHourlyPrice: 6.64358137,
  },
  "c4a-standard-64": {
    hourlyPrice: 4.59904,
    windowsHourlyPrice: 7.54304,
  },
  "c4a-standard-64-lssd": {
    hourlyPrice: 5.97986192,
    windowsHourlyPrice: 8.92386192,
  },
  "c4a-standard-72": {
    hourlyPrice: 5.17392,
    windowsHourlyPrice: 8.48592,
  },
  "c4a-standard-72-lssd": {
    hourlyPrice: 6.75200219,
    windowsHourlyPrice: 10.06400219,
  },
  "c4a-standard-8": {
    hourlyPrice: 0.57488,
    windowsHourlyPrice: 0.94288,
  },
  "c4a-standard-8-lssd": {
    hourlyPrice: 0.77214027,
    windowsHourlyPrice: 1.14014027,
  },
  "c4d-highcpu-16": {
    hourlyPrice: 1.01737032,
    windowsHourlyPrice: 1.75337032,
  },
  "c4d-highcpu-192": {
    hourlyPrice: 12.2084439,
    windowsHourlyPrice: 21.0404439,
  },
  "c4d-highcpu-2": {
    hourlyPrice: 0.12266727,
    windowsHourlyPrice: 0.21466727,
  },
  "c4d-highcpu-32": {
    hourlyPrice: 2.03474065,
    windowsHourlyPrice: 3.50674065,
  },
  "c4d-highcpu-384": {
    hourlyPrice: 24.41688779,
    windowsHourlyPrice: 42.08088779,
  },
  "c4d-highcpu-384-metal": {
    hourlyPrice: 24.70514495,
    windowsHourlyPrice: 42.36914495,
  },
  "c4d-highcpu-4": {
    hourlyPrice: 0.2513399,
    windowsHourlyPrice: 0.4353399,
  },
  "c4d-highcpu-48": {
    hourlyPrice: 3.05211097,
    windowsHourlyPrice: 5.26011097,
  },
  "c4d-highcpu-64": {
    hourlyPrice: 4.0694813,
    windowsHourlyPrice: 7.0134813,
  },
  "c4d-highcpu-8": {
    hourlyPrice: 0.50868516,
    windowsHourlyPrice: 0.87668516,
  },
  "c4d-highcpu-96": {
    hourlyPrice: 6.10422195,
    windowsHourlyPrice: 10.52022195,
  },
  "c4d-highmem-16": {
    hourlyPrice: 1.59388464,
    windowsHourlyPrice: 2.32988464,
  },
  "c4d-highmem-16-lssd": {
    hourlyPrice: 1.72539149,
    windowsHourlyPrice: 2.46139149,
  },
  "c4d-highmem-192": {
    hourlyPrice: 19.12661573,
    windowsHourlyPrice: 27.95861573,
  },
  "c4d-highmem-192-lssd": {
    hourlyPrice: 21.23072532,
    windowsHourlyPrice: 30.06272532,
  },
  "c4d-highmem-2": {
    hourlyPrice: 0.19473156,
    windowsHourlyPrice: 0.28673156,
  },
  "c4d-highmem-32": {
    hourlyPrice: 3.18776929,
    windowsHourlyPrice: 4.65976929,
  },
  "c4d-highmem-32-lssd": {
    hourlyPrice: 3.45078299,
    windowsHourlyPrice: 4.92278299,
  },
  "c4d-highmem-384": {
    hourlyPrice: 38.25323145,
    windowsHourlyPrice: 55.91723145,
  },
  "c4d-highmem-384-lssd": {
    hourlyPrice: 42.46145063,
    windowsHourlyPrice: 60.12545063,
  },
  "c4d-highmem-384-metal": {
    hourlyPrice: 38.54148861,
    windowsHourlyPrice: 56.20548861,
  },
  "c4d-highmem-4": {
    hourlyPrice: 0.39546848,
    windowsHourlyPrice: 0.57946848,
  },
  "c4d-highmem-48": {
    hourlyPrice: 4.78165393,
    windowsHourlyPrice: 6.98965393,
  },
  "c4d-highmem-48-lssd": {
    hourlyPrice: 5.30768133,
    windowsHourlyPrice: 7.51568133,
  },
  "c4d-highmem-64": {
    hourlyPrice: 6.37553858,
    windowsHourlyPrice: 9.31953858,
  },
  "c4d-highmem-64-lssd": {
    hourlyPrice: 7.16457967,
    windowsHourlyPrice: 10.10857967,
  },
  "c4d-highmem-8": {
    hourlyPrice: 0.79694232,
    windowsHourlyPrice: 1.16494232,
  },
  "c4d-highmem-8-lssd": {
    hourlyPrice: 0.92844917,
    windowsHourlyPrice: 1.29644917,
  },
  "c4d-highmem-96": {
    hourlyPrice: 9.56330786,
    windowsHourlyPrice: 13.97930786,
  },
  "c4d-highmem-96-lssd": {
    hourlyPrice: 10.61536266,
    windowsHourlyPrice: 15.03136266,
  },
  "c4d-standard-16": {
    hourlyPrice: 1.20954176,
    windowsHourlyPrice: 1.94554176,
  },
  "c4d-standard-16-lssd": {
    hourlyPrice: 1.34104861,
    windowsHourlyPrice: 2.07704861,
  },
  "c4d-standard-192": {
    hourlyPrice: 14.51450117,
    windowsHourlyPrice: 23.34650117,
  },
  "c4d-standard-192-lssd": {
    hourlyPrice: 16.61861076,
    windowsHourlyPrice: 25.45061076,
  },
  "c4d-standard-2": {
    hourlyPrice: 0.1466887,
    windowsHourlyPrice: 0.2386887,
  },
  "c4d-standard-32": {
    hourlyPrice: 2.41908353,
    windowsHourlyPrice: 3.89108353,
  },
  "c4d-standard-32-lssd": {
    hourlyPrice: 2.68209723,
    windowsHourlyPrice: 4.15409723,
  },
  "c4d-standard-384": {
    hourlyPrice: 29.02900235,
    windowsHourlyPrice: 46.69300235,
  },
  "c4d-standard-384-lssd": {
    hourlyPrice: 33.23722152,
    windowsHourlyPrice: 50.90122152,
  },
  "c4d-standard-384-metal": {
    hourlyPrice: 29.31725951,
    windowsHourlyPrice: 46.98125951,
  },
  "c4d-standard-4": {
    hourlyPrice: 0.29938276,
    windowsHourlyPrice: 0.48338276,
  },
  "c4d-standard-48": {
    hourlyPrice: 3.62862529,
    windowsHourlyPrice: 5.83662529,
  },
  "c4d-standard-48-lssd": {
    hourlyPrice: 4.15465269,
    windowsHourlyPrice: 6.36265269,
  },
  "c4d-standard-64": {
    hourlyPrice: 4.83816706,
    windowsHourlyPrice: 7.78216706,
  },
  "c4d-standard-64-lssd": {
    hourlyPrice: 5.62720815,
    windowsHourlyPrice: 8.57120815,
  },
  "c4d-standard-8": {
    hourlyPrice: 0.60477088,
    windowsHourlyPrice: 0.97277088,
  },
  "c4d-standard-8-lssd": {
    hourlyPrice: 0.73627773,
    windowsHourlyPrice: 1.10427773,
  },
  "c4d-standard-96": {
    hourlyPrice: 7.25725059,
    windowsHourlyPrice: 11.67325059,
  },
  "c4d-standard-96-lssd": {
    hourlyPrice: 8.30930538,
    windowsHourlyPrice: 12.72530538,
  },
  "e2-highcpu-16": {
    hourlyPrice: 0.63321904,
    windowsHourlyPrice: 1.36921904,
  },
  "e2-highcpu-2": {
    hourlyPrice: 0.07915238,
    windowsHourlyPrice: 0.17115238,
  },
  "e2-highcpu-32": {
    hourlyPrice: 1.26643808,
    windowsHourlyPrice: 2.73843808,
  },
  "e2-highcpu-4": {
    hourlyPrice: 0.15830476,
    windowsHourlyPrice: 0.34230476,
  },
  "e2-highcpu-8": {
    hourlyPrice: 0.31660952,
    windowsHourlyPrice: 0.68460952,
  },
  "e2-highmem-16": {
    hourlyPrice: 1.15711584,
    windowsHourlyPrice: 1.89311584,
  },
  "e2-highmem-2": {
    hourlyPrice: 0.14463948,
    windowsHourlyPrice: 0.23663948,
  },
  "e2-highmem-4": {
    hourlyPrice: 0.28927896,
    windowsHourlyPrice: 0.47327896,
  },
  "e2-highmem-8": {
    hourlyPrice: 0.57855792,
    windowsHourlyPrice: 0.94655792,
  },
  "e2-medium": {
    hourlyPrice: 0.08850768,
    windowsHourlyPrice: 0.18050768,
  },
  "e2-micro": {
    hourlyPrice: 0.07447473,
    windowsHourlyPrice: 0.16647473,
  },
  "e2-small": {
    hourlyPrice: 0.07915238,
    windowsHourlyPrice: 0.17115238,
  },
  "e2-standard-16": {
    hourlyPrice: 0.85774624,
    windowsHourlyPrice: 1.59374624,
  },
  "e2-standard-2": {
    hourlyPrice: 0.10721828,
    windowsHourlyPrice: 0.19921828,
  },
  "e2-standard-32": {
    hourlyPrice: 1.71549248,
    windowsHourlyPrice: 3.18749248,
  },
  "e2-standard-4": {
    hourlyPrice: 0.21443656,
    windowsHourlyPrice: 0.39843656,
  },
  "e2-standard-8": {
    hourlyPrice: 0.42887312,
    windowsHourlyPrice: 0.79687312,
  },
  "g2-standard-12": {
    hourlyPrice: 0.70460184,
    windowsHourlyPrice: 1.25660184,
  },
  "g2-standard-16": {
    hourlyPrice: 0.93946912,
    windowsHourlyPrice: 1.67546912,
  },
  "g2-standard-24": {
    hourlyPrice: 1.40920368,
    windowsHourlyPrice: 2.51320368,
  },
  "g2-standard-32": {
    hourlyPrice: 1.87893824,
    windowsHourlyPrice: 3.35093824,
  },
  "g2-standard-4": {
    hourlyPrice: 0.23486728,
    windowsHourlyPrice: 0.41886728,
  },
  "g2-standard-48": {
    hourlyPrice: 2.81840736,
    windowsHourlyPrice: 5.02640736,
  },
  "g2-standard-8": {
    hourlyPrice: 0.46973456,
    windowsHourlyPrice: 0.83773456,
  },
  "g2-standard-96": {
    hourlyPrice: 5.63681472,
    windowsHourlyPrice: 10.05281472,
  },
  "h3-standard-88": {
    hourlyPrice: 7.87776,
    windowsHourlyPrice: 11.92576,
  },
  "m1-megamem-96": {
    hourlyPrice: 17.04345281,
    windowsHourlyPrice: 21.45945281,
  },
  "m1-ultramem-160": {
    hourlyPrice: 40.27584,
    windowsHourlyPrice: 47.63584,
  },
  "m1-ultramem-40": {
    hourlyPrice: 10.06896,
    windowsHourlyPrice: 11.90896,
  },
  "m1-ultramem-80": {
    hourlyPrice: 20.13792,
    windowsHourlyPrice: 23.81792,
  },
  "m2-hypermem-416": {
    hourlyPrice: 107.61216,
    windowsHourlyPrice: 126.74816,
  },
  "m2-megamem-416": {
    hourlyPrice: 80.4661248,
    windowsHourlyPrice: 99.6021248,
  },
  "m2-ultramem-208": {
    hourlyPrice: 67.3790976,
    windowsHourlyPrice: 76.9470976,
  },
  "m2-ultramem-416": {
    hourlyPrice: 134.7581952,
    windowsHourlyPrice: 153.8941952,
  },
  "m2-ultramem2x-96": {
    hourlyPrice: 17.5661664,
    windowsHourlyPrice: 21.9821664,
  },
  "m2-ultramemx-96": {
    hourlyPrice: 11.5726464,
    windowsHourlyPrice: 15.9886464,
  },
  "m3-megamem-128": {
    hourlyPrice: 23.05536,
    windowsHourlyPrice: 28.94336,
  },
  "m3-megamem-64": {
    hourlyPrice: 11.52768,
    windowsHourlyPrice: 14.47168,
  },
  "m3-ultramem-128": {
    hourlyPrice: 38.98368,
    windowsHourlyPrice: 44.87168,
  },
  "m3-ultramem-32": {
    hourlyPrice: 9.74592,
    windowsHourlyPrice: 11.21792,
  },
  "m3-ultramem-64": {
    hourlyPrice: 19.49184,
    windowsHourlyPrice: 22.43584,
  },
  "m4-hypermem-16": {
    hourlyPrice: 2.2808064,
    windowsHourlyPrice: 3.0168064,
  },
  "m4-hypermem-32": {
    hourlyPrice: 4.5616128,
    windowsHourlyPrice: 6.0336128,
  },
  "m4-hypermem-64": {
    hourlyPrice: 9.1232256,
    windowsHourlyPrice: 12.0672256,
  },
  "m4-megamem-112": {
    hourlyPrice: 14.1527648,
    windowsHourlyPrice: 19.3047648,
  },
  "m4-megamem-224": {
    hourlyPrice: 28.3055296,
    windowsHourlyPrice: 38.6095296,
  },
  "m4-megamem-28": {
    hourlyPrice: 3.5381912,
    windowsHourlyPrice: 4.8261912,
  },
  "m4-megamem-56": {
    hourlyPrice: 7.0763824,
    windowsHourlyPrice: 9.6523824,
  },
  "m4-ultramem-112": {
    hourlyPrice: 25.0300448,
    windowsHourlyPrice: 30.1820448,
  },
  "m4-ultramem-224": {
    hourlyPrice: 50.0600896,
    windowsHourlyPrice: 60.3640896,
  },
  "m4-ultramem-56": {
    hourlyPrice: 12.5150224,
    windowsHourlyPrice: 15.0910224,
  },
  "m4n-hypermem-16": {
    hourlyPrice: 4.1064448,
    windowsHourlyPrice: 4.8424448,
  },
  "m4n-hypermem-32": {
    hourlyPrice: 8.2128896,
    windowsHourlyPrice: 9.6848896,
  },
  "m4n-hypermem-64": {
    hourlyPrice: 16.4257792,
    windowsHourlyPrice: 19.3697792,
  },
  "m4n-megamem-112": {
    hourlyPrice: 25.4809376,
    windowsHourlyPrice: 30.6329376,
  },
  "m4n-megamem-224": {
    hourlyPrice: 50.9618752,
    windowsHourlyPrice: 61.2658752,
  },
  "m4n-megamem-28": {
    hourlyPrice: 6.3702344,
    windowsHourlyPrice: 7.6582344,
  },
  "m4n-megamem-56": {
    hourlyPrice: 12.7404688,
    windowsHourlyPrice: 15.3164688,
  },
  "m4n-ultramem-112": {
    hourlyPrice: 45.0659936,
    windowsHourlyPrice: 50.2179936,
  },
  "m4n-ultramem-224": {
    hourlyPrice: 90.1319872,
    windowsHourlyPrice: 100.4359872,
  },
  "m4n-ultramem-56": {
    hourlyPrice: 22.5329968,
    windowsHourlyPrice: 25.1089968,
  },
  "n1-highcpu-16": {
    hourlyPrice: 0.90686473,
    windowsHourlyPrice: 1.64286473,
  },
  "n1-highcpu-2": {
    hourlyPrice: 0.11335644,
    windowsHourlyPrice: 0.20535644,
  },
  "n1-highcpu-32": {
    hourlyPrice: 1.81372284,
    windowsHourlyPrice: 3.28572284,
  },
  "n1-highcpu-4": {
    hourlyPrice: 0.22671287,
    windowsHourlyPrice: 0.41071287,
  },
  "n1-highcpu-64": {
    hourlyPrice: 3.62744567,
    windowsHourlyPrice: 6.57144567,
  },
  "n1-highcpu-8": {
    hourlyPrice: 0.45343236,
    windowsHourlyPrice: 0.82143236,
  },
  "n1-highcpu-96": {
    hourlyPrice: 5.44117513,
    windowsHourlyPrice: 9.85717513,
  },
  "n1-highmem-16": {
    hourlyPrice: 1.5142784,
    windowsHourlyPrice: 2.2502784,
  },
  "n1-highmem-2": {
    hourlyPrice: 0.1892848,
    windowsHourlyPrice: 0.2812848,
  },
  "n1-highmem-32": {
    hourlyPrice: 3.0285568,
    windowsHourlyPrice: 4.5005568,
  },
  "n1-highmem-4": {
    hourlyPrice: 0.3785696,
    windowsHourlyPrice: 0.5625696,
  },
  "n1-highmem-64": {
    hourlyPrice: 6.0571136,
    windowsHourlyPrice: 9.0011136,
  },
  "n1-highmem-8": {
    hourlyPrice: 0.7571392,
    windowsHourlyPrice: 1.1251392,
  },
  "n1-highmem-96": {
    hourlyPrice: 9.0856704,
    windowsHourlyPrice: 13.5016704,
  },
  "n1-megamem-96": {
    hourlyPrice: 14.57410807,
    windowsHourlyPrice: 18.99010807,
  },
  "n1-standard-1": {
    hourlyPrice: 0.0759996,
    windowsHourlyPrice: 0.1219996,
  },
  "n1-standard-16": {
    hourlyPrice: 1.2159936,
    windowsHourlyPrice: 1.9519936,
  },
  "n1-standard-2": {
    hourlyPrice: 0.1519992,
    windowsHourlyPrice: 0.2439992,
  },
  "n1-standard-32": {
    hourlyPrice: 2.4319872,
    windowsHourlyPrice: 3.9039872,
  },
  "n1-standard-4": {
    hourlyPrice: 0.3039984,
    windowsHourlyPrice: 0.4879984,
  },
  "n1-standard-64": {
    hourlyPrice: 4.8639744,
    windowsHourlyPrice: 7.8079744,
  },
  "n1-standard-8": {
    hourlyPrice: 0.6079968,
    windowsHourlyPrice: 0.9759968,
  },
  "n1-standard-96": {
    hourlyPrice: 7.2959616,
    windowsHourlyPrice: 11.7119616,
  },
  "n1-ultramem-160": {
    hourlyPrice: 34.1516608,
    windowsHourlyPrice: 41.5116608,
  },
  "n1-ultramem-40": {
    hourlyPrice: 8.5379152,
    windowsHourlyPrice: 10.3779152,
  },
  "n1-ultramem-80": {
    hourlyPrice: 17.0758304,
    windowsHourlyPrice: 20.7558304,
  },
  "n2-highcpu-16": {
    hourlyPrice: 0.9177088,
    windowsHourlyPrice: 1.6537088,
  },
  "n2-highcpu-2": {
    hourlyPrice: 0.1147136,
    windowsHourlyPrice: 0.2067136,
  },
  "n2-highcpu-32": {
    hourlyPrice: 1.8354176,
    windowsHourlyPrice: 3.3074176,
  },
  "n2-highcpu-4": {
    hourlyPrice: 0.2294272,
    windowsHourlyPrice: 0.4134272,
  },
  "n2-highcpu-48": {
    hourlyPrice: 2.7531264,
    windowsHourlyPrice: 4.9611264,
  },
  "n2-highcpu-64": {
    hourlyPrice: 3.6708352,
    windowsHourlyPrice: 6.6148352,
  },
  "n2-highcpu-8": {
    hourlyPrice: 0.4588544,
    windowsHourlyPrice: 0.8268544,
  },
  "n2-highcpu-80": {
    hourlyPrice: 4.588544,
    windowsHourlyPrice: 8.268544,
  },
  "n2-highcpu-96": {
    hourlyPrice: 5.5062528,
    windowsHourlyPrice: 9.9222528,
  },
  "n2-highmem-128": {
    hourlyPrice: 12.3311616,
    windowsHourlyPrice: 18.2191616,
  },
  "n2-highmem-16": {
    hourlyPrice: 1.6769792,
    windowsHourlyPrice: 2.4129792,
  },
  "n2-highmem-2": {
    hourlyPrice: 0.2096224,
    windowsHourlyPrice: 0.3016224,
  },
  "n2-highmem-32": {
    hourlyPrice: 3.3539584,
    windowsHourlyPrice: 4.8259584,
  },
  "n2-highmem-4": {
    hourlyPrice: 0.4192448,
    windowsHourlyPrice: 0.6032448,
  },
  "n2-highmem-48": {
    hourlyPrice: 5.0309376,
    windowsHourlyPrice: 7.2389376,
  },
  "n2-highmem-64": {
    hourlyPrice: 6.7079168,
    windowsHourlyPrice: 9.6519168,
  },
  "n2-highmem-8": {
    hourlyPrice: 0.8384896,
    windowsHourlyPrice: 1.2064896,
  },
  "n2-highmem-80": {
    hourlyPrice: 8.384896,
    windowsHourlyPrice: 12.064896,
  },
  "n2-highmem-96": {
    hourlyPrice: 10.0618752,
    windowsHourlyPrice: 14.4778752,
  },
  "n2-standard-128": {
    hourlyPrice: 9.9448832,
    windowsHourlyPrice: 15.8328832,
  },
  "n2-standard-16": {
    hourlyPrice: 1.2431104,
    windowsHourlyPrice: 1.9791104,
  },
  "n2-standard-2": {
    hourlyPrice: 0.1553888,
    windowsHourlyPrice: 0.2473888,
  },
  "n2-standard-32": {
    hourlyPrice: 2.4862208,
    windowsHourlyPrice: 3.9582208,
  },
  "n2-standard-4": {
    hourlyPrice: 0.3107776,
    windowsHourlyPrice: 0.4947776,
  },
  "n2-standard-48": {
    hourlyPrice: 3.7293312,
    windowsHourlyPrice: 5.9373312,
  },
  "n2-standard-64": {
    hourlyPrice: 4.9724416,
    windowsHourlyPrice: 7.9164416,
  },
  "n2-standard-8": {
    hourlyPrice: 0.6215552,
    windowsHourlyPrice: 0.9895552,
  },
  "n2-standard-80": {
    hourlyPrice: 6.215552,
    windowsHourlyPrice: 9.895552,
  },
  "n2-standard-96": {
    hourlyPrice: 7.4586624,
    windowsHourlyPrice: 11.8746624,
  },
  "n2d-highcpu-128": {
    hourlyPrice: 6.3873024,
    windowsHourlyPrice: 12.2753024,
  },
  "n2d-highcpu-16": {
    hourlyPrice: 0.7984128,
    windowsHourlyPrice: 1.5344128,
  },
  "n2d-highcpu-2": {
    hourlyPrice: 0.0998016,
    windowsHourlyPrice: 0.1918016,
  },
  "n2d-highcpu-224": {
    hourlyPrice: 11.1777792,
    windowsHourlyPrice: 21.4817792,
  },
  "n2d-highcpu-32": {
    hourlyPrice: 1.5968256,
    windowsHourlyPrice: 3.0688256,
  },
  "n2d-highcpu-4": {
    hourlyPrice: 0.1996032,
    windowsHourlyPrice: 0.3836032,
  },
  "n2d-highcpu-48": {
    hourlyPrice: 2.3952384,
    windowsHourlyPrice: 4.6032384,
  },
  "n2d-highcpu-64": {
    hourlyPrice: 3.1936512,
    windowsHourlyPrice: 6.1376512,
  },
  "n2d-highcpu-8": {
    hourlyPrice: 0.3992064,
    windowsHourlyPrice: 0.7672064,
  },
  "n2d-highcpu-80": {
    hourlyPrice: 3.992064,
    windowsHourlyPrice: 7.672064,
  },
  "n2d-highcpu-96": {
    hourlyPrice: 4.7904768,
    windowsHourlyPrice: 9.2064768,
  },
  "n2d-highmem-16": {
    hourlyPrice: 1.458944,
    windowsHourlyPrice: 2.194944,
  },
  "n2d-highmem-2": {
    hourlyPrice: 0.182368,
    windowsHourlyPrice: 0.274368,
  },
  "n2d-highmem-32": {
    hourlyPrice: 2.917888,
    windowsHourlyPrice: 4.389888,
  },
  "n2d-highmem-4": {
    hourlyPrice: 0.364736,
    windowsHourlyPrice: 0.548736,
  },
  "n2d-highmem-48": {
    hourlyPrice: 4.376832,
    windowsHourlyPrice: 6.584832,
  },
  "n2d-highmem-64": {
    hourlyPrice: 5.835776,
    windowsHourlyPrice: 8.779776,
  },
  "n2d-highmem-8": {
    hourlyPrice: 0.729472,
    windowsHourlyPrice: 1.097472,
  },
  "n2d-highmem-80": {
    hourlyPrice: 7.29472,
    windowsHourlyPrice: 10.97472,
  },
  "n2d-highmem-96": {
    hourlyPrice: 8.753664,
    windowsHourlyPrice: 13.169664,
  },
  "n2d-standard-128": {
    hourlyPrice: 8.6519808,
    windowsHourlyPrice: 14.5399808,
  },
  "n2d-standard-16": {
    hourlyPrice: 1.0814976,
    windowsHourlyPrice: 1.8174976,
  },
  "n2d-standard-2": {
    hourlyPrice: 0.1351872,
    windowsHourlyPrice: 0.2271872,
  },
  "n2d-standard-224": {
    hourlyPrice: 15.1409664,
    windowsHourlyPrice: 25.4449664,
  },
  "n2d-standard-32": {
    hourlyPrice: 2.1629952,
    windowsHourlyPrice: 3.6349952,
  },
  "n2d-standard-4": {
    hourlyPrice: 0.2703744,
    windowsHourlyPrice: 0.4543744,
  },
  "n2d-standard-48": {
    hourlyPrice: 3.2444928,
    windowsHourlyPrice: 5.4524928,
  },
  "n2d-standard-64": {
    hourlyPrice: 4.3259904,
    windowsHourlyPrice: 7.2699904,
  },
  "n2d-standard-8": {
    hourlyPrice: 0.5407488,
    windowsHourlyPrice: 0.9087488,
  },
  "n2d-standard-80": {
    hourlyPrice: 5.407488,
    windowsHourlyPrice: 9.087488,
  },
  "n2d-standard-96": {
    hourlyPrice: 6.4889856,
    windowsHourlyPrice: 10.9049856,
  },
  "n4-highcpu-16": {
    hourlyPrice: 0.979712,
    windowsHourlyPrice: 1.715712,
  },
  "n4-highcpu-2": {
    hourlyPrice: 0.122464,
    windowsHourlyPrice: 0.214464,
  },
  "n4-highcpu-32": {
    hourlyPrice: 1.959424,
    windowsHourlyPrice: 3.431424,
  },
  "n4-highcpu-4": {
    hourlyPrice: 0.244928,
    windowsHourlyPrice: 0.428928,
  },
  "n4-highcpu-48": {
    hourlyPrice: 2.939136,
    windowsHourlyPrice: 5.147136,
  },
  "n4-highcpu-64": {
    hourlyPrice: 3.918848,
    windowsHourlyPrice: 6.862848,
  },
  "n4-highcpu-8": {
    hourlyPrice: 0.489856,
    windowsHourlyPrice: 0.857856,
  },
  "n4-highcpu-80": {
    hourlyPrice: 4.89856,
    windowsHourlyPrice: 8.57856,
  },
  "n4-highmem-16": {
    hourlyPrice: 1.523456,
    windowsHourlyPrice: 2.259456,
  },
  "n4-highmem-2": {
    hourlyPrice: 0.190432,
    windowsHourlyPrice: 0.282432,
  },
  "n4-highmem-32": {
    hourlyPrice: 3.046912,
    windowsHourlyPrice: 4.518912,
  },
  "n4-highmem-4": {
    hourlyPrice: 0.380864,
    windowsHourlyPrice: 0.564864,
  },
  "n4-highmem-48": {
    hourlyPrice: 4.570368,
    windowsHourlyPrice: 6.778368,
  },
  "n4-highmem-64": {
    hourlyPrice: 6.093824,
    windowsHourlyPrice: 9.037824,
  },
  "n4-highmem-8": {
    hourlyPrice: 0.761728,
    windowsHourlyPrice: 1.129728,
  },
  "n4-highmem-80": {
    hourlyPrice: 7.61728,
    windowsHourlyPrice: 11.29728,
  },
  "n4-standard-16": {
    hourlyPrice: 1.16096,
    windowsHourlyPrice: 1.89696,
  },
  "n4-standard-2": {
    hourlyPrice: 0.14512,
    windowsHourlyPrice: 0.23712,
  },
  "n4-standard-32": {
    hourlyPrice: 2.32192,
    windowsHourlyPrice: 3.79392,
  },
  "n4-standard-4": {
    hourlyPrice: 0.29024,
    windowsHourlyPrice: 0.47424,
  },
  "n4-standard-48": {
    hourlyPrice: 3.48288,
    windowsHourlyPrice: 5.69088,
  },
  "n4-standard-64": {
    hourlyPrice: 4.64384,
    windowsHourlyPrice: 7.58784,
  },
  "n4-standard-8": {
    hourlyPrice: 0.58048,
    windowsHourlyPrice: 0.94848,
  },
  "n4-standard-80": {
    hourlyPrice: 5.8048,
    windowsHourlyPrice: 9.4848,
  },
  "n4d-highcpu-16": {
    hourlyPrice: 0.914816,
    windowsHourlyPrice: 1.650816,
  },
  "n4d-highcpu-2": {
    hourlyPrice: 0.114352,
    windowsHourlyPrice: 0.206352,
  },
  "n4d-highcpu-32": {
    hourlyPrice: 1.829632,
    windowsHourlyPrice: 3.301632,
  },
  "n4d-highcpu-4": {
    hourlyPrice: 0.228704,
    windowsHourlyPrice: 0.412704,
  },
  "n4d-highcpu-48": {
    hourlyPrice: 2.744448,
    windowsHourlyPrice: 4.952448,
  },
  "n4d-highcpu-64": {
    hourlyPrice: 3.659264,
    windowsHourlyPrice: 6.603264,
  },
  "n4d-highcpu-8": {
    hourlyPrice: 0.457408,
    windowsHourlyPrice: 0.825408,
  },
  "n4d-highcpu-80": {
    hourlyPrice: 4.57408,
    windowsHourlyPrice: 8.25408,
  },
  "n4d-highcpu-96": {
    hourlyPrice: 5.488896,
    windowsHourlyPrice: 9.904896,
  },
  "n4d-highmem-16": {
    hourlyPrice: 1.423616,
    windowsHourlyPrice: 2.159616,
  },
  "n4d-highmem-2": {
    hourlyPrice: 0.177952,
    windowsHourlyPrice: 0.269952,
  },
  "n4d-highmem-32": {
    hourlyPrice: 2.847232,
    windowsHourlyPrice: 4.319232,
  },
  "n4d-highmem-4": {
    hourlyPrice: 0.355904,
    windowsHourlyPrice: 0.539904,
  },
  "n4d-highmem-48": {
    hourlyPrice: 4.270848,
    windowsHourlyPrice: 6.478848,
  },
  "n4d-highmem-64": {
    hourlyPrice: 5.694464,
    windowsHourlyPrice: 8.638464,
  },
  "n4d-highmem-8": {
    hourlyPrice: 0.711808,
    windowsHourlyPrice: 1.079808,
  },
  "n4d-highmem-80": {
    hourlyPrice: 7.11808,
    windowsHourlyPrice: 10.79808,
  },
  "n4d-highmem-96": {
    hourlyPrice: 8.541696,
    windowsHourlyPrice: 12.957696,
  },
  "n4d-standard-16": {
    hourlyPrice: 1.084416,
    windowsHourlyPrice: 1.820416,
  },
  "n4d-standard-2": {
    hourlyPrice: 0.135552,
    windowsHourlyPrice: 0.227552,
  },
  "n4d-standard-32": {
    hourlyPrice: 2.168832,
    windowsHourlyPrice: 3.640832,
  },
  "n4d-standard-4": {
    hourlyPrice: 0.271104,
    windowsHourlyPrice: 0.455104,
  },
  "n4d-standard-48": {
    hourlyPrice: 3.253248,
    windowsHourlyPrice: 5.461248,
  },
  "n4d-standard-64": {
    hourlyPrice: 4.337664,
    windowsHourlyPrice: 7.281664,
  },
  "n4d-standard-8": {
    hourlyPrice: 0.542208,
    windowsHourlyPrice: 0.910208,
  },
  "n4d-standard-80": {
    hourlyPrice: 5.42208,
    windowsHourlyPrice: 9.10208,
  },
  "n4d-standard-96": {
    hourlyPrice: 6.506496,
    windowsHourlyPrice: 10.922496,
  },
  "t2d-standard-1": {
    hourlyPrice: 0.0675936,
    windowsHourlyPrice: 0.1135936,
  },
  "t2d-standard-16": {
    hourlyPrice: 1.0814976,
    windowsHourlyPrice: 1.8174976,
  },
  "t2d-standard-2": {
    hourlyPrice: 0.1351872,
    windowsHourlyPrice: 0.2271872,
  },
  "t2d-standard-32": {
    hourlyPrice: 2.1629952,
    windowsHourlyPrice: 3.6349952,
  },
  "t2d-standard-4": {
    hourlyPrice: 0.2703744,
    windowsHourlyPrice: 0.4543744,
  },
  "t2d-standard-48": {
    hourlyPrice: 3.2444928,
    windowsHourlyPrice: 5.4524928,
  },
  "t2d-standard-60": {
    hourlyPrice: 4.055616,
    windowsHourlyPrice: 6.815616,
  },
  "t2d-standard-8": {
    hourlyPrice: 0.5407488,
    windowsHourlyPrice: 0.9087488,
  },
  "z3-highmem-14-standardlssd": {
    hourlyPrice: 2.3048592,
    windowsHourlyPrice: 2.9488592,
  },
  "z3-highmem-16-highlssd": {
    hourlyPrice: 2.6341248,
    windowsHourlyPrice: 3.3701248,
  },
  "z3-highmem-176": {
    hourlyPrice: 28.9753728,
    windowsHourlyPrice: 37.0713728,
  },
  "z3-highmem-176-standardlssd": {
    hourlyPrice: 28.9753728,
    windowsHourlyPrice: 37.0713728,
  },
  "z3-highmem-192-highlssd-metal": {
    hourlyPrice: 31.6094976,
    windowsHourlyPrice: 40.4414976,
  },
  "z3-highmem-22-highlssd": {
    hourlyPrice: 3.6219216,
    windowsHourlyPrice: 4.6339216,
  },
  "z3-highmem-22-standardlssd": {
    hourlyPrice: 3.6219216,
    windowsHourlyPrice: 4.6339216,
  },
  "z3-highmem-32-highlssd": {
    hourlyPrice: 5.2682496,
    windowsHourlyPrice: 6.7402496,
  },
  "z3-highmem-44-highlssd": {
    hourlyPrice: 7.2438432,
    windowsHourlyPrice: 9.2678432,
  },
  "z3-highmem-44-standardlssd": {
    hourlyPrice: 7.2438432,
    windowsHourlyPrice: 9.2678432,
  },
  "z3-highmem-8-highlssd": {
    hourlyPrice: 1.3170624,
    windowsHourlyPrice: 1.6850624,
  },
  "z3-highmem-88": {
    hourlyPrice: 14.4876864,
    windowsHourlyPrice: 18.5356864,
  },
  "z3-highmem-88-highlssd": {
    hourlyPrice: 14.4876864,
    windowsHourlyPrice: 18.5356864,
  },
  "z3-highmem-88-standardlssd": {
    hourlyPrice: 14.4876864,
    windowsHourlyPrice: 18.5356864,
  },
};
