// GCP instance prices for region key: northamerica_northeast1 (updated 2026-08-30)
// Auto-generated by tools/split-data.js — do not edit by hand
// Specs for these types live in js/gcp/gcp-data.js as GCP_SPECS.compute
window.northamerica_northeast1 = {
  "a2-highgpu-1g": {
    hourlyPrice: 0.814064,
    windowsHourlyPrice: 1.366064,
  },
  "a2-highgpu-2g": {
    hourlyPrice: 1.628128,
    windowsHourlyPrice: 2.732128,
  },
  "a2-highgpu-4g": {
    hourlyPrice: 3.256256,
    windowsHourlyPrice: 5.464256,
  },
  "a2-highgpu-8g": {
    hourlyPrice: 6.512512,
    windowsHourlyPrice: 10.928512,
  },
  "a2-megagpu-16g": {
    hourlyPrice: 9.684032,
    windowsHourlyPrice: 14.100032,
  },
  "a2-ultragpu-1g": {
    hourlyPrice: 1.210504,
    windowsHourlyPrice: 1.762504,
  },
  "a2-ultragpu-2g": {
    hourlyPrice: 2.421008,
    windowsHourlyPrice: 3.525008,
  },
  "a2-ultragpu-4g": {
    hourlyPrice: 4.842016,
    windowsHourlyPrice: 7.050016,
  },
  "a2-ultragpu-8g": {
    hourlyPrice: 9.684032,
    windowsHourlyPrice: 14.100032,
  },
  "a3-edgegpu-8g": {
    hourlyPrice: 10.41647984,
    windowsHourlyPrice: 19.98447984,
  },
  "a3-edgegpu-8g-nolssd": {
    hourlyPrice: 10.41647984,
    windowsHourlyPrice: 19.98447984,
  },
  "a3-highgpu-1g": {
    hourlyPrice: 1.30205998,
    windowsHourlyPrice: 2.49805998,
  },
  "a3-highgpu-2g": {
    hourlyPrice: 2.60411996,
    windowsHourlyPrice: 4.99611996,
  },
  "a3-highgpu-4g": {
    hourlyPrice: 5.20823992,
    windowsHourlyPrice: 9.99223992,
  },
  "a3-highgpu-8g": {
    hourlyPrice: 10.41647984,
    windowsHourlyPrice: 19.98447984,
  },
  "a3-megagpu-8g": {
    hourlyPrice: 10.41647984,
    windowsHourlyPrice: 19.98447984,
  },
  "a3-ultragpu-8g": {
    hourlyPrice: 13.50609904,
    windowsHourlyPrice: 23.81009904,
  },
  "a3-ultragpu-8g-nolssd": {
    hourlyPrice: 13.50609904,
    windowsHourlyPrice: 23.81009904,
  },
  "c2-standard-16": {
    hourlyPrice: 0.919488,
    windowsHourlyPrice: 1.655488,
  },
  "c2-standard-30": {
    hourlyPrice: 1.72404,
    windowsHourlyPrice: 3.10404,
  },
  "c2-standard-4": {
    hourlyPrice: 0.229872,
    windowsHourlyPrice: 0.413872,
  },
  "c2-standard-60": {
    hourlyPrice: 3.44808,
    windowsHourlyPrice: 6.20808,
  },
  "c2-standard-8": {
    hourlyPrice: 0.459744,
    windowsHourlyPrice: 0.827744,
  },
  "c2d-highcpu-112": {
    hourlyPrice: 4.622128,
    windowsHourlyPrice: 9.774128,
  },
  "c2d-highcpu-16": {
    hourlyPrice: 0.660304,
    windowsHourlyPrice: 1.396304,
  },
  "c2d-highcpu-2": {
    hourlyPrice: 0.082538,
    windowsHourlyPrice: 0.174538,
  },
  "c2d-highcpu-32": {
    hourlyPrice: 1.320608,
    windowsHourlyPrice: 2.792608,
  },
  "c2d-highcpu-4": {
    hourlyPrice: 0.165076,
    windowsHourlyPrice: 0.349076,
  },
  "c2d-highcpu-56": {
    hourlyPrice: 2.311064,
    windowsHourlyPrice: 4.887064,
  },
  "c2d-highcpu-8": {
    hourlyPrice: 0.330152,
    windowsHourlyPrice: 0.698152,
  },
  "c2d-highmem-112": {
    hourlyPrice: 7.551376,
    windowsHourlyPrice: 12.703376,
  },
  "c2d-highmem-16": {
    hourlyPrice: 1.078768,
    windowsHourlyPrice: 1.814768,
  },
  "c2d-highmem-2": {
    hourlyPrice: 0.134846,
    windowsHourlyPrice: 0.226846,
  },
  "c2d-highmem-32": {
    hourlyPrice: 2.157536,
    windowsHourlyPrice: 3.629536,
  },
  "c2d-highmem-4": {
    hourlyPrice: 0.269692,
    windowsHourlyPrice: 0.453692,
  },
  "c2d-highmem-56": {
    hourlyPrice: 3.775688,
    windowsHourlyPrice: 6.351688,
  },
  "c2d-highmem-8": {
    hourlyPrice: 0.539384,
    windowsHourlyPrice: 0.907384,
  },
  "c2d-standard-112": {
    hourlyPrice: 5.598544,
    windowsHourlyPrice: 10.750544,
  },
  "c2d-standard-16": {
    hourlyPrice: 0.799792,
    windowsHourlyPrice: 1.535792,
  },
  "c2d-standard-2": {
    hourlyPrice: 0.099974,
    windowsHourlyPrice: 0.191974,
  },
  "c2d-standard-32": {
    hourlyPrice: 1.599584,
    windowsHourlyPrice: 3.071584,
  },
  "c2d-standard-4": {
    hourlyPrice: 0.199948,
    windowsHourlyPrice: 0.383948,
  },
  "c2d-standard-56": {
    hourlyPrice: 2.799272,
    windowsHourlyPrice: 5.375272,
  },
  "c2d-standard-8": {
    hourlyPrice: 0.399896,
    windowsHourlyPrice: 0.767896,
  },
  "c3-highcpu-176": {
    hourlyPrice: 8.24126688,
    windowsHourlyPrice: 16.33726688,
  },
  "c3-highcpu-192-metal": {
    hourlyPrice: 9.5454976,
    windowsHourlyPrice: 18.3774976,
  },
  "c3-highcpu-22": {
    hourlyPrice: 1.03015836,
    windowsHourlyPrice: 2.04215836,
  },
  "c3-highcpu-4": {
    hourlyPrice: 0.18730152,
    windowsHourlyPrice: 0.37130152,
  },
  "c3-highcpu-44": {
    hourlyPrice: 2.06031672,
    windowsHourlyPrice: 4.08431672,
  },
  "c3-highcpu-8": {
    hourlyPrice: 0.37460304,
    windowsHourlyPrice: 0.74260304,
  },
  "c3-highcpu-88": {
    hourlyPrice: 4.12063344,
    windowsHourlyPrice: 8.16863344,
  },
  "c3-highmem-176": {
    hourlyPrice: 12.82022016,
    windowsHourlyPrice: 20.91622016,
  },
  "c3-highmem-192-metal": {
    hourlyPrice: 13.98569472,
    windowsHourlyPrice: 22.81769472,
  },
  "c3-highmem-22": {
    hourlyPrice: 1.60252752,
    windowsHourlyPrice: 2.61452752,
  },
  "c3-highmem-4": {
    hourlyPrice: 0.29136864,
    windowsHourlyPrice: 0.47536864,
  },
  "c3-highmem-44": {
    hourlyPrice: 3.20505504,
    windowsHourlyPrice: 5.22905504,
  },
  "c3-highmem-8": {
    hourlyPrice: 0.58273728,
    windowsHourlyPrice: 0.95073728,
  },
  "c3-highmem-88": {
    hourlyPrice: 6.41011008,
    windowsHourlyPrice: 10.45811008,
  },
  "c3-standard-176": {
    hourlyPrice: 9.76758464,
    windowsHourlyPrice: 17.86358464,
  },
  "c3-standard-176-lssd": {
    hourlyPrice: 9.76758464,
    windowsHourlyPrice: 17.86358464,
  },
  "c3-standard-192-metal": {
    hourlyPrice: 10.65554688,
    windowsHourlyPrice: 19.48754688,
  },
  "c3-standard-22": {
    hourlyPrice: 1.22094808,
    windowsHourlyPrice: 2.23294808,
  },
  "c3-standard-22-lssd": {
    hourlyPrice: 1.22094808,
    windowsHourlyPrice: 2.23294808,
  },
  "c3-standard-4": {
    hourlyPrice: 0.22199056,
    windowsHourlyPrice: 0.40599056,
  },
  "c3-standard-4-lssd": {
    hourlyPrice: 0.22199056,
    windowsHourlyPrice: 0.40599056,
  },
  "c3-standard-44": {
    hourlyPrice: 2.44189616,
    windowsHourlyPrice: 4.46589616,
  },
  "c3-standard-44-lssd": {
    hourlyPrice: 2.44189616,
    windowsHourlyPrice: 4.46589616,
  },
  "c3-standard-8": {
    hourlyPrice: 0.44398112,
    windowsHourlyPrice: 0.81198112,
  },
  "c3-standard-8-lssd": {
    hourlyPrice: 0.44398112,
    windowsHourlyPrice: 0.81198112,
  },
  "c3-standard-88": {
    hourlyPrice: 4.88379232,
    windowsHourlyPrice: 8.93179232,
  },
  "c3-standard-88-lssd": {
    hourlyPrice: 4.88379232,
    windowsHourlyPrice: 8.93179232,
  },
  "c3d-highcpu-16": {
    hourlyPrice: 0.66032544,
    windowsHourlyPrice: 1.39632544,
  },
  "c3d-highcpu-180": {
    hourlyPrice: 7.40250564,
    windowsHourlyPrice: 15.68250564,
  },
  "c3d-highcpu-30": {
    hourlyPrice: 1.23375094,
    windowsHourlyPrice: 2.61375094,
  },
  "c3d-highcpu-360": {
    hourlyPrice: 14.80501128,
    windowsHourlyPrice: 31.36501128,
  },
  "c3d-highcpu-4": {
    hourlyPrice: 0.16508136,
    windowsHourlyPrice: 0.34908136,
  },
  "c3d-highcpu-60": {
    hourlyPrice: 2.46750188,
    windowsHourlyPrice: 5.22750188,
  },
  "c3d-highcpu-8": {
    hourlyPrice: 0.33016272,
    windowsHourlyPrice: 0.69816272,
  },
  "c3d-highcpu-90": {
    hourlyPrice: 3.70125282,
    windowsHourlyPrice: 7.84125282,
  },
  "c3d-highmem-16": {
    hourlyPrice: 1.0788144,
    windowsHourlyPrice: 1.8148144,
  },
  "c3d-highmem-16-lssd": {
    hourlyPrice: 1.0788144,
    windowsHourlyPrice: 1.8148144,
  },
  "c3d-highmem-180": {
    hourlyPrice: 12.136662,
    windowsHourlyPrice: 20.416662,
  },
  "c3d-highmem-180-lssd": {
    hourlyPrice: 12.136662,
    windowsHourlyPrice: 20.416662,
  },
  "c3d-highmem-30": {
    hourlyPrice: 2.022777,
    windowsHourlyPrice: 3.402777,
  },
  "c3d-highmem-30-lssd": {
    hourlyPrice: 2.022777,
    windowsHourlyPrice: 3.402777,
  },
  "c3d-highmem-360": {
    hourlyPrice: 24.273324,
    windowsHourlyPrice: 40.833324,
  },
  "c3d-highmem-360-lssd": {
    hourlyPrice: 24.273324,
    windowsHourlyPrice: 40.833324,
  },
  "c3d-highmem-4": {
    hourlyPrice: 0.2697036,
    windowsHourlyPrice: 0.4537036,
  },
  "c3d-highmem-60": {
    hourlyPrice: 4.045554,
    windowsHourlyPrice: 6.805554,
  },
  "c3d-highmem-60-lssd": {
    hourlyPrice: 4.045554,
    windowsHourlyPrice: 6.805554,
  },
  "c3d-highmem-8": {
    hourlyPrice: 0.5394072,
    windowsHourlyPrice: 0.9074072,
  },
  "c3d-highmem-8-lssd": {
    hourlyPrice: 0.5394072,
    windowsHourlyPrice: 0.9074072,
  },
  "c3d-highmem-90": {
    hourlyPrice: 6.068331,
    windowsHourlyPrice: 10.208331,
  },
  "c3d-highmem-90-lssd": {
    hourlyPrice: 6.068331,
    windowsHourlyPrice: 10.208331,
  },
  "c3d-standard-16": {
    hourlyPrice: 0.79982176,
    windowsHourlyPrice: 1.53582176,
  },
  "c3d-standard-16-lssd": {
    hourlyPrice: 0.79982176,
    windowsHourlyPrice: 1.53582176,
  },
  "c3d-standard-180": {
    hourlyPrice: 8.9979948,
    windowsHourlyPrice: 17.2779948,
  },
  "c3d-standard-180-lssd": {
    hourlyPrice: 8.9979948,
    windowsHourlyPrice: 17.2779948,
  },
  "c3d-standard-30": {
    hourlyPrice: 1.4996658,
    windowsHourlyPrice: 2.8796658,
  },
  "c3d-standard-30-lssd": {
    hourlyPrice: 1.4996658,
    windowsHourlyPrice: 2.8796658,
  },
  "c3d-standard-360": {
    hourlyPrice: 17.9959896,
    windowsHourlyPrice: 34.5559896,
  },
  "c3d-standard-360-lssd": {
    hourlyPrice: 17.9959896,
    windowsHourlyPrice: 34.5559896,
  },
  "c3d-standard-4": {
    hourlyPrice: 0.19995544,
    windowsHourlyPrice: 0.38395544,
  },
  "c3d-standard-60": {
    hourlyPrice: 2.9993316,
    windowsHourlyPrice: 5.7593316,
  },
  "c3d-standard-60-lssd": {
    hourlyPrice: 2.9993316,
    windowsHourlyPrice: 5.7593316,
  },
  "c3d-standard-8": {
    hourlyPrice: 0.39991088,
    windowsHourlyPrice: 0.76791088,
  },
  "c3d-standard-8-lssd": {
    hourlyPrice: 0.39991088,
    windowsHourlyPrice: 0.76791088,
  },
  "c3d-standard-90": {
    hourlyPrice: 4.4989974,
    windowsHourlyPrice: 8.6389974,
  },
  "c3d-standard-90-lssd": {
    hourlyPrice: 4.4989974,
    windowsHourlyPrice: 8.6389974,
  },
  "c4-highcpu-144": {
    hourlyPrice: 6.74285472,
    windowsHourlyPrice: 13.36685472,
  },
  "c4-highcpu-16": {
    hourlyPrice: 0.74920608,
    windowsHourlyPrice: 1.48520608,
  },
  "c4-highcpu-192": {
    hourlyPrice: 8.99047296,
    windowsHourlyPrice: 17.82247296,
  },
  "c4-highcpu-2": {
    hourlyPrice: 0.09365076,
    windowsHourlyPrice: 0.18565076,
  },
  "c4-highcpu-24": {
    hourlyPrice: 1.12380912,
    windowsHourlyPrice: 2.22780912,
  },
  "c4-highcpu-288": {
    hourlyPrice: 13.48570944,
    windowsHourlyPrice: 26.73370944,
  },
  "c4-highcpu-32": {
    hourlyPrice: 1.49841216,
    windowsHourlyPrice: 2.97041216,
  },
  "c4-highcpu-4": {
    hourlyPrice: 0.18730152,
    windowsHourlyPrice: 0.37130152,
  },
  "c4-highcpu-48": {
    hourlyPrice: 2.24761824,
    windowsHourlyPrice: 4.45561824,
  },
  "c4-highcpu-8": {
    hourlyPrice: 0.37460304,
    windowsHourlyPrice: 0.74260304,
  },
  "c4-highcpu-96": {
    hourlyPrice: 4.49523648,
    windowsHourlyPrice: 8.91123648,
  },
  "c4-highmem-144": {
    hourlyPrice: 10.33317036,
    windowsHourlyPrice: 16.95717036,
  },
  "c4-highmem-144-lssd": {
    hourlyPrice: 10.33317036,
    windowsHourlyPrice: 16.95717036,
  },
  "c4-highmem-16": {
    hourlyPrice: 1.14813004,
    windowsHourlyPrice: 1.88413004,
  },
  "c4-highmem-16-lssd": {
    hourlyPrice: 1.14813004,
    windowsHourlyPrice: 1.88413004,
  },
  "c4-highmem-192": {
    hourlyPrice: 13.77756048,
    windowsHourlyPrice: 22.60956048,
  },
  "c4-highmem-192-lssd": {
    hourlyPrice: 13.77756048,
    windowsHourlyPrice: 22.60956048,
  },
  "c4-highmem-2": {
    hourlyPrice: 0.14134819,
    windowsHourlyPrice: 0.23334819,
  },
  "c4-highmem-24": {
    hourlyPrice: 1.72219506,
    windowsHourlyPrice: 2.82619506,
  },
  "c4-highmem-24-lssd": {
    hourlyPrice: 1.72219506,
    windowsHourlyPrice: 2.82619506,
  },
  "c4-highmem-288": {
    hourlyPrice: 20.66634072,
    windowsHourlyPrice: 33.91434072,
  },
  "c4-highmem-288-lssd": {
    hourlyPrice: 20.66634072,
    windowsHourlyPrice: 33.91434072,
  },
  "c4-highmem-288-lssd-metal": {
    hourlyPrice: 20.66634072,
    windowsHourlyPrice: 33.91434072,
  },
  "c4-highmem-288-metal": {
    hourlyPrice: 20.66634072,
    windowsHourlyPrice: 33.91434072,
  },
  "c4-highmem-32": {
    hourlyPrice: 2.29626008,
    windowsHourlyPrice: 3.76826008,
  },
  "c4-highmem-32-lssd": {
    hourlyPrice: 2.29626008,
    windowsHourlyPrice: 3.76826008,
  },
  "c4-highmem-4": {
    hourlyPrice: 0.28703251,
    windowsHourlyPrice: 0.47103251,
  },
  "c4-highmem-4-lssd": {
    hourlyPrice: 0.28703251,
    windowsHourlyPrice: 0.47103251,
  },
  "c4-highmem-48": {
    hourlyPrice: 3.44439012,
    windowsHourlyPrice: 5.65239012,
  },
  "c4-highmem-48-lssd": {
    hourlyPrice: 3.44439012,
    windowsHourlyPrice: 5.65239012,
  },
  "c4-highmem-8": {
    hourlyPrice: 0.57406502,
    windowsHourlyPrice: 0.94206502,
  },
  "c4-highmem-8-lssd": {
    hourlyPrice: 0.57406502,
    windowsHourlyPrice: 0.94206502,
  },
  "c4-highmem-96": {
    hourlyPrice: 6.88878024,
    windowsHourlyPrice: 11.30478024,
  },
  "c4-highmem-96-lssd": {
    hourlyPrice: 6.88878024,
    windowsHourlyPrice: 11.30478024,
  },
  "c4-standard-144": {
    hourlyPrice: 7.83555948,
    windowsHourlyPrice: 14.45955948,
  },
  "c4-standard-144-lssd": {
    hourlyPrice: 7.83555948,
    windowsHourlyPrice: 14.45955948,
  },
  "c4-standard-16": {
    hourlyPrice: 0.87061772,
    windowsHourlyPrice: 1.60661772,
  },
  "c4-standard-16-lssd": {
    hourlyPrice: 0.87061772,
    windowsHourlyPrice: 1.60661772,
  },
  "c4-standard-192": {
    hourlyPrice: 10.44741264,
    windowsHourlyPrice: 19.27941264,
  },
  "c4-standard-192-lssd": {
    hourlyPrice: 10.44741264,
    windowsHourlyPrice: 19.27941264,
  },
  "c4-standard-2": {
    hourlyPrice: 0.10665915,
    windowsHourlyPrice: 0.19865915,
  },
  "c4-standard-24": {
    hourlyPrice: 1.30592658,
    windowsHourlyPrice: 2.40992658,
  },
  "c4-standard-24-lssd": {
    hourlyPrice: 1.30592658,
    windowsHourlyPrice: 2.40992658,
  },
  "c4-standard-288": {
    hourlyPrice: 15.67111896,
    windowsHourlyPrice: 28.91911896,
  },
  "c4-standard-288-lssd": {
    hourlyPrice: 15.67111896,
    windowsHourlyPrice: 28.91911896,
  },
  "c4-standard-288-lssd-metal": {
    hourlyPrice: 15.67111896,
    windowsHourlyPrice: 28.91911896,
  },
  "c4-standard-288-metal": {
    hourlyPrice: 15.67111896,
    windowsHourlyPrice: 28.91911896,
  },
  "c4-standard-32": {
    hourlyPrice: 1.74123544,
    windowsHourlyPrice: 3.21323544,
  },
  "c4-standard-32-lssd": {
    hourlyPrice: 1.74123544,
    windowsHourlyPrice: 3.21323544,
  },
  "c4-standard-4": {
    hourlyPrice: 0.21765443,
    windowsHourlyPrice: 0.40165443,
  },
  "c4-standard-4-lssd": {
    hourlyPrice: 0.21765443,
    windowsHourlyPrice: 0.40165443,
  },
  "c4-standard-48": {
    hourlyPrice: 2.61185316,
    windowsHourlyPrice: 4.81985316,
  },
  "c4-standard-48-lssd": {
    hourlyPrice: 2.61185316,
    windowsHourlyPrice: 4.81985316,
  },
  "c4-standard-8": {
    hourlyPrice: 0.43530886,
    windowsHourlyPrice: 0.80330886,
  },
  "c4-standard-8-lssd": {
    hourlyPrice: 0.43530886,
    windowsHourlyPrice: 0.80330886,
  },
  "c4-standard-96": {
    hourlyPrice: 5.22370632,
    windowsHourlyPrice: 9.63970632,
  },
  "c4-standard-96-lssd": {
    hourlyPrice: 5.22370632,
    windowsHourlyPrice: 9.63970632,
  },
  "c4a-highcpu-1": {
    hourlyPrice: 0.04170967,
    windowsHourlyPrice: 0.08770967,
  },
  "c4a-highcpu-16": {
    hourlyPrice: 0.66735472,
    windowsHourlyPrice: 1.40335472,
  },
  "c4a-highcpu-2": {
    hourlyPrice: 0.08341934,
    windowsHourlyPrice: 0.17541934,
  },
  "c4a-highcpu-32": {
    hourlyPrice: 1.33470944,
    windowsHourlyPrice: 2.80670944,
  },
  "c4a-highcpu-4": {
    hourlyPrice: 0.16683868,
    windowsHourlyPrice: 0.35083868,
  },
  "c4a-highcpu-48": {
    hourlyPrice: 2.00206416,
    windowsHourlyPrice: 4.21006416,
  },
  "c4a-highcpu-64": {
    hourlyPrice: 2.66941888,
    windowsHourlyPrice: 5.61341888,
  },
  "c4a-highcpu-72": {
    hourlyPrice: 3.00309624,
    windowsHourlyPrice: 6.31509624,
  },
  "c4a-highcpu-8": {
    hourlyPrice: 0.33367736,
    windowsHourlyPrice: 0.70167736,
  },
  "c4a-highmem-1": {
    hourlyPrice: 0.06489883,
    windowsHourlyPrice: 0.11089883,
  },
  "c4a-highmem-16": {
    hourlyPrice: 1.03838128,
    windowsHourlyPrice: 1.77438128,
  },
  "c4a-highmem-16-lssd": {
    hourlyPrice: 1.30988128,
    windowsHourlyPrice: 2.04588128,
  },
  "c4a-highmem-2": {
    hourlyPrice: 0.12979766,
    windowsHourlyPrice: 0.22179766,
  },
  "c4a-highmem-32": {
    hourlyPrice: 2.07676256,
    windowsHourlyPrice: 3.54876256,
  },
  "c4a-highmem-32-lssd": {
    hourlyPrice: 2.48401256,
    windowsHourlyPrice: 3.95601256,
  },
  "c4a-highmem-4": {
    hourlyPrice: 0.25959532,
    windowsHourlyPrice: 0.44359532,
  },
  "c4a-highmem-4-lssd": {
    hourlyPrice: 0.32747032,
    windowsHourlyPrice: 0.51147032,
  },
  "c4a-highmem-48": {
    hourlyPrice: 3.11514384,
    windowsHourlyPrice: 5.32314384,
  },
  "c4a-highmem-48-lssd": {
    hourlyPrice: 3.79389384,
    windowsHourlyPrice: 6.00189384,
  },
  "c4a-highmem-64": {
    hourlyPrice: 4.15352512,
    windowsHourlyPrice: 7.09752512,
  },
  "c4a-highmem-64-lssd": {
    hourlyPrice: 5.10377512,
    windowsHourlyPrice: 8.04777512,
  },
  "c4a-highmem-72": {
    hourlyPrice: 4.67271576,
    windowsHourlyPrice: 7.98471576,
  },
  "c4a-highmem-72-lssd": {
    hourlyPrice: 5.75871576,
    windowsHourlyPrice: 9.07071576,
  },
  "c4a-highmem-8": {
    hourlyPrice: 0.51919064,
    windowsHourlyPrice: 0.88719064,
  },
  "c4a-highmem-8-lssd": {
    hourlyPrice: 0.65494064,
    windowsHourlyPrice: 1.02294064,
  },
  "c4a-highmem-96-metal": {
    hourlyPrice: 6.23028768,
    windowsHourlyPrice: 10.64628768,
  },
  "c4a-standard-1": {
    hourlyPrice: 0.04943939,
    windowsHourlyPrice: 0.09543939,
  },
  "c4a-standard-16": {
    hourlyPrice: 0.79103024,
    windowsHourlyPrice: 1.52703024,
  },
  "c4a-standard-16-lssd": {
    hourlyPrice: 1.06253024,
    windowsHourlyPrice: 1.79853024,
  },
  "c4a-standard-2": {
    hourlyPrice: 0.09887878,
    windowsHourlyPrice: 0.19087878,
  },
  "c4a-standard-32": {
    hourlyPrice: 1.58206048,
    windowsHourlyPrice: 3.05406048,
  },
  "c4a-standard-32-lssd": {
    hourlyPrice: 1.98931048,
    windowsHourlyPrice: 3.46131048,
  },
  "c4a-standard-4": {
    hourlyPrice: 0.19775756,
    windowsHourlyPrice: 0.38175756,
  },
  "c4a-standard-4-lssd": {
    hourlyPrice: 0.26563256,
    windowsHourlyPrice: 0.44963256,
  },
  "c4a-standard-48": {
    hourlyPrice: 2.37309072,
    windowsHourlyPrice: 4.58109072,
  },
  "c4a-standard-48-lssd": {
    hourlyPrice: 3.05184072,
    windowsHourlyPrice: 5.25984072,
  },
  "c4a-standard-64": {
    hourlyPrice: 3.16412096,
    windowsHourlyPrice: 6.10812096,
  },
  "c4a-standard-64-lssd": {
    hourlyPrice: 4.11437096,
    windowsHourlyPrice: 7.05837096,
  },
  "c4a-standard-72": {
    hourlyPrice: 3.55963608,
    windowsHourlyPrice: 6.87163608,
  },
  "c4a-standard-72-lssd": {
    hourlyPrice: 4.64563608,
    windowsHourlyPrice: 7.95763608,
  },
  "c4a-standard-8": {
    hourlyPrice: 0.39551512,
    windowsHourlyPrice: 0.76351512,
  },
  "c4a-standard-8-lssd": {
    hourlyPrice: 0.53126512,
    windowsHourlyPrice: 0.89926512,
  },
  "c4d-highcpu-16": {
    hourlyPrice: 0.70014116,
    windowsHourlyPrice: 1.43614116,
  },
  "c4d-highcpu-192": {
    hourlyPrice: 8.40169388,
    windowsHourlyPrice: 17.23369388,
  },
  "c4d-highcpu-2": {
    hourlyPrice: 0.08441804,
    windowsHourlyPrice: 0.17641804,
  },
  "c4d-highcpu-32": {
    hourlyPrice: 1.40028231,
    windowsHourlyPrice: 2.87228231,
  },
  "c4d-highcpu-384": {
    hourlyPrice: 16.80338775,
    windowsHourlyPrice: 34.46738775,
  },
  "c4d-highcpu-384-metal": {
    hourlyPrice: 17.00176272,
    windowsHourlyPrice: 34.66576272,
  },
  "c4d-highcpu-4": {
    hourlyPrice: 0.17296888,
    windowsHourlyPrice: 0.35696888,
  },
  "c4d-highcpu-48": {
    hourlyPrice: 2.10042347,
    windowsHourlyPrice: 4.30842347,
  },
  "c4d-highcpu-64": {
    hourlyPrice: 2.80056463,
    windowsHourlyPrice: 5.74456463,
  },
  "c4d-highcpu-8": {
    hourlyPrice: 0.35007058,
    windowsHourlyPrice: 0.71807058,
  },
  "c4d-highcpu-96": {
    hourlyPrice: 4.20084694,
    windowsHourlyPrice: 8.61684694,
  },
  "c4d-highmem-16": {
    hourlyPrice: 1.0968911,
    windowsHourlyPrice: 1.8328911,
  },
  "c4d-highmem-16-lssd": {
    hourlyPrice: 1.18739247,
    windowsHourlyPrice: 1.92339247,
  },
  "c4d-highmem-192": {
    hourlyPrice: 13.16269316,
    windowsHourlyPrice: 21.99469316,
  },
  "c4d-highmem-192-lssd": {
    hourlyPrice: 14.61071508,
    windowsHourlyPrice: 23.44271508,
  },
  "c4d-highmem-2": {
    hourlyPrice: 0.13401178,
    windowsHourlyPrice: 0.22601178,
  },
  "c4d-highmem-32": {
    hourlyPrice: 2.19378219,
    windowsHourlyPrice: 3.66578219,
  },
  "c4d-highmem-32-lssd": {
    hourlyPrice: 2.37478493,
    windowsHourlyPrice: 3.84678493,
  },
  "c4d-highmem-384": {
    hourlyPrice: 26.32538632,
    windowsHourlyPrice: 43.98938632,
  },
  "c4d-highmem-384-lssd": {
    hourlyPrice: 29.22143016,
    windowsHourlyPrice: 46.88543016,
  },
  "c4d-highmem-384-metal": {
    hourlyPrice: 26.52376129,
    windowsHourlyPrice: 44.18776129,
  },
  "c4d-highmem-4": {
    hourlyPrice: 0.27215637,
    windowsHourlyPrice: 0.45615637,
  },
  "c4d-highmem-48": {
    hourlyPrice: 3.29067329,
    windowsHourlyPrice: 5.49867329,
  },
  "c4d-highmem-48-lssd": {
    hourlyPrice: 3.65267877,
    windowsHourlyPrice: 5.86067877,
  },
  "c4d-highmem-64": {
    hourlyPrice: 4.38756439,
    windowsHourlyPrice: 7.33156439,
  },
  "c4d-highmem-64-lssd": {
    hourlyPrice: 4.93057261,
    windowsHourlyPrice: 7.87457261,
  },
  "c4d-highmem-8": {
    hourlyPrice: 0.54844555,
    windowsHourlyPrice: 0.91644555,
  },
  "c4d-highmem-8-lssd": {
    hourlyPrice: 0.63894692,
    windowsHourlyPrice: 1.00694692,
  },
  "c4d-highmem-96": {
    hourlyPrice: 6.58134658,
    windowsHourlyPrice: 10.99734658,
  },
  "c4d-highmem-96-lssd": {
    hourlyPrice: 7.30535754,
    windowsHourlyPrice: 11.72135754,
  },
  "c4d-standard-16": {
    hourlyPrice: 0.83239114,
    windowsHourlyPrice: 1.56839114,
  },
  "c4d-standard-16-lssd": {
    hourlyPrice: 0.92289251,
    windowsHourlyPrice: 1.65889251,
  },
  "c4d-standard-192": {
    hourlyPrice: 9.98869364,
    windowsHourlyPrice: 18.82069364,
  },
  "c4d-standard-192-lssd": {
    hourlyPrice: 11.43671556,
    windowsHourlyPrice: 20.26871556,
  },
  "c4d-standard-2": {
    hourlyPrice: 0.10094928,
    windowsHourlyPrice: 0.19294928,
  },
  "c4d-standard-32": {
    hourlyPrice: 1.66478227,
    windowsHourlyPrice: 3.13678227,
  },
  "c4d-standard-32-lssd": {
    hourlyPrice: 1.84578501,
    windowsHourlyPrice: 3.31778501,
  },
  "c4d-standard-384": {
    hourlyPrice: 19.97738728,
    windowsHourlyPrice: 37.64138728,
  },
  "c4d-standard-384-lssd": {
    hourlyPrice: 22.87343111,
    windowsHourlyPrice: 40.53743111,
  },
  "c4d-standard-384-metal": {
    hourlyPrice: 20.17576225,
    windowsHourlyPrice: 37.83976225,
  },
  "c4d-standard-4": {
    hourlyPrice: 0.20603138,
    windowsHourlyPrice: 0.39003138,
  },
  "c4d-standard-48": {
    hourlyPrice: 2.49717341,
    windowsHourlyPrice: 4.70517341,
  },
  "c4d-standard-48-lssd": {
    hourlyPrice: 2.85917889,
    windowsHourlyPrice: 5.06717889,
  },
  "c4d-standard-64": {
    hourlyPrice: 3.32956455,
    windowsHourlyPrice: 6.27356455,
  },
  "c4d-standard-64-lssd": {
    hourlyPrice: 3.87257277,
    windowsHourlyPrice: 6.81657277,
  },
  "c4d-standard-8": {
    hourlyPrice: 0.41619557,
    windowsHourlyPrice: 0.78419557,
  },
  "c4d-standard-8-lssd": {
    hourlyPrice: 0.50669694,
    windowsHourlyPrice: 0.87469694,
  },
  "c4d-standard-96": {
    hourlyPrice: 4.99434682,
    windowsHourlyPrice: 9.41034682,
  },
  "c4d-standard-96-lssd": {
    hourlyPrice: 5.71835778,
    windowsHourlyPrice: 10.13435778,
  },
  "e2-highcpu-16": {
    hourlyPrice: 0.43570464,
    windowsHourlyPrice: 1.17170464,
  },
  "e2-highcpu-2": {
    hourlyPrice: 0.05446308,
    windowsHourlyPrice: 0.14646308,
  },
  "e2-highcpu-32": {
    hourlyPrice: 0.87140928,
    windowsHourlyPrice: 2.34340928,
  },
  "e2-highcpu-4": {
    hourlyPrice: 0.10892616,
    windowsHourlyPrice: 0.29292616,
  },
  "e2-highcpu-8": {
    hourlyPrice: 0.21785232,
    windowsHourlyPrice: 0.58585232,
  },
  "e2-highmem-16": {
    hourlyPrice: 0.79613856,
    windowsHourlyPrice: 1.53213856,
  },
  "e2-highmem-2": {
    hourlyPrice: 0.09951732,
    windowsHourlyPrice: 0.19151732,
  },
  "e2-highmem-4": {
    hourlyPrice: 0.19903464,
    windowsHourlyPrice: 0.38303464,
  },
  "e2-highmem-8": {
    hourlyPrice: 0.39806928,
    windowsHourlyPrice: 0.76606928,
  },
  "e2-medium": {
    hourlyPrice: 0.0608994,
    windowsHourlyPrice: 0.1528994,
  },
  "e2-micro": {
    hourlyPrice: 0.05124492,
    windowsHourlyPrice: 0.14324492,
  },
  "e2-small": {
    hourlyPrice: 0.05446308,
    windowsHourlyPrice: 0.14646308,
  },
  "e2-standard-16": {
    hourlyPrice: 0.59017632,
    windowsHourlyPrice: 1.32617632,
  },
  "e2-standard-2": {
    hourlyPrice: 0.07377204,
    windowsHourlyPrice: 0.16577204,
  },
  "e2-standard-32": {
    hourlyPrice: 1.18035264,
    windowsHourlyPrice: 2.65235264,
  },
  "e2-standard-4": {
    hourlyPrice: 0.14754408,
    windowsHourlyPrice: 0.33154408,
  },
  "e2-standard-8": {
    hourlyPrice: 0.29508816,
    windowsHourlyPrice: 0.66308816,
  },
  "g2-standard-12": {
    hourlyPrice: 0.48489792,
    windowsHourlyPrice: 1.03689792,
  },
  "g2-standard-16": {
    hourlyPrice: 0.64653056,
    windowsHourlyPrice: 1.38253056,
  },
  "g2-standard-24": {
    hourlyPrice: 0.96979584,
    windowsHourlyPrice: 2.07379584,
  },
  "g2-standard-32": {
    hourlyPrice: 1.29306112,
    windowsHourlyPrice: 2.76506112,
  },
  "g2-standard-4": {
    hourlyPrice: 0.16163264,
    windowsHourlyPrice: 0.34563264,
  },
  "g2-standard-48": {
    hourlyPrice: 1.93959168,
    windowsHourlyPrice: 4.14759168,
  },
  "g2-standard-8": {
    hourlyPrice: 0.32326528,
    windowsHourlyPrice: 0.69126528,
  },
  "g2-standard-96": {
    hourlyPrice: 3.87918336,
    windowsHourlyPrice: 8.29518336,
  },
  "h3-standard-88": {
    hourlyPrice: 5.42137728,
    windowsHourlyPrice: 9.46937728,
  },
  "h4d-highmem-192": {
    hourlyPrice: 8.842944,
    windowsHourlyPrice: 17.674944,
  },
  "h4d-highmem-192-lssd": {
    hourlyPrice: 9.42409126,
    windowsHourlyPrice: 18.25609126,
  },
  "h4d-standard-192": {
    hourlyPrice: 7.85376,
    windowsHourlyPrice: 16.68576,
  },
  "m1-megamem-96": {
    hourlyPrice: 11.19729646,
    windowsHourlyPrice: 15.61329646,
  },
  "m1-ultramem-160": {
    hourlyPrice: 26.4644144,
    windowsHourlyPrice: 33.8244144,
  },
  "m1-ultramem-40": {
    hourlyPrice: 6.6161036,
    windowsHourlyPrice: 8.4561036,
  },
  "m1-ultramem-80": {
    hourlyPrice: 13.2322072,
    windowsHourlyPrice: 16.9122072,
  },
  "m2-hypermem-416": {
    hourlyPrice: 70.70729654,
    windowsHourlyPrice: 89.84329654,
  },
  "m2-megamem-416": {
    hourlyPrice: 52.86410115,
    windowsHourlyPrice: 72.00010115,
  },
  "m2-ultramem-208": {
    hourlyPrice: 44.27524597,
    windowsHourlyPrice: 53.84324597,
  },
  "m2-ultramem-416": {
    hourlyPrice: 88.55049194,
    windowsHourlyPrice: 107.68649194,
  },
  "m2-ultramem2x-96": {
    hourlyPrice: 11.54017201,
    windowsHourlyPrice: 15.95617201,
  },
  "m2-ultramemx-96": {
    hourlyPrice: 7.60060781,
    windowsHourlyPrice: 12.01660781,
  },
  "m3-megamem-128": {
    hourlyPrice: 15.86641056,
    windowsHourlyPrice: 21.75441056,
  },
  "m3-megamem-64": {
    hourlyPrice: 7.93320528,
    windowsHourlyPrice: 10.87720528,
  },
  "m3-ultramem-128": {
    hourlyPrice: 26.82808128,
    windowsHourlyPrice: 32.71608128,
  },
  "m3-ultramem-32": {
    hourlyPrice: 6.70702032,
    windowsHourlyPrice: 8.17902032,
  },
  "m3-ultramem-64": {
    hourlyPrice: 13.41404064,
    windowsHourlyPrice: 16.35804064,
  },
  "m4-hypermem-16": {
    hourlyPrice: 1.5691392,
    windowsHourlyPrice: 2.3051392,
  },
  "m4-hypermem-32": {
    hourlyPrice: 3.1382784,
    windowsHourlyPrice: 4.6102784,
  },
  "m4-hypermem-64": {
    hourlyPrice: 6.2765568,
    windowsHourlyPrice: 9.2205568,
  },
  "m4-megamem-112": {
    hourlyPrice: 9.7365344,
    windowsHourlyPrice: 14.8885344,
  },
  "m4-megamem-224": {
    hourlyPrice: 19.4730688,
    windowsHourlyPrice: 29.7770688,
  },
  "m4-megamem-28": {
    hourlyPrice: 2.4341336,
    windowsHourlyPrice: 3.7221336,
  },
  "m4-megamem-56": {
    hourlyPrice: 4.8682672,
    windowsHourlyPrice: 7.4442672,
  },
  "m4-ultramem-112": {
    hourlyPrice: 17.2211744,
    windowsHourlyPrice: 22.3731744,
  },
  "m4-ultramem-224": {
    hourlyPrice: 34.4423488,
    windowsHourlyPrice: 44.7463488,
  },
  "m4-ultramem-56": {
    hourlyPrice: 8.6105872,
    windowsHourlyPrice: 11.1865872,
  },
  "m4n-hypermem-16": {
    hourlyPrice: 2.8260224,
    windowsHourlyPrice: 3.5620224,
  },
  "m4n-hypermem-32": {
    hourlyPrice: 5.6520448,
    windowsHourlyPrice: 7.1240448,
  },
  "m4n-hypermem-64": {
    hourlyPrice: 11.3040896,
    windowsHourlyPrice: 14.2480896,
  },
  "m4n-megamem-112": {
    hourlyPrice: 17.5357728,
    windowsHourlyPrice: 22.6877728,
  },
  "m4n-megamem-224": {
    hourlyPrice: 35.0715456,
    windowsHourlyPrice: 45.3755456,
  },
  "m4n-megamem-28": {
    hourlyPrice: 4.3839432,
    windowsHourlyPrice: 5.6719432,
  },
  "m4n-megamem-56": {
    hourlyPrice: 8.7678864,
    windowsHourlyPrice: 11.3438864,
  },
  "m4n-ultramem-112": {
    hourlyPrice: 31.0140768,
    windowsHourlyPrice: 36.1660768,
  },
  "m4n-ultramem-224": {
    hourlyPrice: 62.0281536,
    windowsHourlyPrice: 72.3321536,
  },
  "m4n-ultramem-56": {
    hourlyPrice: 15.5070384,
    windowsHourlyPrice: 18.0830384,
  },
  "n1-highcpu-16": {
    hourlyPrice: 0.62399542,
    windowsHourlyPrice: 1.35999542,
  },
  "n1-highcpu-2": {
    hourlyPrice: 0.07799829,
    windowsHourlyPrice: 0.16999829,
  },
  "n1-highcpu-32": {
    hourlyPrice: 1.24798629,
    windowsHourlyPrice: 2.71998629,
  },
  "n1-highcpu-4": {
    hourlyPrice: 0.15599658,
    windowsHourlyPrice: 0.33999658,
  },
  "n1-highcpu-64": {
    hourlyPrice: 2.49597258,
    windowsHourlyPrice: 5.43997258,
  },
  "n1-highcpu-8": {
    hourlyPrice: 0.31199771,
    windowsHourlyPrice: 0.67999771,
  },
  "n1-highcpu-96": {
    hourlyPrice: 3.74396342,
    windowsHourlyPrice: 8.15996342,
  },
  "n1-highmem-16": {
    hourlyPrice: 1.041888,
    windowsHourlyPrice: 1.777888,
  },
  "n1-highmem-2": {
    hourlyPrice: 0.130236,
    windowsHourlyPrice: 0.222236,
  },
  "n1-highmem-32": {
    hourlyPrice: 2.083776,
    windowsHourlyPrice: 3.555776,
  },
  "n1-highmem-4": {
    hourlyPrice: 0.260472,
    windowsHourlyPrice: 0.444472,
  },
  "n1-highmem-64": {
    hourlyPrice: 4.167552,
    windowsHourlyPrice: 7.111552,
  },
  "n1-highmem-8": {
    hourlyPrice: 0.520944,
    windowsHourlyPrice: 0.888944,
  },
  "n1-highmem-96": {
    hourlyPrice: 6.251328,
    windowsHourlyPrice: 10.667328,
  },
  "n1-megamem-96": {
    hourlyPrice: 10.02730058,
    windowsHourlyPrice: 14.44330058,
  },
  "n1-standard-1": {
    hourlyPrice: 0.052292,
    windowsHourlyPrice: 0.098292,
  },
  "n1-standard-16": {
    hourlyPrice: 0.836672,
    windowsHourlyPrice: 1.572672,
  },
  "n1-standard-2": {
    hourlyPrice: 0.104584,
    windowsHourlyPrice: 0.196584,
  },
  "n1-standard-32": {
    hourlyPrice: 1.673344,
    windowsHourlyPrice: 3.145344,
  },
  "n1-standard-4": {
    hourlyPrice: 0.209168,
    windowsHourlyPrice: 0.393168,
  },
  "n1-standard-64": {
    hourlyPrice: 3.346688,
    windowsHourlyPrice: 6.290688,
  },
  "n1-standard-8": {
    hourlyPrice: 0.418336,
    windowsHourlyPrice: 0.786336,
  },
  "n1-standard-96": {
    hourlyPrice: 5.020032,
    windowsHourlyPrice: 9.436032,
  },
  "n1-ultramem-160": {
    hourlyPrice: 23.496736,
    windowsHourlyPrice: 30.856736,
  },
  "n1-ultramem-40": {
    hourlyPrice: 5.874184,
    windowsHourlyPrice: 7.714184,
  },
  "n1-ultramem-80": {
    hourlyPrice: 11.748368,
    windowsHourlyPrice: 15.428368,
  },
  "n2-highcpu-16": {
    hourlyPrice: 0.631456,
    windowsHourlyPrice: 1.367456,
  },
  "n2-highcpu-2": {
    hourlyPrice: 0.078932,
    windowsHourlyPrice: 0.170932,
  },
  "n2-highcpu-32": {
    hourlyPrice: 1.262912,
    windowsHourlyPrice: 2.734912,
  },
  "n2-highcpu-4": {
    hourlyPrice: 0.157864,
    windowsHourlyPrice: 0.341864,
  },
  "n2-highcpu-48": {
    hourlyPrice: 1.894368,
    windowsHourlyPrice: 4.102368,
  },
  "n2-highcpu-64": {
    hourlyPrice: 2.525824,
    windowsHourlyPrice: 5.469824,
  },
  "n2-highcpu-8": {
    hourlyPrice: 0.315728,
    windowsHourlyPrice: 0.683728,
  },
  "n2-highcpu-80": {
    hourlyPrice: 3.15728,
    windowsHourlyPrice: 6.83728,
  },
  "n2-highcpu-96": {
    hourlyPrice: 3.788736,
    windowsHourlyPrice: 8.204736,
  },
  "n2-highmem-128": {
    hourlyPrice: 8.484352,
    windowsHourlyPrice: 14.372352,
  },
  "n2-highmem-16": {
    hourlyPrice: 1.153824,
    windowsHourlyPrice: 1.889824,
  },
  "n2-highmem-2": {
    hourlyPrice: 0.144228,
    windowsHourlyPrice: 0.236228,
  },
  "n2-highmem-32": {
    hourlyPrice: 2.307648,
    windowsHourlyPrice: 3.779648,
  },
  "n2-highmem-4": {
    hourlyPrice: 0.288456,
    windowsHourlyPrice: 0.472456,
  },
  "n2-highmem-48": {
    hourlyPrice: 3.461472,
    windowsHourlyPrice: 5.669472,
  },
  "n2-highmem-64": {
    hourlyPrice: 4.615296,
    windowsHourlyPrice: 7.559296,
  },
  "n2-highmem-8": {
    hourlyPrice: 0.576912,
    windowsHourlyPrice: 0.944912,
  },
  "n2-highmem-80": {
    hourlyPrice: 5.76912,
    windowsHourlyPrice: 9.44912,
  },
  "n2-highmem-96": {
    hourlyPrice: 6.922944,
    windowsHourlyPrice: 11.338944,
  },
  "n2-standard-128": {
    hourlyPrice: 6.842624,
    windowsHourlyPrice: 12.730624,
  },
  "n2-standard-16": {
    hourlyPrice: 0.855328,
    windowsHourlyPrice: 1.591328,
  },
  "n2-standard-2": {
    hourlyPrice: 0.106916,
    windowsHourlyPrice: 0.198916,
  },
  "n2-standard-32": {
    hourlyPrice: 1.710656,
    windowsHourlyPrice: 3.182656,
  },
  "n2-standard-4": {
    hourlyPrice: 0.213832,
    windowsHourlyPrice: 0.397832,
  },
  "n2-standard-48": {
    hourlyPrice: 2.565984,
    windowsHourlyPrice: 4.773984,
  },
  "n2-standard-64": {
    hourlyPrice: 3.421312,
    windowsHourlyPrice: 6.365312,
  },
  "n2-standard-8": {
    hourlyPrice: 0.427664,
    windowsHourlyPrice: 0.795664,
  },
  "n2-standard-80": {
    hourlyPrice: 4.27664,
    windowsHourlyPrice: 7.95664,
  },
  "n2-standard-96": {
    hourlyPrice: 5.131968,
    windowsHourlyPrice: 9.547968,
  },
  "n2d-highcpu-128": {
    hourlyPrice: 4.395008,
    windowsHourlyPrice: 10.283008,
  },
  "n2d-highcpu-16": {
    hourlyPrice: 0.549376,
    windowsHourlyPrice: 1.285376,
  },
  "n2d-highcpu-2": {
    hourlyPrice: 0.068672,
    windowsHourlyPrice: 0.160672,
  },
  "n2d-highcpu-224": {
    hourlyPrice: 7.691264,
    windowsHourlyPrice: 17.995264,
  },
  "n2d-highcpu-32": {
    hourlyPrice: 1.098752,
    windowsHourlyPrice: 2.570752,
  },
  "n2d-highcpu-4": {
    hourlyPrice: 0.137344,
    windowsHourlyPrice: 0.321344,
  },
  "n2d-highcpu-48": {
    hourlyPrice: 1.648128,
    windowsHourlyPrice: 3.856128,
  },
  "n2d-highcpu-64": {
    hourlyPrice: 2.197504,
    windowsHourlyPrice: 5.141504,
  },
  "n2d-highcpu-8": {
    hourlyPrice: 0.274688,
    windowsHourlyPrice: 0.642688,
  },
  "n2d-highcpu-80": {
    hourlyPrice: 2.74688,
    windowsHourlyPrice: 6.42688,
  },
  "n2d-highcpu-96": {
    hourlyPrice: 3.296256,
    windowsHourlyPrice: 7.712256,
  },
  "n2d-highmem-16": {
    hourlyPrice: 1.003872,
    windowsHourlyPrice: 1.739872,
  },
  "n2d-highmem-2": {
    hourlyPrice: 0.125484,
    windowsHourlyPrice: 0.217484,
  },
  "n2d-highmem-32": {
    hourlyPrice: 2.007744,
    windowsHourlyPrice: 3.479744,
  },
  "n2d-highmem-4": {
    hourlyPrice: 0.250968,
    windowsHourlyPrice: 0.434968,
  },
  "n2d-highmem-48": {
    hourlyPrice: 3.011616,
    windowsHourlyPrice: 5.219616,
  },
  "n2d-highmem-64": {
    hourlyPrice: 4.015488,
    windowsHourlyPrice: 6.959488,
  },
  "n2d-highmem-8": {
    hourlyPrice: 0.501936,
    windowsHourlyPrice: 0.869936,
  },
  "n2d-highmem-80": {
    hourlyPrice: 5.01936,
    windowsHourlyPrice: 8.69936,
  },
  "n2d-highmem-96": {
    hourlyPrice: 6.023232,
    windowsHourlyPrice: 10.439232,
  },
  "n2d-standard-128": {
    hourlyPrice: 5.95328,
    windowsHourlyPrice: 11.84128,
  },
  "n2d-standard-16": {
    hourlyPrice: 0.74416,
    windowsHourlyPrice: 1.48016,
  },
  "n2d-standard-2": {
    hourlyPrice: 0.09302,
    windowsHourlyPrice: 0.18502,
  },
  "n2d-standard-224": {
    hourlyPrice: 10.41824,
    windowsHourlyPrice: 20.72224,
  },
  "n2d-standard-32": {
    hourlyPrice: 1.48832,
    windowsHourlyPrice: 2.96032,
  },
  "n2d-standard-4": {
    hourlyPrice: 0.18604,
    windowsHourlyPrice: 0.37004,
  },
  "n2d-standard-48": {
    hourlyPrice: 2.23248,
    windowsHourlyPrice: 4.44048,
  },
  "n2d-standard-64": {
    hourlyPrice: 2.97664,
    windowsHourlyPrice: 5.92064,
  },
  "n2d-standard-8": {
    hourlyPrice: 0.37208,
    windowsHourlyPrice: 0.74008,
  },
  "n2d-standard-80": {
    hourlyPrice: 3.7208,
    windowsHourlyPrice: 7.4008,
  },
  "n2d-standard-96": {
    hourlyPrice: 4.46496,
    windowsHourlyPrice: 8.88096,
  },
  "n4-highcpu-16": {
    hourlyPrice: 0.67422544,
    windowsHourlyPrice: 1.41022544,
  },
  "n4-highcpu-2": {
    hourlyPrice: 0.08427818,
    windowsHourlyPrice: 0.17627818,
  },
  "n4-highcpu-32": {
    hourlyPrice: 1.34845088,
    windowsHourlyPrice: 2.82045088,
  },
  "n4-highcpu-4": {
    hourlyPrice: 0.16855636,
    windowsHourlyPrice: 0.35255636,
  },
  "n4-highcpu-48": {
    hourlyPrice: 2.02267632,
    windowsHourlyPrice: 4.23067632,
  },
  "n4-highcpu-64": {
    hourlyPrice: 2.69690176,
    windowsHourlyPrice: 5.64090176,
  },
  "n4-highcpu-8": {
    hourlyPrice: 0.33711272,
    windowsHourlyPrice: 0.70511272,
  },
  "n4-highcpu-80": {
    hourlyPrice: 3.3711272,
    windowsHourlyPrice: 7.0511272,
  },
  "n4-highmem-16": {
    hourlyPrice: 1.04842288,
    windowsHourlyPrice: 1.78442288,
  },
  "n4-highmem-2": {
    hourlyPrice: 0.13105286,
    windowsHourlyPrice: 0.22305286,
  },
  "n4-highmem-32": {
    hourlyPrice: 2.09684576,
    windowsHourlyPrice: 3.56884576,
  },
  "n4-highmem-4": {
    hourlyPrice: 0.26210572,
    windowsHourlyPrice: 0.44610572,
  },
  "n4-highmem-48": {
    hourlyPrice: 3.14526864,
    windowsHourlyPrice: 5.35326864,
  },
  "n4-highmem-64": {
    hourlyPrice: 4.19369152,
    windowsHourlyPrice: 7.13769152,
  },
  "n4-highmem-8": {
    hourlyPrice: 0.52421144,
    windowsHourlyPrice: 0.89221144,
  },
  "n4-highmem-80": {
    hourlyPrice: 5.2421144,
    windowsHourlyPrice: 8.9221144,
  },
  "n4-standard-16": {
    hourlyPrice: 0.79895792,
    windowsHourlyPrice: 1.53495792,
  },
  "n4-standard-2": {
    hourlyPrice: 0.09986974,
    windowsHourlyPrice: 0.19186974,
  },
  "n4-standard-32": {
    hourlyPrice: 1.59791584,
    windowsHourlyPrice: 3.06991584,
  },
  "n4-standard-4": {
    hourlyPrice: 0.19973948,
    windowsHourlyPrice: 0.38373948,
  },
  "n4-standard-48": {
    hourlyPrice: 2.39687376,
    windowsHourlyPrice: 4.60487376,
  },
  "n4-standard-64": {
    hourlyPrice: 3.19583168,
    windowsHourlyPrice: 6.13983168,
  },
  "n4-standard-8": {
    hourlyPrice: 0.39947896,
    windowsHourlyPrice: 0.76747896,
  },
  "n4-standard-80": {
    hourlyPrice: 3.9947896,
    windowsHourlyPrice: 7.6747896,
  },
  "n4d-highcpu-16": {
    hourlyPrice: 0.629328,
    windowsHourlyPrice: 1.365328,
  },
  "n4d-highcpu-2": {
    hourlyPrice: 0.078666,
    windowsHourlyPrice: 0.170666,
  },
  "n4d-highcpu-32": {
    hourlyPrice: 1.258656,
    windowsHourlyPrice: 2.730656,
  },
  "n4d-highcpu-4": {
    hourlyPrice: 0.157332,
    windowsHourlyPrice: 0.341332,
  },
  "n4d-highcpu-48": {
    hourlyPrice: 1.887984,
    windowsHourlyPrice: 4.095984,
  },
  "n4d-highcpu-64": {
    hourlyPrice: 2.517312,
    windowsHourlyPrice: 5.461312,
  },
  "n4d-highcpu-8": {
    hourlyPrice: 0.314664,
    windowsHourlyPrice: 0.682664,
  },
  "n4d-highcpu-80": {
    hourlyPrice: 3.14664,
    windowsHourlyPrice: 6.82664,
  },
  "n4d-highcpu-96": {
    hourlyPrice: 3.775968,
    windowsHourlyPrice: 8.191968,
  },
  "n4d-highmem-16": {
    hourlyPrice: 0.978768,
    windowsHourlyPrice: 1.714768,
  },
  "n4d-highmem-2": {
    hourlyPrice: 0.122346,
    windowsHourlyPrice: 0.214346,
  },
  "n4d-highmem-32": {
    hourlyPrice: 1.957536,
    windowsHourlyPrice: 3.429536,
  },
  "n4d-highmem-4": {
    hourlyPrice: 0.244692,
    windowsHourlyPrice: 0.428692,
  },
  "n4d-highmem-48": {
    hourlyPrice: 2.936304,
    windowsHourlyPrice: 5.144304,
  },
  "n4d-highmem-64": {
    hourlyPrice: 3.915072,
    windowsHourlyPrice: 6.859072,
  },
  "n4d-highmem-8": {
    hourlyPrice: 0.489384,
    windowsHourlyPrice: 0.857384,
  },
  "n4d-highmem-80": {
    hourlyPrice: 4.89384,
    windowsHourlyPrice: 8.57384,
  },
  "n4d-highmem-96": {
    hourlyPrice: 5.872608,
    windowsHourlyPrice: 10.288608,
  },
  "n4d-standard-16": {
    hourlyPrice: 0.745808,
    windowsHourlyPrice: 1.481808,
  },
  "n4d-standard-2": {
    hourlyPrice: 0.093226,
    windowsHourlyPrice: 0.185226,
  },
  "n4d-standard-32": {
    hourlyPrice: 1.491616,
    windowsHourlyPrice: 2.963616,
  },
  "n4d-standard-4": {
    hourlyPrice: 0.186452,
    windowsHourlyPrice: 0.370452,
  },
  "n4d-standard-48": {
    hourlyPrice: 2.237424,
    windowsHourlyPrice: 4.445424,
  },
  "n4d-standard-64": {
    hourlyPrice: 2.983232,
    windowsHourlyPrice: 5.927232,
  },
  "n4d-standard-8": {
    hourlyPrice: 0.372904,
    windowsHourlyPrice: 0.740904,
  },
  "n4d-standard-80": {
    hourlyPrice: 3.72904,
    windowsHourlyPrice: 7.40904,
  },
  "n4d-standard-96": {
    hourlyPrice: 4.474848,
    windowsHourlyPrice: 8.890848,
  },
  "t2a-standard-1": {
    hourlyPrice: 0.0385,
    windowsHourlyPrice: 0.0845,
  },
  "t2a-standard-16": {
    hourlyPrice: 0.616,
    windowsHourlyPrice: 1.352,
  },
  "t2a-standard-2": {
    hourlyPrice: 0.077,
    windowsHourlyPrice: 0.169,
  },
  "t2a-standard-32": {
    hourlyPrice: 1.232,
    windowsHourlyPrice: 2.704,
  },
  "t2a-standard-4": {
    hourlyPrice: 0.154,
    windowsHourlyPrice: 0.338,
  },
  "t2a-standard-48": {
    hourlyPrice: 1.848,
    windowsHourlyPrice: 4.056,
  },
  "t2a-standard-8": {
    hourlyPrice: 0.308,
    windowsHourlyPrice: 0.676,
  },
  "t2d-standard-1": {
    hourlyPrice: 0.04651,
    windowsHourlyPrice: 0.09251,
  },
  "t2d-standard-16": {
    hourlyPrice: 0.74416,
    windowsHourlyPrice: 1.48016,
  },
  "t2d-standard-2": {
    hourlyPrice: 0.09302,
    windowsHourlyPrice: 0.18502,
  },
  "t2d-standard-32": {
    hourlyPrice: 1.48832,
    windowsHourlyPrice: 2.96032,
  },
  "t2d-standard-4": {
    hourlyPrice: 0.18604,
    windowsHourlyPrice: 0.37004,
  },
  "t2d-standard-48": {
    hourlyPrice: 2.23248,
    windowsHourlyPrice: 4.44048,
  },
  "t2d-standard-60": {
    hourlyPrice: 2.7906,
    windowsHourlyPrice: 5.5506,
  },
  "t2d-standard-8": {
    hourlyPrice: 0.37208,
    windowsHourlyPrice: 0.74008,
  },
  "z3-highmem-14-standardlssd": {
    hourlyPrice: 1.58617522,
    windowsHourlyPrice: 2.23017522,
  },
  "z3-highmem-16-highlssd": {
    hourlyPrice: 1.81277168,
    windowsHourlyPrice: 2.54877168,
  },
  "z3-highmem-176": {
    hourlyPrice: 19.94048848,
    windowsHourlyPrice: 28.03648848,
  },
  "z3-highmem-176-standardlssd": {
    hourlyPrice: 19.94048848,
    windowsHourlyPrice: 28.03648848,
  },
  "z3-highmem-192-highlssd-metal": {
    hourlyPrice: 21.75326016,
    windowsHourlyPrice: 30.58526016,
  },
  "z3-highmem-22-highlssd": {
    hourlyPrice: 2.49256106,
    windowsHourlyPrice: 3.50456106,
  },
  "z3-highmem-22-standardlssd": {
    hourlyPrice: 2.49256106,
    windowsHourlyPrice: 3.50456106,
  },
  "z3-highmem-32-highlssd": {
    hourlyPrice: 3.62554336,
    windowsHourlyPrice: 5.09754336,
  },
  "z3-highmem-44-highlssd": {
    hourlyPrice: 4.98512212,
    windowsHourlyPrice: 7.00912212,
  },
  "z3-highmem-44-standardlssd": {
    hourlyPrice: 4.98512212,
    windowsHourlyPrice: 7.00912212,
  },
  "z3-highmem-8-highlssd": {
    hourlyPrice: 0.90638584,
    windowsHourlyPrice: 1.27438584,
  },
  "z3-highmem-88": {
    hourlyPrice: 9.97024424,
    windowsHourlyPrice: 14.01824424,
  },
  "z3-highmem-88-highlssd": {
    hourlyPrice: 9.97024424,
    windowsHourlyPrice: 14.01824424,
  },
  "z3-highmem-88-standardlssd": {
    hourlyPrice: 9.97024424,
    windowsHourlyPrice: 14.01824424,
  },
};
