// GCP instance prices for region key: africa_south1 (updated 2026-08-30)
// Auto-generated by tools/split-data.js — do not edit by hand
// Specs for these types live in js/gcp/gcp-data.js as GCP_SPECS.compute
window.africa_south1 = {
  "a2-highgpu-1g": {
    hourlyPrice: 0.96723628,
    windowsHourlyPrice: 1.51923628,
  },
  "a2-highgpu-2g": {
    hourlyPrice: 1.93447256,
    windowsHourlyPrice: 3.03847256,
  },
  "a2-highgpu-4g": {
    hourlyPrice: 3.86894512,
    windowsHourlyPrice: 6.07694512,
  },
  "a2-highgpu-8g": {
    hourlyPrice: 7.73789024,
    windowsHourlyPrice: 12.15389024,
  },
  "a2-megagpu-16g": {
    hourlyPrice: 11.50645024,
    windowsHourlyPrice: 15.92245024,
  },
  "a2-ultragpu-1g": {
    hourlyPrice: 1.43830628,
    windowsHourlyPrice: 1.99030628,
  },
  "a2-ultragpu-2g": {
    hourlyPrice: 2.87661256,
    windowsHourlyPrice: 3.98061256,
  },
  "a2-ultragpu-4g": {
    hourlyPrice: 5.75322512,
    windowsHourlyPrice: 7.96122512,
  },
  "a2-ultragpu-8g": {
    hourlyPrice: 11.50645024,
    windowsHourlyPrice: 15.92245024,
  },
  "a3-edgegpu-8g": {
    hourlyPrice: 12.37377024,
    windowsHourlyPrice: 21.94177024,
  },
  "a3-edgegpu-8g-nolssd": {
    hourlyPrice: 12.37377024,
    windowsHourlyPrice: 21.94177024,
  },
  "a3-highgpu-1g": {
    hourlyPrice: 1.54672128,
    windowsHourlyPrice: 2.74272128,
  },
  "a3-highgpu-2g": {
    hourlyPrice: 3.09344256,
    windowsHourlyPrice: 5.48544256,
  },
  "a3-highgpu-4g": {
    hourlyPrice: 6.18688512,
    windowsHourlyPrice: 10.97088512,
  },
  "a3-highgpu-8g": {
    hourlyPrice: 12.37377024,
    windowsHourlyPrice: 21.94177024,
  },
  "a3-megagpu-8g": {
    hourlyPrice: 12.37377024,
    windowsHourlyPrice: 21.94177024,
  },
  "a3-ultragpu-8g": {
    hourlyPrice: 16.04393928,
    windowsHourlyPrice: 26.34793928,
  },
  "a3-ultragpu-8g-nolssd": {
    hourlyPrice: 16.04393928,
    windowsHourlyPrice: 26.34793928,
  },
  "c2-standard-16": {
    hourlyPrice: 0.9188,
    windowsHourlyPrice: 1.6548,
  },
  "c2-standard-30": {
    hourlyPrice: 1.72275,
    windowsHourlyPrice: 3.10275,
  },
  "c2-standard-4": {
    hourlyPrice: 0.2297,
    windowsHourlyPrice: 0.4137,
  },
  "c2-standard-60": {
    hourlyPrice: 3.4455,
    windowsHourlyPrice: 6.2055,
  },
  "c2-standard-8": {
    hourlyPrice: 0.4594,
    windowsHourlyPrice: 0.8274,
  },
  "c2d-highcpu-112": {
    hourlyPrice: 4.622128,
    windowsHourlyPrice: 9.774128,
  },
  "c2d-highcpu-16": {
    hourlyPrice: 0.660304,
    windowsHourlyPrice: 1.396304,
  },
  "c2d-highcpu-2": {
    hourlyPrice: 0.082538,
    windowsHourlyPrice: 0.174538,
  },
  "c2d-highcpu-32": {
    hourlyPrice: 1.320608,
    windowsHourlyPrice: 2.792608,
  },
  "c2d-highcpu-4": {
    hourlyPrice: 0.165076,
    windowsHourlyPrice: 0.349076,
  },
  "c2d-highcpu-56": {
    hourlyPrice: 2.311064,
    windowsHourlyPrice: 4.887064,
  },
  "c2d-highcpu-8": {
    hourlyPrice: 0.330152,
    windowsHourlyPrice: 0.698152,
  },
  "c2d-highmem-112": {
    hourlyPrice: 7.551376,
    windowsHourlyPrice: 12.703376,
  },
  "c2d-highmem-16": {
    hourlyPrice: 1.078768,
    windowsHourlyPrice: 1.814768,
  },
  "c2d-highmem-2": {
    hourlyPrice: 0.134846,
    windowsHourlyPrice: 0.226846,
  },
  "c2d-highmem-32": {
    hourlyPrice: 2.157536,
    windowsHourlyPrice: 3.629536,
  },
  "c2d-highmem-4": {
    hourlyPrice: 0.269692,
    windowsHourlyPrice: 0.453692,
  },
  "c2d-highmem-56": {
    hourlyPrice: 3.775688,
    windowsHourlyPrice: 6.351688,
  },
  "c2d-highmem-8": {
    hourlyPrice: 0.539384,
    windowsHourlyPrice: 0.907384,
  },
  "c2d-standard-112": {
    hourlyPrice: 5.598544,
    windowsHourlyPrice: 10.750544,
  },
  "c2d-standard-16": {
    hourlyPrice: 0.799792,
    windowsHourlyPrice: 1.535792,
  },
  "c2d-standard-2": {
    hourlyPrice: 0.099974,
    windowsHourlyPrice: 0.191974,
  },
  "c2d-standard-32": {
    hourlyPrice: 1.599584,
    windowsHourlyPrice: 3.071584,
  },
  "c2d-standard-4": {
    hourlyPrice: 0.199948,
    windowsHourlyPrice: 0.383948,
  },
  "c2d-standard-56": {
    hourlyPrice: 2.799272,
    windowsHourlyPrice: 5.375272,
  },
  "c2d-standard-8": {
    hourlyPrice: 0.399896,
    windowsHourlyPrice: 0.767896,
  },
  "c3-highcpu-176": {
    hourlyPrice: 8.2412528,
    windowsHourlyPrice: 16.3372528,
  },
  "c3-highcpu-192-metal": {
    hourlyPrice: 9.5454784,
    windowsHourlyPrice: 18.3774784,
  },
  "c3-highcpu-22": {
    hourlyPrice: 1.0301566,
    windowsHourlyPrice: 2.0421566,
  },
  "c3-highcpu-4": {
    hourlyPrice: 0.1873012,
    windowsHourlyPrice: 0.3713012,
  },
  "c3-highcpu-44": {
    hourlyPrice: 2.0603132,
    windowsHourlyPrice: 4.0843132,
  },
  "c3-highcpu-8": {
    hourlyPrice: 0.3746024,
    windowsHourlyPrice: 0.7426024,
  },
  "c3-highcpu-88": {
    hourlyPrice: 4.1206264,
    windowsHourlyPrice: 8.1686264,
  },
  "c3-highmem-176": {
    hourlyPrice: 12.8201744,
    windowsHourlyPrice: 20.9161744,
  },
  "c3-highmem-192-metal": {
    hourlyPrice: 13.9856448,
    windowsHourlyPrice: 22.8176448,
  },
  "c3-highmem-22": {
    hourlyPrice: 1.6025218,
    windowsHourlyPrice: 2.6145218,
  },
  "c3-highmem-4": {
    hourlyPrice: 0.2913676,
    windowsHourlyPrice: 0.4753676,
  },
  "c3-highmem-44": {
    hourlyPrice: 3.2050436,
    windowsHourlyPrice: 5.2290436,
  },
  "c3-highmem-8": {
    hourlyPrice: 0.5827352,
    windowsHourlyPrice: 0.9507352,
  },
  "c3-highmem-88": {
    hourlyPrice: 6.4100872,
    windowsHourlyPrice: 10.4580872,
  },
  "c3-standard-176": {
    hourlyPrice: 9.76756,
    windowsHourlyPrice: 17.86356,
  },
  "c3-standard-176-lssd": {
    hourlyPrice: 9.76756,
    windowsHourlyPrice: 17.86356,
  },
  "c3-standard-192-metal": {
    hourlyPrice: 10.65552,
    windowsHourlyPrice: 19.48752,
  },
  "c3-standard-22": {
    hourlyPrice: 1.220945,
    windowsHourlyPrice: 2.232945,
  },
  "c3-standard-22-lssd": {
    hourlyPrice: 1.220945,
    windowsHourlyPrice: 2.232945,
  },
  "c3-standard-4": {
    hourlyPrice: 0.22199,
    windowsHourlyPrice: 0.40599,
  },
  "c3-standard-4-lssd": {
    hourlyPrice: 0.22199,
    windowsHourlyPrice: 0.40599,
  },
  "c3-standard-44": {
    hourlyPrice: 2.44189,
    windowsHourlyPrice: 4.46589,
  },
  "c3-standard-44-lssd": {
    hourlyPrice: 2.44189,
    windowsHourlyPrice: 4.46589,
  },
  "c3-standard-8": {
    hourlyPrice: 0.44398,
    windowsHourlyPrice: 0.81198,
  },
  "c3-standard-8-lssd": {
    hourlyPrice: 0.44398,
    windowsHourlyPrice: 0.81198,
  },
  "c3-standard-88": {
    hourlyPrice: 4.88378,
    windowsHourlyPrice: 8.93178,
  },
  "c3-standard-88-lssd": {
    hourlyPrice: 4.88378,
    windowsHourlyPrice: 8.93178,
  },
  "c3d-highcpu-16": {
    hourlyPrice: 0.66032512,
    windowsHourlyPrice: 1.39632512,
  },
  "c3d-highcpu-180": {
    hourlyPrice: 7.40250204,
    windowsHourlyPrice: 15.68250204,
  },
  "c3d-highcpu-30": {
    hourlyPrice: 1.23375034,
    windowsHourlyPrice: 2.61375034,
  },
  "c3d-highcpu-360": {
    hourlyPrice: 14.80500408,
    windowsHourlyPrice: 31.36500408,
  },
  "c3d-highcpu-4": {
    hourlyPrice: 0.16508128,
    windowsHourlyPrice: 0.34908128,
  },
  "c3d-highcpu-60": {
    hourlyPrice: 2.46750068,
    windowsHourlyPrice: 5.22750068,
  },
  "c3d-highcpu-8": {
    hourlyPrice: 0.33016256,
    windowsHourlyPrice: 0.69816256,
  },
  "c3d-highcpu-90": {
    hourlyPrice: 3.70125102,
    windowsHourlyPrice: 7.84125102,
  },
  "c3d-highmem-16": {
    hourlyPrice: 1.07881408,
    windowsHourlyPrice: 1.81481408,
  },
  "c3d-highmem-16-lssd": {
    hourlyPrice: 1.07881408,
    windowsHourlyPrice: 1.81481408,
  },
  "c3d-highmem-180": {
    hourlyPrice: 12.1366584,
    windowsHourlyPrice: 20.4166584,
  },
  "c3d-highmem-180-lssd": {
    hourlyPrice: 12.1366584,
    windowsHourlyPrice: 20.4166584,
  },
  "c3d-highmem-30": {
    hourlyPrice: 2.0227764,
    windowsHourlyPrice: 3.4027764,
  },
  "c3d-highmem-30-lssd": {
    hourlyPrice: 2.0227764,
    windowsHourlyPrice: 3.4027764,
  },
  "c3d-highmem-360": {
    hourlyPrice: 24.2733168,
    windowsHourlyPrice: 40.8333168,
  },
  "c3d-highmem-360-lssd": {
    hourlyPrice: 24.2733168,
    windowsHourlyPrice: 40.8333168,
  },
  "c3d-highmem-4": {
    hourlyPrice: 0.26970352,
    windowsHourlyPrice: 0.45370352,
  },
  "c3d-highmem-60": {
    hourlyPrice: 4.0455528,
    windowsHourlyPrice: 6.8055528,
  },
  "c3d-highmem-60-lssd": {
    hourlyPrice: 4.0455528,
    windowsHourlyPrice: 6.8055528,
  },
  "c3d-highmem-8": {
    hourlyPrice: 0.53940704,
    windowsHourlyPrice: 0.90740704,
  },
  "c3d-highmem-8-lssd": {
    hourlyPrice: 0.53940704,
    windowsHourlyPrice: 0.90740704,
  },
  "c3d-highmem-90": {
    hourlyPrice: 6.0683292,
    windowsHourlyPrice: 10.2083292,
  },
  "c3d-highmem-90-lssd": {
    hourlyPrice: 6.0683292,
    windowsHourlyPrice: 10.2083292,
  },
  "c3d-standard-16": {
    hourlyPrice: 0.79982144,
    windowsHourlyPrice: 1.53582144,
  },
  "c3d-standard-16-lssd": {
    hourlyPrice: 0.79982144,
    windowsHourlyPrice: 1.53582144,
  },
  "c3d-standard-180": {
    hourlyPrice: 8.9979912,
    windowsHourlyPrice: 17.2779912,
  },
  "c3d-standard-180-lssd": {
    hourlyPrice: 8.9979912,
    windowsHourlyPrice: 17.2779912,
  },
  "c3d-standard-30": {
    hourlyPrice: 1.4996652,
    windowsHourlyPrice: 2.8796652,
  },
  "c3d-standard-30-lssd": {
    hourlyPrice: 1.4996652,
    windowsHourlyPrice: 2.8796652,
  },
  "c3d-standard-360": {
    hourlyPrice: 17.9959824,
    windowsHourlyPrice: 34.5559824,
  },
  "c3d-standard-360-lssd": {
    hourlyPrice: 17.9959824,
    windowsHourlyPrice: 34.5559824,
  },
  "c3d-standard-4": {
    hourlyPrice: 0.19995536,
    windowsHourlyPrice: 0.38395536,
  },
  "c3d-standard-60": {
    hourlyPrice: 2.9993304,
    windowsHourlyPrice: 5.7593304,
  },
  "c3d-standard-60-lssd": {
    hourlyPrice: 2.9993304,
    windowsHourlyPrice: 5.7593304,
  },
  "c3d-standard-8": {
    hourlyPrice: 0.39991072,
    windowsHourlyPrice: 0.76791072,
  },
  "c3d-standard-8-lssd": {
    hourlyPrice: 0.39991072,
    windowsHourlyPrice: 0.76791072,
  },
  "c3d-standard-90": {
    hourlyPrice: 4.4989956,
    windowsHourlyPrice: 8.6389956,
  },
  "c3d-standard-90-lssd": {
    hourlyPrice: 4.4989956,
    windowsHourlyPrice: 8.6389956,
  },
  "c4-highcpu-144": {
    hourlyPrice: 6.74285184,
    windowsHourlyPrice: 13.36685184,
  },
  "c4-highcpu-16": {
    hourlyPrice: 0.74920576,
    windowsHourlyPrice: 1.48520576,
  },
  "c4-highcpu-192": {
    hourlyPrice: 8.99046912,
    windowsHourlyPrice: 17.82246912,
  },
  "c4-highcpu-2": {
    hourlyPrice: 0.09365072,
    windowsHourlyPrice: 0.18565072,
  },
  "c4-highcpu-24": {
    hourlyPrice: 1.12380864,
    windowsHourlyPrice: 2.22780864,
  },
  "c4-highcpu-288": {
    hourlyPrice: 13.48570368,
    windowsHourlyPrice: 26.73370368,
  },
  "c4-highcpu-32": {
    hourlyPrice: 1.49841152,
    windowsHourlyPrice: 2.97041152,
  },
  "c4-highcpu-4": {
    hourlyPrice: 0.18730144,
    windowsHourlyPrice: 0.37130144,
  },
  "c4-highcpu-48": {
    hourlyPrice: 2.24761728,
    windowsHourlyPrice: 4.45561728,
  },
  "c4-highcpu-8": {
    hourlyPrice: 0.37460288,
    windowsHourlyPrice: 0.74260288,
  },
  "c4-highcpu-96": {
    hourlyPrice: 4.49523456,
    windowsHourlyPrice: 8.91123456,
  },
  "c4-highmem-144": {
    hourlyPrice: 10.33316748,
    windowsHourlyPrice: 16.95716748,
  },
  "c4-highmem-144-lssd": {
    hourlyPrice: 10.33316748,
    windowsHourlyPrice: 16.95716748,
  },
  "c4-highmem-16": {
    hourlyPrice: 1.14812972,
    windowsHourlyPrice: 1.88412972,
  },
  "c4-highmem-16-lssd": {
    hourlyPrice: 1.14812972,
    windowsHourlyPrice: 1.88412972,
  },
  "c4-highmem-192": {
    hourlyPrice: 13.77755664,
    windowsHourlyPrice: 22.60955664,
  },
  "c4-highmem-192-lssd": {
    hourlyPrice: 13.77755664,
    windowsHourlyPrice: 22.60955664,
  },
  "c4-highmem-2": {
    hourlyPrice: 0.14134815,
    windowsHourlyPrice: 0.23334815,
  },
  "c4-highmem-24": {
    hourlyPrice: 1.72219458,
    windowsHourlyPrice: 2.82619458,
  },
  "c4-highmem-24-lssd": {
    hourlyPrice: 1.72219458,
    windowsHourlyPrice: 2.82619458,
  },
  "c4-highmem-288": {
    hourlyPrice: 20.66633496,
    windowsHourlyPrice: 33.91433496,
  },
  "c4-highmem-288-lssd": {
    hourlyPrice: 20.66633496,
    windowsHourlyPrice: 33.91433496,
  },
  "c4-highmem-288-lssd-metal": {
    hourlyPrice: 20.66633496,
    windowsHourlyPrice: 33.91433496,
  },
  "c4-highmem-288-metal": {
    hourlyPrice: 20.66633496,
    windowsHourlyPrice: 33.91433496,
  },
  "c4-highmem-32": {
    hourlyPrice: 2.29625944,
    windowsHourlyPrice: 3.76825944,
  },
  "c4-highmem-32-lssd": {
    hourlyPrice: 2.29625944,
    windowsHourlyPrice: 3.76825944,
  },
  "c4-highmem-4": {
    hourlyPrice: 0.28703243,
    windowsHourlyPrice: 0.47103243,
  },
  "c4-highmem-4-lssd": {
    hourlyPrice: 0.28703243,
    windowsHourlyPrice: 0.47103243,
  },
  "c4-highmem-48": {
    hourlyPrice: 3.44438916,
    windowsHourlyPrice: 5.65238916,
  },
  "c4-highmem-48-lssd": {
    hourlyPrice: 3.44438916,
    windowsHourlyPrice: 5.65238916,
  },
  "c4-highmem-8": {
    hourlyPrice: 0.57406486,
    windowsHourlyPrice: 0.94206486,
  },
  "c4-highmem-8-lssd": {
    hourlyPrice: 0.57406486,
    windowsHourlyPrice: 0.94206486,
  },
  "c4-highmem-96": {
    hourlyPrice: 6.88877832,
    windowsHourlyPrice: 11.30477832,
  },
  "c4-highmem-96-lssd": {
    hourlyPrice: 6.88877832,
    windowsHourlyPrice: 11.30477832,
  },
  "c4-standard-144": {
    hourlyPrice: 7.8355566,
    windowsHourlyPrice: 14.4595566,
  },
  "c4-standard-144-lssd": {
    hourlyPrice: 7.8355566,
    windowsHourlyPrice: 14.4595566,
  },
  "c4-standard-16": {
    hourlyPrice: 0.8706174,
    windowsHourlyPrice: 1.6066174,
  },
  "c4-standard-16-lssd": {
    hourlyPrice: 0.8706174,
    windowsHourlyPrice: 1.6066174,
  },
  "c4-standard-192": {
    hourlyPrice: 10.4474088,
    windowsHourlyPrice: 19.2794088,
  },
  "c4-standard-192-lssd": {
    hourlyPrice: 10.4474088,
    windowsHourlyPrice: 19.2794088,
  },
  "c4-standard-2": {
    hourlyPrice: 0.10665911,
    windowsHourlyPrice: 0.19865911,
  },
  "c4-standard-24": {
    hourlyPrice: 1.3059261,
    windowsHourlyPrice: 2.4099261,
  },
  "c4-standard-24-lssd": {
    hourlyPrice: 1.3059261,
    windowsHourlyPrice: 2.4099261,
  },
  "c4-standard-288": {
    hourlyPrice: 15.6711132,
    windowsHourlyPrice: 28.9191132,
  },
  "c4-standard-288-lssd": {
    hourlyPrice: 15.6711132,
    windowsHourlyPrice: 28.9191132,
  },
  "c4-standard-288-lssd-metal": {
    hourlyPrice: 15.6711132,
    windowsHourlyPrice: 28.9191132,
  },
  "c4-standard-288-metal": {
    hourlyPrice: 15.6711132,
    windowsHourlyPrice: 28.9191132,
  },
  "c4-standard-32": {
    hourlyPrice: 1.7412348,
    windowsHourlyPrice: 3.2132348,
  },
  "c4-standard-32-lssd": {
    hourlyPrice: 1.7412348,
    windowsHourlyPrice: 3.2132348,
  },
  "c4-standard-4": {
    hourlyPrice: 0.21765435,
    windowsHourlyPrice: 0.40165435,
  },
  "c4-standard-4-lssd": {
    hourlyPrice: 0.21765435,
    windowsHourlyPrice: 0.40165435,
  },
  "c4-standard-48": {
    hourlyPrice: 2.6118522,
    windowsHourlyPrice: 4.8198522,
  },
  "c4-standard-48-lssd": {
    hourlyPrice: 2.6118522,
    windowsHourlyPrice: 4.8198522,
  },
  "c4-standard-8": {
    hourlyPrice: 0.4353087,
    windowsHourlyPrice: 0.8033087,
  },
  "c4-standard-8-lssd": {
    hourlyPrice: 0.4353087,
    windowsHourlyPrice: 0.8033087,
  },
  "c4-standard-96": {
    hourlyPrice: 5.2237044,
    windowsHourlyPrice: 9.6397044,
  },
  "c4-standard-96-lssd": {
    hourlyPrice: 5.2237044,
    windowsHourlyPrice: 9.6397044,
  },
  "c4a-highcpu-1": {
    hourlyPrice: 0.0417098,
    windowsHourlyPrice: 0.0877098,
  },
  "c4a-highcpu-16": {
    hourlyPrice: 0.6673568,
    windowsHourlyPrice: 1.4033568,
  },
  "c4a-highcpu-2": {
    hourlyPrice: 0.0834196,
    windowsHourlyPrice: 0.1754196,
  },
  "c4a-highcpu-32": {
    hourlyPrice: 1.3347136,
    windowsHourlyPrice: 2.8067136,
  },
  "c4a-highcpu-4": {
    hourlyPrice: 0.1668392,
    windowsHourlyPrice: 0.3508392,
  },
  "c4a-highcpu-48": {
    hourlyPrice: 2.0020704,
    windowsHourlyPrice: 4.2100704,
  },
  "c4a-highcpu-64": {
    hourlyPrice: 2.6694272,
    windowsHourlyPrice: 5.6134272,
  },
  "c4a-highcpu-72": {
    hourlyPrice: 3.0031056,
    windowsHourlyPrice: 6.3151056,
  },
  "c4a-highcpu-8": {
    hourlyPrice: 0.3336784,
    windowsHourlyPrice: 0.7016784,
  },
  "c4a-highmem-1": {
    hourlyPrice: 0.0648992,
    windowsHourlyPrice: 0.1108992,
  },
  "c4a-highmem-16": {
    hourlyPrice: 1.0383872,
    windowsHourlyPrice: 1.7743872,
  },
  "c4a-highmem-16-lssd": {
    hourlyPrice: 1.3098872,
    windowsHourlyPrice: 2.0458872,
  },
  "c4a-highmem-2": {
    hourlyPrice: 0.1297984,
    windowsHourlyPrice: 0.2217984,
  },
  "c4a-highmem-32": {
    hourlyPrice: 2.0767744,
    windowsHourlyPrice: 3.5487744,
  },
  "c4a-highmem-32-lssd": {
    hourlyPrice: 2.4840244,
    windowsHourlyPrice: 3.9560244,
  },
  "c4a-highmem-4": {
    hourlyPrice: 0.2595968,
    windowsHourlyPrice: 0.4435968,
  },
  "c4a-highmem-4-lssd": {
    hourlyPrice: 0.3274718,
    windowsHourlyPrice: 0.5114718,
  },
  "c4a-highmem-48": {
    hourlyPrice: 3.1151616,
    windowsHourlyPrice: 5.3231616,
  },
  "c4a-highmem-48-lssd": {
    hourlyPrice: 3.7939116,
    windowsHourlyPrice: 6.0019116,
  },
  "c4a-highmem-64": {
    hourlyPrice: 4.1535488,
    windowsHourlyPrice: 7.0975488,
  },
  "c4a-highmem-64-lssd": {
    hourlyPrice: 5.1037988,
    windowsHourlyPrice: 8.0477988,
  },
  "c4a-highmem-72": {
    hourlyPrice: 4.6727424,
    windowsHourlyPrice: 7.9847424,
  },
  "c4a-highmem-72-lssd": {
    hourlyPrice: 5.7587424,
    windowsHourlyPrice: 9.0707424,
  },
  "c4a-highmem-8": {
    hourlyPrice: 0.5191936,
    windowsHourlyPrice: 0.8871936,
  },
  "c4a-highmem-8-lssd": {
    hourlyPrice: 0.6549436,
    windowsHourlyPrice: 1.0229436,
  },
  "c4a-highmem-96-metal": {
    hourlyPrice: 6.2303232,
    windowsHourlyPrice: 10.6463232,
  },
  "c4a-standard-1": {
    hourlyPrice: 0.0494396,
    windowsHourlyPrice: 0.0954396,
  },
  "c4a-standard-16": {
    hourlyPrice: 0.7910336,
    windowsHourlyPrice: 1.5270336,
  },
  "c4a-standard-16-lssd": {
    hourlyPrice: 1.0625336,
    windowsHourlyPrice: 1.7985336,
  },
  "c4a-standard-2": {
    hourlyPrice: 0.0988792,
    windowsHourlyPrice: 0.1908792,
  },
  "c4a-standard-32": {
    hourlyPrice: 1.5820672,
    windowsHourlyPrice: 3.0540672,
  },
  "c4a-standard-32-lssd": {
    hourlyPrice: 1.9893172,
    windowsHourlyPrice: 3.4613172,
  },
  "c4a-standard-4": {
    hourlyPrice: 0.1977584,
    windowsHourlyPrice: 0.3817584,
  },
  "c4a-standard-4-lssd": {
    hourlyPrice: 0.2656334,
    windowsHourlyPrice: 0.4496334,
  },
  "c4a-standard-48": {
    hourlyPrice: 2.3731008,
    windowsHourlyPrice: 4.5811008,
  },
  "c4a-standard-48-lssd": {
    hourlyPrice: 3.0518508,
    windowsHourlyPrice: 5.2598508,
  },
  "c4a-standard-64": {
    hourlyPrice: 3.1641344,
    windowsHourlyPrice: 6.1081344,
  },
  "c4a-standard-64-lssd": {
    hourlyPrice: 4.1143844,
    windowsHourlyPrice: 7.0583844,
  },
  "c4a-standard-72": {
    hourlyPrice: 3.5596512,
    windowsHourlyPrice: 6.8716512,
  },
  "c4a-standard-72-lssd": {
    hourlyPrice: 4.6456512,
    windowsHourlyPrice: 7.9576512,
  },
  "c4a-standard-8": {
    hourlyPrice: 0.3955168,
    windowsHourlyPrice: 0.7635168,
  },
  "c4a-standard-8-lssd": {
    hourlyPrice: 0.5312668,
    windowsHourlyPrice: 0.8992668,
  },
  "c4d-highcpu-16": {
    hourlyPrice: 0.70014116,
    windowsHourlyPrice: 1.43614116,
  },
  "c4d-highcpu-192": {
    hourlyPrice: 8.40169388,
    windowsHourlyPrice: 17.23369388,
  },
  "c4d-highcpu-2": {
    hourlyPrice: 0.08441804,
    windowsHourlyPrice: 0.17641804,
  },
  "c4d-highcpu-32": {
    hourlyPrice: 1.40028231,
    windowsHourlyPrice: 2.87228231,
  },
  "c4d-highcpu-384": {
    hourlyPrice: 16.80338775,
    windowsHourlyPrice: 34.46738775,
  },
  "c4d-highcpu-384-metal": {
    hourlyPrice: 17.00176272,
    windowsHourlyPrice: 34.66576272,
  },
  "c4d-highcpu-4": {
    hourlyPrice: 0.17296888,
    windowsHourlyPrice: 0.35696888,
  },
  "c4d-highcpu-48": {
    hourlyPrice: 2.10042347,
    windowsHourlyPrice: 4.30842347,
  },
  "c4d-highcpu-64": {
    hourlyPrice: 2.80056463,
    windowsHourlyPrice: 5.74456463,
  },
  "c4d-highcpu-8": {
    hourlyPrice: 0.35007058,
    windowsHourlyPrice: 0.71807058,
  },
  "c4d-highcpu-96": {
    hourlyPrice: 4.20084694,
    windowsHourlyPrice: 8.61684694,
  },
  "c4d-highmem-16": {
    hourlyPrice: 1.0968911,
    windowsHourlyPrice: 1.8328911,
  },
  "c4d-highmem-16-lssd": {
    hourlyPrice: 1.18739452,
    windowsHourlyPrice: 1.92339452,
  },
  "c4d-highmem-192": {
    hourlyPrice: 13.16269316,
    windowsHourlyPrice: 21.99469316,
  },
  "c4d-highmem-192-lssd": {
    hourlyPrice: 14.61074796,
    windowsHourlyPrice: 23.44274796,
  },
  "c4d-highmem-2": {
    hourlyPrice: 0.13401178,
    windowsHourlyPrice: 0.22601178,
  },
  "c4d-highmem-32": {
    hourlyPrice: 2.19378219,
    windowsHourlyPrice: 3.66578219,
  },
  "c4d-highmem-32-lssd": {
    hourlyPrice: 2.37478904,
    windowsHourlyPrice: 3.84678904,
  },
  "c4d-highmem-384": {
    hourlyPrice: 26.32538632,
    windowsHourlyPrice: 43.98938632,
  },
  "c4d-highmem-384-lssd": {
    hourlyPrice: 29.22149591,
    windowsHourlyPrice: 46.88549591,
  },
  "c4d-highmem-384-metal": {
    hourlyPrice: 26.52376129,
    windowsHourlyPrice: 44.18776129,
  },
  "c4d-highmem-4": {
    hourlyPrice: 0.27215637,
    windowsHourlyPrice: 0.45615637,
  },
  "c4d-highmem-48": {
    hourlyPrice: 3.29067329,
    windowsHourlyPrice: 5.49867329,
  },
  "c4d-highmem-48-lssd": {
    hourlyPrice: 3.65268699,
    windowsHourlyPrice: 5.86068699,
  },
  "c4d-highmem-64": {
    hourlyPrice: 4.38756439,
    windowsHourlyPrice: 7.33156439,
  },
  "c4d-highmem-64-lssd": {
    hourlyPrice: 4.93058494,
    windowsHourlyPrice: 7.87458494,
  },
  "c4d-highmem-8": {
    hourlyPrice: 0.54844555,
    windowsHourlyPrice: 0.91644555,
  },
  "c4d-highmem-8-lssd": {
    hourlyPrice: 0.63894897,
    windowsHourlyPrice: 1.00694897,
  },
  "c4d-highmem-96": {
    hourlyPrice: 6.58134658,
    windowsHourlyPrice: 10.99734658,
  },
  "c4d-highmem-96-lssd": {
    hourlyPrice: 7.30537398,
    windowsHourlyPrice: 11.72137398,
  },
  "c4d-standard-16": {
    hourlyPrice: 0.83239114,
    windowsHourlyPrice: 1.56839114,
  },
  "c4d-standard-16-lssd": {
    hourlyPrice: 0.92289456,
    windowsHourlyPrice: 1.65889456,
  },
  "c4d-standard-192": {
    hourlyPrice: 9.98869364,
    windowsHourlyPrice: 18.82069364,
  },
  "c4d-standard-192-lssd": {
    hourlyPrice: 11.43674843,
    windowsHourlyPrice: 20.26874843,
  },
  "c4d-standard-2": {
    hourlyPrice: 0.10094928,
    windowsHourlyPrice: 0.19294928,
  },
  "c4d-standard-32": {
    hourlyPrice: 1.66478227,
    windowsHourlyPrice: 3.13678227,
  },
  "c4d-standard-32-lssd": {
    hourlyPrice: 1.84578912,
    windowsHourlyPrice: 3.31778912,
  },
  "c4d-standard-384": {
    hourlyPrice: 19.97738728,
    windowsHourlyPrice: 37.64138728,
  },
  "c4d-standard-384-lssd": {
    hourlyPrice: 22.87349687,
    windowsHourlyPrice: 40.53749687,
  },
  "c4d-standard-384-metal": {
    hourlyPrice: 20.17576225,
    windowsHourlyPrice: 37.83976225,
  },
  "c4d-standard-4": {
    hourlyPrice: 0.20603138,
    windowsHourlyPrice: 0.39003138,
  },
  "c4d-standard-48": {
    hourlyPrice: 2.49717341,
    windowsHourlyPrice: 4.70517341,
  },
  "c4d-standard-48-lssd": {
    hourlyPrice: 2.85918711,
    windowsHourlyPrice: 5.06718711,
  },
  "c4d-standard-64": {
    hourlyPrice: 3.32956455,
    windowsHourlyPrice: 6.27356455,
  },
  "c4d-standard-64-lssd": {
    hourlyPrice: 3.87258509,
    windowsHourlyPrice: 6.81658509,
  },
  "c4d-standard-8": {
    hourlyPrice: 0.41619557,
    windowsHourlyPrice: 0.78419557,
  },
  "c4d-standard-8-lssd": {
    hourlyPrice: 0.50669899,
    windowsHourlyPrice: 0.87469899,
  },
  "c4d-standard-96": {
    hourlyPrice: 4.99434682,
    windowsHourlyPrice: 9.41034682,
  },
  "c4d-standard-96-lssd": {
    hourlyPrice: 5.71837422,
    windowsHourlyPrice: 10.13437422,
  },
  "e2-highcpu-16": {
    hourlyPrice: 0.43535136,
    windowsHourlyPrice: 1.17135136,
  },
  "e2-highcpu-2": {
    hourlyPrice: 0.05441892,
    windowsHourlyPrice: 0.14641892,
  },
  "e2-highcpu-32": {
    hourlyPrice: 0.87070272,
    windowsHourlyPrice: 2.34270272,
  },
  "e2-highcpu-4": {
    hourlyPrice: 0.10883784,
    windowsHourlyPrice: 0.29283784,
  },
  "e2-highcpu-8": {
    hourlyPrice: 0.21767568,
    windowsHourlyPrice: 0.58567568,
  },
  "e2-highmem-16": {
    hourlyPrice: 0.79555344,
    windowsHourlyPrice: 1.53155344,
  },
  "e2-highmem-2": {
    hourlyPrice: 0.09944418,
    windowsHourlyPrice: 0.19144418,
  },
  "e2-highmem-4": {
    hourlyPrice: 0.19888836,
    windowsHourlyPrice: 0.38288836,
  },
  "e2-highmem-8": {
    hourlyPrice: 0.39777672,
    windowsHourlyPrice: 0.76577672,
  },
  "e2-medium": {
    hourlyPrice: 0.0608511,
    windowsHourlyPrice: 0.1528511,
  },
  "e2-micro": {
    hourlyPrice: 0.05120283,
    windowsHourlyPrice: 0.14320283,
  },
  "e2-small": {
    hourlyPrice: 0.05441892,
    windowsHourlyPrice: 0.14641892,
  },
  "e2-standard-16": {
    hourlyPrice: 0.58972368,
    windowsHourlyPrice: 1.32572368,
  },
  "e2-standard-2": {
    hourlyPrice: 0.07371546,
    windowsHourlyPrice: 0.16571546,
  },
  "e2-standard-32": {
    hourlyPrice: 1.17944736,
    windowsHourlyPrice: 2.65144736,
  },
  "e2-standard-4": {
    hourlyPrice: 0.14743092,
    windowsHourlyPrice: 0.33143092,
  },
  "e2-standard-8": {
    hourlyPrice: 0.29486184,
    windowsHourlyPrice: 0.66286184,
  },
  "g2-standard-12": {
    hourlyPrice: 0.57601176,
    windowsHourlyPrice: 1.12801176,
  },
  "g2-standard-16": {
    hourlyPrice: 0.76801568,
    windowsHourlyPrice: 1.50401568,
  },
  "g2-standard-24": {
    hourlyPrice: 1.15202352,
    windowsHourlyPrice: 2.25602352,
  },
  "g2-standard-32": {
    hourlyPrice: 1.53603136,
    windowsHourlyPrice: 3.00803136,
  },
  "g2-standard-4": {
    hourlyPrice: 0.19200392,
    windowsHourlyPrice: 0.37600392,
  },
  "g2-standard-48": {
    hourlyPrice: 2.30404704,
    windowsHourlyPrice: 4.51204704,
  },
  "g2-standard-8": {
    hourlyPrice: 0.38400784,
    windowsHourlyPrice: 0.75200784,
  },
  "g2-standard-96": {
    hourlyPrice: 4.60809408,
    windowsHourlyPrice: 9.02409408,
  },
  "h3-standard-88": {
    hourlyPrice: 5.42137728,
    windowsHourlyPrice: 9.46937728,
  },
  "m1-megamem-96": {
    hourlyPrice: 11.74324068,
    windowsHourlyPrice: 16.15924068,
  },
  "m1-ultramem-160": {
    hourlyPrice: 27.7557352,
    windowsHourlyPrice: 35.1157352,
  },
  "m1-ultramem-40": {
    hourlyPrice: 6.9389338,
    windowsHourlyPrice: 8.7789338,
  },
  "m1-ultramem-80": {
    hourlyPrice: 13.8778676,
    windowsHourlyPrice: 17.5578676,
  },
  "m2-hypermem-416": {
    hourlyPrice: 74.15679171,
    windowsHourlyPrice: 93.29279171,
  },
  "m2-megamem-416": {
    hourlyPrice: 55.44133034,
    windowsHourlyPrice: 74.57733034,
  },
  "m2-ultramem-208": {
    hourlyPrice: 46.43612654,
    windowsHourlyPrice: 56.00412654,
  },
  "m2-ultramem-416": {
    hourlyPrice: 92.87225309,
    windowsHourlyPrice: 112.00825309,
  },
  "m2-ultramem2x-96": {
    hourlyPrice: 12.1026904,
    windowsHourlyPrice: 16.5186904,
  },
  "m2-ultramemx-96": {
    hourlyPrice: 7.9705403,
    windowsHourlyPrice: 12.3865403,
  },
  "m3-megamem-128": {
    hourlyPrice: 15.8663936,
    windowsHourlyPrice: 21.7543936,
  },
  "m3-megamem-64": {
    hourlyPrice: 7.9331968,
    windowsHourlyPrice: 10.8771968,
  },
  "m3-ultramem-128": {
    hourlyPrice: 26.8280448,
    windowsHourlyPrice: 32.7160448,
  },
  "m3-ultramem-32": {
    hourlyPrice: 6.7070112,
    windowsHourlyPrice: 8.1790112,
  },
  "m3-ultramem-64": {
    hourlyPrice: 13.4140224,
    windowsHourlyPrice: 16.3580224,
  },
  "m4-hypermem-16": {
    hourlyPrice: 1.6254784,
    windowsHourlyPrice: 2.3614784,
  },
  "m4-hypermem-32": {
    hourlyPrice: 3.2509568,
    windowsHourlyPrice: 4.7229568,
  },
  "m4-hypermem-64": {
    hourlyPrice: 6.5019136,
    windowsHourlyPrice: 9.4459136,
  },
  "m4-megamem-112": {
    hourlyPrice: 10.0862688,
    windowsHourlyPrice: 15.2382688,
  },
  "m4-megamem-224": {
    hourlyPrice: 20.1725376,
    windowsHourlyPrice: 30.4765376,
  },
  "m4-megamem-28": {
    hourlyPrice: 2.5215672,
    windowsHourlyPrice: 3.8095672,
  },
  "m4-megamem-56": {
    hourlyPrice: 5.0431344,
    windowsHourlyPrice: 7.6191344,
  },
  "m4-ultramem-112": {
    hourlyPrice: 17.8387488,
    windowsHourlyPrice: 22.9907488,
  },
  "m4-ultramem-224": {
    hourlyPrice: 35.6774976,
    windowsHourlyPrice: 45.9814976,
  },
  "m4-ultramem-56": {
    hourlyPrice: 8.9193744,
    windowsHourlyPrice: 11.4953744,
  },
  "n1-highcpu-16": {
    hourlyPrice: 0.62348822,
    windowsHourlyPrice: 1.35948822,
  },
  "n1-highcpu-2": {
    hourlyPrice: 0.07793489,
    windowsHourlyPrice: 0.16993489,
  },
  "n1-highcpu-32": {
    hourlyPrice: 1.24697189,
    windowsHourlyPrice: 2.71897189,
  },
  "n1-highcpu-4": {
    hourlyPrice: 0.15586978,
    windowsHourlyPrice: 0.33986978,
  },
  "n1-highcpu-64": {
    hourlyPrice: 2.49394378,
    windowsHourlyPrice: 5.43794378,
  },
  "n1-highcpu-8": {
    hourlyPrice: 0.31174411,
    windowsHourlyPrice: 0.67974411,
  },
  "n1-highcpu-96": {
    hourlyPrice: 3.74092022,
    windowsHourlyPrice: 8.15692022,
  },
  "n1-highmem-16": {
    hourlyPrice: 1.041112,
    windowsHourlyPrice: 1.777112,
  },
  "n1-highmem-2": {
    hourlyPrice: 0.130139,
    windowsHourlyPrice: 0.222139,
  },
  "n1-highmem-32": {
    hourlyPrice: 2.082224,
    windowsHourlyPrice: 3.554224,
  },
  "n1-highmem-4": {
    hourlyPrice: 0.260278,
    windowsHourlyPrice: 0.444278,
  },
  "n1-highmem-64": {
    hourlyPrice: 4.164448,
    windowsHourlyPrice: 7.108448,
  },
  "n1-highmem-8": {
    hourlyPrice: 0.520556,
    windowsHourlyPrice: 0.888556,
  },
  "n1-highmem-96": {
    hourlyPrice: 6.246672,
    windowsHourlyPrice: 10.662672,
  },
  "n1-megamem-96": {
    hourlyPrice: 10.02021578,
    windowsHourlyPrice: 14.43621578,
  },
  "n1-standard-1": {
    hourlyPrice: 0.05225175,
    windowsHourlyPrice: 0.09825175,
  },
  "n1-standard-16": {
    hourlyPrice: 0.836028,
    windowsHourlyPrice: 1.572028,
  },
  "n1-standard-2": {
    hourlyPrice: 0.1045035,
    windowsHourlyPrice: 0.1965035,
  },
  "n1-standard-32": {
    hourlyPrice: 1.672056,
    windowsHourlyPrice: 3.144056,
  },
  "n1-standard-4": {
    hourlyPrice: 0.209007,
    windowsHourlyPrice: 0.393007,
  },
  "n1-standard-64": {
    hourlyPrice: 3.344112,
    windowsHourlyPrice: 6.288112,
  },
  "n1-standard-8": {
    hourlyPrice: 0.418014,
    windowsHourlyPrice: 0.786014,
  },
  "n1-standard-96": {
    hourlyPrice: 5.016168,
    windowsHourlyPrice: 9.432168,
  },
  "n1-ultramem-160": {
    hourlyPrice: 23.480564,
    windowsHourlyPrice: 30.840564,
  },
  "n1-ultramem-40": {
    hourlyPrice: 5.870141,
    windowsHourlyPrice: 7.710141,
  },
  "n1-ultramem-80": {
    hourlyPrice: 11.740282,
    windowsHourlyPrice: 15.420282,
  },
  "n2-highcpu-16": {
    hourlyPrice: 0.630944,
    windowsHourlyPrice: 1.366944,
  },
  "n2-highcpu-2": {
    hourlyPrice: 0.078868,
    windowsHourlyPrice: 0.170868,
  },
  "n2-highcpu-32": {
    hourlyPrice: 1.261888,
    windowsHourlyPrice: 2.733888,
  },
  "n2-highcpu-4": {
    hourlyPrice: 0.157736,
    windowsHourlyPrice: 0.341736,
  },
  "n2-highcpu-48": {
    hourlyPrice: 1.892832,
    windowsHourlyPrice: 4.100832,
  },
  "n2-highcpu-64": {
    hourlyPrice: 2.523776,
    windowsHourlyPrice: 5.467776,
  },
  "n2-highcpu-8": {
    hourlyPrice: 0.315472,
    windowsHourlyPrice: 0.683472,
  },
  "n2-highcpu-80": {
    hourlyPrice: 3.15472,
    windowsHourlyPrice: 6.83472,
  },
  "n2-highcpu-96": {
    hourlyPrice: 3.785664,
    windowsHourlyPrice: 8.201664,
  },
  "n2-highmem-128": {
    hourlyPrice: 8.478048,
    windowsHourlyPrice: 14.366048,
  },
  "n2-highmem-16": {
    hourlyPrice: 1.152976,
    windowsHourlyPrice: 1.888976,
  },
  "n2-highmem-2": {
    hourlyPrice: 0.144122,
    windowsHourlyPrice: 0.236122,
  },
  "n2-highmem-32": {
    hourlyPrice: 2.305952,
    windowsHourlyPrice: 3.777952,
  },
  "n2-highmem-4": {
    hourlyPrice: 0.288244,
    windowsHourlyPrice: 0.472244,
  },
  "n2-highmem-48": {
    hourlyPrice: 3.458928,
    windowsHourlyPrice: 5.666928,
  },
  "n2-highmem-64": {
    hourlyPrice: 4.611904,
    windowsHourlyPrice: 7.555904,
  },
  "n2-highmem-8": {
    hourlyPrice: 0.576488,
    windowsHourlyPrice: 0.944488,
  },
  "n2-highmem-80": {
    hourlyPrice: 5.76488,
    windowsHourlyPrice: 9.44488,
  },
  "n2-highmem-96": {
    hourlyPrice: 6.917856,
    windowsHourlyPrice: 11.333856,
  },
  "n2-standard-128": {
    hourlyPrice: 6.837376,
    windowsHourlyPrice: 12.725376,
  },
  "n2-standard-16": {
    hourlyPrice: 0.854672,
    windowsHourlyPrice: 1.590672,
  },
  "n2-standard-2": {
    hourlyPrice: 0.106834,
    windowsHourlyPrice: 0.198834,
  },
  "n2-standard-32": {
    hourlyPrice: 1.709344,
    windowsHourlyPrice: 3.181344,
  },
  "n2-standard-4": {
    hourlyPrice: 0.213668,
    windowsHourlyPrice: 0.397668,
  },
  "n2-standard-48": {
    hourlyPrice: 2.564016,
    windowsHourlyPrice: 4.772016,
  },
  "n2-standard-64": {
    hourlyPrice: 3.418688,
    windowsHourlyPrice: 6.362688,
  },
  "n2-standard-8": {
    hourlyPrice: 0.427336,
    windowsHourlyPrice: 0.795336,
  },
  "n2-standard-80": {
    hourlyPrice: 4.27336,
    windowsHourlyPrice: 7.95336,
  },
  "n2-standard-96": {
    hourlyPrice: 5.128032,
    windowsHourlyPrice: 9.544032,
  },
  "n2d-highcpu-128": {
    hourlyPrice: 4.391424,
    windowsHourlyPrice: 10.279424,
  },
  "n2d-highcpu-16": {
    hourlyPrice: 0.548928,
    windowsHourlyPrice: 1.284928,
  },
  "n2d-highcpu-2": {
    hourlyPrice: 0.068616,
    windowsHourlyPrice: 0.160616,
  },
  "n2d-highcpu-224": {
    hourlyPrice: 7.684992,
    windowsHourlyPrice: 17.988992,
  },
  "n2d-highcpu-32": {
    hourlyPrice: 1.097856,
    windowsHourlyPrice: 2.569856,
  },
  "n2d-highcpu-4": {
    hourlyPrice: 0.137232,
    windowsHourlyPrice: 0.321232,
  },
  "n2d-highcpu-48": {
    hourlyPrice: 1.646784,
    windowsHourlyPrice: 3.854784,
  },
  "n2d-highcpu-64": {
    hourlyPrice: 2.195712,
    windowsHourlyPrice: 5.139712,
  },
  "n2d-highcpu-8": {
    hourlyPrice: 0.274464,
    windowsHourlyPrice: 0.642464,
  },
  "n2d-highcpu-80": {
    hourlyPrice: 2.74464,
    windowsHourlyPrice: 6.42464,
  },
  "n2d-highcpu-96": {
    hourlyPrice: 3.293568,
    windowsHourlyPrice: 7.709568,
  },
  "n2d-highmem-16": {
    hourlyPrice: 1.003088,
    windowsHourlyPrice: 1.739088,
  },
  "n2d-highmem-2": {
    hourlyPrice: 0.125386,
    windowsHourlyPrice: 0.217386,
  },
  "n2d-highmem-32": {
    hourlyPrice: 2.006176,
    windowsHourlyPrice: 3.478176,
  },
  "n2d-highmem-4": {
    hourlyPrice: 0.250772,
    windowsHourlyPrice: 0.434772,
  },
  "n2d-highmem-48": {
    hourlyPrice: 3.009264,
    windowsHourlyPrice: 5.217264,
  },
  "n2d-highmem-64": {
    hourlyPrice: 4.012352,
    windowsHourlyPrice: 6.956352,
  },
  "n2d-highmem-8": {
    hourlyPrice: 0.501544,
    windowsHourlyPrice: 0.869544,
  },
  "n2d-highmem-80": {
    hourlyPrice: 5.01544,
    windowsHourlyPrice: 8.69544,
  },
  "n2d-highmem-96": {
    hourlyPrice: 6.018528,
    windowsHourlyPrice: 10.434528,
  },
  "n2d-standard-128": {
    hourlyPrice: 5.948544,
    windowsHourlyPrice: 11.836544,
  },
  "n2d-standard-16": {
    hourlyPrice: 0.743568,
    windowsHourlyPrice: 1.479568,
  },
  "n2d-standard-2": {
    hourlyPrice: 0.092946,
    windowsHourlyPrice: 0.184946,
  },
  "n2d-standard-224": {
    hourlyPrice: 10.409952,
    windowsHourlyPrice: 20.713952,
  },
  "n2d-standard-32": {
    hourlyPrice: 1.487136,
    windowsHourlyPrice: 2.959136,
  },
  "n2d-standard-4": {
    hourlyPrice: 0.185892,
    windowsHourlyPrice: 0.369892,
  },
  "n2d-standard-48": {
    hourlyPrice: 2.230704,
    windowsHourlyPrice: 4.438704,
  },
  "n2d-standard-64": {
    hourlyPrice: 2.974272,
    windowsHourlyPrice: 5.918272,
  },
  "n2d-standard-8": {
    hourlyPrice: 0.371784,
    windowsHourlyPrice: 0.739784,
  },
  "n2d-standard-80": {
    hourlyPrice: 3.71784,
    windowsHourlyPrice: 7.39784,
  },
  "n2d-standard-96": {
    hourlyPrice: 4.461408,
    windowsHourlyPrice: 8.877408,
  },
  "n4-highcpu-16": {
    hourlyPrice: 0.67422544,
    windowsHourlyPrice: 1.41022544,
  },
  "n4-highcpu-2": {
    hourlyPrice: 0.08427818,
    windowsHourlyPrice: 0.17627818,
  },
  "n4-highcpu-32": {
    hourlyPrice: 1.34845088,
    windowsHourlyPrice: 2.82045088,
  },
  "n4-highcpu-4": {
    hourlyPrice: 0.16855636,
    windowsHourlyPrice: 0.35255636,
  },
  "n4-highcpu-48": {
    hourlyPrice: 2.02267632,
    windowsHourlyPrice: 4.23067632,
  },
  "n4-highcpu-64": {
    hourlyPrice: 2.69690176,
    windowsHourlyPrice: 5.64090176,
  },
  "n4-highcpu-8": {
    hourlyPrice: 0.33711272,
    windowsHourlyPrice: 0.70511272,
  },
  "n4-highcpu-80": {
    hourlyPrice: 3.3711272,
    windowsHourlyPrice: 7.0511272,
  },
  "n4-highmem-16": {
    hourlyPrice: 1.04842288,
    windowsHourlyPrice: 1.78442288,
  },
  "n4-highmem-2": {
    hourlyPrice: 0.13105286,
    windowsHourlyPrice: 0.22305286,
  },
  "n4-highmem-32": {
    hourlyPrice: 2.09684576,
    windowsHourlyPrice: 3.56884576,
  },
  "n4-highmem-4": {
    hourlyPrice: 0.26210572,
    windowsHourlyPrice: 0.44610572,
  },
  "n4-highmem-48": {
    hourlyPrice: 3.14526864,
    windowsHourlyPrice: 5.35326864,
  },
  "n4-highmem-64": {
    hourlyPrice: 4.19369152,
    windowsHourlyPrice: 7.13769152,
  },
  "n4-highmem-8": {
    hourlyPrice: 0.52421144,
    windowsHourlyPrice: 0.89221144,
  },
  "n4-highmem-80": {
    hourlyPrice: 5.2421144,
    windowsHourlyPrice: 8.9221144,
  },
  "n4-standard-16": {
    hourlyPrice: 0.79895792,
    windowsHourlyPrice: 1.53495792,
  },
  "n4-standard-2": {
    hourlyPrice: 0.09986974,
    windowsHourlyPrice: 0.19186974,
  },
  "n4-standard-32": {
    hourlyPrice: 1.59791584,
    windowsHourlyPrice: 3.06991584,
  },
  "n4-standard-4": {
    hourlyPrice: 0.19973948,
    windowsHourlyPrice: 0.38373948,
  },
  "n4-standard-48": {
    hourlyPrice: 2.39687376,
    windowsHourlyPrice: 4.60487376,
  },
  "n4-standard-64": {
    hourlyPrice: 3.19583168,
    windowsHourlyPrice: 6.13983168,
  },
  "n4-standard-8": {
    hourlyPrice: 0.39947896,
    windowsHourlyPrice: 0.76747896,
  },
  "n4-standard-80": {
    hourlyPrice: 3.9947896,
    windowsHourlyPrice: 7.6747896,
  },
  "n4a-highcpu-1": {
    hourlyPrice: 0.03576,
    windowsHourlyPrice: 0.08176,
  },
  "n4a-highcpu-16": {
    hourlyPrice: 0.57216,
    windowsHourlyPrice: 1.30816,
  },
  "n4a-highcpu-2": {
    hourlyPrice: 0.07152,
    windowsHourlyPrice: 0.16352,
  },
  "n4a-highcpu-32": {
    hourlyPrice: 1.14432,
    windowsHourlyPrice: 2.61632,
  },
  "n4a-highcpu-4": {
    hourlyPrice: 0.14304,
    windowsHourlyPrice: 0.32704,
  },
  "n4a-highcpu-48": {
    hourlyPrice: 1.71648,
    windowsHourlyPrice: 3.92448,
  },
  "n4a-highcpu-64": {
    hourlyPrice: 2.28864,
    windowsHourlyPrice: 5.23264,
  },
  "n4a-highcpu-8": {
    hourlyPrice: 0.28608,
    windowsHourlyPrice: 0.65408,
  },
  "n4a-highmem-1": {
    hourlyPrice: 0.05562,
    windowsHourlyPrice: 0.10162,
  },
  "n4a-highmem-16": {
    hourlyPrice: 0.88992,
    windowsHourlyPrice: 1.62592,
  },
  "n4a-highmem-2": {
    hourlyPrice: 0.11124,
    windowsHourlyPrice: 0.20324,
  },
  "n4a-highmem-32": {
    hourlyPrice: 1.77984,
    windowsHourlyPrice: 3.25184,
  },
  "n4a-highmem-4": {
    hourlyPrice: 0.22248,
    windowsHourlyPrice: 0.40648,
  },
  "n4a-highmem-48": {
    hourlyPrice: 2.66976,
    windowsHourlyPrice: 4.87776,
  },
  "n4a-highmem-64": {
    hourlyPrice: 3.55968,
    windowsHourlyPrice: 6.50368,
  },
  "n4a-highmem-8": {
    hourlyPrice: 0.44496,
    windowsHourlyPrice: 0.81296,
  },
  "n4a-standard-1": {
    hourlyPrice: 0.04238,
    windowsHourlyPrice: 0.08838,
  },
  "n4a-standard-16": {
    hourlyPrice: 0.67808,
    windowsHourlyPrice: 1.41408,
  },
  "n4a-standard-2": {
    hourlyPrice: 0.08476,
    windowsHourlyPrice: 0.17676,
  },
  "n4a-standard-32": {
    hourlyPrice: 1.35616,
    windowsHourlyPrice: 2.82816,
  },
  "n4a-standard-4": {
    hourlyPrice: 0.16952,
    windowsHourlyPrice: 0.35352,
  },
  "n4a-standard-48": {
    hourlyPrice: 2.03424,
    windowsHourlyPrice: 4.24224,
  },
  "n4a-standard-64": {
    hourlyPrice: 2.71232,
    windowsHourlyPrice: 5.65632,
  },
  "n4a-standard-8": {
    hourlyPrice: 0.33904,
    windowsHourlyPrice: 0.70704,
  },
  "n4d-highcpu-16": {
    hourlyPrice: 0.629328,
    windowsHourlyPrice: 1.365328,
  },
  "n4d-highcpu-2": {
    hourlyPrice: 0.078666,
    windowsHourlyPrice: 0.170666,
  },
  "n4d-highcpu-32": {
    hourlyPrice: 1.258656,
    windowsHourlyPrice: 2.730656,
  },
  "n4d-highcpu-4": {
    hourlyPrice: 0.157332,
    windowsHourlyPrice: 0.341332,
  },
  "n4d-highcpu-48": {
    hourlyPrice: 1.887984,
    windowsHourlyPrice: 4.095984,
  },
  "n4d-highcpu-64": {
    hourlyPrice: 2.517312,
    windowsHourlyPrice: 5.461312,
  },
  "n4d-highcpu-8": {
    hourlyPrice: 0.314664,
    windowsHourlyPrice: 0.682664,
  },
  "n4d-highcpu-80": {
    hourlyPrice: 3.14664,
    windowsHourlyPrice: 6.82664,
  },
  "n4d-highcpu-96": {
    hourlyPrice: 3.775968,
    windowsHourlyPrice: 8.191968,
  },
  "n4d-highmem-16": {
    hourlyPrice: 0.978768,
    windowsHourlyPrice: 1.714768,
  },
  "n4d-highmem-2": {
    hourlyPrice: 0.122346,
    windowsHourlyPrice: 0.214346,
  },
  "n4d-highmem-32": {
    hourlyPrice: 1.957536,
    windowsHourlyPrice: 3.429536,
  },
  "n4d-highmem-4": {
    hourlyPrice: 0.244692,
    windowsHourlyPrice: 0.428692,
  },
  "n4d-highmem-48": {
    hourlyPrice: 2.936304,
    windowsHourlyPrice: 5.144304,
  },
  "n4d-highmem-64": {
    hourlyPrice: 3.915072,
    windowsHourlyPrice: 6.859072,
  },
  "n4d-highmem-8": {
    hourlyPrice: 0.489384,
    windowsHourlyPrice: 0.857384,
  },
  "n4d-highmem-80": {
    hourlyPrice: 4.89384,
    windowsHourlyPrice: 8.57384,
  },
  "n4d-highmem-96": {
    hourlyPrice: 5.872608,
    windowsHourlyPrice: 10.288608,
  },
  "n4d-standard-16": {
    hourlyPrice: 0.745808,
    windowsHourlyPrice: 1.481808,
  },
  "n4d-standard-2": {
    hourlyPrice: 0.093226,
    windowsHourlyPrice: 0.185226,
  },
  "n4d-standard-32": {
    hourlyPrice: 1.491616,
    windowsHourlyPrice: 2.963616,
  },
  "n4d-standard-4": {
    hourlyPrice: 0.186452,
    windowsHourlyPrice: 0.370452,
  },
  "n4d-standard-48": {
    hourlyPrice: 2.237424,
    windowsHourlyPrice: 4.445424,
  },
  "n4d-standard-64": {
    hourlyPrice: 2.983232,
    windowsHourlyPrice: 5.927232,
  },
  "n4d-standard-8": {
    hourlyPrice: 0.372904,
    windowsHourlyPrice: 0.740904,
  },
  "n4d-standard-80": {
    hourlyPrice: 3.72904,
    windowsHourlyPrice: 7.40904,
  },
  "n4d-standard-96": {
    hourlyPrice: 4.474848,
    windowsHourlyPrice: 8.890848,
  },
  "t2d-standard-1": {
    hourlyPrice: 0.046473,
    windowsHourlyPrice: 0.092473,
  },
  "t2d-standard-16": {
    hourlyPrice: 0.743568,
    windowsHourlyPrice: 1.479568,
  },
  "t2d-standard-2": {
    hourlyPrice: 0.092946,
    windowsHourlyPrice: 0.184946,
  },
  "t2d-standard-32": {
    hourlyPrice: 1.487136,
    windowsHourlyPrice: 2.959136,
  },
  "t2d-standard-4": {
    hourlyPrice: 0.185892,
    windowsHourlyPrice: 0.369892,
  },
  "t2d-standard-48": {
    hourlyPrice: 2.230704,
    windowsHourlyPrice: 4.438704,
  },
  "t2d-standard-60": {
    hourlyPrice: 2.78838,
    windowsHourlyPrice: 5.54838,
  },
  "t2d-standard-8": {
    hourlyPrice: 0.371784,
    windowsHourlyPrice: 0.739784,
  },
  "z3-highmem-14-standardlssd": {
    hourlyPrice: 1.88422206,
    windowsHourlyPrice: 2.52822206,
  },
  "z3-highmem-16-highlssd": {
    hourlyPrice: 2.15339664,
    windowsHourlyPrice: 2.88939664,
  },
  "z3-highmem-176": {
    hourlyPrice: 23.68736304,
    windowsHourlyPrice: 31.78336304,
  },
  "z3-highmem-176-standardlssd": {
    hourlyPrice: 23.68736304,
    windowsHourlyPrice: 31.78336304,
  },
  "z3-highmem-192-highlssd-metal": {
    hourlyPrice: 25.84075968,
    windowsHourlyPrice: 34.67275968,
  },
  "z3-highmem-22-highlssd": {
    hourlyPrice: 2.96092038,
    windowsHourlyPrice: 3.97292038,
  },
  "z3-highmem-22-standardlssd": {
    hourlyPrice: 2.96092038,
    windowsHourlyPrice: 3.97292038,
  },
  "z3-highmem-32-highlssd": {
    hourlyPrice: 4.30679328,
    windowsHourlyPrice: 5.77879328,
  },
  "z3-highmem-44-highlssd": {
    hourlyPrice: 5.92184076,
    windowsHourlyPrice: 7.94584076,
  },
  "z3-highmem-44-standardlssd": {
    hourlyPrice: 5.92184076,
    windowsHourlyPrice: 7.94584076,
  },
  "z3-highmem-8-highlssd": {
    hourlyPrice: 1.07669832,
    windowsHourlyPrice: 1.44469832,
  },
  "z3-highmem-88": {
    hourlyPrice: 11.84368152,
    windowsHourlyPrice: 15.89168152,
  },
  "z3-highmem-88-highlssd": {
    hourlyPrice: 11.84368152,
    windowsHourlyPrice: 15.89168152,
  },
  "z3-highmem-88-standardlssd": {
    hourlyPrice: 11.84368152,
    windowsHourlyPrice: 15.89168152,
  },
};
