// AZURE instance prices for region key: southafricanorth (updated 2026-08-30)
// Auto-generated by tools/split-data.js — do not edit by hand
// Specs for these types live in js/azure/azure-data.js as AZURE_SPECS.compute
window.southafricanorth = {
  "a1v2": {
    linuxPrice: 0.0482,
    windowsPrice: 0.0942,
  },
  "a2mv2": {
    linuxPrice: 0.133,
    windowsPrice: 0.225,
  },
  "a2v2": {
    linuxPrice: 0.101,
    windowsPrice: 0.193,
  },
  "a4mv2": {
    linuxPrice: 0.266,
    windowsPrice: 0.45,
  },
  "a4v2": {
    linuxPrice: 0.213,
    windowsPrice: 0.397,
  },
  "a8mv2": {
    linuxPrice: 0.532,
    windowsPrice: 0.9,
  },
  "a8v2": {
    linuxPrice: 0.446,
    windowsPrice: 0.814,
  },
  "b12ms": {
    linuxPrice: 0.651,
    windowsPrice: 0.699,
  },
  "b16alsv2": {
    linuxPrice: 0.765,
    windowsPrice: 0.765,
  },
  "b16asv2": {
    linuxPrice: 0.855,
    windowsPrice: 0.855,
  },
  "b16lsv2": {
    linuxPrice: 0.769,
    windowsPrice: 0.842,
  },
  "b16ms": {
    linuxPrice: 0.868,
    windowsPrice: 0.932,
  },
  "b16sv2": {
    linuxPrice: 0.868,
    windowsPrice: 0.942,
  },
  "b1ls": {
    linuxPrice: 0.0068,
    windowsPrice: 0.0078,
  },
  "b1ms": {
    linuxPrice: 0.0271,
    windowsPrice: 0.0291,
  },
  "b1s": {
    linuxPrice: 0.0136,
    windowsPrice: 0.0156,
  },
  "b20ms": {
    linuxPrice: 1.085,
    windowsPrice: 1.165,
  },
  "b2alsv2": {
    linuxPrice: 0.0488,
    windowsPrice: 0.058,
  },
  "b2asv2": {
    linuxPrice: 0.0977,
    windowsPrice: 0.107,
  },
  "b2atsv2": {
    linuxPrice: 0.0214,
    windowsPrice: 0.0214,
  },
  "b2lsv2": {
    linuxPrice: 0.0635,
    windowsPrice: 0.0635,
  },
  "b2ms": {
    linuxPrice: 0.108,
    windowsPrice: 0.116,
  },
  "b2s": {
    linuxPrice: 0.0542,
    windowsPrice: 0.0622,
  },
  "b2sv2": {
    linuxPrice: 0.109,
    windowsPrice: 0.118,
  },
  "b2tsv2": {
    linuxPrice: 0.0136,
    windowsPrice: 0.0228,
  },
  "b32alsv2": {
    linuxPrice: 1.531,
    windowsPrice: 1.531,
  },
  "b32asv2": {
    linuxPrice: 1.71,
    windowsPrice: 1.71,
  },
  "b32lsv2": {
    linuxPrice: 1.684,
    windowsPrice: 1.684,
  },
  "b32sv2": {
    linuxPrice: 1.736,
    windowsPrice: 1.883,
  },
  "b4alsv2": {
    linuxPrice: 0.191,
    windowsPrice: 0.191,
  },
  "b4asv2": {
    linuxPrice: 0.195,
    windowsPrice: 0.214,
  },
  "b4lsv2": {
    linuxPrice: 0.211,
    windowsPrice: 0.211,
  },
  "b4ms": {
    linuxPrice: 0.217,
    windowsPrice: 0.233,
  },
  "b4sv2": {
    linuxPrice: 0.217,
    windowsPrice: 0.235,
  },
  "b8alsv2": {
    linuxPrice: 0.383,
    windowsPrice: 0.383,
  },
  "b8asv2": {
    linuxPrice: 0.427,
    windowsPrice: 0.427,
  },
  "b8lsv2": {
    linuxPrice: 0.421,
    windowsPrice: 0.421,
  },
  "b8ms": {
    linuxPrice: 0.434,
    windowsPrice: 0.466,
  },
  "b8sv2": {
    linuxPrice: 0.471,
    windowsPrice: 0.471,
  },
  "d1": {
    linuxPrice: 0.0898,
    windowsPrice: 0.136,
  },
  "d11": {
    linuxPrice: 0.232,
    windowsPrice: 0.324,
  },
  "d11s": {
    linuxPrice: 0.232,
    windowsPrice: 0.324,
  },
  "d11v2": {
    linuxPrice: 0.2,
    windowsPrice: 0.292,
  },
  "d12": {
    linuxPrice: 0.465,
    windowsPrice: 0.649,
  },
  "d128adsv7": {
    linuxPrice: 9.766,
    windowsPrice: 15.654,
  },
  "d128aldsv7": {
    linuxPrice: 8.154,
    windowsPrice: 14.042,
  },
  "d128alsv7": {
    linuxPrice: 6.874,
    windowsPrice: 12.762,
  },
  "d128asv7": {
    linuxPrice: 7.77,
    windowsPrice: 13.658,
  },
  "d128dsv6": {
    linuxPrice: 10.605,
    windowsPrice: 16.493,
  },
  "d128dsv7": {
    linuxPrice: 12.865,
    windowsPrice: 18.753,
  },
  "d128ldsv6": {
    linuxPrice: 9.391,
    windowsPrice: 15.279,
  },
  "d128ldsv7": {
    linuxPrice: 10.492,
    windowsPrice: 16.38,
  },
  "d128lsv6": {
    linuxPrice: 7.598,
    windowsPrice: 13.486,
  },
  "d128lsv7": {
    linuxPrice: 9.236,
    windowsPrice: 15.124,
  },
  "d128ndsv6": {
    linuxPrice: 14.868,
    windowsPrice: 20.756,
  },
  "d128nldsv6": {
    linuxPrice: 12.05,
    windowsPrice: 17.938,
  },
  "d128nlsv6": {
    linuxPrice: 9.757,
    windowsPrice: 15.645,
  },
  "d128nsv6": {
    linuxPrice: 13.01,
    windowsPrice: 18.898,
  },
  "d128sv6": {
    linuxPrice: 8.58,
    windowsPrice: 14.468,
  },
  "d128sv7": {
    linuxPrice: 10.432,
    windowsPrice: 16.32,
  },
  "d12s": {
    linuxPrice: 0.465,
    windowsPrice: 0.649,
  },
  "d12v2": {
    linuxPrice: 0.401,
    windowsPrice: 0.585,
  },
  "d13": {
    linuxPrice: 0.93,
    windowsPrice: 1.298,
  },
  "d13s": {
    linuxPrice: 0.93,
    windowsPrice: 1.298,
  },
  "d13v2": {
    linuxPrice: 0.801,
    windowsPrice: 1.169,
  },
  "d14": {
    linuxPrice: 1.859,
    windowsPrice: 2.595,
  },
  "d14s": {
    linuxPrice: 1.859,
    windowsPrice: 2.595,
  },
  "d14v2": {
    linuxPrice: 1.603,
    windowsPrice: 2.339,
  },
  "d15iv2": {
    linuxPrice: 2.003,
    windowsPrice: 2.923,
  },
  "d15v2": {
    linuxPrice: 2.003,
    windowsPrice: 2.923,
  },
  "d160adsv7": {
    linuxPrice: 12.208,
    windowsPrice: 19.568,
  },
  "d160aldsv7": {
    linuxPrice: 10.192,
    windowsPrice: 17.552,
  },
  "d160alsv7": {
    linuxPrice: 8.592,
    windowsPrice: 15.952,
  },
  "d160asv7": {
    linuxPrice: 9.712,
    windowsPrice: 17.072,
  },
  "d16adsv5": {
    linuxPrice: 1.1,
    windowsPrice: 1.836,
  },
  "d16adsv6": {
    linuxPrice: 1.221,
    windowsPrice: 1.957,
  },
  "d16adsv7": {
    linuxPrice: 1.221,
    windowsPrice: 1.957,
  },
  "d16aldsv6": {
    linuxPrice: 1.019,
    windowsPrice: 1.755,
  },
  "d16aldsv7": {
    linuxPrice: 1.019,
    windowsPrice: 1.755,
  },
  "d16alsv6": {
    linuxPrice: 0.859,
    windowsPrice: 1.595,
  },
  "d16alsv7": {
    linuxPrice: 0.859,
    windowsPrice: 1.595,
  },
  "d16asv4": {
    linuxPrice: 1.016,
    windowsPrice: 1.752,
  },
  "d16asv5": {
    linuxPrice: 1.652,
    windowsPrice: 1.652,
  },
  "d16asv6": {
    linuxPrice: 0.971,
    windowsPrice: 1.707,
  },
  "d16asv7": {
    linuxPrice: 0.971,
    windowsPrice: 1.707,
  },
  "d16av4": {
    linuxPrice: 1.016,
    windowsPrice: 1.752,
  },
  "d16dsv4": {
    linuxPrice: 1.2,
    windowsPrice: 1.936,
  },
  "d16dsv5": {
    linuxPrice: 1.2,
    windowsPrice: 1.936,
  },
  "d16dsv6": {
    linuxPrice: 1.326,
    windowsPrice: 2.062,
  },
  "d16dsv7": {
    linuxPrice: 1.608,
    windowsPrice: 2.344,
  },
  "d16dv4": {
    linuxPrice: 1.2,
    windowsPrice: 1.936,
  },
  "d16dv5": {
    linuxPrice: 1.2,
    windowsPrice: 1.936,
  },
  "d16ldsv5": {
    linuxPrice: 1.04,
    windowsPrice: 1.776,
  },
  "d16ldsv6": {
    linuxPrice: 1.174,
    windowsPrice: 1.91,
  },
  "d16ldsv7": {
    linuxPrice: 1.311,
    windowsPrice: 2.047,
  },
  "d16lsv5": {
    linuxPrice: 0.912,
    windowsPrice: 1.648,
  },
  "d16lsv6": {
    linuxPrice: 0.95,
    windowsPrice: 1.686,
  },
  "d16lsv7": {
    linuxPrice: 1.155,
    windowsPrice: 1.891,
  },
  "d16ndsv6": {
    linuxPrice: 1.859,
    windowsPrice: 2.595,
  },
  "d16nldsv6": {
    linuxPrice: 1.506,
    windowsPrice: 2.242,
  },
  "d16nlsv6": {
    linuxPrice: 1.22,
    windowsPrice: 1.956,
  },
  "d16nsv6": {
    linuxPrice: 1.626,
    windowsPrice: 2.362,
  },
  "d16pdsv6": {
    linuxPrice: 1.03,
    windowsPrice: 0,
  },
  "d16pldsv6": {
    linuxPrice: 0.875,
    windowsPrice: 0,
  },
  "d16plsv6": {
    linuxPrice: 0.696,
    windowsPrice: 0,
  },
  "d16psv6": {
    linuxPrice: 0.787,
    windowsPrice: 0,
  },
  "d16sv3": {
    linuxPrice: 1.016,
    windowsPrice: 1.752,
  },
  "d16sv4": {
    linuxPrice: 1.016,
    windowsPrice: 1.752,
  },
  "d16sv5": {
    linuxPrice: 1.016,
    windowsPrice: 1.752,
  },
  "d16sv6": {
    linuxPrice: 1.072,
    windowsPrice: 1.808,
  },
  "d16sv7": {
    linuxPrice: 1.304,
    windowsPrice: 2.04,
  },
  "d16v3": {
    linuxPrice: 1.016,
    windowsPrice: 1.752,
  },
  "d16v4": {
    linuxPrice: 1.016,
    windowsPrice: 1.752,
  },
  "d16v5": {
    linuxPrice: 1.016,
    windowsPrice: 1.752,
  },
  "d192dsv6": {
    linuxPrice: 15.907,
    windowsPrice: 24.739,
  },
  "d192dsv7": {
    linuxPrice: 19.297,
    windowsPrice: 28.129,
  },
  "d192ldsv7": {
    linuxPrice: 15.737,
    windowsPrice: 24.569,
  },
  "d192lsv7": {
    linuxPrice: 13.854,
    windowsPrice: 22.686,
  },
  "d192sv6": {
    linuxPrice: 12.87,
    windowsPrice: 21.702,
  },
  "d192sv7": {
    linuxPrice: 15.647,
    windowsPrice: 24.479,
  },
  "d1s": {
    linuxPrice: 0.0898,
    windowsPrice: 0.136,
  },
  "d1v2": {
    linuxPrice: 0.0767,
    windowsPrice: 0.123,
  },
  "d2": {
    linuxPrice: 0.18,
    windowsPrice: 0.272,
  },
  "d248dsv7": {
    linuxPrice: 24.926,
    windowsPrice: 36.334,
  },
  "d248ldsv7": {
    linuxPrice: 20.327,
    windowsPrice: 31.735,
  },
  "d248lsv7": {
    linuxPrice: 17.895,
    windowsPrice: 29.303,
  },
  "d248sv7": {
    linuxPrice: 20.211,
    windowsPrice: 31.619,
  },
  "d2adsv5": {
    linuxPrice: 0.23,
    windowsPrice: 0.23,
  },
  "d2adsv6": {
    linuxPrice: 0.153,
    windowsPrice: 0.245,
  },
  "d2adsv7": {
    linuxPrice: 0.153,
    windowsPrice: 0.245,
  },
  "d2aldsv6": {
    linuxPrice: 0.127,
    windowsPrice: 0.219,
  },
  "d2aldsv7": {
    linuxPrice: 0.127,
    windowsPrice: 0.219,
  },
  "d2alsv6": {
    linuxPrice: 0.107,
    windowsPrice: 0.199,
  },
  "d2alsv7": {
    linuxPrice: 0.107,
    windowsPrice: 0.199,
  },
  "d2asv4": {
    linuxPrice: 0.127,
    windowsPrice: 0.219,
  },
  "d2asv5": {
    linuxPrice: 0.207,
    windowsPrice: 0.207,
  },
  "d2asv6": {
    linuxPrice: 0.121,
    windowsPrice: 0.213,
  },
  "d2asv7": {
    linuxPrice: 0.121,
    windowsPrice: 0.213,
  },
  "d2av4": {
    linuxPrice: 0.127,
    windowsPrice: 0.219,
  },
  "d2dsv4": {
    linuxPrice: 0.15,
    windowsPrice: 0.242,
  },
  "d2dsv5": {
    linuxPrice: 0.15,
    windowsPrice: 0.242,
  },
  "d2dsv6": {
    linuxPrice: 0.166,
    windowsPrice: 0.258,
  },
  "d2dsv7": {
    linuxPrice: 0.201,
    windowsPrice: 0.293,
  },
  "d2dv4": {
    linuxPrice: 0.15,
    windowsPrice: 0.242,
  },
  "d2dv5": {
    linuxPrice: 0.15,
    windowsPrice: 0.242,
  },
  "d2ldsv5": {
    linuxPrice: 0.13,
    windowsPrice: 0.222,
  },
  "d2ldsv6": {
    linuxPrice: 0.147,
    windowsPrice: 0.239,
  },
  "d2ldsv7": {
    linuxPrice: 0.164,
    windowsPrice: 0.256,
  },
  "d2lsv5": {
    linuxPrice: 0.114,
    windowsPrice: 0.206,
  },
  "d2lsv6": {
    linuxPrice: 0.119,
    windowsPrice: 0.211,
  },
  "d2lsv7": {
    linuxPrice: 0.144,
    windowsPrice: 0.236,
  },
  "d2ndsv6": {
    linuxPrice: 0.232,
    windowsPrice: 0.324,
  },
  "d2nldsv6": {
    linuxPrice: 0.188,
    windowsPrice: 0.28,
  },
  "d2nlsv6": {
    linuxPrice: 0.152,
    windowsPrice: 0.244,
  },
  "d2nsv6": {
    linuxPrice: 0.203,
    windowsPrice: 0.295,
  },
  "d2pdsv6": {
    linuxPrice: 0.129,
    windowsPrice: 0,
  },
  "d2pldsv6": {
    linuxPrice: 0.109,
    windowsPrice: 0,
  },
  "d2plsv6": {
    linuxPrice: 0.087,
    windowsPrice: 0,
  },
  "d2psv6": {
    linuxPrice: 0.0984,
    windowsPrice: 0,
  },
  "d2s": {
    linuxPrice: 0.18,
    windowsPrice: 0.272,
  },
  "d2sv3": {
    linuxPrice: 0.127,
    windowsPrice: 0.219,
  },
  "d2sv4": {
    linuxPrice: 0.127,
    windowsPrice: 0.219,
  },
  "d2sv5": {
    linuxPrice: 0.127,
    windowsPrice: 0.219,
  },
  "d2sv6": {
    linuxPrice: 0.134,
    windowsPrice: 0.226,
  },
  "d2sv7": {
    linuxPrice: 0.163,
    windowsPrice: 0.255,
  },
  "d2v2": {
    linuxPrice: 0.153,
    windowsPrice: 0.245,
  },
  "d2v3": {
    linuxPrice: 0.127,
    windowsPrice: 0.219,
  },
  "d2v4": {
    linuxPrice: 0.127,
    windowsPrice: 0.219,
  },
  "d2v5": {
    linuxPrice: 0.127,
    windowsPrice: 0.219,
  },
  "d3": {
    linuxPrice: 0.359,
    windowsPrice: 0.543,
  },
  "d32adsv5": {
    linuxPrice: 2.2,
    windowsPrice: 3.672,
  },
  "d32adsv6": {
    linuxPrice: 2.442,
    windowsPrice: 3.914,
  },
  "d32adsv7": {
    linuxPrice: 2.442,
    windowsPrice: 3.914,
  },
  "d32aldsv6": {
    linuxPrice: 2.038,
    windowsPrice: 3.51,
  },
  "d32aldsv7": {
    linuxPrice: 2.038,
    windowsPrice: 3.51,
  },
  "d32alsv6": {
    linuxPrice: 1.718,
    windowsPrice: 3.19,
  },
  "d32alsv7": {
    linuxPrice: 1.718,
    windowsPrice: 3.19,
  },
  "d32asv4": {
    linuxPrice: 2.032,
    windowsPrice: 3.504,
  },
  "d32asv5": {
    linuxPrice: 3.304,
    windowsPrice: 3.304,
  },
  "d32asv6": {
    linuxPrice: 1.942,
    windowsPrice: 3.414,
  },
  "d32asv7": {
    linuxPrice: 1.942,
    windowsPrice: 3.414,
  },
  "d32av4": {
    linuxPrice: 2.032,
    windowsPrice: 3.504,
  },
  "d32dsv4": {
    linuxPrice: 2.4,
    windowsPrice: 3.872,
  },
  "d32dsv5": {
    linuxPrice: 2.4,
    windowsPrice: 3.872,
  },
  "d32dsv6": {
    linuxPrice: 2.651,
    windowsPrice: 4.123,
  },
  "d32dsv7": {
    linuxPrice: 3.216,
    windowsPrice: 4.688,
  },
  "d32dv4": {
    linuxPrice: 2.4,
    windowsPrice: 3.872,
  },
  "d32dv5": {
    linuxPrice: 2.4,
    windowsPrice: 3.872,
  },
  "d32ldsv5": {
    linuxPrice: 2.08,
    windowsPrice: 3.552,
  },
  "d32ldsv6": {
    linuxPrice: 2.348,
    windowsPrice: 3.82,
  },
  "d32ldsv7": {
    linuxPrice: 2.623,
    windowsPrice: 4.095,
  },
  "d32lsv5": {
    linuxPrice: 1.824,
    windowsPrice: 3.296,
  },
  "d32lsv6": {
    linuxPrice: 1.9,
    windowsPrice: 3.372,
  },
  "d32lsv7": {
    linuxPrice: 2.309,
    windowsPrice: 3.781,
  },
  "d32ndsv6": {
    linuxPrice: 3.717,
    windowsPrice: 5.189,
  },
  "d32nldsv6": {
    linuxPrice: 3.013,
    windowsPrice: 4.485,
  },
  "d32nlsv6": {
    linuxPrice: 2.439,
    windowsPrice: 3.911,
  },
  "d32nsv6": {
    linuxPrice: 3.252,
    windowsPrice: 4.724,
  },
  "d32pdsv6": {
    linuxPrice: 2.061,
    windowsPrice: 0,
  },
  "d32pldsv6": {
    linuxPrice: 1.75,
    windowsPrice: 0,
  },
  "d32plsv6": {
    linuxPrice: 1.392,
    windowsPrice: 0,
  },
  "d32psv6": {
    linuxPrice: 1.574,
    windowsPrice: 0,
  },
  "d32sv3": {
    linuxPrice: 2.032,
    windowsPrice: 3.504,
  },
  "d32sv4": {
    linuxPrice: 2.032,
    windowsPrice: 3.504,
  },
  "d32sv5": {
    linuxPrice: 2.032,
    windowsPrice: 3.504,
  },
  "d32sv6": {
    linuxPrice: 2.145,
    windowsPrice: 3.617,
  },
  "d32sv7": {
    linuxPrice: 2.608,
    windowsPrice: 4.08,
  },
  "d32v3": {
    linuxPrice: 2.032,
    windowsPrice: 3.504,
  },
  "d32v4": {
    linuxPrice: 2.032,
    windowsPrice: 3.504,
  },
  "d32v5": {
    linuxPrice: 2.032,
    windowsPrice: 3.504,
  },
  "d372dsv7": {
    linuxPrice: 37.389,
    windowsPrice: 54.501,
  },
  "d372sv7": {
    linuxPrice: 30.317,
    windowsPrice: 47.429,
  },
  "d3s": {
    linuxPrice: 0.359,
    windowsPrice: 0.543,
  },
  "d3v2": {
    linuxPrice: 0.307,
    windowsPrice: 0.491,
  },
  "d4": {
    linuxPrice: 0.718,
    windowsPrice: 1.086,
  },
  "d48adsv5": {
    linuxPrice: 3.3,
    windowsPrice: 5.508,
  },
  "d48adsv6": {
    linuxPrice: 3.662,
    windowsPrice: 5.87,
  },
  "d48adsv7": {
    linuxPrice: 3.662,
    windowsPrice: 5.87,
  },
  "d48aldsv6": {
    linuxPrice: 3.058,
    windowsPrice: 5.266,
  },
  "d48aldsv7": {
    linuxPrice: 3.058,
    windowsPrice: 5.266,
  },
  "d48alsv6": {
    linuxPrice: 2.578,
    windowsPrice: 4.786,
  },
  "d48alsv7": {
    linuxPrice: 2.578,
    windowsPrice: 4.786,
  },
  "d48asv4": {
    linuxPrice: 3.048,
    windowsPrice: 5.256,
  },
  "d48asv5": {
    linuxPrice: 4.956,
    windowsPrice: 4.956,
  },
  "d48asv6": {
    linuxPrice: 2.914,
    windowsPrice: 5.122,
  },
  "d48asv7": {
    linuxPrice: 2.914,
    windowsPrice: 5.122,
  },
  "d48av4": {
    linuxPrice: 3.048,
    windowsPrice: 5.256,
  },
  "d48dsv4": {
    linuxPrice: 3.6,
    windowsPrice: 5.808,
  },
  "d48dsv5": {
    linuxPrice: 3.6,
    windowsPrice: 5.808,
  },
  "d48dsv6": {
    linuxPrice: 3.977,
    windowsPrice: 6.185,
  },
  "d48dsv7": {
    linuxPrice: 4.824,
    windowsPrice: 7.032,
  },
  "d48dv4": {
    linuxPrice: 3.6,
    windowsPrice: 5.808,
  },
  "d48dv5": {
    linuxPrice: 3.6,
    windowsPrice: 5.808,
  },
  "d48ldsv5": {
    linuxPrice: 3.12,
    windowsPrice: 5.328,
  },
  "d48ldsv6": {
    linuxPrice: 3.522,
    windowsPrice: 5.73,
  },
  "d48ldsv7": {
    linuxPrice: 3.934,
    windowsPrice: 6.142,
  },
  "d48lsv5": {
    linuxPrice: 2.736,
    windowsPrice: 4.944,
  },
  "d48lsv6": {
    linuxPrice: 2.849,
    windowsPrice: 5.057,
  },
  "d48lsv7": {
    linuxPrice: 3.464,
    windowsPrice: 5.672,
  },
  "d48ndsv6": {
    linuxPrice: 5.576,
    windowsPrice: 7.784,
  },
  "d48nldsv6": {
    linuxPrice: 4.519,
    windowsPrice: 6.727,
  },
  "d48nlsv6": {
    linuxPrice: 3.659,
    windowsPrice: 5.867,
  },
  "d48nsv6": {
    linuxPrice: 4.879,
    windowsPrice: 7.087,
  },
  "d48pdsv6": {
    linuxPrice: 3.091,
    windowsPrice: 0,
  },
  "d48pldsv6": {
    linuxPrice: 2.626,
    windowsPrice: 0,
  },
  "d48plsv6": {
    linuxPrice: 2.088,
    windowsPrice: 0,
  },
  "d48psv6": {
    linuxPrice: 2.362,
    windowsPrice: 0,
  },
  "d48sv3": {
    linuxPrice: 3.048,
    windowsPrice: 5.256,
  },
  "d48sv4": {
    linuxPrice: 3.048,
    windowsPrice: 5.256,
  },
  "d48sv5": {
    linuxPrice: 3.048,
    windowsPrice: 5.256,
  },
  "d48sv6": {
    linuxPrice: 3.217,
    windowsPrice: 5.425,
  },
  "d48sv7": {
    linuxPrice: 3.912,
    windowsPrice: 6.12,
  },
  "d48v3": {
    linuxPrice: 3.048,
    windowsPrice: 5.256,
  },
  "d48v4": {
    linuxPrice: 3.048,
    windowsPrice: 5.256,
  },
  "d48v5": {
    linuxPrice: 3.048,
    windowsPrice: 5.256,
  },
  "d4adsv5": {
    linuxPrice: 0.459,
    windowsPrice: 0.459,
  },
  "d4adsv6": {
    linuxPrice: 0.305,
    windowsPrice: 0.489,
  },
  "d4adsv7": {
    linuxPrice: 0.305,
    windowsPrice: 0.489,
  },
  "d4aldsv6": {
    linuxPrice: 0.255,
    windowsPrice: 0.439,
  },
  "d4aldsv7": {
    linuxPrice: 0.255,
    windowsPrice: 0.439,
  },
  "d4alsv6": {
    linuxPrice: 0.215,
    windowsPrice: 0.399,
  },
  "d4alsv7": {
    linuxPrice: 0.215,
    windowsPrice: 0.399,
  },
  "d4asv4": {
    linuxPrice: 0.254,
    windowsPrice: 0.438,
  },
  "d4asv5": {
    linuxPrice: 0.413,
    windowsPrice: 0.413,
  },
  "d4asv6": {
    linuxPrice: 0.243,
    windowsPrice: 0.427,
  },
  "d4asv7": {
    linuxPrice: 0.243,
    windowsPrice: 0.427,
  },
  "d4av4": {
    linuxPrice: 0.254,
    windowsPrice: 0.438,
  },
  "d4dsv4": {
    linuxPrice: 0.3,
    windowsPrice: 0.484,
  },
  "d4dsv5": {
    linuxPrice: 0.3,
    windowsPrice: 0.484,
  },
  "d4dsv6": {
    linuxPrice: 0.331,
    windowsPrice: 0.515,
  },
  "d4dsv7": {
    linuxPrice: 0.402,
    windowsPrice: 0.586,
  },
  "d4dv4": {
    linuxPrice: 0.3,
    windowsPrice: 0.484,
  },
  "d4dv5": {
    linuxPrice: 0.3,
    windowsPrice: 0.484,
  },
  "d4ldsv5": {
    linuxPrice: 0.26,
    windowsPrice: 0.444,
  },
  "d4ldsv6": {
    linuxPrice: 0.293,
    windowsPrice: 0.477,
  },
  "d4ldsv7": {
    linuxPrice: 0.328,
    windowsPrice: 0.512,
  },
  "d4lsv5": {
    linuxPrice: 0.228,
    windowsPrice: 0.412,
  },
  "d4lsv6": {
    linuxPrice: 0.237,
    windowsPrice: 0.421,
  },
  "d4lsv7": {
    linuxPrice: 0.289,
    windowsPrice: 0.473,
  },
  "d4ndsv6": {
    linuxPrice: 0.428,
    windowsPrice: 0.612,
  },
  "d4nldsv6": {
    linuxPrice: 0.377,
    windowsPrice: 0.561,
  },
  "d4nlsv6": {
    linuxPrice: 0.305,
    windowsPrice: 0.489,
  },
  "d4nsv6": {
    linuxPrice: 0.407,
    windowsPrice: 0.591,
  },
  "d4pdsv6": {
    linuxPrice: 0.258,
    windowsPrice: 0,
  },
  "d4pldsv6": {
    linuxPrice: 0.219,
    windowsPrice: 0,
  },
  "d4plsv6": {
    linuxPrice: 0.174,
    windowsPrice: 0,
  },
  "d4psv6": {
    linuxPrice: 0.197,
    windowsPrice: 0,
  },
  "d4s": {
    linuxPrice: 0.718,
    windowsPrice: 1.086,
  },
  "d4sv3": {
    linuxPrice: 0.254,
    windowsPrice: 0.438,
  },
  "d4sv4": {
    linuxPrice: 0.254,
    windowsPrice: 0.438,
  },
  "d4sv5": {
    linuxPrice: 0.254,
    windowsPrice: 0.438,
  },
  "d4sv6": {
    linuxPrice: 0.268,
    windowsPrice: 0.452,
  },
  "d4sv7": {
    linuxPrice: 0.326,
    windowsPrice: 0.51,
  },
  "d4v2": {
    linuxPrice: 0.614,
    windowsPrice: 0.982,
  },
  "d4v3": {
    linuxPrice: 0.254,
    windowsPrice: 0.438,
  },
  "d4v4": {
    linuxPrice: 0.254,
    windowsPrice: 0.438,
  },
  "d4v5": {
    linuxPrice: 0.254,
    windowsPrice: 0.438,
  },
  "d5v2": {
    linuxPrice: 1.227,
    windowsPrice: 1.963,
  },
  "d64adsv5": {
    linuxPrice: 4.4,
    windowsPrice: 7.344,
  },
  "d64adsv6": {
    linuxPrice: 4.883,
    windowsPrice: 7.827,
  },
  "d64adsv7": {
    linuxPrice: 4.883,
    windowsPrice: 7.827,
  },
  "d64aldsv6": {
    linuxPrice: 4.077,
    windowsPrice: 7.021,
  },
  "d64aldsv7": {
    linuxPrice: 4.077,
    windowsPrice: 7.021,
  },
  "d64alsv6": {
    linuxPrice: 3.437,
    windowsPrice: 6.381,
  },
  "d64alsv7": {
    linuxPrice: 3.437,
    windowsPrice: 6.381,
  },
  "d64asv4": {
    linuxPrice: 4.064,
    windowsPrice: 7.008,
  },
  "d64asv5": {
    linuxPrice: 6.608,
    windowsPrice: 6.608,
  },
  "d64asv6": {
    linuxPrice: 3.885,
    windowsPrice: 6.829,
  },
  "d64asv7": {
    linuxPrice: 3.885,
    windowsPrice: 6.829,
  },
  "d64av4": {
    linuxPrice: 4.064,
    windowsPrice: 7.008,
  },
  "d64dsv4": {
    linuxPrice: 4.8,
    windowsPrice: 7.744,
  },
  "d64dsv5": {
    linuxPrice: 4.8,
    windowsPrice: 7.744,
  },
  "d64dsv6": {
    linuxPrice: 5.302,
    windowsPrice: 8.246,
  },
  "d64dsv7": {
    linuxPrice: 6.432,
    windowsPrice: 9.376,
  },
  "d64dv4": {
    linuxPrice: 4.8,
    windowsPrice: 7.744,
  },
  "d64dv5": {
    linuxPrice: 4.8,
    windowsPrice: 7.744,
  },
  "d64ldsv5": {
    linuxPrice: 4.16,
    windowsPrice: 7.104,
  },
  "d64ldsv6": {
    linuxPrice: 4.696,
    windowsPrice: 7.64,
  },
  "d64ldsv7": {
    linuxPrice: 5.246,
    windowsPrice: 8.19,
  },
  "d64lsv5": {
    linuxPrice: 3.648,
    windowsPrice: 6.592,
  },
  "d64lsv6": {
    linuxPrice: 3.799,
    windowsPrice: 6.743,
  },
  "d64lsv7": {
    linuxPrice: 4.618,
    windowsPrice: 7.562,
  },
  "d64ndsv6": {
    linuxPrice: 7.434,
    windowsPrice: 10.378,
  },
  "d64nldsv6": {
    linuxPrice: 6.025,
    windowsPrice: 8.969,
  },
  "d64nlsv6": {
    linuxPrice: 4.879,
    windowsPrice: 7.823,
  },
  "d64nsv6": {
    linuxPrice: 6.505,
    windowsPrice: 9.449,
  },
  "d64pdsv6": {
    linuxPrice: 4.122,
    windowsPrice: 0,
  },
  "d64pldsv6": {
    linuxPrice: 3.501,
    windowsPrice: 0,
  },
  "d64plsv6": {
    linuxPrice: 2.784,
    windowsPrice: 0,
  },
  "d64psv6": {
    linuxPrice: 3.149,
    windowsPrice: 0,
  },
  "d64sv3": {
    linuxPrice: 4.064,
    windowsPrice: 7.008,
  },
  "d64sv4": {
    linuxPrice: 4.064,
    windowsPrice: 7.008,
  },
  "d64sv5": {
    linuxPrice: 4.064,
    windowsPrice: 7.008,
  },
  "d64sv6": {
    linuxPrice: 4.29,
    windowsPrice: 7.234,
  },
  "d64sv7": {
    linuxPrice: 5.216,
    windowsPrice: 8.16,
  },
  "d64v3": {
    linuxPrice: 4.064,
    windowsPrice: 7.008,
  },
  "d64v4": {
    linuxPrice: 4.064,
    windowsPrice: 7.008,
  },
  "d64v5": {
    linuxPrice: 4.064,
    windowsPrice: 7.008,
  },
  "d8adsv5": {
    linuxPrice: 0.55,
    windowsPrice: 0.918,
  },
  "d8adsv6": {
    linuxPrice: 0.61,
    windowsPrice: 0.978,
  },
  "d8adsv7": {
    linuxPrice: 0.61,
    windowsPrice: 0.978,
  },
  "d8aldsv6": {
    linuxPrice: 0.51,
    windowsPrice: 0.878,
  },
  "d8aldsv7": {
    linuxPrice: 0.51,
    windowsPrice: 0.878,
  },
  "d8alsv6": {
    linuxPrice: 0.43,
    windowsPrice: 0.798,
  },
  "d8alsv7": {
    linuxPrice: 0.43,
    windowsPrice: 0.798,
  },
  "d8asv4": {
    linuxPrice: 0.508,
    windowsPrice: 0.876,
  },
  "d8asv5": {
    linuxPrice: 0.458,
    windowsPrice: 0.826,
  },
  "d8asv6": {
    linuxPrice: 0.486,
    windowsPrice: 0.854,
  },
  "d8asv7": {
    linuxPrice: 0.486,
    windowsPrice: 0.854,
  },
  "d8av4": {
    linuxPrice: 0.508,
    windowsPrice: 0.876,
  },
  "d8dsv4": {
    linuxPrice: 0.6,
    windowsPrice: 0.968,
  },
  "d8dsv5": {
    linuxPrice: 0.6,
    windowsPrice: 0.968,
  },
  "d8dsv6": {
    linuxPrice: 0.663,
    windowsPrice: 1.031,
  },
  "d8dsv7": {
    linuxPrice: 0.804,
    windowsPrice: 1.172,
  },
  "d8dv4": {
    linuxPrice: 0.6,
    windowsPrice: 0.968,
  },
  "d8dv5": {
    linuxPrice: 0.6,
    windowsPrice: 0.968,
  },
  "d8ldsv5": {
    linuxPrice: 0.52,
    windowsPrice: 0.888,
  },
  "d8ldsv6": {
    linuxPrice: 0.587,
    windowsPrice: 0.955,
  },
  "d8ldsv7": {
    linuxPrice: 0.656,
    windowsPrice: 1.024,
  },
  "d8lsv5": {
    linuxPrice: 0.456,
    windowsPrice: 0.824,
  },
  "d8lsv6": {
    linuxPrice: 0.475,
    windowsPrice: 0.843,
  },
  "d8lsv7": {
    linuxPrice: 0.577,
    windowsPrice: 0.945,
  },
  "d8ndsv6": {
    linuxPrice: 0.929,
    windowsPrice: 1.297,
  },
  "d8nldsv6": {
    linuxPrice: 0.753,
    windowsPrice: 1.121,
  },
  "d8nlsv6": {
    linuxPrice: 0.61,
    windowsPrice: 0.978,
  },
  "d8nsv6": {
    linuxPrice: 0.813,
    windowsPrice: 1.181,
  },
  "d8pdsv6": {
    linuxPrice: 0.515,
    windowsPrice: 0,
  },
  "d8pldsv6": {
    linuxPrice: 0.438,
    windowsPrice: 0,
  },
  "d8plsv6": {
    linuxPrice: 0.348,
    windowsPrice: 0,
  },
  "d8psv6": {
    linuxPrice: 0.394,
    windowsPrice: 0,
  },
  "d8sv3": {
    linuxPrice: 0.508,
    windowsPrice: 0.876,
  },
  "d8sv4": {
    linuxPrice: 0.508,
    windowsPrice: 0.876,
  },
  "d8sv5": {
    linuxPrice: 0.508,
    windowsPrice: 0.876,
  },
  "d8sv6": {
    linuxPrice: 0.536,
    windowsPrice: 0.904,
  },
  "d8sv7": {
    linuxPrice: 0.652,
    windowsPrice: 1.02,
  },
  "d8v3": {
    linuxPrice: 0.508,
    windowsPrice: 0.876,
  },
  "d8v4": {
    linuxPrice: 0.508,
    windowsPrice: 0.876,
  },
  "d8v5": {
    linuxPrice: 0.508,
    windowsPrice: 0.876,
  },
  "d96adsv5": {
    linuxPrice: 6.6,
    windowsPrice: 11.016,
  },
  "d96adsv6": {
    linuxPrice: 7.325,
    windowsPrice: 11.741,
  },
  "d96adsv7": {
    linuxPrice: 7.325,
    windowsPrice: 11.741,
  },
  "d96aldsv6": {
    linuxPrice: 6.115,
    windowsPrice: 10.531,
  },
  "d96aldsv7": {
    linuxPrice: 6.115,
    windowsPrice: 10.531,
  },
  "d96alsv6": {
    linuxPrice: 5.155,
    windowsPrice: 9.571,
  },
  "d96alsv7": {
    linuxPrice: 5.155,
    windowsPrice: 9.571,
  },
  "d96asv4": {
    linuxPrice: 6.096,
    windowsPrice: 10.512,
  },
  "d96asv5": {
    linuxPrice: 9.912,
    windowsPrice: 9.912,
  },
  "d96asv6": {
    linuxPrice: 5.827,
    windowsPrice: 10.243,
  },
  "d96asv7": {
    linuxPrice: 5.827,
    windowsPrice: 10.243,
  },
  "d96av4": {
    linuxPrice: 6.096,
    windowsPrice: 10.512,
  },
  "d96dsv5": {
    linuxPrice: 7.2,
    windowsPrice: 11.616,
  },
  "d96dsv6": {
    linuxPrice: 7.954,
    windowsPrice: 12.37,
  },
  "d96dsv7": {
    linuxPrice: 9.649,
    windowsPrice: 14.065,
  },
  "d96dv5": {
    linuxPrice: 7.2,
    windowsPrice: 11.616,
  },
  "d96ldsv5": {
    linuxPrice: 6.24,
    windowsPrice: 10.656,
  },
  "d96ldsv6": {
    linuxPrice: 7.044,
    windowsPrice: 11.46,
  },
  "d96ldsv7": {
    linuxPrice: 7.869,
    windowsPrice: 12.285,
  },
  "d96lsv5": {
    linuxPrice: 5.472,
    windowsPrice: 9.888,
  },
  "d96lsv6": {
    linuxPrice: 5.699,
    windowsPrice: 10.115,
  },
  "d96lsv7": {
    linuxPrice: 6.927,
    windowsPrice: 11.343,
  },
  "d96ndsv6": {
    linuxPrice: 11.151,
    windowsPrice: 15.567,
  },
  "d96nldsv6": {
    linuxPrice: 9.038,
    windowsPrice: 13.454,
  },
  "d96nlsv6": {
    linuxPrice: 7.318,
    windowsPrice: 11.734,
  },
  "d96nsv6": {
    linuxPrice: 9.757,
    windowsPrice: 14.173,
  },
  "d96pdsv6": {
    linuxPrice: 6.182,
    windowsPrice: 0,
  },
  "d96pldsv6": {
    linuxPrice: 5.251,
    windowsPrice: 0,
  },
  "d96plsv6": {
    linuxPrice: 4.176,
    windowsPrice: 0,
  },
  "d96psv6": {
    linuxPrice: 4.723,
    windowsPrice: 0,
  },
  "d96sv5": {
    linuxPrice: 6.096,
    windowsPrice: 10.512,
  },
  "d96sv6": {
    linuxPrice: 6.435,
    windowsPrice: 10.851,
  },
  "d96sv7": {
    linuxPrice: 7.824,
    windowsPrice: 12.24,
  },
  "d96v5": {
    linuxPrice: 6.096,
    windowsPrice: 10.512,
  },
  "dc16adsv6": {
    linuxPrice: 1.221,
    windowsPrice: 1.957,
  },
  "dc16asv6": {
    linuxPrice: 0.971,
    windowsPrice: 1.707,
  },
  "dc2adsv6": {
    linuxPrice: 0.153,
    windowsPrice: 0.245,
  },
  "dc2asv6": {
    linuxPrice: 0.121,
    windowsPrice: 0.213,
  },
  "dc32adsv6": {
    linuxPrice: 2.442,
    windowsPrice: 3.914,
  },
  "dc32asv6": {
    linuxPrice: 1.942,
    windowsPrice: 3.414,
  },
  "dc48adsv6": {
    linuxPrice: 3.662,
    windowsPrice: 5.87,
  },
  "dc48asv6": {
    linuxPrice: 2.914,
    windowsPrice: 5.122,
  },
  "dc4adsv6": {
    linuxPrice: 0.305,
    windowsPrice: 0.489,
  },
  "dc4asv6": {
    linuxPrice: 0.243,
    windowsPrice: 0.427,
  },
  "dc64adsv6": {
    linuxPrice: 4.883,
    windowsPrice: 7.827,
  },
  "dc64asv6": {
    linuxPrice: 3.885,
    windowsPrice: 6.829,
  },
  "dc8adsv6": {
    linuxPrice: 0.61,
    windowsPrice: 0.978,
  },
  "dc8asv6": {
    linuxPrice: 0.486,
    windowsPrice: 0.854,
  },
  "dc96adsv6": {
    linuxPrice: 7.325,
    windowsPrice: 11.741,
  },
  "dc96asv6": {
    linuxPrice: 5.827,
    windowsPrice: 10.243,
  },
  "ds11": {
    linuxPrice: 0.232,
    windowsPrice: 0.324,
  },
  "ds11v2": {
    linuxPrice: 0.2,
    windowsPrice: 0.292,
  },
  "ds12": {
    linuxPrice: 0.465,
    windowsPrice: 0.649,
  },
  "ds12v2": {
    linuxPrice: 0.401,
    windowsPrice: 0.585,
  },
  "ds13": {
    linuxPrice: 0.93,
    windowsPrice: 1.298,
  },
  "ds13v2": {
    linuxPrice: 0.801,
    windowsPrice: 1.169,
  },
  "ds14": {
    linuxPrice: 1.859,
    windowsPrice: 2.595,
  },
  "ds14v2": {
    linuxPrice: 1.603,
    windowsPrice: 2.339,
  },
  "ds15iv2": {
    linuxPrice: 2.003,
    windowsPrice: 2.923,
  },
  "ds15v2": {
    linuxPrice: 2.003,
    windowsPrice: 2.923,
  },
  "ds1v2": {
    linuxPrice: 0.0767,
    windowsPrice: 0.123,
  },
  "ds2v2": {
    linuxPrice: 0.153,
    windowsPrice: 0.245,
  },
  "ds3v2": {
    linuxPrice: 0.307,
    windowsPrice: 0.491,
  },
  "ds4v2": {
    linuxPrice: 0.614,
    windowsPrice: 0.982,
  },
  "ds5v2": {
    linuxPrice: 1.227,
    windowsPrice: 1.963,
  },
  "e104idsv5": {
    linuxPrice: 10.868,
    windowsPrice: 15.652,
  },
  "e104idv5": {
    linuxPrice: 10.868,
    windowsPrice: 15.652,
  },
  "e104isv5": {
    linuxPrice: 9.61,
    windowsPrice: 14.394,
  },
  "e104iv5": {
    linuxPrice: 9.61,
    windowsPrice: 14.394,
  },
  "e112bdsv5": {
    linuxPrice: 13.675,
    windowsPrice: 18.827,
  },
  "e112bsv5": {
    linuxPrice: 12.32,
    windowsPrice: 17.472,
  },
  "e128": {
    linuxPrice: 10.202,
    windowsPrice: 18.304,
  },
  "e128adsv7": {
    linuxPrice: 12.416,
    windowsPrice: 18.304,
  },
  "e128asv7": {
    linuxPrice: 10.202,
    windowsPrice: 16.09,
  },
  "e128bdsv6": {
    linuxPrice: 17.507,
    windowsPrice: 23.395,
  },
  "e128bsv6": {
    linuxPrice: 15.62,
    windowsPrice: 21.508,
  },
  "e128dsv6": {
    linuxPrice: 13.919,
    windowsPrice: 19.807,
  },
  "e128dsv7": {
    linuxPrice: 16.392,
    windowsPrice: 22.28,
  },
  "e128ndsv6": {
    linuxPrice: 18.257,
    windowsPrice: 24.145,
  },
  "e128nsv6": {
    linuxPrice: 16.289,
    windowsPrice: 22.177,
  },
  "e128sv6": {
    linuxPrice: 11.261,
    windowsPrice: 17.149,
  },
  "e128sv7": {
    linuxPrice: 13.693,
    windowsPrice: 19.581,
  },
  "e16": {
    linuxPrice: 1.208,
    windowsPrice: 2.144,
  },
  "e160adsv7": {
    linuxPrice: 15.52,
    windowsPrice: 22.88,
  },
  "e160asv7": {
    linuxPrice: 12.752,
    windowsPrice: 20.112,
  },
  "e16adsv5": {
    linuxPrice: 1.384,
    windowsPrice: 2.12,
  },
  "e16adsv6": {
    linuxPrice: 1.552,
    windowsPrice: 2.288,
  },
  "e16adsv7": {
    linuxPrice: 1.552,
    windowsPrice: 2.288,
  },
  "e16asv4": {
    linuxPrice: 1.344,
    windowsPrice: 2.08,
  },
  "e16asv5": {
    linuxPrice: 1.208,
    windowsPrice: 1.944,
  },
  "e16asv6": {
    linuxPrice: 1.275,
    windowsPrice: 2.011,
  },
  "e16asv7": {
    linuxPrice: 1.275,
    windowsPrice: 2.011,
  },
  "e16av4": {
    linuxPrice: 1.344,
    windowsPrice: 2.08,
  },
  "e16bdsv5": {
    linuxPrice: 1.776,
    windowsPrice: 2.512,
  },
  "e16bdsv6": {
    linuxPrice: 2.188,
    windowsPrice: 2.924,
  },
  "e16bsv5": {
    linuxPrice: 1.6,
    windowsPrice: 2.336,
  },
  "e16bsv6": {
    linuxPrice: 1.952,
    windowsPrice: 2.688,
  },
  "e16dsv4": {
    linuxPrice: 1.52,
    windowsPrice: 2.256,
  },
  "e16dsv5": {
    linuxPrice: 1.52,
    windowsPrice: 2.256,
  },
  "e16dsv6": {
    linuxPrice: 1.74,
    windowsPrice: 2.476,
  },
  "e16dsv7": {
    linuxPrice: 2.049,
    windowsPrice: 2.785,
  },
  "e16dv4": {
    linuxPrice: 1.52,
    windowsPrice: 2.256,
  },
  "e16dv5": {
    linuxPrice: 1.52,
    windowsPrice: 2.256,
  },
  "e16ndsv6": {
    linuxPrice: 2.282,
    windowsPrice: 3.018,
  },
  "e16nsv6": {
    linuxPrice: 2.036,
    windowsPrice: 2.772,
  },
  "e16pdsv6": {
    linuxPrice: 1.312,
    windowsPrice: 0,
  },
  "e16psv6": {
    linuxPrice: 1.034,
    windowsPrice: 0,
  },
  "e16sv3": {
    linuxPrice: 1.344,
    windowsPrice: 2.08,
  },
  "e16sv4": {
    linuxPrice: 1.344,
    windowsPrice: 2.08,
  },
  "e16sv5": {
    linuxPrice: 1.344,
    windowsPrice: 2.08,
  },
  "e16sv6": {
    linuxPrice: 1.408,
    windowsPrice: 2.144,
  },
  "e16sv7": {
    linuxPrice: 1.712,
    windowsPrice: 2.448,
  },
  "e16v3": {
    linuxPrice: 1.344,
    windowsPrice: 2.08,
  },
  "e16v4": {
    linuxPrice: 1.344,
    windowsPrice: 2.08,
  },
  "e16v5": {
    linuxPrice: 1.344,
    windowsPrice: 2.08,
  },
  "e192dsv7": {
    linuxPrice: 24.589,
    windowsPrice: 33.421,
  },
  "e192ibdsv6": {
    linuxPrice: 28.886,
    windowsPrice: 37.718,
  },
  "e192ibsv6": {
    linuxPrice: 25.773,
    windowsPrice: 34.605,
  },
  "e192idsv6": {
    linuxPrice: 22.966,
    windowsPrice: 31.798,
  },
  "e192sv7": {
    linuxPrice: 20.539,
    windowsPrice: 29.371,
  },
  "e20adsv5": {
    linuxPrice: 1.73,
    windowsPrice: 2.65,
  },
  "e20adsv6": {
    linuxPrice: 1.94,
    windowsPrice: 2.86,
  },
  "e20asv4": {
    linuxPrice: 1.68,
    windowsPrice: 2.6,
  },
  "e20asv5": {
    linuxPrice: 2.43,
    windowsPrice: 2.43,
  },
  "e20asv6": {
    linuxPrice: 1.594,
    windowsPrice: 2.514,
  },
  "e20av4": {
    linuxPrice: 1.68,
    windowsPrice: 2.6,
  },
  "e20dsv4": {
    linuxPrice: 1.9,
    windowsPrice: 2.82,
  },
  "e20dsv5": {
    linuxPrice: 1.9,
    windowsPrice: 2.82,
  },
  "e20dsv6": {
    linuxPrice: 2.175,
    windowsPrice: 3.095,
  },
  "e20dsv7": {
    linuxPrice: 2.561,
    windowsPrice: 3.481,
  },
  "e20dv4": {
    linuxPrice: 1.9,
    windowsPrice: 2.82,
  },
  "e20dv5": {
    linuxPrice: 1.9,
    windowsPrice: 2.82,
  },
  "e20sv3": {
    linuxPrice: 1.68,
    windowsPrice: 2.6,
  },
  "e20sv4": {
    linuxPrice: 1.68,
    windowsPrice: 2.6,
  },
  "e20sv5": {
    linuxPrice: 1.68,
    windowsPrice: 2.6,
  },
  "e20sv6": {
    linuxPrice: 1.76,
    windowsPrice: 2.68,
  },
  "e20sv7": {
    linuxPrice: 2.14,
    windowsPrice: 3.06,
  },
  "e20v3": {
    linuxPrice: 1.68,
    windowsPrice: 2.6,
  },
  "e20v4": {
    linuxPrice: 1.68,
    windowsPrice: 2.6,
  },
  "e20v5": {
    linuxPrice: 1.68,
    windowsPrice: 2.6,
  },
  "e248dsv7": {
    linuxPrice: 31.76,
    windowsPrice: 43.168,
  },
  "e248sv7": {
    linuxPrice: 26.53,
    windowsPrice: 37.938,
  },
  "e2adsv5": {
    linuxPrice: 0.173,
    windowsPrice: 0.265,
  },
  "e2adsv6": {
    linuxPrice: 0.194,
    windowsPrice: 0.286,
  },
  "e2adsv7": {
    linuxPrice: 0.194,
    windowsPrice: 0.286,
  },
  "e2asv4": {
    linuxPrice: 0.168,
    windowsPrice: 0.26,
  },
  "e2asv5": {
    linuxPrice: 0.151,
    windowsPrice: 0.243,
  },
  "e2asv6": {
    linuxPrice: 0.159,
    windowsPrice: 0.251,
  },
  "e2asv7": {
    linuxPrice: 0.159,
    windowsPrice: 0.251,
  },
  "e2av4": {
    linuxPrice: 0.168,
    windowsPrice: 0.26,
  },
  "e2bdsv5": {
    linuxPrice: 0.222,
    windowsPrice: 0.314,
  },
  "e2bdsv6": {
    linuxPrice: 0.274,
    windowsPrice: 0.366,
  },
  "e2bsv5": {
    linuxPrice: 0.2,
    windowsPrice: 0.292,
  },
  "e2bsv6": {
    linuxPrice: 0.244,
    windowsPrice: 0.336,
  },
  "e2dsv4": {
    linuxPrice: 0.19,
    windowsPrice: 0.282,
  },
  "e2dsv5": {
    linuxPrice: 0.19,
    windowsPrice: 0.282,
  },
  "e2dsv6": {
    linuxPrice: 0.217,
    windowsPrice: 0.309,
  },
  "e2dsv7": {
    linuxPrice: 0.256,
    windowsPrice: 0.348,
  },
  "e2dv4": {
    linuxPrice: 0.19,
    windowsPrice: 0.282,
  },
  "e2dv5": {
    linuxPrice: 0.19,
    windowsPrice: 0.282,
  },
  "e2ndsv6": {
    linuxPrice: 0.285,
    windowsPrice: 0.377,
  },
  "e2nsv6": {
    linuxPrice: 0.255,
    windowsPrice: 0.347,
  },
  "e2pdsv6": {
    linuxPrice: 0.164,
    windowsPrice: 0,
  },
  "e2psv6": {
    linuxPrice: 0.129,
    windowsPrice: 0,
  },
  "e2sv3": {
    linuxPrice: 0.168,
    windowsPrice: 0.26,
  },
  "e2sv4": {
    linuxPrice: 0.168,
    windowsPrice: 0.26,
  },
  "e2sv5": {
    linuxPrice: 0.168,
    windowsPrice: 0.26,
  },
  "e2sv6": {
    linuxPrice: 0.176,
    windowsPrice: 0.268,
  },
  "e2sv7": {
    linuxPrice: 0.214,
    windowsPrice: 0.306,
  },
  "e2v3": {
    linuxPrice: 0.168,
    windowsPrice: 0.26,
  },
  "e2v4": {
    linuxPrice: 0.168,
    windowsPrice: 0.26,
  },
  "e2v5": {
    linuxPrice: 0.168,
    windowsPrice: 0.26,
  },
  "e32": {
    linuxPrice: 3.04,
    windowsPrice: 3.888,
  },
  "e32adsv5": {
    linuxPrice: 2.768,
    windowsPrice: 4.24,
  },
  "e32adsv6": {
    linuxPrice: 3.104,
    windowsPrice: 4.576,
  },
  "e32adsv7": {
    linuxPrice: 3.104,
    windowsPrice: 4.576,
  },
  "e32asv4": {
    linuxPrice: 2.688,
    windowsPrice: 4.16,
  },
  "e32asv5": {
    linuxPrice: 3.888,
    windowsPrice: 3.888,
  },
  "e32asv6": {
    linuxPrice: 2.55,
    windowsPrice: 4.022,
  },
  "e32asv7": {
    linuxPrice: 2.55,
    windowsPrice: 4.022,
  },
  "e32av4": {
    linuxPrice: 2.688,
    windowsPrice: 4.16,
  },
  "e32bdsv5": {
    linuxPrice: 3.552,
    windowsPrice: 5.024,
  },
  "e32bdsv6": {
    linuxPrice: 4.377,
    windowsPrice: 5.849,
  },
  "e32bsv5": {
    linuxPrice: 3.2,
    windowsPrice: 4.672,
  },
  "e32bsv6": {
    linuxPrice: 3.905,
    windowsPrice: 5.377,
  },
  "e32dsv4": {
    linuxPrice: 3.04,
    windowsPrice: 4.512,
  },
  "e32dsv5": {
    linuxPrice: 3.04,
    windowsPrice: 4.512,
  },
  "e32dsv6": {
    linuxPrice: 3.48,
    windowsPrice: 4.952,
  },
  "e32dsv7": {
    linuxPrice: 4.098,
    windowsPrice: 5.57,
  },
  "e32dv4": {
    linuxPrice: 3.04,
    windowsPrice: 4.512,
  },
  "e32dv5": {
    linuxPrice: 3.04,
    windowsPrice: 4.512,
  },
  "e32ndsv6": {
    linuxPrice: 4.564,
    windowsPrice: 6.036,
  },
  "e32nsv6": {
    linuxPrice: 4.072,
    windowsPrice: 5.544,
  },
  "e32pdsv6": {
    linuxPrice: 2.624,
    windowsPrice: 0,
  },
  "e32psv6": {
    linuxPrice: 2.067,
    windowsPrice: 0,
  },
  "e32sv3": {
    linuxPrice: 2.688,
    windowsPrice: 4.16,
  },
  "e32sv4": {
    linuxPrice: 2.688,
    windowsPrice: 4.16,
  },
  "e32sv5": {
    linuxPrice: 2.688,
    windowsPrice: 4.16,
  },
  "e32sv6": {
    linuxPrice: 2.815,
    windowsPrice: 4.287,
  },
  "e32sv7": {
    linuxPrice: 3.423,
    windowsPrice: 4.895,
  },
  "e32v3": {
    linuxPrice: 2.688,
    windowsPrice: 4.16,
  },
  "e32v4": {
    linuxPrice: 2.688,
    windowsPrice: 4.16,
  },
  "e32v5": {
    linuxPrice: 2.688,
    windowsPrice: 4.16,
  },
  "e372idsv7": {
    linuxPrice: 52.405,
    windowsPrice: 69.517,
  },
  "e372isv7": {
    linuxPrice: 43.774,
    windowsPrice: 60.886,
  },
  "e4": {
    linuxPrice: 0.388,
    windowsPrice: 0.53,
  },
  "e48adsv5": {
    linuxPrice: 4.152,
    windowsPrice: 6.36,
  },
  "e48adsv6": {
    linuxPrice: 4.656,
    windowsPrice: 6.864,
  },
  "e48adsv7": {
    linuxPrice: 4.656,
    windowsPrice: 6.864,
  },
  "e48asv4": {
    linuxPrice: 4.032,
    windowsPrice: 6.24,
  },
  "e48asv5": {
    linuxPrice: 5.832,
    windowsPrice: 5.832,
  },
  "e48asv6": {
    linuxPrice: 3.826,
    windowsPrice: 6.034,
  },
  "e48asv7": {
    linuxPrice: 3.826,
    windowsPrice: 6.034,
  },
  "e48av4": {
    linuxPrice: 4.032,
    windowsPrice: 6.24,
  },
  "e48bdsv5": {
    linuxPrice: 5.328,
    windowsPrice: 7.536,
  },
  "e48bdsv6": {
    linuxPrice: 6.565,
    windowsPrice: 8.773,
  },
  "e48bsv5": {
    linuxPrice: 4.8,
    windowsPrice: 7.008,
  },
  "e48bsv6": {
    linuxPrice: 5.857,
    windowsPrice: 8.065,
  },
  "e48dsv4": {
    linuxPrice: 4.56,
    windowsPrice: 6.768,
  },
  "e48dsv5": {
    linuxPrice: 4.56,
    windowsPrice: 6.768,
  },
  "e48dsv6": {
    linuxPrice: 5.22,
    windowsPrice: 7.428,
  },
  "e48dsv7": {
    linuxPrice: 6.147,
    windowsPrice: 8.355,
  },
  "e48dv4": {
    linuxPrice: 4.56,
    windowsPrice: 6.768,
  },
  "e48dv5": {
    linuxPrice: 4.56,
    windowsPrice: 6.768,
  },
  "e48ndsv6": {
    linuxPrice: 6.846,
    windowsPrice: 9.054,
  },
  "e48nsv6": {
    linuxPrice: 6.109,
    windowsPrice: 8.317,
  },
  "e48pdsv6": {
    linuxPrice: 3.936,
    windowsPrice: 0,
  },
  "e48psv6": {
    linuxPrice: 3.101,
    windowsPrice: 0,
  },
  "e48sv3": {
    linuxPrice: 4.032,
    windowsPrice: 6.24,
  },
  "e48sv4": {
    linuxPrice: 4.032,
    windowsPrice: 6.24,
  },
  "e48sv5": {
    linuxPrice: 4.032,
    windowsPrice: 6.24,
  },
  "e48sv6": {
    linuxPrice: 4.223,
    windowsPrice: 6.431,
  },
  "e48sv7": {
    linuxPrice: 5.135,
    windowsPrice: 7.343,
  },
  "e48v3": {
    linuxPrice: 4.032,
    windowsPrice: 6.24,
  },
  "e48v4": {
    linuxPrice: 4.032,
    windowsPrice: 6.24,
  },
  "e48v5": {
    linuxPrice: 4.032,
    windowsPrice: 6.24,
  },
  "e4adsv5": {
    linuxPrice: 0.346,
    windowsPrice: 0.53,
  },
  "e4adsv6": {
    linuxPrice: 0.388,
    windowsPrice: 0.572,
  },
  "e4adsv7": {
    linuxPrice: 0.388,
    windowsPrice: 0.572,
  },
  "e4asv4": {
    linuxPrice: 0.336,
    windowsPrice: 0.52,
  },
  "e4asv5": {
    linuxPrice: 0.302,
    windowsPrice: 0.486,
  },
  "e4asv6": {
    linuxPrice: 0.319,
    windowsPrice: 0.503,
  },
  "e4asv7": {
    linuxPrice: 0.319,
    windowsPrice: 0.503,
  },
  "e4av4": {
    linuxPrice: 0.336,
    windowsPrice: 0.52,
  },
  "e4bdsv5": {
    linuxPrice: 0.444,
    windowsPrice: 0.628,
  },
  "e4bdsv6": {
    linuxPrice: 0.547,
    windowsPrice: 0.731,
  },
  "e4bsv5": {
    linuxPrice: 0.4,
    windowsPrice: 0.584,
  },
  "e4bsv6": {
    linuxPrice: 0.488,
    windowsPrice: 0.672,
  },
  "e4dsv4": {
    linuxPrice: 0.38,
    windowsPrice: 0.564,
  },
  "e4dsv5": {
    linuxPrice: 0.38,
    windowsPrice: 0.564,
  },
  "e4dsv6": {
    linuxPrice: 0.435,
    windowsPrice: 0.619,
  },
  "e4dsv7": {
    linuxPrice: 0.512,
    windowsPrice: 0.696,
  },
  "e4dv4": {
    linuxPrice: 0.38,
    windowsPrice: 0.564,
  },
  "e4dv5": {
    linuxPrice: 0.38,
    windowsPrice: 0.564,
  },
  "e4ndsv6": {
    linuxPrice: 0.571,
    windowsPrice: 0.755,
  },
  "e4nsv6": {
    linuxPrice: 0.509,
    windowsPrice: 0.693,
  },
  "e4pdsv6": {
    linuxPrice: 0.328,
    windowsPrice: 0,
  },
  "e4psv6": {
    linuxPrice: 0.258,
    windowsPrice: 0,
  },
  "e4sv3": {
    linuxPrice: 0.336,
    windowsPrice: 0.52,
  },
  "e4sv4": {
    linuxPrice: 0.336,
    windowsPrice: 0.52,
  },
  "e4sv5": {
    linuxPrice: 0.336,
    windowsPrice: 0.52,
  },
  "e4sv6": {
    linuxPrice: 0.352,
    windowsPrice: 0.536,
  },
  "e4sv7": {
    linuxPrice: 0.428,
    windowsPrice: 0.612,
  },
  "e4v3": {
    linuxPrice: 0.336,
    windowsPrice: 0.52,
  },
  "e4v4": {
    linuxPrice: 0.336,
    windowsPrice: 0.52,
  },
  "e4v5": {
    linuxPrice: 0.336,
    windowsPrice: 0.52,
  },
  "e64": {
    linuxPrice: 5.376,
    windowsPrice: 8.32,
  },
  "e64adsv5": {
    linuxPrice: 5.536,
    windowsPrice: 8.48,
  },
  "e64adsv6": {
    linuxPrice: 6.208,
    windowsPrice: 9.152,
  },
  "e64adsv7": {
    linuxPrice: 6.208,
    windowsPrice: 9.152,
  },
  "e64asv4": {
    linuxPrice: 5.376,
    windowsPrice: 8.32,
  },
  "e64asv5": {
    linuxPrice: 4.832,
    windowsPrice: 7.776,
  },
  "e64asv6": {
    linuxPrice: 5.101,
    windowsPrice: 8.045,
  },
  "e64asv7": {
    linuxPrice: 5.101,
    windowsPrice: 8.045,
  },
  "e64av4": {
    linuxPrice: 5.376,
    windowsPrice: 8.32,
  },
  "e64bdsv5": {
    linuxPrice: 7.104,
    windowsPrice: 10.048,
  },
  "e64bdsv6": {
    linuxPrice: 8.753,
    windowsPrice: 11.697,
  },
  "e64bsv5": {
    linuxPrice: 6.4,
    windowsPrice: 9.344,
  },
  "e64bsv6": {
    linuxPrice: 7.81,
    windowsPrice: 10.754,
  },
  "e64dsv4": {
    linuxPrice: 6.08,
    windowsPrice: 9.024,
  },
  "e64dsv5": {
    linuxPrice: 6.08,
    windowsPrice: 9.024,
  },
  "e64dsv6": {
    linuxPrice: 6.959,
    windowsPrice: 9.903,
  },
  "e64dsv7": {
    linuxPrice: 8.196,
    windowsPrice: 11.14,
  },
  "e64dv4": {
    linuxPrice: 6.08,
    windowsPrice: 9.024,
  },
  "e64dv5": {
    linuxPrice: 6.08,
    windowsPrice: 9.024,
  },
  "e64isv3": {
    linuxPrice: 4.863,
    windowsPrice: 7.807,
  },
  "e64iv3": {
    linuxPrice: 4.863,
    windowsPrice: 7.807,
  },
  "e64ndsv6": {
    linuxPrice: 9.129,
    windowsPrice: 12.073,
  },
  "e64nsv6": {
    linuxPrice: 8.145,
    windowsPrice: 11.089,
  },
  "e64pdsv6": {
    linuxPrice: 5.248,
    windowsPrice: 0,
  },
  "e64psv6": {
    linuxPrice: 4.134,
    windowsPrice: 0,
  },
  "e64sv3": {
    linuxPrice: 4.863,
    windowsPrice: 7.807,
  },
  "e64sv4": {
    linuxPrice: 5.376,
    windowsPrice: 8.32,
  },
  "e64sv5": {
    linuxPrice: 5.376,
    windowsPrice: 8.32,
  },
  "e64sv6": {
    linuxPrice: 5.631,
    windowsPrice: 8.575,
  },
  "e64sv7": {
    linuxPrice: 6.846,
    windowsPrice: 9.79,
  },
  "e64v3": {
    linuxPrice: 4.863,
    windowsPrice: 7.807,
  },
  "e64v4": {
    linuxPrice: 5.376,
    windowsPrice: 8.32,
  },
  "e64v5": {
    linuxPrice: 5.376,
    windowsPrice: 8.32,
  },
  "e8": {
    linuxPrice: 0.672,
    windowsPrice: 1.04,
  },
  "e80idsv4": {
    linuxPrice: 7.6,
    windowsPrice: 11.28,
  },
  "e80isv4": {
    linuxPrice: 6.72,
    windowsPrice: 10.4,
  },
  "e8adsv5": {
    linuxPrice: 0.692,
    windowsPrice: 1.06,
  },
  "e8adsv6": {
    linuxPrice: 0.776,
    windowsPrice: 1.144,
  },
  "e8adsv7": {
    linuxPrice: 0.776,
    windowsPrice: 1.144,
  },
  "e8asv4": {
    linuxPrice: 0.672,
    windowsPrice: 1.04,
  },
  "e8asv5": {
    linuxPrice: 0.972,
    windowsPrice: 0.972,
  },
  "e8asv6": {
    linuxPrice: 0.638,
    windowsPrice: 1.006,
  },
  "e8asv7": {
    linuxPrice: 0.638,
    windowsPrice: 1.006,
  },
  "e8av4": {
    linuxPrice: 0.672,
    windowsPrice: 1.04,
  },
  "e8bdsv5": {
    linuxPrice: 0.888,
    windowsPrice: 1.256,
  },
  "e8bdsv6": {
    linuxPrice: 1.094,
    windowsPrice: 1.462,
  },
  "e8bsv5": {
    linuxPrice: 0.8,
    windowsPrice: 1.168,
  },
  "e8bsv6": {
    linuxPrice: 0.976,
    windowsPrice: 1.344,
  },
  "e8dsv4": {
    linuxPrice: 0.76,
    windowsPrice: 1.128,
  },
  "e8dsv5": {
    linuxPrice: 0.76,
    windowsPrice: 1.128,
  },
  "e8dsv6": {
    linuxPrice: 0.87,
    windowsPrice: 1.238,
  },
  "e8dsv7": {
    linuxPrice: 1.025,
    windowsPrice: 1.393,
  },
  "e8dv4": {
    linuxPrice: 0.76,
    windowsPrice: 1.128,
  },
  "e8dv5": {
    linuxPrice: 0.76,
    windowsPrice: 1.128,
  },
  "e8ndsv6": {
    linuxPrice: 1.141,
    windowsPrice: 1.509,
  },
  "e8nsv6": {
    linuxPrice: 1.018,
    windowsPrice: 1.386,
  },
  "e8pdsv6": {
    linuxPrice: 0.656,
    windowsPrice: 0,
  },
  "e8psv6": {
    linuxPrice: 0.517,
    windowsPrice: 0,
  },
  "e8sv3": {
    linuxPrice: 0.672,
    windowsPrice: 1.04,
  },
  "e8sv4": {
    linuxPrice: 0.672,
    windowsPrice: 1.04,
  },
  "e8sv5": {
    linuxPrice: 0.672,
    windowsPrice: 1.04,
  },
  "e8sv6": {
    linuxPrice: 0.704,
    windowsPrice: 1.072,
  },
  "e8sv7": {
    linuxPrice: 0.856,
    windowsPrice: 1.224,
  },
  "e8v3": {
    linuxPrice: 0.672,
    windowsPrice: 1.04,
  },
  "e8v4": {
    linuxPrice: 0.672,
    windowsPrice: 1.04,
  },
  "e8v5": {
    linuxPrice: 0.672,
    windowsPrice: 1.04,
  },
  "e96": {
    linuxPrice: 8.304,
    windowsPrice: 14.855,
  },
  "e96adsv5": {
    linuxPrice: 12.72,
    windowsPrice: 12.72,
  },
  "e96adsv6": {
    linuxPrice: 9.312,
    windowsPrice: 13.728,
  },
  "e96adsv7": {
    linuxPrice: 9.312,
    windowsPrice: 13.728,
  },
  "e96asv4": {
    linuxPrice: 8.064,
    windowsPrice: 12.48,
  },
  "e96asv5": {
    linuxPrice: 7.248,
    windowsPrice: 11.664,
  },
  "e96asv6": {
    linuxPrice: 7.651,
    windowsPrice: 12.067,
  },
  "e96asv7": {
    linuxPrice: 7.651,
    windowsPrice: 12.067,
  },
  "e96av4": {
    linuxPrice: 8.064,
    windowsPrice: 12.48,
  },
  "e96bdsv5": {
    linuxPrice: 10.656,
    windowsPrice: 15.072,
  },
  "e96bdsv6": {
    linuxPrice: 13.13,
    windowsPrice: 17.546,
  },
  "e96bsv5": {
    linuxPrice: 9.6,
    windowsPrice: 14.016,
  },
  "e96bsv6": {
    linuxPrice: 11.715,
    windowsPrice: 16.131,
  },
  "e96dsv5": {
    linuxPrice: 9.12,
    windowsPrice: 13.536,
  },
  "e96dsv6": {
    linuxPrice: 10.439,
    windowsPrice: 14.855,
  },
  "e96dsv7": {
    linuxPrice: 12.294,
    windowsPrice: 16.71,
  },
  "e96dv5": {
    linuxPrice: 9.12,
    windowsPrice: 13.536,
  },
  "e96ndsv6": {
    linuxPrice: 13.693,
    windowsPrice: 18.109,
  },
  "e96nsv6": {
    linuxPrice: 12.217,
    windowsPrice: 16.633,
  },
  "e96pdsv6": {
    linuxPrice: 7.872,
    windowsPrice: 0,
  },
  "e96psv6": {
    linuxPrice: 6.202,
    windowsPrice: 0,
  },
  "e96sv5": {
    linuxPrice: 8.064,
    windowsPrice: 12.48,
  },
  "e96sv6": {
    linuxPrice: 8.446,
    windowsPrice: 12.862,
  },
  "e96sv7": {
    linuxPrice: 10.27,
    windowsPrice: 14.686,
  },
  "e96v5": {
    linuxPrice: 8.064,
    windowsPrice: 12.48,
  },
  "ec16adsv6": {
    linuxPrice: 1.552,
    windowsPrice: 2.288,
  },
  "ec16asv6": {
    linuxPrice: 1.275,
    windowsPrice: 2.011,
  },
  "ec2adsv6": {
    linuxPrice: 0.194,
    windowsPrice: 0.286,
  },
  "ec2asv6": {
    linuxPrice: 0.159,
    windowsPrice: 0.251,
  },
  "ec32adsv6": {
    linuxPrice: 3.104,
    windowsPrice: 4.576,
  },
  "ec32asv6": {
    linuxPrice: 2.55,
    windowsPrice: 4.022,
  },
  "ec48adsv6": {
    linuxPrice: 4.656,
    windowsPrice: 6.864,
  },
  "ec48asv6": {
    linuxPrice: 3.826,
    windowsPrice: 6.034,
  },
  "ec4adsv6": {
    linuxPrice: 0.388,
    windowsPrice: 0.572,
  },
  "ec4asv6": {
    linuxPrice: 0.319,
    windowsPrice: 0.503,
  },
  "ec64adsv6": {
    linuxPrice: 6.208,
    windowsPrice: 9.152,
  },
  "ec64asv6": {
    linuxPrice: 5.101,
    windowsPrice: 8.045,
  },
  "ec8adsv6": {
    linuxPrice: 0.776,
    windowsPrice: 1.144,
  },
  "ec8asv6": {
    linuxPrice: 0.638,
    windowsPrice: 1.006,
  },
  "ec96adsv6": {
    linuxPrice: 9.312,
    windowsPrice: 13.728,
  },
  "ec96asv6": {
    linuxPrice: 7.651,
    windowsPrice: 12.067,
  },
  "f1": {
    linuxPrice: 0.0667,
    windowsPrice: 0.113,
  },
  "f16": {
    linuxPrice: 1.066,
    windowsPrice: 1.802,
  },
  "f16adsv7": {
    linuxPrice: 1.834,
    windowsPrice: 2.57,
  },
  "f16aldsv7": {
    linuxPrice: 1.529,
    windowsPrice: 2.265,
  },
  "f16alsv6": {
    linuxPrice: 1.293,
    windowsPrice: 2.029,
  },
  "f16alsv7": {
    linuxPrice: 1.293,
    windowsPrice: 2.029,
  },
  "f16amdsv7": {
    linuxPrice: 2.331,
    windowsPrice: 3.067,
  },
  "f16amsv6": {
    linuxPrice: 1.914,
    windowsPrice: 2.65,
  },
  "f16amsv7": {
    linuxPrice: 1.914,
    windowsPrice: 2.65,
  },
  "f16asv6": {
    linuxPrice: 1.461,
    windowsPrice: 2.197,
  },
  "f16asv7": {
    linuxPrice: 1.461,
    windowsPrice: 2.197,
  },
  "f16s": {
    linuxPrice: 1.066,
    windowsPrice: 1.802,
  },
  "f16sv2": {
    linuxPrice: 0.911,
    windowsPrice: 1.647,
  },
  "f1adsv7": {
    linuxPrice: 0.115,
    windowsPrice: 0.161,
  },
  "f1aldsv7": {
    linuxPrice: 0.0956,
    windowsPrice: 0.142,
  },
  "f1alsv7": {
    linuxPrice: 0.0808,
    windowsPrice: 0.127,
  },
  "f1amdsv7": {
    linuxPrice: 0.146,
    windowsPrice: 0.192,
  },
  "f1amsv7": {
    linuxPrice: 0.12,
    windowsPrice: 0.166,
  },
  "f1asv7": {
    linuxPrice: 0.0913,
    windowsPrice: 0.137,
  },
  "f1s": {
    linuxPrice: 0.0667,
    windowsPrice: 0.113,
  },
  "f2": {
    linuxPrice: 0.133,
    windowsPrice: 0.225,
  },
  "f2adsv7": {
    linuxPrice: 0.229,
    windowsPrice: 0.321,
  },
  "f2aldsv7": {
    linuxPrice: 0.191,
    windowsPrice: 0.283,
  },
  "f2alsv6": {
    linuxPrice: 0.162,
    windowsPrice: 0.254,
  },
  "f2alsv7": {
    linuxPrice: 0.162,
    windowsPrice: 0.254,
  },
  "f2amdsv7": {
    linuxPrice: 0.291,
    windowsPrice: 0.383,
  },
  "f2amsv6": {
    linuxPrice: 0.239,
    windowsPrice: 0.331,
  },
  "f2amsv7": {
    linuxPrice: 0.239,
    windowsPrice: 0.331,
  },
  "f2asv6": {
    linuxPrice: 0.183,
    windowsPrice: 0.275,
  },
  "f2asv7": {
    linuxPrice: 0.183,
    windowsPrice: 0.275,
  },
  "f2s": {
    linuxPrice: 0.133,
    windowsPrice: 0.225,
  },
  "f2sv2": {
    linuxPrice: 0.114,
    windowsPrice: 0.206,
  },
  "f32": {
    linuxPrice: 4.662,
    windowsPrice: 5.299,
  },
  "f32adsv7": {
    linuxPrice: 3.668,
    windowsPrice: 5.14,
  },
  "f32aldsv7": {
    linuxPrice: 3.058,
    windowsPrice: 4.53,
  },
  "f32alsv6": {
    linuxPrice: 2.586,
    windowsPrice: 4.058,
  },
  "f32alsv7": {
    linuxPrice: 2.586,
    windowsPrice: 4.058,
  },
  "f32amdsv7": {
    linuxPrice: 4.662,
    windowsPrice: 6.134,
  },
  "f32amsv6": {
    linuxPrice: 3.827,
    windowsPrice: 5.299,
  },
  "f32amsv7": {
    linuxPrice: 3.827,
    windowsPrice: 5.299,
  },
  "f32asv6": {
    linuxPrice: 2.922,
    windowsPrice: 4.394,
  },
  "f32asv7": {
    linuxPrice: 2.922,
    windowsPrice: 4.394,
  },
  "f32sv2": {
    linuxPrice: 1.822,
    windowsPrice: 3.294,
  },
  "f4": {
    linuxPrice: 0.267,
    windowsPrice: 0.451,
  },
  "f48adsv7": {
    linuxPrice: 5.502,
    windowsPrice: 7.71,
  },
  "f48aldsv7": {
    linuxPrice: 4.587,
    windowsPrice: 6.795,
  },
  "f48alsv6": {
    linuxPrice: 3.878,
    windowsPrice: 6.086,
  },
  "f48alsv7": {
    linuxPrice: 3.878,
    windowsPrice: 6.086,
  },
  "f48amdsv7": {
    linuxPrice: 6.993,
    windowsPrice: 9.201,
  },
  "f48amsv6": {
    linuxPrice: 5.741,
    windowsPrice: 7.949,
  },
  "f48amsv7": {
    linuxPrice: 5.741,
    windowsPrice: 7.949,
  },
  "f48asv6": {
    linuxPrice: 4.382,
    windowsPrice: 6.59,
  },
  "f48asv7": {
    linuxPrice: 4.382,
    windowsPrice: 6.59,
  },
  "f48sv2": {
    linuxPrice: 2.734,
    windowsPrice: 4.942,
  },
  "f4adsv7": {
    linuxPrice: 0.459,
    windowsPrice: 0.643,
  },
  "f4aldsv7": {
    linuxPrice: 0.382,
    windowsPrice: 0.566,
  },
  "f4alsv6": {
    linuxPrice: 0.323,
    windowsPrice: 0.507,
  },
  "f4alsv7": {
    linuxPrice: 0.323,
    windowsPrice: 0.507,
  },
  "f4amdsv7": {
    linuxPrice: 0.583,
    windowsPrice: 0.767,
  },
  "f4amsv6": {
    linuxPrice: 0.478,
    windowsPrice: 0.662,
  },
  "f4amsv7": {
    linuxPrice: 0.478,
    windowsPrice: 0.662,
  },
  "f4asv6": {
    linuxPrice: 0.365,
    windowsPrice: 0.549,
  },
  "f4asv7": {
    linuxPrice: 0.365,
    windowsPrice: 0.549,
  },
  "f4s": {
    linuxPrice: 0.267,
    windowsPrice: 0.451,
  },
  "f4sv2": {
    linuxPrice: 0.228,
    windowsPrice: 0.412,
  },
  "f64": {
    linuxPrice: 9.324,
    windowsPrice: 12.268,
  },
  "f64adsv7": {
    linuxPrice: 7.336,
    windowsPrice: 10.28,
  },
  "f64aldsv7": {
    linuxPrice: 6.115,
    windowsPrice: 9.059,
  },
  "f64alsv6": {
    linuxPrice: 5.171,
    windowsPrice: 8.115,
  },
  "f64alsv7": {
    linuxPrice: 5.171,
    windowsPrice: 8.115,
  },
  "f64amdsv7": {
    linuxPrice: 9.324,
    windowsPrice: 12.268,
  },
  "f64amsv6": {
    linuxPrice: 7.654,
    windowsPrice: 10.598,
  },
  "f64amsv7": {
    linuxPrice: 7.654,
    windowsPrice: 10.598,
  },
  "f64asv6": {
    linuxPrice: 5.843,
    windowsPrice: 8.787,
  },
  "f64asv7": {
    linuxPrice: 5.843,
    windowsPrice: 8.787,
  },
  "f64sv2": {
    linuxPrice: 3.645,
    windowsPrice: 6.589,
  },
  "f72sv2": {
    linuxPrice: 4.1,
    windowsPrice: 7.412,
  },
  "f8": {
    linuxPrice: 0.533,
    windowsPrice: 0.901,
  },
  "f80adsv7": {
    linuxPrice: 9.17,
    windowsPrice: 12.85,
  },
  "f80aldsv7": {
    linuxPrice: 7.644,
    windowsPrice: 11.324,
  },
  "f80alsv7": {
    linuxPrice: 6.464,
    windowsPrice: 10.144,
  },
  "f80amdsv7": {
    linuxPrice: 11.655,
    windowsPrice: 15.335,
  },
  "f80amsv7": {
    linuxPrice: 9.568,
    windowsPrice: 13.248,
  },
  "f80asv7": {
    linuxPrice: 7.304,
    windowsPrice: 10.984,
  },
  "f8adsv7": {
    linuxPrice: 0.917,
    windowsPrice: 1.285,
  },
  "f8aldsv7": {
    linuxPrice: 0.764,
    windowsPrice: 1.132,
  },
  "f8alsv6": {
    linuxPrice: 0.646,
    windowsPrice: 1.014,
  },
  "f8alsv7": {
    linuxPrice: 0.646,
    windowsPrice: 1.014,
  },
  "f8amdsv7": {
    linuxPrice: 1.165,
    windowsPrice: 1.533,
  },
  "f8amsv6": {
    linuxPrice: 0.957,
    windowsPrice: 1.325,
  },
  "f8amsv7": {
    linuxPrice: 0.957,
    windowsPrice: 1.325,
  },
  "f8asv6": {
    linuxPrice: 0.73,
    windowsPrice: 1.098,
  },
  "f8asv7": {
    linuxPrice: 0.73,
    windowsPrice: 1.098,
  },
  "f8s": {
    linuxPrice: 0.533,
    windowsPrice: 0.901,
  },
  "f8sv2": {
    linuxPrice: 0.456,
    windowsPrice: 0.824,
  },
  "fx12": {
    linuxPrice: 2.344,
    windowsPrice: 2.449,
  },
  "fx12mdsv2": {
    linuxPrice: 2.344,
    windowsPrice: 2.896,
  },
  "fx12msv2": {
    linuxPrice: 1.897,
    windowsPrice: 2.449,
  },
  "fx16": {
    linuxPrice: 2.529,
    windowsPrice: 3.265,
  },
  "fx16mdsv2": {
    linuxPrice: 3.126,
    windowsPrice: 3.862,
  },
  "fx16msv2": {
    linuxPrice: 2.529,
    windowsPrice: 3.265,
  },
  "fx24": {
    linuxPrice: 3.794,
    windowsPrice: 4.898,
  },
  "fx24mdsv2": {
    linuxPrice: 4.689,
    windowsPrice: 5.793,
  },
  "fx24msv2": {
    linuxPrice: 3.794,
    windowsPrice: 4.898,
  },
  "fx2mdsv2": {
    linuxPrice: 0.391,
    windowsPrice: 0.483,
  },
  "fx2msv2": {
    linuxPrice: 0.316,
    windowsPrice: 0.408,
  },
  "fx32": {
    linuxPrice: 5.058,
    windowsPrice: 6.53,
  },
  "fx32mdsv2": {
    linuxPrice: 6.252,
    windowsPrice: 7.724,
  },
  "fx32msv2": {
    linuxPrice: 5.058,
    windowsPrice: 6.53,
  },
  "fx4": {
    linuxPrice: 0.632,
    windowsPrice: 0.965,
  },
  "fx48": {
    linuxPrice: 7.588,
    windowsPrice: 9.796,
  },
  "fx48mdsv2": {
    linuxPrice: 9.378,
    windowsPrice: 11.586,
  },
  "fx48msv2": {
    linuxPrice: 7.588,
    windowsPrice: 9.796,
  },
  "fx4mdsv2": {
    linuxPrice: 0.781,
    windowsPrice: 0.965,
  },
  "fx4msv2": {
    linuxPrice: 0.632,
    windowsPrice: 0.816,
  },
  "fx64": {
    linuxPrice: 10.117,
    windowsPrice: 15.448,
  },
  "fx64mdsv2": {
    linuxPrice: 12.504,
    windowsPrice: 15.448,
  },
  "fx64msv2": {
    linuxPrice: 10.117,
    windowsPrice: 13.061,
  },
  "fx8": {
    linuxPrice: 1.563,
    windowsPrice: 1.633,
  },
  "fx8mdsv2": {
    linuxPrice: 1.563,
    windowsPrice: 1.931,
  },
  "fx8msv2": {
    linuxPrice: 1.265,
    windowsPrice: 1.633,
  },
  "fx96": {
    linuxPrice: 15.175,
    windowsPrice: 23.172,
  },
  "fx96mdsv2": {
    linuxPrice: 18.756,
    windowsPrice: 23.172,
  },
  "fx96msv2": {
    linuxPrice: 15.175,
    windowsPrice: 19.591,
  },
  "l12aosv4": {
    linuxPrice: 1.782,
    windowsPrice: 2.334,
  },
  "l16aosv4": {
    linuxPrice: 2.376,
    windowsPrice: 3.112,
  },
  "l16asv3": {
    linuxPrice: 1.64,
    windowsPrice: 2.376,
  },
  "l16asv4": {
    linuxPrice: 1.804,
    windowsPrice: 2.54,
  },
  "l16sv3": {
    linuxPrice: 1.832,
    windowsPrice: 2.568,
  },
  "l16sv4": {
    linuxPrice: 1.832,
    windowsPrice: 2.568,
  },
  "l24aosv4": {
    linuxPrice: 3.564,
    windowsPrice: 4.668,
  },
  "l2aosv4": {
    linuxPrice: 0.297,
    windowsPrice: 0.389,
  },
  "l2asv4": {
    linuxPrice: 0.226,
    windowsPrice: 0.318,
  },
  "l2sv4": {
    linuxPrice: 0.229,
    windowsPrice: 0.321,
  },
  "l32aosv4": {
    linuxPrice: 4.752,
    windowsPrice: 6.224,
  },
  "l32asv3": {
    linuxPrice: 3.28,
    windowsPrice: 4.752,
  },
  "l32asv4": {
    linuxPrice: 3.608,
    windowsPrice: 5.08,
  },
  "l32sv3": {
    linuxPrice: 3.664,
    windowsPrice: 5.136,
  },
  "l32sv4": {
    linuxPrice: 3.664,
    windowsPrice: 5.136,
  },
  "l48asv3": {
    linuxPrice: 4.92,
    windowsPrice: 7.128,
  },
  "l48asv4": {
    linuxPrice: 5.412,
    windowsPrice: 7.62,
  },
  "l48sv3": {
    linuxPrice: 5.496,
    windowsPrice: 7.704,
  },
  "l48sv4": {
    linuxPrice: 5.496,
    windowsPrice: 7.704,
  },
  "l4aosv4": {
    linuxPrice: 0.594,
    windowsPrice: 0.778,
  },
  "l4asv4": {
    linuxPrice: 0.451,
    windowsPrice: 0.635,
  },
  "l4sv4": {
    linuxPrice: 0.458,
    windowsPrice: 0.642,
  },
  "l64asv3": {
    linuxPrice: 6.56,
    windowsPrice: 9.504,
  },
  "l64asv4": {
    linuxPrice: 7.216,
    windowsPrice: 10.16,
  },
  "l64sv3": {
    linuxPrice: 7.328,
    windowsPrice: 10.272,
  },
  "l64sv4": {
    linuxPrice: 7.328,
    windowsPrice: 10.272,
  },
  "l80asv3": {
    linuxPrice: 8.2,
    windowsPrice: 11.88,
  },
  "l80asv4": {
    linuxPrice: 9.02,
    windowsPrice: 12.7,
  },
  "l80sv3": {
    linuxPrice: 9.16,
    windowsPrice: 12.84,
  },
  "l80sv4": {
    linuxPrice: 9.16,
    windowsPrice: 12.84,
  },
  "l8aosv4": {
    linuxPrice: 1.188,
    windowsPrice: 1.556,
  },
  "l8asv3": {
    linuxPrice: 0.82,
    windowsPrice: 1.188,
  },
  "l8asv4": {
    linuxPrice: 0.902,
    windowsPrice: 1.27,
  },
  "l8sv3": {
    linuxPrice: 0.916,
    windowsPrice: 1.284,
  },
  "l8sv4": {
    linuxPrice: 0.916,
    windowsPrice: 1.284,
  },
  "l96asv4": {
    linuxPrice: 10.824,
    windowsPrice: 15.24,
  },
  "l96sv4": {
    linuxPrice: 10.992,
    windowsPrice: 15.408,
  },
  "m128": {
    linuxPrice: 17.873,
    windowsPrice: 23.761,
  },
  "m128dmsv2": {
    linuxPrice: 35.767,
    windowsPrice: 41.655,
  },
  "m128dsv2": {
    linuxPrice: 17.877,
    windowsPrice: 23.765,
  },
  "m128m": {
    linuxPrice: 35.762,
    windowsPrice: 41.65,
  },
  "m128ms": {
    linuxPrice: 35.762,
    windowsPrice: 41.65,
  },
  "m128msv2": {
    linuxPrice: 35.203,
    windowsPrice: 41.091,
  },
  "m128s": {
    linuxPrice: 17.873,
    windowsPrice: 23.761,
  },
  "m128sv2": {
    linuxPrice: 17.313,
    windowsPrice: 23.201,
  },
  "m16": {
    linuxPrice: 4.118,
    windowsPrice: 4.854,
  },
  "m16ms": {
    linuxPrice: 4.118,
    windowsPrice: 4.854,
  },
  "m192idmsv2": {
    linuxPrice: 42.969,
    windowsPrice: 51.801,
  },
  "m192idsv2": {
    linuxPrice: 21.484,
    windowsPrice: 30.316,
  },
  "m192imsv2": {
    linuxPrice: 42.405,
    windowsPrice: 51.237,
  },
  "m192isv2": {
    linuxPrice: 20.92,
    windowsPrice: 29.752,
  },
  "m208msv2": {
    linuxPrice: 59.791,
    windowsPrice: 69.359,
  },
  "m208sv2": {
    linuxPrice: 29.895,
    windowsPrice: 39.463,
  },
  "m32": {
    linuxPrice: 8.236,
    windowsPrice: 9.708,
  },
  "m32dmsv2": {
    linuxPrice: 8.236,
    windowsPrice: 9.708,
  },
  "m32ls": {
    linuxPrice: 3.829709,
    windowsPrice: 5.301709,
  },
  "m32ms": {
    linuxPrice: 8.236,
    windowsPrice: 9.708,
  },
  "m32msv2": {
    linuxPrice: 8.095,
    windowsPrice: 9.567,
  },
  "m32ts": {
    linuxPrice: 3.608431,
    windowsPrice: 5.080431,
  },
  "m416msv2": {
    linuxPrice: 132.86,
    windowsPrice: 152,
  },
  "m416s8v2": {
    linuxPrice: 96.52,
    windowsPrice: 115.66,
  },
  "m416sv2": {
    linuxPrice: 66.437,
    windowsPrice: 85.572,
  },
  "m64": {
    linuxPrice: 8.936,
    windowsPrice: 11.88,
  },
  "m64dmsv2": {
    linuxPrice: 13.857,
    windowsPrice: 16.801,
  },
  "m64dsv2": {
    linuxPrice: 8.937,
    windowsPrice: 11.881,
  },
  "m64ls": {
    linuxPrice: 7.218195,
    windowsPrice: 10.162195,
  },
  "m64m": {
    linuxPrice: 13.852,
    windowsPrice: 16.796,
  },
  "m64ms": {
    linuxPrice: 13.852,
    windowsPrice: 16.796,
  },
  "m64msv2": {
    linuxPrice: 13.575,
    windowsPrice: 16.519,
  },
  "m64s": {
    linuxPrice: 8.936,
    windowsPrice: 11.88,
  },
  "m64sv2": {
    linuxPrice: 8.655,
    windowsPrice: 11.599,
  },
  "m8": {
    linuxPrice: 2.059,
    windowsPrice: 2.427,
  },
  "m896ixds24v3": {
    linuxPrice: 417.66,
    windowsPrice: 0,
  },
  "m8ms": {
    linuxPrice: 2.059,
    windowsPrice: 2.427,
  },
  "nd96amsr": {
    linuxPrice: 47.844,
    windowsPrice: 52.26,
  },
  "nd96isrh100v5": {
    linuxPrice: 168.672,
    windowsPrice: 173.088,
  },
  "nd96isrh200v5": {
    linuxPrice: 123.808,
    windowsPrice: 128.224,
  },
  "nv12adsv5": {
    linuxPrice: 1.326,
    windowsPrice: 1.878,
  },
  "nv12sv3": {
    linuxPrice: 1.46,
    windowsPrice: 2.012,
  },
  "nv18adsv5": {
    linuxPrice: 2.336,
    windowsPrice: 3.164,
  },
  "nv24sv3": {
    linuxPrice: 2.921,
    windowsPrice: 4.025,
  },
  "nv36admsv5": {
    linuxPrice: 6.599,
    windowsPrice: 8.255,
  },
  "nv36adsv5": {
    linuxPrice: 4.672,
    windowsPrice: 6.328,
  },
  "nv48sv3": {
    linuxPrice: 5.841,
    windowsPrice: 8.049,
  },
  "nv6adsv5": {
    linuxPrice: 0.663,
    windowsPrice: 0.939,
  },
  "nv72adsv5": {
    linuxPrice: 9.519,
    windowsPrice: 12.831,
  },
};
