// AZURE instance prices for region key: swedensouth (updated 2026-08-30)
// Auto-generated by tools/split-data.js — do not edit by hand
// Specs for these types live in js/azure/azure-data.js as AZURE_SPECS.compute
window.swedensouth = {
  "a1v2": {
    linuxPrice: 0.0533,
    windowsPrice: 0.0993,
  },
  "a2mv2": {
    linuxPrice: 0.147,
    windowsPrice: 0.239,
  },
  "a2v2": {
    linuxPrice: 0.112,
    windowsPrice: 0.204,
  },
  "a4mv2": {
    linuxPrice: 0.294,
    windowsPrice: 0.478,
  },
  "a4v2": {
    linuxPrice: 0.237,
    windowsPrice: 0.421,
  },
  "a8mv2": {
    linuxPrice: 0.588,
    windowsPrice: 0.956,
  },
  "a8v2": {
    linuxPrice: 0.495,
    windowsPrice: 0.863,
  },
  "b12ms": {
    linuxPrice: 0.673,
    windowsPrice: 0.721,
  },
  "b16alsv2": {
    linuxPrice: 0.716,
    windowsPrice: 0.79,
  },
  "b16asv2": {
    linuxPrice: 0.809,
    windowsPrice: 0.882,
  },
  "b16lsv2": {
    linuxPrice: 0.869,
    windowsPrice: 0.869,
  },
  "b16ms": {
    linuxPrice: 0.898,
    windowsPrice: 0.962,
  },
  "b16sv2": {
    linuxPrice: 0.899,
    windowsPrice: 0.972,
  },
  "b1ls": {
    linuxPrice: 0.00702,
    windowsPrice: 0.011,
  },
  "b1ms": {
    linuxPrice: 0.0281,
    windowsPrice: 0.0321,
  },
  "b1s": {
    linuxPrice: 0.014,
    windowsPrice: 0.018,
  },
  "b20ms": {
    linuxPrice: 1.123,
    windowsPrice: 1.203,
  },
  "b2alsv2": {
    linuxPrice: 0.0505,
    windowsPrice: 0.0597,
  },
  "b2asv2": {
    linuxPrice: 0.101,
    windowsPrice: 0.11,
  },
  "b2atsv2": {
    linuxPrice: 0.0126,
    windowsPrice: 0.0218,
  },
  "b2lsv2": {
    linuxPrice: 0.0562,
    windowsPrice: 0.0654,
  },
  "b2ms": {
    linuxPrice: 0.112,
    windowsPrice: 0.12,
  },
  "b2s": {
    linuxPrice: 0.0562,
    windowsPrice: 0.0642,
  },
  "b2sv2": {
    linuxPrice: 0.122,
    windowsPrice: 0.122,
  },
  "b2tsv2": {
    linuxPrice: 0.014,
    windowsPrice: 0.0232,
  },
  "b32alsv2": {
    linuxPrice: 1.432,
    windowsPrice: 1.579,
  },
  "b32asv2": {
    linuxPrice: 1.617,
    windowsPrice: 1.765,
  },
  "b32lsv2": {
    linuxPrice: 1.739,
    windowsPrice: 1.739,
  },
  "b32sv2": {
    linuxPrice: 1.944,
    windowsPrice: 1.944,
  },
  "b4alsv2": {
    linuxPrice: 0.179,
    windowsPrice: 0.197,
  },
  "b4asv2": {
    linuxPrice: 0.221,
    windowsPrice: 0.221,
  },
  "b4lsv2": {
    linuxPrice: 0.199,
    windowsPrice: 0.217,
  },
  "b4ms": {
    linuxPrice: 0.225,
    windowsPrice: 0.241,
  },
  "b4sv2": {
    linuxPrice: 0.243,
    windowsPrice: 0.243,
  },
  "b8alsv2": {
    linuxPrice: 0.358,
    windowsPrice: 0.395,
  },
  "b8asv2": {
    linuxPrice: 0.404,
    windowsPrice: 0.441,
  },
  "b8lsv2": {
    linuxPrice: 0.435,
    windowsPrice: 0.435,
  },
  "b8ms": {
    linuxPrice: 0.449,
    windowsPrice: 0.481,
  },
  "b8sv2": {
    linuxPrice: 0.486,
    windowsPrice: 0.486,
  },
  "d11v2": {
    linuxPrice: 0.223,
    windowsPrice: 0.315,
  },
  "d128dsv6": {
    linuxPrice: 11.013,
    windowsPrice: 16.901,
  },
  "d128ldsv6": {
    linuxPrice: 9.825,
    windowsPrice: 15.713,
  },
  "d128lsv6": {
    linuxPrice: 7.95,
    windowsPrice: 13.838,
  },
  "d128ndsv6": {
    linuxPrice: 13.811,
    windowsPrice: 19.699,
  },
  "d128nldsv6": {
    linuxPrice: 12.515,
    windowsPrice: 18.403,
  },
  "d128nlsv6": {
    linuxPrice: 10.134,
    windowsPrice: 16.022,
  },
  "d128nsv6": {
    linuxPrice: 12.314,
    windowsPrice: 18.202,
  },
  "d128sv6": {
    linuxPrice: 8.911,
    windowsPrice: 14.799,
  },
  "d12v2": {
    linuxPrice: 0.449,
    windowsPrice: 0.633,
  },
  "d13v2": {
    linuxPrice: 0.898,
    windowsPrice: 1.266,
  },
  "d14v2": {
    linuxPrice: 1.795,
    windowsPrice: 2.531,
  },
  "d15iv2": {
    linuxPrice: 2.244,
    windowsPrice: 3.164,
  },
  "d15v2": {
    linuxPrice: 2.244,
    windowsPrice: 3.164,
  },
  "d16adsv5": {
    linuxPrice: 1.88,
    windowsPrice: 1.88,
  },
  "d16adsv6": {
    linuxPrice: 1.274,
    windowsPrice: 2.01,
  },
  "d16aldsv6": {
    linuxPrice: 1.064,
    windowsPrice: 1.8,
  },
  "d16alsv6": {
    linuxPrice: 0.896,
    windowsPrice: 1.632,
  },
  "d16asv4": {
    linuxPrice: 1.061,
    windowsPrice: 1.797,
  },
  "d16asv5": {
    linuxPrice: 0.957,
    windowsPrice: 1.693,
  },
  "d16asv6": {
    linuxPrice: 1.013,
    windowsPrice: 1.749,
  },
  "d16av4": {
    linuxPrice: 1.061,
    windowsPrice: 1.797,
  },
  "d16dsv5": {
    linuxPrice: 1.248,
    windowsPrice: 1.984,
  },
  "d16dsv6": {
    linuxPrice: 1.377,
    windowsPrice: 2.113,
  },
  "d16dv4": {
    linuxPrice: 1.248,
    windowsPrice: 1.984,
  },
  "d16dv5": {
    linuxPrice: 1.248,
    windowsPrice: 1.984,
  },
  "d16ldsv5": {
    linuxPrice: 1.082,
    windowsPrice: 1.818,
  },
  "d16ldsv6": {
    linuxPrice: 1.228,
    windowsPrice: 1.964,
  },
  "d16lsv5": {
    linuxPrice: 0.946,
    windowsPrice: 1.682,
  },
  "d16lsv6": {
    linuxPrice: 0.994,
    windowsPrice: 1.73,
  },
  "d16ndsv6": {
    linuxPrice: 1.726,
    windowsPrice: 2.462,
  },
  "d16nldsv6": {
    linuxPrice: 1.564,
    windowsPrice: 2.3,
  },
  "d16nlsv6": {
    linuxPrice: 1.267,
    windowsPrice: 2.003,
  },
  "d16nsv6": {
    linuxPrice: 1.539,
    windowsPrice: 2.275,
  },
  "d16sv3": {
    linuxPrice: 1.061,
    windowsPrice: 1.797,
  },
  "d16sv4": {
    linuxPrice: 1.061,
    windowsPrice: 1.797,
  },
  "d16sv5": {
    linuxPrice: 1.061,
    windowsPrice: 1.797,
  },
  "d16sv6": {
    linuxPrice: 1.114,
    windowsPrice: 1.85,
  },
  "d16v3": {
    linuxPrice: 1.061,
    windowsPrice: 1.797,
  },
  "d16v4": {
    linuxPrice: 1.061,
    windowsPrice: 1.797,
  },
  "d16v5": {
    linuxPrice: 1.061,
    windowsPrice: 1.797,
  },
  "d192dsv6": {
    linuxPrice: 16.52,
    windowsPrice: 25.352,
  },
  "d192sv6": {
    linuxPrice: 13.367,
    windowsPrice: 22.199,
  },
  "d1v2": {
    linuxPrice: 0.0884,
    windowsPrice: 0.134,
  },
  "d2adsv5": {
    linuxPrice: 0.143,
    windowsPrice: 0.235,
  },
  "d2adsv6": {
    linuxPrice: 0.159,
    windowsPrice: 0.251,
  },
  "d2aldsv6": {
    linuxPrice: 0.133,
    windowsPrice: 0.225,
  },
  "d2alsv6": {
    linuxPrice: 0.112,
    windowsPrice: 0.204,
  },
  "d2asv4": {
    linuxPrice: 0.133,
    windowsPrice: 0.225,
  },
  "d2asv5": {
    linuxPrice: 0.12,
    windowsPrice: 0.212,
  },
  "d2asv6": {
    linuxPrice: 0.127,
    windowsPrice: 0.219,
  },
  "d2av4": {
    linuxPrice: 0.133,
    windowsPrice: 0.225,
  },
  "d2dsv5": {
    linuxPrice: 0.156,
    windowsPrice: 0.248,
  },
  "d2dsv6": {
    linuxPrice: 0.172,
    windowsPrice: 0.264,
  },
  "d2dv4": {
    linuxPrice: 0.156,
    windowsPrice: 0.248,
  },
  "d2dv5": {
    linuxPrice: 0.156,
    windowsPrice: 0.248,
  },
  "d2ldsv5": {
    linuxPrice: 0.135,
    windowsPrice: 0.227,
  },
  "d2ldsv6": {
    linuxPrice: 0.154,
    windowsPrice: 0.246,
  },
  "d2lsv5": {
    linuxPrice: 0.118,
    windowsPrice: 0.21,
  },
  "d2lsv6": {
    linuxPrice: 0.124,
    windowsPrice: 0.216,
  },
  "d2ndsv6": {
    linuxPrice: 0.216,
    windowsPrice: 0.308,
  },
  "d2nldsv6": {
    linuxPrice: 0.196,
    windowsPrice: 0.288,
  },
  "d2nlsv6": {
    linuxPrice: 0.158,
    windowsPrice: 0.25,
  },
  "d2nsv6": {
    linuxPrice: 0.192,
    windowsPrice: 0.284,
  },
  "d2sv3": {
    linuxPrice: 0.133,
    windowsPrice: 0.225,
  },
  "d2sv4": {
    linuxPrice: 0.133,
    windowsPrice: 0.225,
  },
  "d2sv5": {
    linuxPrice: 0.133,
    windowsPrice: 0.225,
  },
  "d2sv6": {
    linuxPrice: 0.139,
    windowsPrice: 0.231,
  },
  "d2v2": {
    linuxPrice: 0.177,
    windowsPrice: 0.269,
  },
  "d2v3": {
    linuxPrice: 0.133,
    windowsPrice: 0.225,
  },
  "d2v4": {
    linuxPrice: 0.133,
    windowsPrice: 0.225,
  },
  "d2v5": {
    linuxPrice: 0.133,
    windowsPrice: 0.225,
  },
  "d32adsv5": {
    linuxPrice: 3.76,
    windowsPrice: 3.76,
  },
  "d32adsv6": {
    linuxPrice: 2.547,
    windowsPrice: 4.019,
  },
  "d32aldsv6": {
    linuxPrice: 2.128,
    windowsPrice: 3.6,
  },
  "d32alsv6": {
    linuxPrice: 1.792,
    windowsPrice: 3.264,
  },
  "d32asv4": {
    linuxPrice: 2.122,
    windowsPrice: 3.594,
  },
  "d32asv5": {
    linuxPrice: 3.386,
    windowsPrice: 3.386,
  },
  "d32asv6": {
    linuxPrice: 2.026,
    windowsPrice: 3.498,
  },
  "d32av4": {
    linuxPrice: 2.122,
    windowsPrice: 3.594,
  },
  "d32dsv5": {
    linuxPrice: 2.496,
    windowsPrice: 3.968,
  },
  "d32dsv6": {
    linuxPrice: 2.753,
    windowsPrice: 4.225,
  },
  "d32dv4": {
    linuxPrice: 2.496,
    windowsPrice: 3.968,
  },
  "d32dv5": {
    linuxPrice: 2.496,
    windowsPrice: 3.968,
  },
  "d32ldsv5": {
    linuxPrice: 2.163,
    windowsPrice: 3.635,
  },
  "d32ldsv6": {
    linuxPrice: 2.456,
    windowsPrice: 3.928,
  },
  "d32lsv5": {
    linuxPrice: 1.893,
    windowsPrice: 3.365,
  },
  "d32lsv6": {
    linuxPrice: 1.988,
    windowsPrice: 3.46,
  },
  "d32ndsv6": {
    linuxPrice: 3.453,
    windowsPrice: 4.925,
  },
  "d32nldsv6": {
    linuxPrice: 3.129,
    windowsPrice: 4.601,
  },
  "d32nlsv6": {
    linuxPrice: 2.533,
    windowsPrice: 4.005,
  },
  "d32nsv6": {
    linuxPrice: 3.078,
    windowsPrice: 4.55,
  },
  "d32sv3": {
    linuxPrice: 2.122,
    windowsPrice: 3.594,
  },
  "d32sv4": {
    linuxPrice: 2.122,
    windowsPrice: 3.594,
  },
  "d32sv5": {
    linuxPrice: 2.122,
    windowsPrice: 3.594,
  },
  "d32sv6": {
    linuxPrice: 2.228,
    windowsPrice: 3.7,
  },
  "d32v3": {
    linuxPrice: 2.122,
    windowsPrice: 3.594,
  },
  "d32v4": {
    linuxPrice: 2.122,
    windowsPrice: 3.594,
  },
  "d32v5": {
    linuxPrice: 2.122,
    windowsPrice: 3.594,
  },
  "d3v2": {
    linuxPrice: 0.353,
    windowsPrice: 0.537,
  },
  "d48adsv5": {
    linuxPrice: 5.64,
    windowsPrice: 5.64,
  },
  "d48adsv6": {
    linuxPrice: 3.821,
    windowsPrice: 6.029,
  },
  "d48aldsv6": {
    linuxPrice: 3.192,
    windowsPrice: 5.4,
  },
  "d48alsv6": {
    linuxPrice: 2.688,
    windowsPrice: 4.896,
  },
  "d48asv4": {
    linuxPrice: 3.182,
    windowsPrice: 5.39,
  },
  "d48asv5": {
    linuxPrice: 2.87,
    windowsPrice: 5.078,
  },
  "d48asv6": {
    linuxPrice: 3.038,
    windowsPrice: 5.246,
  },
  "d48av4": {
    linuxPrice: 3.182,
    windowsPrice: 5.39,
  },
  "d48dsv5": {
    linuxPrice: 3.744,
    windowsPrice: 5.952,
  },
  "d48dsv6": {
    linuxPrice: 4.13,
    windowsPrice: 6.338,
  },
  "d48dv4": {
    linuxPrice: 3.744,
    windowsPrice: 5.952,
  },
  "d48dv5": {
    linuxPrice: 3.744,
    windowsPrice: 5.952,
  },
  "d48ldsv5": {
    linuxPrice: 3.245,
    windowsPrice: 5.453,
  },
  "d48ldsv6": {
    linuxPrice: 3.684,
    windowsPrice: 5.892,
  },
  "d48lsv5": {
    linuxPrice: 2.839,
    windowsPrice: 5.047,
  },
  "d48lsv6": {
    linuxPrice: 2.981,
    windowsPrice: 5.189,
  },
  "d48ndsv6": {
    linuxPrice: 5.179,
    windowsPrice: 7.387,
  },
  "d48nldsv6": {
    linuxPrice: 4.693,
    windowsPrice: 6.901,
  },
  "d48nlsv6": {
    linuxPrice: 3.8,
    windowsPrice: 6.008,
  },
  "d48nsv6": {
    linuxPrice: 4.618,
    windowsPrice: 6.826,
  },
  "d48sv3": {
    linuxPrice: 3.182,
    windowsPrice: 5.39,
  },
  "d48sv4": {
    linuxPrice: 3.182,
    windowsPrice: 5.39,
  },
  "d48sv5": {
    linuxPrice: 3.182,
    windowsPrice: 5.39,
  },
  "d48sv6": {
    linuxPrice: 3.342,
    windowsPrice: 5.55,
  },
  "d48v3": {
    linuxPrice: 3.182,
    windowsPrice: 5.39,
  },
  "d48v4": {
    linuxPrice: 3.182,
    windowsPrice: 5.39,
  },
  "d48v5": {
    linuxPrice: 3.182,
    windowsPrice: 5.39,
  },
  "d4adsv5": {
    linuxPrice: 0.286,
    windowsPrice: 0.47,
  },
  "d4adsv6": {
    linuxPrice: 0.318,
    windowsPrice: 0.502,
  },
  "d4aldsv6": {
    linuxPrice: 0.266,
    windowsPrice: 0.45,
  },
  "d4alsv6": {
    linuxPrice: 0.224,
    windowsPrice: 0.408,
  },
  "d4asv4": {
    linuxPrice: 0.265,
    windowsPrice: 0.449,
  },
  "d4asv5": {
    linuxPrice: 0.423,
    windowsPrice: 0.423,
  },
  "d4asv6": {
    linuxPrice: 0.253,
    windowsPrice: 0.437,
  },
  "d4av4": {
    linuxPrice: 0.265,
    windowsPrice: 0.449,
  },
  "d4dsv5": {
    linuxPrice: 0.312,
    windowsPrice: 0.496,
  },
  "d4dsv6": {
    linuxPrice: 0.344,
    windowsPrice: 0.528,
  },
  "d4dv4": {
    linuxPrice: 0.312,
    windowsPrice: 0.496,
  },
  "d4dv5": {
    linuxPrice: 0.312,
    windowsPrice: 0.496,
  },
  "d4ldsv5": {
    linuxPrice: 0.27,
    windowsPrice: 0.454,
  },
  "d4ldsv6": {
    linuxPrice: 0.307,
    windowsPrice: 0.491,
  },
  "d4lsv5": {
    linuxPrice: 0.237,
    windowsPrice: 0.421,
  },
  "d4lsv6": {
    linuxPrice: 0.248,
    windowsPrice: 0.432,
  },
  "d4ndsv6": {
    linuxPrice: 0.397,
    windowsPrice: 0.581,
  },
  "d4nldsv6": {
    linuxPrice: 0.391,
    windowsPrice: 0.575,
  },
  "d4nlsv6": {
    linuxPrice: 0.317,
    windowsPrice: 0.501,
  },
  "d4nsv6": {
    linuxPrice: 0.385,
    windowsPrice: 0.569,
  },
  "d4sv3": {
    linuxPrice: 0.265,
    windowsPrice: 0.449,
  },
  "d4sv4": {
    linuxPrice: 0.265,
    windowsPrice: 0.449,
  },
  "d4sv5": {
    linuxPrice: 0.265,
    windowsPrice: 0.449,
  },
  "d4sv6": {
    linuxPrice: 0.278,
    windowsPrice: 0.462,
  },
  "d4v2": {
    linuxPrice: 0.707,
    windowsPrice: 1.075,
  },
  "d4v3": {
    linuxPrice: 0.265,
    windowsPrice: 0.449,
  },
  "d4v4": {
    linuxPrice: 0.265,
    windowsPrice: 0.449,
  },
  "d4v5": {
    linuxPrice: 0.265,
    windowsPrice: 0.449,
  },
  "d5v2": {
    linuxPrice: 1.414,
    windowsPrice: 2.15,
  },
  "d64adsv5": {
    linuxPrice: 4.576,
    windowsPrice: 7.52,
  },
  "d64adsv6": {
    linuxPrice: 5.094,
    windowsPrice: 8.038,
  },
  "d64aldsv6": {
    linuxPrice: 4.256,
    windowsPrice: 7.2,
  },
  "d64alsv6": {
    linuxPrice: 3.584,
    windowsPrice: 6.528,
  },
  "d64asv4": {
    linuxPrice: 4.243,
    windowsPrice: 7.187,
  },
  "d64asv5": {
    linuxPrice: 6.771,
    windowsPrice: 6.771,
  },
  "d64asv6": {
    linuxPrice: 4.051,
    windowsPrice: 6.995,
  },
  "d64av4": {
    linuxPrice: 4.243,
    windowsPrice: 7.187,
  },
  "d64dsv5": {
    linuxPrice: 4.992,
    windowsPrice: 7.936,
  },
  "d64dsv6": {
    linuxPrice: 5.507,
    windowsPrice: 8.451,
  },
  "d64dv4": {
    linuxPrice: 4.992,
    windowsPrice: 7.936,
  },
  "d64dv5": {
    linuxPrice: 4.992,
    windowsPrice: 7.936,
  },
  "d64ldsv5": {
    linuxPrice: 4.326,
    windowsPrice: 7.27,
  },
  "d64ldsv6": {
    linuxPrice: 4.913,
    windowsPrice: 7.857,
  },
  "d64lsv5": {
    linuxPrice: 3.786,
    windowsPrice: 6.73,
  },
  "d64lsv6": {
    linuxPrice: 3.975,
    windowsPrice: 6.919,
  },
  "d64ndsv6": {
    linuxPrice: 6.906,
    windowsPrice: 9.85,
  },
  "d64nldsv6": {
    linuxPrice: 6.258,
    windowsPrice: 9.202,
  },
  "d64nlsv6": {
    linuxPrice: 5.067,
    windowsPrice: 8.011,
  },
  "d64nsv6": {
    linuxPrice: 6.157,
    windowsPrice: 9.101,
  },
  "d64sv3": {
    linuxPrice: 4.243,
    windowsPrice: 7.187,
  },
  "d64sv4": {
    linuxPrice: 4.243,
    windowsPrice: 7.187,
  },
  "d64sv5": {
    linuxPrice: 4.243,
    windowsPrice: 7.187,
  },
  "d64sv6": {
    linuxPrice: 4.456,
    windowsPrice: 7.4,
  },
  "d64v3": {
    linuxPrice: 4.243,
    windowsPrice: 7.187,
  },
  "d64v4": {
    linuxPrice: 4.243,
    windowsPrice: 7.187,
  },
  "d64v5": {
    linuxPrice: 4.243,
    windowsPrice: 7.187,
  },
  "d8adsv5": {
    linuxPrice: 0.94,
    windowsPrice: 0.94,
  },
  "d8adsv6": {
    linuxPrice: 0.637,
    windowsPrice: 1.005,
  },
  "d8aldsv6": {
    linuxPrice: 0.532,
    windowsPrice: 0.9,
  },
  "d8alsv6": {
    linuxPrice: 0.448,
    windowsPrice: 0.816,
  },
  "d8asv4": {
    linuxPrice: 0.53,
    windowsPrice: 0.898,
  },
  "d8asv5": {
    linuxPrice: 0.846,
    windowsPrice: 0.846,
  },
  "d8asv6": {
    linuxPrice: 0.506,
    windowsPrice: 0.874,
  },
  "d8av4": {
    linuxPrice: 0.53,
    windowsPrice: 0.898,
  },
  "d8dsv5": {
    linuxPrice: 0.624,
    windowsPrice: 0.992,
  },
  "d8dsv6": {
    linuxPrice: 0.688,
    windowsPrice: 1.056,
  },
  "d8dv4": {
    linuxPrice: 0.624,
    windowsPrice: 0.992,
  },
  "d8dv5": {
    linuxPrice: 0.624,
    windowsPrice: 0.992,
  },
  "d8ldsv5": {
    linuxPrice: 0.541,
    windowsPrice: 0.909,
  },
  "d8ldsv6": {
    linuxPrice: 0.614,
    windowsPrice: 0.982,
  },
  "d8lsv5": {
    linuxPrice: 0.473,
    windowsPrice: 0.841,
  },
  "d8lsv6": {
    linuxPrice: 0.497,
    windowsPrice: 0.865,
  },
  "d8ndsv6": {
    linuxPrice: 0.863,
    windowsPrice: 1.231,
  },
  "d8nldsv6": {
    linuxPrice: 0.782,
    windowsPrice: 1.15,
  },
  "d8nlsv6": {
    linuxPrice: 0.633,
    windowsPrice: 1.001,
  },
  "d8nsv6": {
    linuxPrice: 0.77,
    windowsPrice: 1.138,
  },
  "d8sv3": {
    linuxPrice: 0.53,
    windowsPrice: 0.898,
  },
  "d8sv4": {
    linuxPrice: 0.53,
    windowsPrice: 0.898,
  },
  "d8sv5": {
    linuxPrice: 0.53,
    windowsPrice: 0.898,
  },
  "d8sv6": {
    linuxPrice: 0.557,
    windowsPrice: 0.925,
  },
  "d8v3": {
    linuxPrice: 0.53,
    windowsPrice: 0.898,
  },
  "d8v4": {
    linuxPrice: 0.53,
    windowsPrice: 0.898,
  },
  "d8v5": {
    linuxPrice: 0.53,
    windowsPrice: 0.898,
  },
  "d96adsv5": {
    linuxPrice: 11.28,
    windowsPrice: 11.28,
  },
  "d96adsv6": {
    linuxPrice: 7.642,
    windowsPrice: 12.058,
  },
  "d96aldsv6": {
    linuxPrice: 6.384,
    windowsPrice: 10.8,
  },
  "d96alsv6": {
    linuxPrice: 5.376,
    windowsPrice: 9.792,
  },
  "d96asv4": {
    linuxPrice: 6.365,
    windowsPrice: 10.781,
  },
  "d96asv5": {
    linuxPrice: 5.741,
    windowsPrice: 10.157,
  },
  "d96asv6": {
    linuxPrice: 6.077,
    windowsPrice: 10.493,
  },
  "d96av4": {
    linuxPrice: 6.365,
    windowsPrice: 10.781,
  },
  "d96dsv5": {
    linuxPrice: 7.488,
    windowsPrice: 11.904,
  },
  "d96dsv6": {
    linuxPrice: 8.26,
    windowsPrice: 12.676,
  },
  "d96dv5": {
    linuxPrice: 7.488,
    windowsPrice: 11.904,
  },
  "d96ldsv5": {
    linuxPrice: 6.49,
    windowsPrice: 10.906,
  },
  "d96ldsv6": {
    linuxPrice: 7.369,
    windowsPrice: 11.785,
  },
  "d96lsv5": {
    linuxPrice: 5.678,
    windowsPrice: 10.094,
  },
  "d96lsv6": {
    linuxPrice: 5.963,
    windowsPrice: 10.379,
  },
  "d96ndsv6": {
    linuxPrice: 10.358,
    windowsPrice: 14.774,
  },
  "d96nldsv6": {
    linuxPrice: 9.386,
    windowsPrice: 13.802,
  },
  "d96nlsv6": {
    linuxPrice: 7.6,
    windowsPrice: 12.016,
  },
  "d96nsv6": {
    linuxPrice: 9.235,
    windowsPrice: 13.651,
  },
  "d96sv5": {
    linuxPrice: 6.365,
    windowsPrice: 10.781,
  },
  "d96sv6": {
    linuxPrice: 6.684,
    windowsPrice: 11.1,
  },
  "d96v5": {
    linuxPrice: 6.365,
    windowsPrice: 10.781,
  },
  "dc16adsv6": {
    linuxPrice: 1.274,
    windowsPrice: 2.01,
  },
  "dc16asv6": {
    linuxPrice: 1.013,
    windowsPrice: 1.749,
  },
  "dc2adsv6": {
    linuxPrice: 0.159,
    windowsPrice: 0.251,
  },
  "dc2asv6": {
    linuxPrice: 0.127,
    windowsPrice: 0.219,
  },
  "dc32adsv6": {
    linuxPrice: 2.547,
    windowsPrice: 4.019,
  },
  "dc32asv6": {
    linuxPrice: 2.026,
    windowsPrice: 3.498,
  },
  "dc48adsv6": {
    linuxPrice: 3.821,
    windowsPrice: 6.029,
  },
  "dc48asv6": {
    linuxPrice: 3.038,
    windowsPrice: 5.246,
  },
  "dc4adsv6": {
    linuxPrice: 0.318,
    windowsPrice: 0.502,
  },
  "dc4asv6": {
    linuxPrice: 0.253,
    windowsPrice: 0.437,
  },
  "dc64adsv6": {
    linuxPrice: 5.094,
    windowsPrice: 8.038,
  },
  "dc64asv6": {
    linuxPrice: 4.051,
    windowsPrice: 6.995,
  },
  "dc8adsv6": {
    linuxPrice: 0.637,
    windowsPrice: 1.005,
  },
  "dc8asv6": {
    linuxPrice: 0.506,
    windowsPrice: 0.874,
  },
  "dc96adsv6": {
    linuxPrice: 7.642,
    windowsPrice: 12.058,
  },
  "dc96asv6": {
    linuxPrice: 6.077,
    windowsPrice: 10.493,
  },
  "ds11": {
    linuxPrice: 0.223,
    windowsPrice: 0.315,
  },
  "ds11v2": {
    linuxPrice: 0.223,
    windowsPrice: 0.315,
  },
  "ds12": {
    linuxPrice: 0.449,
    windowsPrice: 0.541,
  },
  "ds12v2": {
    linuxPrice: 0.449,
    windowsPrice: 0.633,
  },
  "ds13": {
    linuxPrice: 0.898,
    windowsPrice: 1.266,
  },
  "ds13v2": {
    linuxPrice: 0.898,
    windowsPrice: 1.266,
  },
  "ds14": {
    linuxPrice: 1.795,
    windowsPrice: 2.531,
  },
  "ds14v2": {
    linuxPrice: 1.795,
    windowsPrice: 2.531,
  },
  "ds15iv2": {
    linuxPrice: 2.244,
    windowsPrice: 3.164,
  },
  "ds15v2": {
    linuxPrice: 2.244,
    windowsPrice: 3.164,
  },
  "ds1v2": {
    linuxPrice: 0.0884,
    windowsPrice: 0.134,
  },
  "ds2v2": {
    linuxPrice: 0.177,
    windowsPrice: 0.269,
  },
  "ds3v2": {
    linuxPrice: 0.353,
    windowsPrice: 0.537,
  },
  "ds4v2": {
    linuxPrice: 0.707,
    windowsPrice: 1.075,
  },
  "ds5v2": {
    linuxPrice: 1.414,
    windowsPrice: 2.15,
  },
  "e104idsv5": {
    linuxPrice: 11.303,
    windowsPrice: 16.087,
  },
  "e104idv5": {
    linuxPrice: 11.303,
    windowsPrice: 16.087,
  },
  "e104isv5": {
    linuxPrice: 9.964,
    windowsPrice: 14.748,
  },
  "e104iv5": {
    linuxPrice: 9.964,
    windowsPrice: 14.748,
  },
  "e112bdsv5": {
    linuxPrice: 14.214,
    windowsPrice: 19.366,
  },
  "e112bsv5": {
    linuxPrice: 12.773,
    windowsPrice: 17.925,
  },
  "e128": {
    linuxPrice: 11.707,
    windowsPrice: 17.595,
  },
  "e128bdsv6": {
    linuxPrice: 17.23,
    windowsPrice: 23.118,
  },
  "e128bsv6": {
    linuxPrice: 15.478,
    windowsPrice: 21.366,
  },
  "e128dsv6": {
    linuxPrice: 14.469,
    windowsPrice: 20.357,
  },
  "e128ndsv6": {
    linuxPrice: 17.23,
    windowsPrice: 23.118,
  },
  "e128nsv6": {
    linuxPrice: 15.478,
    windowsPrice: 21.366,
  },
  "e128sv6": {
    linuxPrice: 11.707,
    windowsPrice: 17.595,
  },
  "e16": {
    linuxPrice: 1.394,
    windowsPrice: 2.317,
  },
  "e16adsv5": {
    linuxPrice: 1.446,
    windowsPrice: 2.182,
  },
  "e16adsv6": {
    linuxPrice: 1.619,
    windowsPrice: 2.355,
  },
  "e16asv4": {
    linuxPrice: 1.394,
    windowsPrice: 2.13,
  },
  "e16asv5": {
    linuxPrice: 1.994,
    windowsPrice: 1.994,
  },
  "e16asv6": {
    linuxPrice: 1.331,
    windowsPrice: 2.067,
  },
  "e16av4": {
    linuxPrice: 1.394,
    windowsPrice: 2.13,
  },
  "e16bdsv5": {
    linuxPrice: 1.846,
    windowsPrice: 2.582,
  },
  "e16bdsv6": {
    linuxPrice: 2.154,
    windowsPrice: 2.89,
  },
  "e16bsv5": {
    linuxPrice: 1.659,
    windowsPrice: 2.395,
  },
  "e16bsv6": {
    linuxPrice: 1.935,
    windowsPrice: 2.671,
  },
  "e16dsv4": {
    linuxPrice: 1.581,
    windowsPrice: 2.317,
  },
  "e16dsv5": {
    linuxPrice: 1.581,
    windowsPrice: 2.317,
  },
  "e16dsv6": {
    linuxPrice: 1.809,
    windowsPrice: 2.545,
  },
  "e16dv4": {
    linuxPrice: 1.581,
    windowsPrice: 2.317,
  },
  "e16dv5": {
    linuxPrice: 1.581,
    windowsPrice: 2.317,
  },
  "e16ndsv6": {
    linuxPrice: 2.154,
    windowsPrice: 2.89,
  },
  "e16nsv6": {
    linuxPrice: 1.935,
    windowsPrice: 2.671,
  },
  "e16sv3": {
    linuxPrice: 1.394,
    windowsPrice: 2.13,
  },
  "e16sv5": {
    linuxPrice: 1.394,
    windowsPrice: 2.13,
  },
  "e16sv6": {
    linuxPrice: 1.463,
    windowsPrice: 2.199,
  },
  "e16v3": {
    linuxPrice: 1.394,
    windowsPrice: 2.13,
  },
  "e16v5": {
    linuxPrice: 1.394,
    windowsPrice: 2.13,
  },
  "e192ibdsv6": {
    linuxPrice: 28.429,
    windowsPrice: 37.261,
  },
  "e192ibsv6": {
    linuxPrice: 25.538,
    windowsPrice: 34.37,
  },
  "e192idsv6": {
    linuxPrice: 23.874,
    windowsPrice: 32.706,
  },
  "e20adsv5": {
    linuxPrice: 1.807,
    windowsPrice: 2.727,
  },
  "e20adsv6": {
    linuxPrice: 2.024,
    windowsPrice: 2.944,
  },
  "e20asv4": {
    linuxPrice: 1.742,
    windowsPrice: 2.662,
  },
  "e20asv5": {
    linuxPrice: 1.573,
    windowsPrice: 2.493,
  },
  "e20asv6": {
    linuxPrice: 1.664,
    windowsPrice: 2.584,
  },
  "e20av4": {
    linuxPrice: 1.742,
    windowsPrice: 2.662,
  },
  "e20dsv4": {
    linuxPrice: 1.976,
    windowsPrice: 2.896,
  },
  "e20dsv5": {
    linuxPrice: 1.976,
    windowsPrice: 2.896,
  },
  "e20dsv6": {
    linuxPrice: 2.261,
    windowsPrice: 3.181,
  },
  "e20dv4": {
    linuxPrice: 1.976,
    windowsPrice: 2.896,
  },
  "e20dv5": {
    linuxPrice: 1.976,
    windowsPrice: 2.896,
  },
  "e20sv3": {
    linuxPrice: 1.742,
    windowsPrice: 2.662,
  },
  "e20sv5": {
    linuxPrice: 1.742,
    windowsPrice: 2.662,
  },
  "e20sv6": {
    linuxPrice: 1.829,
    windowsPrice: 2.749,
  },
  "e20v3": {
    linuxPrice: 1.742,
    windowsPrice: 2.662,
  },
  "e20v5": {
    linuxPrice: 1.742,
    windowsPrice: 2.662,
  },
  "e2adsv5": {
    linuxPrice: 0.273,
    windowsPrice: 0.273,
  },
  "e2adsv6": {
    linuxPrice: 0.202,
    windowsPrice: 0.294,
  },
  "e2asv4": {
    linuxPrice: 0.174,
    windowsPrice: 0.266,
  },
  "e2asv5": {
    linuxPrice: 0.249,
    windowsPrice: 0.249,
  },
  "e2asv6": {
    linuxPrice: 0.166,
    windowsPrice: 0.258,
  },
  "e2av4": {
    linuxPrice: 0.174,
    windowsPrice: 0.266,
  },
  "e2bdsv5": {
    linuxPrice: 0.231,
    windowsPrice: 0.323,
  },
  "e2bdsv6": {
    linuxPrice: 0.269,
    windowsPrice: 0.361,
  },
  "e2bsv5": {
    linuxPrice: 0.207,
    windowsPrice: 0.299,
  },
  "e2bsv6": {
    linuxPrice: 0.242,
    windowsPrice: 0.334,
  },
  "e2dsv4": {
    linuxPrice: 0.198,
    windowsPrice: 0.29,
  },
  "e2dsv5": {
    linuxPrice: 0.198,
    windowsPrice: 0.29,
  },
  "e2dsv6": {
    linuxPrice: 0.226,
    windowsPrice: 0.318,
  },
  "e2dv4": {
    linuxPrice: 0.198,
    windowsPrice: 0.29,
  },
  "e2dv5": {
    linuxPrice: 0.198,
    windowsPrice: 0.29,
  },
  "e2ndsv6": {
    linuxPrice: 0.269,
    windowsPrice: 0.361,
  },
  "e2nsv6": {
    linuxPrice: 0.242,
    windowsPrice: 0.334,
  },
  "e2sv3": {
    linuxPrice: 0.174,
    windowsPrice: 0.266,
  },
  "e2sv5": {
    linuxPrice: 0.174,
    windowsPrice: 0.266,
  },
  "e2sv6": {
    linuxPrice: 0.183,
    windowsPrice: 0.275,
  },
  "e2v3": {
    linuxPrice: 0.174,
    windowsPrice: 0.266,
  },
  "e2v5": {
    linuxPrice: 0.174,
    windowsPrice: 0.266,
  },
  "e32": {
    linuxPrice: 2.787,
    windowsPrice: 4.634,
  },
  "e32adsv5": {
    linuxPrice: 4.363,
    windowsPrice: 4.363,
  },
  "e32adsv6": {
    linuxPrice: 3.238,
    windowsPrice: 4.71,
  },
  "e32asv4": {
    linuxPrice: 2.787,
    windowsPrice: 4.259,
  },
  "e32asv5": {
    linuxPrice: 3.989,
    windowsPrice: 3.989,
  },
  "e32asv6": {
    linuxPrice: 2.662,
    windowsPrice: 4.134,
  },
  "e32av4": {
    linuxPrice: 2.787,
    windowsPrice: 4.259,
  },
  "e32bdsv5": {
    linuxPrice: 3.692,
    windowsPrice: 5.164,
  },
  "e32bdsv6": {
    linuxPrice: 4.307,
    windowsPrice: 5.779,
  },
  "e32bsv5": {
    linuxPrice: 3.318,
    windowsPrice: 4.79,
  },
  "e32bsv6": {
    linuxPrice: 3.869,
    windowsPrice: 5.341,
  },
  "e32dsv4": {
    linuxPrice: 3.162,
    windowsPrice: 4.634,
  },
  "e32dsv5": {
    linuxPrice: 3.162,
    windowsPrice: 4.634,
  },
  "e32dsv6": {
    linuxPrice: 3.617,
    windowsPrice: 5.089,
  },
  "e32dv4": {
    linuxPrice: 3.162,
    windowsPrice: 4.634,
  },
  "e32dv5": {
    linuxPrice: 3.162,
    windowsPrice: 4.634,
  },
  "e32ndsv6": {
    linuxPrice: 4.307,
    windowsPrice: 5.779,
  },
  "e32nsv6": {
    linuxPrice: 3.869,
    windowsPrice: 5.341,
  },
  "e32sv3": {
    linuxPrice: 2.787,
    windowsPrice: 4.259,
  },
  "e32sv5": {
    linuxPrice: 2.787,
    windowsPrice: 4.259,
  },
  "e32sv6": {
    linuxPrice: 2.927,
    windowsPrice: 4.399,
  },
  "e32v3": {
    linuxPrice: 2.787,
    windowsPrice: 4.259,
  },
  "e32v5": {
    linuxPrice: 2.787,
    windowsPrice: 4.259,
  },
  "e4": {
    linuxPrice: 0.348,
    windowsPrice: 0.532,
  },
  "e48adsv5": {
    linuxPrice: 4.337,
    windowsPrice: 6.545,
  },
  "e48adsv6": {
    linuxPrice: 4.858,
    windowsPrice: 7.066,
  },
  "e48asv4": {
    linuxPrice: 4.181,
    windowsPrice: 6.389,
  },
  "e48asv5": {
    linuxPrice: 5.983,
    windowsPrice: 5.983,
  },
  "e48asv6": {
    linuxPrice: 3.994,
    windowsPrice: 6.202,
  },
  "e48av4": {
    linuxPrice: 4.181,
    windowsPrice: 6.389,
  },
  "e48bdsv5": {
    linuxPrice: 5.538,
    windowsPrice: 7.746,
  },
  "e48bdsv6": {
    linuxPrice: 6.461,
    windowsPrice: 8.669,
  },
  "e48bsv5": {
    linuxPrice: 4.976,
    windowsPrice: 7.184,
  },
  "e48bsv6": {
    linuxPrice: 5.804,
    windowsPrice: 8.012,
  },
  "e48dsv4": {
    linuxPrice: 4.742,
    windowsPrice: 6.95,
  },
  "e48dsv5": {
    linuxPrice: 4.742,
    windowsPrice: 6.95,
  },
  "e48dsv6": {
    linuxPrice: 5.426,
    windowsPrice: 7.634,
  },
  "e48dv4": {
    linuxPrice: 4.742,
    windowsPrice: 6.95,
  },
  "e48dv5": {
    linuxPrice: 4.742,
    windowsPrice: 6.95,
  },
  "e48ndsv6": {
    linuxPrice: 6.461,
    windowsPrice: 8.669,
  },
  "e48nsv6": {
    linuxPrice: 5.804,
    windowsPrice: 8.012,
  },
  "e48sv3": {
    linuxPrice: 4.181,
    windowsPrice: 6.389,
  },
  "e48sv5": {
    linuxPrice: 4.181,
    windowsPrice: 6.389,
  },
  "e48sv6": {
    linuxPrice: 4.39,
    windowsPrice: 6.598,
  },
  "e48v3": {
    linuxPrice: 4.181,
    windowsPrice: 6.389,
  },
  "e48v5": {
    linuxPrice: 4.181,
    windowsPrice: 6.389,
  },
  "e4adsv5": {
    linuxPrice: 0.545,
    windowsPrice: 0.545,
  },
  "e4adsv6": {
    linuxPrice: 0.405,
    windowsPrice: 0.589,
  },
  "e4asv4": {
    linuxPrice: 0.348,
    windowsPrice: 0.532,
  },
  "e4asv5": {
    linuxPrice: 0.499,
    windowsPrice: 0.499,
  },
  "e4asv6": {
    linuxPrice: 0.333,
    windowsPrice: 0.517,
  },
  "e4av4": {
    linuxPrice: 0.348,
    windowsPrice: 0.532,
  },
  "e4bdsv5": {
    linuxPrice: 0.462,
    windowsPrice: 0.646,
  },
  "e4bdsv6": {
    linuxPrice: 0.538,
    windowsPrice: 0.722,
  },
  "e4bsv5": {
    linuxPrice: 0.415,
    windowsPrice: 0.599,
  },
  "e4bsv6": {
    linuxPrice: 0.484,
    windowsPrice: 0.668,
  },
  "e4dsv4": {
    linuxPrice: 0.395,
    windowsPrice: 0.579,
  },
  "e4dsv5": {
    linuxPrice: 0.395,
    windowsPrice: 0.579,
  },
  "e4dsv6": {
    linuxPrice: 0.452,
    windowsPrice: 0.636,
  },
  "e4dv4": {
    linuxPrice: 0.395,
    windowsPrice: 0.579,
  },
  "e4dv5": {
    linuxPrice: 0.395,
    windowsPrice: 0.579,
  },
  "e4ndsv6": {
    linuxPrice: 0.538,
    windowsPrice: 0.722,
  },
  "e4nsv6": {
    linuxPrice: 0.484,
    windowsPrice: 0.668,
  },
  "e4sv3": {
    linuxPrice: 0.348,
    windowsPrice: 0.532,
  },
  "e4sv5": {
    linuxPrice: 0.348,
    windowsPrice: 0.532,
  },
  "e4sv6": {
    linuxPrice: 0.366,
    windowsPrice: 0.55,
  },
  "e4v3": {
    linuxPrice: 0.348,
    windowsPrice: 0.532,
  },
  "e4v5": {
    linuxPrice: 0.348,
    windowsPrice: 0.532,
  },
  "e64": {
    linuxPrice: 7.235,
    windowsPrice: 10.179,
  },
  "e64adsv5": {
    linuxPrice: 5.782,
    windowsPrice: 8.726,
  },
  "e64adsv6": {
    linuxPrice: 6.477,
    windowsPrice: 9.421,
  },
  "e64asv4": {
    linuxPrice: 5.574,
    windowsPrice: 8.518,
  },
  "e64asv5": {
    linuxPrice: 7.978,
    windowsPrice: 7.978,
  },
  "e64asv6": {
    linuxPrice: 5.325,
    windowsPrice: 8.269,
  },
  "e64av4": {
    linuxPrice: 5.574,
    windowsPrice: 8.518,
  },
  "e64bdsv5": {
    linuxPrice: 7.384,
    windowsPrice: 10.328,
  },
  "e64bdsv6": {
    linuxPrice: 8.615,
    windowsPrice: 11.559,
  },
  "e64bsv5": {
    linuxPrice: 6.635,
    windowsPrice: 9.579,
  },
  "e64bsv6": {
    linuxPrice: 7.739,
    windowsPrice: 10.683,
  },
  "e64dsv4": {
    linuxPrice: 6.323,
    windowsPrice: 9.267,
  },
  "e64dsv5": {
    linuxPrice: 6.323,
    windowsPrice: 9.267,
  },
  "e64dsv6": {
    linuxPrice: 7.235,
    windowsPrice: 10.179,
  },
  "e64dv4": {
    linuxPrice: 6.323,
    windowsPrice: 9.267,
  },
  "e64dv5": {
    linuxPrice: 6.323,
    windowsPrice: 9.267,
  },
  "e64isv3": {
    linuxPrice: 5.574,
    windowsPrice: 8.518,
  },
  "e64iv3": {
    linuxPrice: 5.574,
    windowsPrice: 8.518,
  },
  "e64ndsv6": {
    linuxPrice: 8.615,
    windowsPrice: 11.559,
  },
  "e64nsv6": {
    linuxPrice: 7.739,
    windowsPrice: 10.683,
  },
  "e64sv3": {
    linuxPrice: 5.574,
    windowsPrice: 8.518,
  },
  "e64sv5": {
    linuxPrice: 5.574,
    windowsPrice: 8.518,
  },
  "e64sv6": {
    linuxPrice: 5.853,
    windowsPrice: 8.797,
  },
  "e64v3": {
    linuxPrice: 5.574,
    windowsPrice: 8.518,
  },
  "e64v5": {
    linuxPrice: 5.574,
    windowsPrice: 8.518,
  },
  "e8": {
    linuxPrice: 0.79,
    windowsPrice: 1.065,
  },
  "e80idsv4": {
    linuxPrice: 7.904,
    windowsPrice: 11.584,
  },
  "e8adsv5": {
    linuxPrice: 0.723,
    windowsPrice: 1.091,
  },
  "e8adsv6": {
    linuxPrice: 0.81,
    windowsPrice: 1.178,
  },
  "e8asv4": {
    linuxPrice: 0.697,
    windowsPrice: 1.065,
  },
  "e8asv5": {
    linuxPrice: 0.629,
    windowsPrice: 0.997,
  },
  "e8asv6": {
    linuxPrice: 0.666,
    windowsPrice: 1.034,
  },
  "e8av4": {
    linuxPrice: 0.697,
    windowsPrice: 1.065,
  },
  "e8bdsv5": {
    linuxPrice: 0.923,
    windowsPrice: 1.291,
  },
  "e8bdsv6": {
    linuxPrice: 1.077,
    windowsPrice: 1.445,
  },
  "e8bsv5": {
    linuxPrice: 0.829,
    windowsPrice: 1.197,
  },
  "e8bsv6": {
    linuxPrice: 0.967,
    windowsPrice: 1.335,
  },
  "e8dsv4": {
    linuxPrice: 0.79,
    windowsPrice: 1.158,
  },
  "e8dsv5": {
    linuxPrice: 0.79,
    windowsPrice: 1.158,
  },
  "e8dsv6": {
    linuxPrice: 0.904,
    windowsPrice: 1.272,
  },
  "e8dv4": {
    linuxPrice: 0.79,
    windowsPrice: 1.158,
  },
  "e8dv5": {
    linuxPrice: 0.79,
    windowsPrice: 1.158,
  },
  "e8ndsv6": {
    linuxPrice: 1.077,
    windowsPrice: 1.445,
  },
  "e8nsv6": {
    linuxPrice: 0.967,
    windowsPrice: 1.335,
  },
  "e8sv3": {
    linuxPrice: 0.697,
    windowsPrice: 1.065,
  },
  "e8sv5": {
    linuxPrice: 0.697,
    windowsPrice: 1.065,
  },
  "e8sv6": {
    linuxPrice: 0.732,
    windowsPrice: 1.1,
  },
  "e8v3": {
    linuxPrice: 0.697,
    windowsPrice: 1.065,
  },
  "e8v5": {
    linuxPrice: 0.697,
    windowsPrice: 1.065,
  },
  "e96": {
    linuxPrice: 2.927,
    windowsPrice: 12.778,
  },
  "e96adsv5": {
    linuxPrice: 13.09,
    windowsPrice: 13.09,
  },
  "e96adsv6": {
    linuxPrice: 9.715,
    windowsPrice: 14.131,
  },
  "e96asv4": {
    linuxPrice: 8.362,
    windowsPrice: 12.778,
  },
  "e96asv5": {
    linuxPrice: 7.55,
    windowsPrice: 11.966,
  },
  "e96asv6": {
    linuxPrice: 7.987,
    windowsPrice: 12.403,
  },
  "e96av4": {
    linuxPrice: 8.362,
    windowsPrice: 12.778,
  },
  "e96bdsv5": {
    linuxPrice: 11.076,
    windowsPrice: 15.492,
  },
  "e96bdsv6": {
    linuxPrice: 12.922,
    windowsPrice: 17.338,
  },
  "e96bsv5": {
    linuxPrice: 9.953,
    windowsPrice: 14.369,
  },
  "e96bsv6": {
    linuxPrice: 11.608,
    windowsPrice: 16.024,
  },
  "e96dsv5": {
    linuxPrice: 9.485,
    windowsPrice: 13.901,
  },
  "e96dsv6": {
    linuxPrice: 10.852,
    windowsPrice: 15.268,
  },
  "e96dv5": {
    linuxPrice: 9.485,
    windowsPrice: 13.901,
  },
  "e96ndsv6": {
    linuxPrice: 12.922,
    windowsPrice: 17.338,
  },
  "e96nsv6": {
    linuxPrice: 11.608,
    windowsPrice: 16.024,
  },
  "e96sv5": {
    linuxPrice: 8.362,
    windowsPrice: 12.778,
  },
  "e96sv6": {
    linuxPrice: 8.78,
    windowsPrice: 13.196,
  },
  "e96v5": {
    linuxPrice: 8.362,
    windowsPrice: 12.778,
  },
  "ec16adsv6": {
    linuxPrice: 1.619,
    windowsPrice: 2.355,
  },
  "ec16asv6": {
    linuxPrice: 1.331,
    windowsPrice: 2.067,
  },
  "ec2adsv6": {
    linuxPrice: 0.202,
    windowsPrice: 0.294,
  },
  "ec2asv6": {
    linuxPrice: 0.166,
    windowsPrice: 0.258,
  },
  "ec32adsv6": {
    linuxPrice: 3.238,
    windowsPrice: 4.71,
  },
  "ec32asv6": {
    linuxPrice: 2.662,
    windowsPrice: 4.134,
  },
  "ec48adsv6": {
    linuxPrice: 4.858,
    windowsPrice: 7.066,
  },
  "ec48asv6": {
    linuxPrice: 3.994,
    windowsPrice: 6.202,
  },
  "ec4adsv6": {
    linuxPrice: 0.405,
    windowsPrice: 0.589,
  },
  "ec4asv6": {
    linuxPrice: 0.333,
    windowsPrice: 0.517,
  },
  "ec64adsv6": {
    linuxPrice: 6.477,
    windowsPrice: 9.421,
  },
  "ec64asv6": {
    linuxPrice: 5.325,
    windowsPrice: 8.269,
  },
  "ec8adsv6": {
    linuxPrice: 0.81,
    windowsPrice: 1.178,
  },
  "ec8asv6": {
    linuxPrice: 0.666,
    windowsPrice: 1.034,
  },
  "ec96adsv6": {
    linuxPrice: 9.715,
    windowsPrice: 14.131,
  },
  "ec96asv6": {
    linuxPrice: 7.987,
    windowsPrice: 12.403,
  },
  "f1": {
    linuxPrice: 0.0739,
    windowsPrice: 0.12,
  },
  "f16": {
    linuxPrice: 1.182,
    windowsPrice: 1.918,
  },
  "f16alsv6": {
    linuxPrice: 1.35,
    windowsPrice: 2.086,
  },
  "f16amsv6": {
    linuxPrice: 1.997,
    windowsPrice: 2.733,
  },
  "f16asv6": {
    linuxPrice: 1.525,
    windowsPrice: 2.261,
  },
  "f16s": {
    linuxPrice: 1.182,
    windowsPrice: 1.918,
  },
  "f16sv2": {
    linuxPrice: 0.952,
    windowsPrice: 1.688,
  },
  "f1s": {
    linuxPrice: 0.0739,
    windowsPrice: 0.12,
  },
  "f2": {
    linuxPrice: 0.148,
    windowsPrice: 0.24,
  },
  "f2alsv6": {
    linuxPrice: 0.169,
    windowsPrice: 0.261,
  },
  "f2amsv6": {
    linuxPrice: 0.25,
    windowsPrice: 0.342,
  },
  "f2asv6": {
    linuxPrice: 0.191,
    windowsPrice: 0.283,
  },
  "f2s": {
    linuxPrice: 0.148,
    windowsPrice: 0.24,
  },
  "f2sv2": {
    linuxPrice: 0.119,
    windowsPrice: 0.211,
  },
  "f32alsv6": {
    linuxPrice: 2.701,
    windowsPrice: 4.173,
  },
  "f32amsv6": {
    linuxPrice: 3.994,
    windowsPrice: 5.466,
  },
  "f32asv6": {
    linuxPrice: 3.05,
    windowsPrice: 4.522,
  },
  "f32sv2": {
    linuxPrice: 1.904,
    windowsPrice: 3.376,
  },
  "f4": {
    linuxPrice: 0.295,
    windowsPrice: 0.479,
  },
  "f48alsv6": {
    linuxPrice: 4.051,
    windowsPrice: 6.259,
  },
  "f48amsv6": {
    linuxPrice: 5.99,
    windowsPrice: 8.198,
  },
  "f48asv6": {
    linuxPrice: 4.574,
    windowsPrice: 6.782,
  },
  "f48sv2": {
    linuxPrice: 2.856,
    windowsPrice: 5.064,
  },
  "f4alsv6": {
    linuxPrice: 0.338,
    windowsPrice: 0.522,
  },
  "f4amsv6": {
    linuxPrice: 0.499,
    windowsPrice: 0.683,
  },
  "f4asv6": {
    linuxPrice: 0.381,
    windowsPrice: 0.565,
  },
  "f4s": {
    linuxPrice: 0.295,
    windowsPrice: 0.479,
  },
  "f4sv2": {
    linuxPrice: 0.238,
    windowsPrice: 0.422,
  },
  "f64alsv6": {
    linuxPrice: 5.402,
    windowsPrice: 8.346,
  },
  "f64amsv6": {
    linuxPrice: 7.987,
    windowsPrice: 10.931,
  },
  "f64asv6": {
    linuxPrice: 6.099,
    windowsPrice: 9.043,
  },
  "f64sv2": {
    linuxPrice: 3.808,
    windowsPrice: 6.752,
  },
  "f72sv2": {
    linuxPrice: 4.284,
    windowsPrice: 7.596,
  },
  "f8": {
    linuxPrice: 0.591,
    windowsPrice: 0.959,
  },
  "f8alsv6": {
    linuxPrice: 0.675,
    windowsPrice: 1.043,
  },
  "f8amsv6": {
    linuxPrice: 0.998,
    windowsPrice: 1.366,
  },
  "f8asv6": {
    linuxPrice: 0.762,
    windowsPrice: 1.13,
  },
  "f8s": {
    linuxPrice: 0.591,
    windowsPrice: 0.959,
  },
  "f8sv2": {
    linuxPrice: 0.476,
    windowsPrice: 0.844,
  },
  "l16asv3": {
    linuxPrice: 1.695,
    windowsPrice: 2.431,
  },
  "l16sv3": {
    linuxPrice: 1.893,
    windowsPrice: 2.629,
  },
  "l32asv3": {
    linuxPrice: 3.39,
    windowsPrice: 4.862,
  },
  "l32sv3": {
    linuxPrice: 3.786,
    windowsPrice: 5.258,
  },
  "l48asv3": {
    linuxPrice: 5.086,
    windowsPrice: 7.294,
  },
  "l48sv3": {
    linuxPrice: 5.678,
    windowsPrice: 7.886,
  },
  "l64asv3": {
    linuxPrice: 6.781,
    windowsPrice: 9.725,
  },
  "l64sv3": {
    linuxPrice: 7.571,
    windowsPrice: 10.515,
  },
  "l80asv3": {
    linuxPrice: 8.476,
    windowsPrice: 12.156,
  },
  "l80sv3": {
    linuxPrice: 9.464,
    windowsPrice: 13.144,
  },
  "l8asv3": {
    linuxPrice: 0.848,
    windowsPrice: 1.216,
  },
  "l8sv3": {
    linuxPrice: 0.946,
    windowsPrice: 1.314,
  },
};
