// AWS instance prices for region key: us_gov_east_1 (updated 2026-08-30)
// Auto-generated by tools/split-data.js — do not edit by hand
// Specs for these types live in js/aws/aws-data.js as AWS_SPECS.compute
window.us_gov_east_1 = {
  "c5.12xlarge": {
    onDemandLinuxHr: 2.448,
    onDemandWindowsHr: 2.448,
  },
  "c5.18xlarge": {
    onDemandLinuxHr: 3.672,
    onDemandWindowsHr: 3.672,
  },
  "c5.24xlarge": {
    onDemandLinuxHr: 4.896,
    onDemandWindowsHr: 9.312,
  },
  "c5.2xlarge": {
    onDemandLinuxHr: 0.408,
    onDemandWindowsHr: 0.776,
  },
  "c5.4xlarge": {
    onDemandLinuxHr: 0.816,
    onDemandWindowsHr: 1.552,
  },
  "c5.9xlarge": {
    onDemandLinuxHr: 1.836,
    onDemandWindowsHr: 1.836,
  },
  "c5.large": {
    onDemandLinuxHr: 0.102,
    onDemandWindowsHr: 0.102,
  },
  "c5.metal": {
    onDemandLinuxHr: 4.896,
    onDemandWindowsHr: 9.312,
  },
  "c5.xlarge": {
    onDemandLinuxHr: 0.204,
    onDemandWindowsHr: 0.204,
  },
  "c5a.12xlarge": {
    onDemandLinuxHr: 2.208,
    onDemandWindowsHr: 4.416,
  },
  "c5a.16xlarge": {
    onDemandLinuxHr: 2.944,
    onDemandWindowsHr: 5.888,
  },
  "c5a.24xlarge": {
    onDemandLinuxHr: 4.416,
    onDemandWindowsHr: 4.416,
  },
  "c5a.2xlarge": {
    onDemandLinuxHr: 0.368,
    onDemandWindowsHr: 0.368,
  },
  "c5a.4xlarge": {
    onDemandLinuxHr: 0.736,
    onDemandWindowsHr: 1.472,
  },
  "c5a.8xlarge": {
    onDemandLinuxHr: 1.472,
    onDemandWindowsHr: 2.944,
  },
  "c5a.large": {
    onDemandLinuxHr: 0.092,
    onDemandWindowsHr: 0.184,
  },
  "c5a.xlarge": {
    onDemandLinuxHr: 0.184,
    onDemandWindowsHr: 0.368,
  },
  "c5d.18xlarge": {
    onDemandLinuxHr: 4.176,
    onDemandWindowsHr: 4.176,
  },
  "c5d.2xlarge": {
    onDemandLinuxHr: 0.464,
    onDemandWindowsHr: 0.832,
  },
  "c5d.4xlarge": {
    onDemandLinuxHr: 0.928,
    onDemandWindowsHr: 0.928,
  },
  "c5d.9xlarge": {
    onDemandLinuxHr: 2.088,
    onDemandWindowsHr: 3.744,
  },
  "c5d.large": {
    onDemandLinuxHr: 0.116,
    onDemandWindowsHr: 0.208,
  },
  "c5d.xlarge": {
    onDemandLinuxHr: 0.232,
    onDemandWindowsHr: 0.416,
  },
  "c5n.18xlarge": {
    onDemandLinuxHr: 4.68,
    onDemandWindowsHr: 4.68,
  },
  "c5n.2xlarge": {
    onDemandLinuxHr: 0.52,
    onDemandWindowsHr: 0.888,
  },
  "c5n.4xlarge": {
    onDemandLinuxHr: 1.04,
    onDemandWindowsHr: 1.776,
  },
  "c5n.9xlarge": {
    onDemandLinuxHr: 2.34,
    onDemandWindowsHr: 3.996,
  },
  "c5n.large": {
    onDemandLinuxHr: 0.13,
    onDemandWindowsHr: 0.222,
  },
  "c5n.metal": {
    onDemandLinuxHr: 4.68,
    onDemandWindowsHr: 7.992,
  },
  "c5n.xlarge": {
    onDemandLinuxHr: 0.26,
    onDemandWindowsHr: 0.26,
  },
  "c6g.12xlarge": {
    onDemandLinuxHr: 1.9584,
    onDemandWindowsHr: 0,
  },
  "c6g.16xlarge": {
    onDemandLinuxHr: 2.6112,
    onDemandWindowsHr: 0,
  },
  "c6g.2xlarge": {
    onDemandLinuxHr: 0.3264,
    onDemandWindowsHr: 0,
  },
  "c6g.4xlarge": {
    onDemandLinuxHr: 0.6528,
    onDemandWindowsHr: 0,
  },
  "c6g.8xlarge": {
    onDemandLinuxHr: 1.3056,
    onDemandWindowsHr: 0,
  },
  "c6g.large": {
    onDemandLinuxHr: 0.0816,
    onDemandWindowsHr: 0,
  },
  "c6g.medium": {
    onDemandLinuxHr: 0.0408,
    onDemandWindowsHr: 0,
  },
  "c6g.metal": {
    onDemandLinuxHr: 2.6112,
    onDemandWindowsHr: 0,
  },
  "c6g.xlarge": {
    onDemandLinuxHr: 0.1632,
    onDemandWindowsHr: 0,
  },
  "c6gd.12xlarge": {
    onDemandLinuxHr: 2.2272,
    onDemandWindowsHr: 0,
  },
  "c6gd.16xlarge": {
    onDemandLinuxHr: 2.9696,
    onDemandWindowsHr: 0,
  },
  "c6gd.2xlarge": {
    onDemandLinuxHr: 0.3712,
    onDemandWindowsHr: 0,
  },
  "c6gd.4xlarge": {
    onDemandLinuxHr: 0.7424,
    onDemandWindowsHr: 0,
  },
  "c6gd.8xlarge": {
    onDemandLinuxHr: 1.4848,
    onDemandWindowsHr: 0,
  },
  "c6gd.large": {
    onDemandLinuxHr: 0.0928,
    onDemandWindowsHr: 0,
  },
  "c6gd.medium": {
    onDemandLinuxHr: 0.0464,
    onDemandWindowsHr: 0,
  },
  "c6gd.metal": {
    onDemandLinuxHr: 2.9696,
    onDemandWindowsHr: 0,
  },
  "c6gd.xlarge": {
    onDemandLinuxHr: 0.1856,
    onDemandWindowsHr: 0,
  },
  "c6gn.12xlarge": {
    onDemandLinuxHr: 2.496,
    onDemandWindowsHr: 0,
  },
  "c6gn.16xlarge": {
    onDemandLinuxHr: 3.328,
    onDemandWindowsHr: 0,
  },
  "c6gn.2xlarge": {
    onDemandLinuxHr: 0.416,
    onDemandWindowsHr: 0,
  },
  "c6gn.4xlarge": {
    onDemandLinuxHr: 0.832,
    onDemandWindowsHr: 0,
  },
  "c6gn.8xlarge": {
    onDemandLinuxHr: 1.664,
    onDemandWindowsHr: 0,
  },
  "c6gn.large": {
    onDemandLinuxHr: 0.104,
    onDemandWindowsHr: 0,
  },
  "c6gn.medium": {
    onDemandLinuxHr: 0.052,
    onDemandWindowsHr: 0,
  },
  "c6gn.xlarge": {
    onDemandLinuxHr: 0.208,
    onDemandWindowsHr: 0,
  },
  "c6i.12xlarge": {
    onDemandLinuxHr: 2.448,
    onDemandWindowsHr: 2.448,
  },
  "c6i.16xlarge": {
    onDemandLinuxHr: 3.264,
    onDemandWindowsHr: 3.264,
  },
  "c6i.24xlarge": {
    onDemandLinuxHr: 4.896,
    onDemandWindowsHr: 4.896,
  },
  "c6i.2xlarge": {
    onDemandLinuxHr: 0.408,
    onDemandWindowsHr: 0.776,
  },
  "c6i.32xlarge": {
    onDemandLinuxHr: 6.528,
    onDemandWindowsHr: 6.528,
  },
  "c6i.4xlarge": {
    onDemandLinuxHr: 0.816,
    onDemandWindowsHr: 0.816,
  },
  "c6i.8xlarge": {
    onDemandLinuxHr: 1.632,
    onDemandWindowsHr: 3.104,
  },
  "c6i.large": {
    onDemandLinuxHr: 0.102,
    onDemandWindowsHr: 0.102,
  },
  "c6i.metal": {
    onDemandLinuxHr: 6.528,
    onDemandWindowsHr: 12.416,
  },
  "c6i.xlarge": {
    onDemandLinuxHr: 0.204,
    onDemandWindowsHr: 0.204,
  },
  "c6in.12xlarge": {
    onDemandLinuxHr: 3.276,
    onDemandWindowsHr: 3.276,
  },
  "c6in.16xlarge": {
    onDemandLinuxHr: 4.368,
    onDemandWindowsHr: 7.312,
  },
  "c6in.24xlarge": {
    onDemandLinuxHr: 6.552,
    onDemandWindowsHr: 6.552,
  },
  "c6in.2xlarge": {
    onDemandLinuxHr: 0.546,
    onDemandWindowsHr: 0.914,
  },
  "c6in.32xlarge": {
    onDemandLinuxHr: 8.736,
    onDemandWindowsHr: 8.736,
  },
  "c6in.4xlarge": {
    onDemandLinuxHr: 1.092,
    onDemandWindowsHr: 1.092,
  },
  "c6in.8xlarge": {
    onDemandLinuxHr: 2.184,
    onDemandWindowsHr: 2.184,
  },
  "c6in.large": {
    onDemandLinuxHr: 0.1365,
    onDemandWindowsHr: 0.2285,
  },
  "c6in.metal": {
    onDemandLinuxHr: 8.736,
    onDemandWindowsHr: 14.624,
  },
  "c6in.xlarge": {
    onDemandLinuxHr: 0.273,
    onDemandWindowsHr: 0.457,
  },
  "c7g.12xlarge": {
    onDemandLinuxHr: 2.0808,
    onDemandWindowsHr: 0,
  },
  "c7g.16xlarge": {
    onDemandLinuxHr: 2.7744,
    onDemandWindowsHr: 0,
  },
  "c7g.2xlarge": {
    onDemandLinuxHr: 0.3468,
    onDemandWindowsHr: 0,
  },
  "c7g.4xlarge": {
    onDemandLinuxHr: 0.6936,
    onDemandWindowsHr: 0,
  },
  "c7g.8xlarge": {
    onDemandLinuxHr: 1.3872,
    onDemandWindowsHr: 0,
  },
  "c7g.large": {
    onDemandLinuxHr: 0.0867,
    onDemandWindowsHr: 0,
  },
  "c7g.medium": {
    onDemandLinuxHr: 0.0434,
    onDemandWindowsHr: 0,
  },
  "c7g.metal": {
    onDemandLinuxHr: 2.7744,
    onDemandWindowsHr: 0,
  },
  "c7g.xlarge": {
    onDemandLinuxHr: 0.1734,
    onDemandWindowsHr: 0,
  },
  "c7gd.12xlarge": {
    onDemandLinuxHr: 2.6309,
    onDemandWindowsHr: 0,
  },
  "c7gd.16xlarge": {
    onDemandLinuxHr: 3.5078,
    onDemandWindowsHr: 0,
  },
  "c7gd.2xlarge": {
    onDemandLinuxHr: 0.4385,
    onDemandWindowsHr: 0,
  },
  "c7gd.4xlarge": {
    onDemandLinuxHr: 0.877,
    onDemandWindowsHr: 0,
  },
  "c7gd.8xlarge": {
    onDemandLinuxHr: 1.7539,
    onDemandWindowsHr: 0,
  },
  "c7gd.large": {
    onDemandLinuxHr: 0.1096,
    onDemandWindowsHr: 0,
  },
  "c7gd.medium": {
    onDemandLinuxHr: 0.0548,
    onDemandWindowsHr: 0,
  },
  "c7gd.metal": {
    onDemandLinuxHr: 3.5078,
    onDemandWindowsHr: 0,
  },
  "c7gd.xlarge": {
    onDemandLinuxHr: 0.2192,
    onDemandWindowsHr: 0,
  },
  "c7i.12xlarge": {
    onDemandLinuxHr: 2.5704,
    onDemandWindowsHr: 4.7784,
  },
  "c7i.16xlarge": {
    onDemandLinuxHr: 3.4272,
    onDemandWindowsHr: 3.4272,
  },
  "c7i.24xlarge": {
    onDemandLinuxHr: 5.1408,
    onDemandWindowsHr: 5.1408,
  },
  "c7i.2xlarge": {
    onDemandLinuxHr: 0.4284,
    onDemandWindowsHr: 0.4284,
  },
  "c7i.48xlarge": {
    onDemandLinuxHr: 10.2816,
    onDemandWindowsHr: 10.2816,
  },
  "c7i.4xlarge": {
    onDemandLinuxHr: 0.8568,
    onDemandWindowsHr: 1.5928,
  },
  "c7i.8xlarge": {
    onDemandLinuxHr: 1.7136,
    onDemandWindowsHr: 1.7136,
  },
  "c7i.large": {
    onDemandLinuxHr: 0.1071,
    onDemandWindowsHr: 0.1071,
  },
  "c7i.metal-24xl": {
    onDemandLinuxHr: 5.1408,
    onDemandWindowsHr: 9.5568,
  },
  "c7i.metal-48xl": {
    onDemandLinuxHr: 10.2816,
    onDemandWindowsHr: 19.1136,
  },
  "c7i.xlarge": {
    onDemandLinuxHr: 0.2142,
    onDemandWindowsHr: 0.2142,
  },
  "c8g.12xlarge": {
    onDemandLinuxHr: 2.28912,
    onDemandWindowsHr: 0,
  },
  "c8g.16xlarge": {
    onDemandLinuxHr: 3.05216,
    onDemandWindowsHr: 0,
  },
  "c8g.24xlarge": {
    onDemandLinuxHr: 4.57824,
    onDemandWindowsHr: 0,
  },
  "c8g.2xlarge": {
    onDemandLinuxHr: 0.38152,
    onDemandWindowsHr: 0,
  },
  "c8g.48xlarge": {
    onDemandLinuxHr: 9.15648,
    onDemandWindowsHr: 0,
  },
  "c8g.4xlarge": {
    onDemandLinuxHr: 0.76304,
    onDemandWindowsHr: 0,
  },
  "c8g.8xlarge": {
    onDemandLinuxHr: 1.52608,
    onDemandWindowsHr: 0,
  },
  "c8g.large": {
    onDemandLinuxHr: 0.09538,
    onDemandWindowsHr: 0,
  },
  "c8g.medium": {
    onDemandLinuxHr: 0.04769,
    onDemandWindowsHr: 0,
  },
  "c8g.metal-24xl": {
    onDemandLinuxHr: 4.57824,
    onDemandWindowsHr: 0,
  },
  "c8g.metal-48xl": {
    onDemandLinuxHr: 9.15648,
    onDemandWindowsHr: 0,
  },
  "c8g.xlarge": {
    onDemandLinuxHr: 0.19076,
    onDemandWindowsHr: 0,
  },
  "c8gn.12xlarge": {
    onDemandLinuxHr: 3.4234,
    onDemandWindowsHr: 0,
  },
  "c8gn.16xlarge": {
    onDemandLinuxHr: 4.5645,
    onDemandWindowsHr: 0,
  },
  "c8gn.24xlarge": {
    onDemandLinuxHr: 6.8467,
    onDemandWindowsHr: 0,
  },
  "c8gn.2xlarge": {
    onDemandLinuxHr: 0.5706,
    onDemandWindowsHr: 0,
  },
  "c8gn.4xlarge": {
    onDemandLinuxHr: 1.1411,
    onDemandWindowsHr: 0,
  },
  "c8gn.8xlarge": {
    onDemandLinuxHr: 2.2822,
    onDemandWindowsHr: 0,
  },
  "c8gn.large": {
    onDemandLinuxHr: 0.1426,
    onDemandWindowsHr: 0,
  },
  "c8gn.medium": {
    onDemandLinuxHr: 0.0713,
    onDemandWindowsHr: 0,
  },
  "c8gn.xlarge": {
    onDemandLinuxHr: 0.2853,
    onDemandWindowsHr: 0,
  },
  "d2.2xlarge": {
    onDemandLinuxHr: 1.656,
    onDemandWindowsHr: 1.656,
  },
  "d2.4xlarge": {
    onDemandLinuxHr: 3.312,
    onDemandWindowsHr: 4.048,
  },
  "d2.8xlarge": {
    onDemandLinuxHr: 6.624,
    onDemandWindowsHr: 6.624,
  },
  "d2.xlarge": {
    onDemandLinuxHr: 0.828,
    onDemandWindowsHr: 1.012,
  },
  "g4dn.12xlarge": {
    onDemandLinuxHr: 4.931,
    onDemandWindowsHr: 7.139,
  },
  "g4dn.16xlarge": {
    onDemandLinuxHr: 5.486,
    onDemandWindowsHr: 5.486,
  },
  "g4dn.2xlarge": {
    onDemandLinuxHr: 0.948,
    onDemandWindowsHr: 1.316,
  },
  "g4dn.4xlarge": {
    onDemandLinuxHr: 1.518,
    onDemandWindowsHr: 1.518,
  },
  "g4dn.8xlarge": {
    onDemandLinuxHr: 2.743,
    onDemandWindowsHr: 2.743,
  },
  "g4dn.xlarge": {
    onDemandLinuxHr: 0.663,
    onDemandWindowsHr: 0.847,
  },
  "g6.12xlarge": {
    onDemandLinuxHr: 5.80003,
    onDemandWindowsHr: 5.80003,
  },
  "g6.16xlarge": {
    onDemandLinuxHr: 4.28145,
    onDemandWindowsHr: 7.22545,
  },
  "g6.24xlarge": {
    onDemandLinuxHr: 8.41367,
    onDemandWindowsHr: 12.82967,
  },
  "g6.2xlarge": {
    onDemandLinuxHr: 1.2322,
    onDemandWindowsHr: 1.6002,
  },
  "g6.48xlarge": {
    onDemandLinuxHr: 16.82734,
    onDemandWindowsHr: 25.65934,
  },
  "g6.4xlarge": {
    onDemandLinuxHr: 1.66781,
    onDemandWindowsHr: 1.66781,
  },
  "g6.8xlarge": {
    onDemandLinuxHr: 2.53903,
    onDemandWindowsHr: 4.01103,
  },
  "g6.xlarge": {
    onDemandLinuxHr: 1.0144,
    onDemandWindowsHr: 1.0144,
  },
  "gr6.4xlarge": {
    onDemandLinuxHr: 1.9401,
    onDemandWindowsHr: 2.6761,
  },
  "gr6.8xlarge": {
    onDemandLinuxHr: 3.08359,
    onDemandWindowsHr: 3.08359,
  },
  "hpc6a.48xlarge": {
    onDemandLinuxHr: 3.467,
    onDemandWindowsHr: 7.883,
  },
  "i3.16xlarge": {
    onDemandLinuxHr: 6.016,
    onDemandWindowsHr: 8.96,
  },
  "i3.2xlarge": {
    onDemandLinuxHr: 0.752,
    onDemandWindowsHr: 0.752,
  },
  "i3.4xlarge": {
    onDemandLinuxHr: 1.504,
    onDemandWindowsHr: 2.24,
  },
  "i3.8xlarge": {
    onDemandLinuxHr: 3.008,
    onDemandWindowsHr: 3.008,
  },
  "i3.large": {
    onDemandLinuxHr: 0.188,
    onDemandWindowsHr: 0.28,
  },
  "i3.metal": {
    onDemandLinuxHr: 6.016,
    onDemandWindowsHr: 8.96,
  },
  "i3.xlarge": {
    onDemandLinuxHr: 0.376,
    onDemandWindowsHr: 0.376,
  },
  "i3en.12xlarge": {
    onDemandLinuxHr: 6.552,
    onDemandWindowsHr: 8.76,
  },
  "i3en.24xlarge": {
    onDemandLinuxHr: 13.104,
    onDemandWindowsHr: 17.52,
  },
  "i3en.2xlarge": {
    onDemandLinuxHr: 1.092,
    onDemandWindowsHr: 1.092,
  },
  "i3en.3xlarge": {
    onDemandLinuxHr: 1.638,
    onDemandWindowsHr: 1.638,
  },
  "i3en.6xlarge": {
    onDemandLinuxHr: 3.276,
    onDemandWindowsHr: 3.276,
  },
  "i3en.large": {
    onDemandLinuxHr: 0.273,
    onDemandWindowsHr: 0.273,
  },
  "i3en.metal": {
    onDemandLinuxHr: 13.104,
    onDemandWindowsHr: 17.52,
  },
  "i3en.xlarge": {
    onDemandLinuxHr: 0.546,
    onDemandWindowsHr: 0.546,
  },
  "i4i.12xlarge": {
    onDemandLinuxHr: 4.963,
    onDemandWindowsHr: 4.963,
  },
  "i4i.16xlarge": {
    onDemandLinuxHr: 6.618,
    onDemandWindowsHr: 6.618,
  },
  "i4i.24xlarge": {
    onDemandLinuxHr: 9.9264,
    onDemandWindowsHr: 9.9264,
  },
  "i4i.2xlarge": {
    onDemandLinuxHr: 0.827,
    onDemandWindowsHr: 0.827,
  },
  "i4i.32xlarge": {
    onDemandLinuxHr: 13.2352,
    onDemandWindowsHr: 19.1232,
  },
  "i4i.4xlarge": {
    onDemandLinuxHr: 1.654,
    onDemandWindowsHr: 2.39,
  },
  "i4i.8xlarge": {
    onDemandLinuxHr: 3.309,
    onDemandWindowsHr: 4.781,
  },
  "i4i.large": {
    onDemandLinuxHr: 0.207,
    onDemandWindowsHr: 0.299,
  },
  "i4i.metal": {
    onDemandLinuxHr: 13.235,
    onDemandWindowsHr: 19.123,
  },
  "i4i.xlarge": {
    onDemandLinuxHr: 0.414,
    onDemandWindowsHr: 0.414,
  },
  "i7i.12xlarge": {
    onDemandLinuxHr: 5.4595,
    onDemandWindowsHr: 7.6675,
  },
  "i7i.16xlarge": {
    onDemandLinuxHr: 7.2794,
    onDemandWindowsHr: 10.2234,
  },
  "i7i.24xlarge": {
    onDemandLinuxHr: 10.919,
    onDemandWindowsHr: 15.335,
  },
  "i7i.2xlarge": {
    onDemandLinuxHr: 0.9099,
    onDemandWindowsHr: 1.2779,
  },
  "i7i.48xlarge": {
    onDemandLinuxHr: 21.8381,
    onDemandWindowsHr: 30.6701,
  },
  "i7i.4xlarge": {
    onDemandLinuxHr: 1.8198,
    onDemandWindowsHr: 2.5558,
  },
  "i7i.8xlarge": {
    onDemandLinuxHr: 3.6397,
    onDemandWindowsHr: 5.1117,
  },
  "i7i.large": {
    onDemandLinuxHr: 0.2275,
    onDemandWindowsHr: 0.3195,
  },
  "i7i.metal-24xl": {
    onDemandLinuxHr: 10.919,
    onDemandWindowsHr: 15.335,
  },
  "i7i.metal-48xl": {
    onDemandLinuxHr: 21.8381,
    onDemandWindowsHr: 30.6701,
  },
  "i7i.xlarge": {
    onDemandLinuxHr: 0.455,
    onDemandWindowsHr: 0.639,
  },
  "i7ie.12xlarge": {
    onDemandLinuxHr: 7.5348,
    onDemandWindowsHr: 9.7428,
  },
  "i7ie.18xlarge": {
    onDemandLinuxHr: 11.3022,
    onDemandWindowsHr: 11.3022,
  },
  "i7ie.24xlarge": {
    onDemandLinuxHr: 15.0696,
    onDemandWindowsHr: 15.0696,
  },
  "i7ie.2xlarge": {
    onDemandLinuxHr: 1.2558,
    onDemandWindowsHr: 1.6238,
  },
  "i7ie.3xlarge": {
    onDemandLinuxHr: 1.8837,
    onDemandWindowsHr: 2.4357,
  },
  "i7ie.48xlarge": {
    onDemandLinuxHr: 30.1392,
    onDemandWindowsHr: 30.1392,
  },
  "i7ie.6xlarge": {
    onDemandLinuxHr: 3.7674,
    onDemandWindowsHr: 3.7674,
  },
  "i7ie.large": {
    onDemandLinuxHr: 0.314,
    onDemandWindowsHr: 0.314,
  },
  "i7ie.metal-24xl": {
    onDemandLinuxHr: 15.0696,
    onDemandWindowsHr: 19.4856,
  },
  "i7ie.metal-48xl": {
    onDemandLinuxHr: 30.1392,
    onDemandWindowsHr: 38.9712,
  },
  "i7ie.xlarge": {
    onDemandLinuxHr: 0.6279,
    onDemandWindowsHr: 0.8119,
  },
  "i8g.12xlarge": {
    onDemandLinuxHr: 4.9632,
    onDemandWindowsHr: 0,
  },
  "i8g.16xlarge": {
    onDemandLinuxHr: 6.6176,
    onDemandWindowsHr: 0,
  },
  "i8g.24xlarge": {
    onDemandLinuxHr: 9.9264,
    onDemandWindowsHr: 0,
  },
  "i8g.2xlarge": {
    onDemandLinuxHr: 0.8272,
    onDemandWindowsHr: 0,
  },
  "i8g.48xlarge": {
    onDemandLinuxHr: 19.8528,
    onDemandWindowsHr: 0,
  },
  "i8g.4xlarge": {
    onDemandLinuxHr: 1.6544,
    onDemandWindowsHr: 0,
  },
  "i8g.8xlarge": {
    onDemandLinuxHr: 3.3088,
    onDemandWindowsHr: 0,
  },
  "i8g.large": {
    onDemandLinuxHr: 0.2068,
    onDemandWindowsHr: 0,
  },
  "i8g.metal-24xl": {
    onDemandLinuxHr: 9.9264,
    onDemandWindowsHr: 0,
  },
  "i8g.metal-48xl": {
    onDemandLinuxHr: 19.8528,
    onDemandWindowsHr: 0,
  },
  "i8g.xlarge": {
    onDemandLinuxHr: 0.4136,
    onDemandWindowsHr: 0,
  },
  "i8ge.12xlarge": {
    onDemandLinuxHr: 6.8796,
    onDemandWindowsHr: 0,
  },
  "i8ge.18xlarge": {
    onDemandLinuxHr: 10.3194,
    onDemandWindowsHr: 0,
  },
  "i8ge.24xlarge": {
    onDemandLinuxHr: 13.7592,
    onDemandWindowsHr: 0,
  },
  "i8ge.2xlarge": {
    onDemandLinuxHr: 1.1466,
    onDemandWindowsHr: 0,
  },
  "i8ge.3xlarge": {
    onDemandLinuxHr: 1.7199,
    onDemandWindowsHr: 0,
  },
  "i8ge.48xlarge": {
    onDemandLinuxHr: 27.5184,
    onDemandWindowsHr: 0,
  },
  "i8ge.6xlarge": {
    onDemandLinuxHr: 3.4398,
    onDemandWindowsHr: 0,
  },
  "i8ge.large": {
    onDemandLinuxHr: 0.2867,
    onDemandWindowsHr: 0,
  },
  "i8ge.metal-24xl": {
    onDemandLinuxHr: 13.7592,
    onDemandWindowsHr: 0,
  },
  "i8ge.metal-48xl": {
    onDemandLinuxHr: 27.5184,
    onDemandWindowsHr: 0,
  },
  "i8ge.xlarge": {
    onDemandLinuxHr: 0.5733,
    onDemandWindowsHr: 0,
  },
  "inf1.24xlarge": {
    onDemandLinuxHr: 5.953,
    onDemandWindowsHr: 0,
  },
  "inf1.2xlarge": {
    onDemandLinuxHr: 0.456,
    onDemandWindowsHr: 0,
  },
  "inf1.6xlarge": {
    onDemandLinuxHr: 1.488,
    onDemandWindowsHr: 0,
  },
  "inf1.xlarge": {
    onDemandLinuxHr: 0.288,
    onDemandWindowsHr: 0,
  },
  "m5.12xlarge": {
    onDemandLinuxHr: 2.904,
    onDemandWindowsHr: 5.112,
  },
  "m5.16xlarge": {
    onDemandLinuxHr: 3.872,
    onDemandWindowsHr: 6.816,
  },
  "m5.24xlarge": {
    onDemandLinuxHr: 5.808,
    onDemandWindowsHr: 5.808,
  },
  "m5.2xlarge": {
    onDemandLinuxHr: 0.484,
    onDemandWindowsHr: 0.852,
  },
  "m5.4xlarge": {
    onDemandLinuxHr: 0.968,
    onDemandWindowsHr: 1.704,
  },
  "m5.8xlarge": {
    onDemandLinuxHr: 1.936,
    onDemandWindowsHr: 3.408,
  },
  "m5.large": {
    onDemandLinuxHr: 0.121,
    onDemandWindowsHr: 0.213,
  },
  "m5.metal": {
    onDemandLinuxHr: 5.808,
    onDemandWindowsHr: 10.224,
  },
  "m5.xlarge": {
    onDemandLinuxHr: 0.242,
    onDemandWindowsHr: 0.242,
  },
  "m5a.12xlarge": {
    onDemandLinuxHr: 2.616,
    onDemandWindowsHr: 4.824,
  },
  "m5a.16xlarge": {
    onDemandLinuxHr: 3.488,
    onDemandWindowsHr: 3.488,
  },
  "m5a.24xlarge": {
    onDemandLinuxHr: 5.232,
    onDemandWindowsHr: 5.232,
  },
  "m5a.2xlarge": {
    onDemandLinuxHr: 0.436,
    onDemandWindowsHr: 0.436,
  },
  "m5a.4xlarge": {
    onDemandLinuxHr: 0.872,
    onDemandWindowsHr: 1.608,
  },
  "m5a.8xlarge": {
    onDemandLinuxHr: 1.744,
    onDemandWindowsHr: 1.744,
  },
  "m5a.large": {
    onDemandLinuxHr: 0.109,
    onDemandWindowsHr: 0.201,
  },
  "m5a.xlarge": {
    onDemandLinuxHr: 0.218,
    onDemandWindowsHr: 0.402,
  },
  "m5d.12xlarge": {
    onDemandLinuxHr: 3.432,
    onDemandWindowsHr: 5.64,
  },
  "m5d.16xlarge": {
    onDemandLinuxHr: 4.576,
    onDemandWindowsHr: 7.52,
  },
  "m5d.24xlarge": {
    onDemandLinuxHr: 6.864,
    onDemandWindowsHr: 11.28,
  },
  "m5d.2xlarge": {
    onDemandLinuxHr: 0.572,
    onDemandWindowsHr: 0.94,
  },
  "m5d.4xlarge": {
    onDemandLinuxHr: 1.144,
    onDemandWindowsHr: 1.88,
  },
  "m5d.8xlarge": {
    onDemandLinuxHr: 2.288,
    onDemandWindowsHr: 2.288,
  },
  "m5d.large": {
    onDemandLinuxHr: 0.143,
    onDemandWindowsHr: 0.143,
  },
  "m5d.metal": {
    onDemandLinuxHr: 6.864,
    onDemandWindowsHr: 11.28,
  },
  "m5d.xlarge": {
    onDemandLinuxHr: 0.286,
    onDemandWindowsHr: 0.47,
  },
  "m5dn.12xlarge": {
    onDemandLinuxHr: 4.104,
    onDemandWindowsHr: 4.104,
  },
  "m5dn.16xlarge": {
    onDemandLinuxHr: 5.472,
    onDemandWindowsHr: 8.416,
  },
  "m5dn.24xlarge": {
    onDemandLinuxHr: 8.208,
    onDemandWindowsHr: 12.624,
  },
  "m5dn.2xlarge": {
    onDemandLinuxHr: 0.684,
    onDemandWindowsHr: 0.684,
  },
  "m5dn.4xlarge": {
    onDemandLinuxHr: 1.368,
    onDemandWindowsHr: 1.368,
  },
  "m5dn.8xlarge": {
    onDemandLinuxHr: 2.736,
    onDemandWindowsHr: 4.208,
  },
  "m5dn.large": {
    onDemandLinuxHr: 0.171,
    onDemandWindowsHr: 0.263,
  },
  "m5dn.metal": {
    onDemandLinuxHr: 8.208,
    onDemandWindowsHr: 12.624,
  },
  "m5dn.xlarge": {
    onDemandLinuxHr: 0.342,
    onDemandWindowsHr: 0.342,
  },
  "m5n.12xlarge": {
    onDemandLinuxHr: 3.576,
    onDemandWindowsHr: 5.784,
  },
  "m5n.16xlarge": {
    onDemandLinuxHr: 4.768,
    onDemandWindowsHr: 4.768,
  },
  "m5n.24xlarge": {
    onDemandLinuxHr: 7.152,
    onDemandWindowsHr: 11.568,
  },
  "m5n.2xlarge": {
    onDemandLinuxHr: 0.596,
    onDemandWindowsHr: 0.596,
  },
  "m5n.4xlarge": {
    onDemandLinuxHr: 1.192,
    onDemandWindowsHr: 1.928,
  },
  "m5n.8xlarge": {
    onDemandLinuxHr: 2.384,
    onDemandWindowsHr: 2.384,
  },
  "m5n.large": {
    onDemandLinuxHr: 0.149,
    onDemandWindowsHr: 0.241,
  },
  "m5n.metal": {
    onDemandLinuxHr: 7.152,
    onDemandWindowsHr: 11.568,
  },
  "m5n.xlarge": {
    onDemandLinuxHr: 0.298,
    onDemandWindowsHr: 0.482,
  },
  "m6g.12xlarge": {
    onDemandLinuxHr: 2.3232,
    onDemandWindowsHr: 0,
  },
  "m6g.16xlarge": {
    onDemandLinuxHr: 3.0976,
    onDemandWindowsHr: 0,
  },
  "m6g.2xlarge": {
    onDemandLinuxHr: 0.3872,
    onDemandWindowsHr: 0,
  },
  "m6g.4xlarge": {
    onDemandLinuxHr: 0.7744,
    onDemandWindowsHr: 0,
  },
  "m6g.8xlarge": {
    onDemandLinuxHr: 1.5488,
    onDemandWindowsHr: 0,
  },
  "m6g.large": {
    onDemandLinuxHr: 0.0968,
    onDemandWindowsHr: 0,
  },
  "m6g.medium": {
    onDemandLinuxHr: 0.0484,
    onDemandWindowsHr: 0,
  },
  "m6g.metal": {
    onDemandLinuxHr: 3.0976,
    onDemandWindowsHr: 0,
  },
  "m6g.xlarge": {
    onDemandLinuxHr: 0.1936,
    onDemandWindowsHr: 0,
  },
  "m6gd.12xlarge": {
    onDemandLinuxHr: 2.7456,
    onDemandWindowsHr: 0,
  },
  "m6gd.16xlarge": {
    onDemandLinuxHr: 3.6608,
    onDemandWindowsHr: 0,
  },
  "m6gd.2xlarge": {
    onDemandLinuxHr: 0.4576,
    onDemandWindowsHr: 0,
  },
  "m6gd.4xlarge": {
    onDemandLinuxHr: 0.9152,
    onDemandWindowsHr: 0,
  },
  "m6gd.8xlarge": {
    onDemandLinuxHr: 1.8304,
    onDemandWindowsHr: 0,
  },
  "m6gd.large": {
    onDemandLinuxHr: 0.1144,
    onDemandWindowsHr: 0,
  },
  "m6gd.medium": {
    onDemandLinuxHr: 0.0572,
    onDemandWindowsHr: 0,
  },
  "m6gd.metal": {
    onDemandLinuxHr: 3.6608,
    onDemandWindowsHr: 0,
  },
  "m6gd.xlarge": {
    onDemandLinuxHr: 0.2288,
    onDemandWindowsHr: 0,
  },
  "m6i.12xlarge": {
    onDemandLinuxHr: 2.904,
    onDemandWindowsHr: 2.904,
  },
  "m6i.16xlarge": {
    onDemandLinuxHr: 3.872,
    onDemandWindowsHr: 6.816,
  },
  "m6i.24xlarge": {
    onDemandLinuxHr: 5.808,
    onDemandWindowsHr: 10.224,
  },
  "m6i.2xlarge": {
    onDemandLinuxHr: 0.484,
    onDemandWindowsHr: 0.852,
  },
  "m6i.32xlarge": {
    onDemandLinuxHr: 7.744,
    onDemandWindowsHr: 13.632,
  },
  "m6i.4xlarge": {
    onDemandLinuxHr: 0.968,
    onDemandWindowsHr: 1.704,
  },
  "m6i.8xlarge": {
    onDemandLinuxHr: 1.936,
    onDemandWindowsHr: 1.936,
  },
  "m6i.large": {
    onDemandLinuxHr: 0.121,
    onDemandWindowsHr: 0.213,
  },
  "m6i.metal": {
    onDemandLinuxHr: 7.744,
    onDemandWindowsHr: 13.632,
  },
  "m6i.xlarge": {
    onDemandLinuxHr: 0.242,
    onDemandWindowsHr: 0.242,
  },
  "m7g.12xlarge": {
    onDemandLinuxHr: 2.4672,
    onDemandWindowsHr: 0,
  },
  "m7g.16xlarge": {
    onDemandLinuxHr: 3.2896,
    onDemandWindowsHr: 0,
  },
  "m7g.2xlarge": {
    onDemandLinuxHr: 0.4112,
    onDemandWindowsHr: 0,
  },
  "m7g.4xlarge": {
    onDemandLinuxHr: 0.8224,
    onDemandWindowsHr: 0,
  },
  "m7g.8xlarge": {
    onDemandLinuxHr: 1.6448,
    onDemandWindowsHr: 0,
  },
  "m7g.large": {
    onDemandLinuxHr: 0.1028,
    onDemandWindowsHr: 0,
  },
  "m7g.medium": {
    onDemandLinuxHr: 0.0514,
    onDemandWindowsHr: 0,
  },
  "m7g.metal": {
    onDemandLinuxHr: 3.2896,
    onDemandWindowsHr: 0,
  },
  "m7g.xlarge": {
    onDemandLinuxHr: 0.2056,
    onDemandWindowsHr: 0,
  },
  "m7i-flex.12xlarge": {
    onDemandLinuxHr: 2.8968,
    onDemandWindowsHr: 2.8968,
  },
  "m7i-flex.16xlarge": {
    onDemandLinuxHr: 3.8624,
    onDemandWindowsHr: 3.8624,
  },
  "m7i-flex.2xlarge": {
    onDemandLinuxHr: 0.4828,
    onDemandWindowsHr: 0.8324,
  },
  "m7i-flex.4xlarge": {
    onDemandLinuxHr: 0.9656,
    onDemandWindowsHr: 0.9656,
  },
  "m7i-flex.8xlarge": {
    onDemandLinuxHr: 1.9312,
    onDemandWindowsHr: 1.9312,
  },
  "m7i-flex.large": {
    onDemandLinuxHr: 0.1207,
    onDemandWindowsHr: 0.2081,
  },
  "m7i-flex.xlarge": {
    onDemandLinuxHr: 0.2414,
    onDemandWindowsHr: 0.2414,
  },
  "m7i.12xlarge": {
    onDemandLinuxHr: 3.0492,
    onDemandWindowsHr: 3.0492,
  },
  "m7i.16xlarge": {
    onDemandLinuxHr: 4.0656,
    onDemandWindowsHr: 7.0096,
  },
  "m7i.24xlarge": {
    onDemandLinuxHr: 6.0984,
    onDemandWindowsHr: 6.0984,
  },
  "m7i.2xlarge": {
    onDemandLinuxHr: 0.5082,
    onDemandWindowsHr: 0.8762,
  },
  "m7i.48xlarge": {
    onDemandLinuxHr: 12.1968,
    onDemandWindowsHr: 21.0288,
  },
  "m7i.4xlarge": {
    onDemandLinuxHr: 1.0164,
    onDemandWindowsHr: 1.7524,
  },
  "m7i.8xlarge": {
    onDemandLinuxHr: 2.0328,
    onDemandWindowsHr: 3.5048,
  },
  "m7i.large": {
    onDemandLinuxHr: 0.12705,
    onDemandWindowsHr: 0.21905,
  },
  "m7i.metal-24xl": {
    onDemandLinuxHr: 6.0984,
    onDemandWindowsHr: 10.5144,
  },
  "m7i.metal-48xl": {
    onDemandLinuxHr: 12.1968,
    onDemandWindowsHr: 21.0288,
  },
  "m7i.xlarge": {
    onDemandLinuxHr: 0.2541,
    onDemandWindowsHr: 0.4381,
  },
  "m8g.12xlarge": {
    onDemandLinuxHr: 2.71392,
    onDemandWindowsHr: 0,
  },
  "m8g.16xlarge": {
    onDemandLinuxHr: 3.61856,
    onDemandWindowsHr: 0,
  },
  "m8g.24xlarge": {
    onDemandLinuxHr: 5.42784,
    onDemandWindowsHr: 0,
  },
  "m8g.2xlarge": {
    onDemandLinuxHr: 0.45232,
    onDemandWindowsHr: 0,
  },
  "m8g.48xlarge": {
    onDemandLinuxHr: 10.85568,
    onDemandWindowsHr: 0,
  },
  "m8g.4xlarge": {
    onDemandLinuxHr: 0.90464,
    onDemandWindowsHr: 0,
  },
  "m8g.8xlarge": {
    onDemandLinuxHr: 1.80928,
    onDemandWindowsHr: 0,
  },
  "m8g.large": {
    onDemandLinuxHr: 0.11308,
    onDemandWindowsHr: 0,
  },
  "m8g.medium": {
    onDemandLinuxHr: 0.05654,
    onDemandWindowsHr: 0,
  },
  "m8g.metal-24xl": {
    onDemandLinuxHr: 5.42784,
    onDemandWindowsHr: 0,
  },
  "m8g.metal-48xl": {
    onDemandLinuxHr: 10.85568,
    onDemandWindowsHr: 0,
  },
  "m8g.xlarge": {
    onDemandLinuxHr: 0.22616,
    onDemandWindowsHr: 0,
  },
  "m8gd.12xlarge": {
    onDemandLinuxHr: 3.504,
    onDemandWindowsHr: 0,
  },
  "m8gd.16xlarge": {
    onDemandLinuxHr: 4.672,
    onDemandWindowsHr: 0,
  },
  "m8gd.24xlarge": {
    onDemandLinuxHr: 7.008,
    onDemandWindowsHr: 0,
  },
  "m8gd.2xlarge": {
    onDemandLinuxHr: 0.584,
    onDemandWindowsHr: 0,
  },
  "m8gd.48xlarge": {
    onDemandLinuxHr: 14.016,
    onDemandWindowsHr: 0,
  },
  "m8gd.4xlarge": {
    onDemandLinuxHr: 1.168,
    onDemandWindowsHr: 0,
  },
  "m8gd.8xlarge": {
    onDemandLinuxHr: 2.336,
    onDemandWindowsHr: 0,
  },
  "m8gd.large": {
    onDemandLinuxHr: 0.146,
    onDemandWindowsHr: 0,
  },
  "m8gd.medium": {
    onDemandLinuxHr: 0.073,
    onDemandWindowsHr: 0,
  },
  "m8gd.metal-24xl": {
    onDemandLinuxHr: 7.008,
    onDemandWindowsHr: 0,
  },
  "m8gd.metal-48xl": {
    onDemandLinuxHr: 14.016,
    onDemandWindowsHr: 0,
  },
  "m8gd.xlarge": {
    onDemandLinuxHr: 0.292,
    onDemandWindowsHr: 0,
  },
  "m8i-flex.12xlarge": {
    onDemandLinuxHr: 3.04176,
    onDemandWindowsHr: 5.13936,
  },
  "m8i-flex.16xlarge": {
    onDemandLinuxHr: 4.05568,
    onDemandWindowsHr: 4.05568,
  },
  "m8i-flex.2xlarge": {
    onDemandLinuxHr: 0.50696,
    onDemandWindowsHr: 0.85656,
  },
  "m8i-flex.4xlarge": {
    onDemandLinuxHr: 1.01392,
    onDemandWindowsHr: 1.71312,
  },
  "m8i-flex.8xlarge": {
    onDemandLinuxHr: 2.02784,
    onDemandWindowsHr: 3.42624,
  },
  "m8i-flex.large": {
    onDemandLinuxHr: 0.12674,
    onDemandWindowsHr: 0.12674,
  },
  "m8i-flex.xlarge": {
    onDemandLinuxHr: 0.25348,
    onDemandWindowsHr: 0.42828,
  },
  "m8i.12xlarge": {
    onDemandLinuxHr: 3.2016,
    onDemandWindowsHr: 5.4096,
  },
  "m8i.16xlarge": {
    onDemandLinuxHr: 4.2688,
    onDemandWindowsHr: 4.2688,
  },
  "m8i.24xlarge": {
    onDemandLinuxHr: 6.4032,
    onDemandWindowsHr: 10.8192,
  },
  "m8i.2xlarge": {
    onDemandLinuxHr: 0.5336,
    onDemandWindowsHr: 0.5336,
  },
  "m8i.32xlarge": {
    onDemandLinuxHr: 8.5376,
    onDemandWindowsHr: 14.4256,
  },
  "m8i.48xlarge": {
    onDemandLinuxHr: 12.8064,
    onDemandWindowsHr: 21.6384,
  },
  "m8i.4xlarge": {
    onDemandLinuxHr: 1.0672,
    onDemandWindowsHr: 1.8032,
  },
  "m8i.8xlarge": {
    onDemandLinuxHr: 2.1344,
    onDemandWindowsHr: 3.6064,
  },
  "m8i.96xlarge": {
    onDemandLinuxHr: 25.6128,
    onDemandWindowsHr: 25.6128,
  },
  "m8i.large": {
    onDemandLinuxHr: 0.1334,
    onDemandWindowsHr: 0.2254,
  },
  "m8i.metal-48xl": {
    onDemandLinuxHr: 12.8064,
    onDemandWindowsHr: 21.6384,
  },
  "m8i.metal-96xl": {
    onDemandLinuxHr: 25.6128,
    onDemandWindowsHr: 43.2768,
  },
  "m8i.xlarge": {
    onDemandLinuxHr: 0.2668,
    onDemandWindowsHr: 0.4508,
  },
  "p3dn.24xlarge": {
    onDemandLinuxHr: 37.454,
    onDemandWindowsHr: 41.87,
  },
  "p6-b200.48xlarge": {
    onDemandLinuxHr: 136.71936,
    onDemandWindowsHr: 0,
  },
  "p6-b300.48xlarge": {
    onDemandLinuxHr: 170.9,
    onDemandWindowsHr: 0,
  },
  "r5.12xlarge": {
    onDemandLinuxHr: 3.624,
    onDemandWindowsHr: 3.624,
  },
  "r5.16xlarge": {
    onDemandLinuxHr: 4.832,
    onDemandWindowsHr: 7.776,
  },
  "r5.24xlarge": {
    onDemandLinuxHr: 7.248,
    onDemandWindowsHr: 7.248,
  },
  "r5.2xlarge": {
    onDemandLinuxHr: 0.604,
    onDemandWindowsHr: 0.604,
  },
  "r5.4xlarge": {
    onDemandLinuxHr: 1.208,
    onDemandWindowsHr: 1.944,
  },
  "r5.8xlarge": {
    onDemandLinuxHr: 2.416,
    onDemandWindowsHr: 2.416,
  },
  "r5.large": {
    onDemandLinuxHr: 0.151,
    onDemandWindowsHr: 0.243,
  },
  "r5.metal": {
    onDemandLinuxHr: 7.248,
    onDemandWindowsHr: 11.664,
  },
  "r5.xlarge": {
    onDemandLinuxHr: 0.302,
    onDemandWindowsHr: 0.486,
  },
  "r5a.12xlarge": {
    onDemandLinuxHr: 3.264,
    onDemandWindowsHr: 5.472,
  },
  "r5a.16xlarge": {
    onDemandLinuxHr: 4.352,
    onDemandWindowsHr: 4.352,
  },
  "r5a.24xlarge": {
    onDemandLinuxHr: 6.528,
    onDemandWindowsHr: 6.528,
  },
  "r5a.2xlarge": {
    onDemandLinuxHr: 0.544,
    onDemandWindowsHr: 0.912,
  },
  "r5a.4xlarge": {
    onDemandLinuxHr: 1.088,
    onDemandWindowsHr: 1.088,
  },
  "r5a.8xlarge": {
    onDemandLinuxHr: 2.176,
    onDemandWindowsHr: 3.648,
  },
  "r5a.large": {
    onDemandLinuxHr: 0.136,
    onDemandWindowsHr: 0.228,
  },
  "r5a.xlarge": {
    onDemandLinuxHr: 0.272,
    onDemandWindowsHr: 0.272,
  },
  "r5d.12xlarge": {
    onDemandLinuxHr: 4.152,
    onDemandWindowsHr: 4.152,
  },
  "r5d.16xlarge": {
    onDemandLinuxHr: 5.536,
    onDemandWindowsHr: 5.536,
  },
  "r5d.24xlarge": {
    onDemandLinuxHr: 8.304,
    onDemandWindowsHr: 12.72,
  },
  "r5d.2xlarge": {
    onDemandLinuxHr: 0.692,
    onDemandWindowsHr: 0.692,
  },
  "r5d.4xlarge": {
    onDemandLinuxHr: 1.384,
    onDemandWindowsHr: 2.12,
  },
  "r5d.8xlarge": {
    onDemandLinuxHr: 2.768,
    onDemandWindowsHr: 4.24,
  },
  "r5d.large": {
    onDemandLinuxHr: 0.173,
    onDemandWindowsHr: 0.173,
  },
  "r5d.metal": {
    onDemandLinuxHr: 8.304,
    onDemandWindowsHr: 12.72,
  },
  "r5d.xlarge": {
    onDemandLinuxHr: 0.346,
    onDemandWindowsHr: 0.53,
  },
  "r5dn.12xlarge": {
    onDemandLinuxHr: 4.824,
    onDemandWindowsHr: 4.824,
  },
  "r5dn.16xlarge": {
    onDemandLinuxHr: 6.432,
    onDemandWindowsHr: 9.376,
  },
  "r5dn.24xlarge": {
    onDemandLinuxHr: 9.648,
    onDemandWindowsHr: 9.648,
  },
  "r5dn.2xlarge": {
    onDemandLinuxHr: 0.804,
    onDemandWindowsHr: 0.804,
  },
  "r5dn.4xlarge": {
    onDemandLinuxHr: 1.608,
    onDemandWindowsHr: 2.344,
  },
  "r5dn.8xlarge": {
    onDemandLinuxHr: 3.216,
    onDemandWindowsHr: 4.688,
  },
  "r5dn.large": {
    onDemandLinuxHr: 0.201,
    onDemandWindowsHr: 0.293,
  },
  "r5dn.metal": {
    onDemandLinuxHr: 9.648,
    onDemandWindowsHr: 14.064,
  },
  "r5dn.xlarge": {
    onDemandLinuxHr: 0.402,
    onDemandWindowsHr: 0.402,
  },
  "r5n.12xlarge": {
    onDemandLinuxHr: 4.296,
    onDemandWindowsHr: 4.296,
  },
  "r5n.16xlarge": {
    onDemandLinuxHr: 5.728,
    onDemandWindowsHr: 5.728,
  },
  "r5n.24xlarge": {
    onDemandLinuxHr: 8.592,
    onDemandWindowsHr: 13.008,
  },
  "r5n.2xlarge": {
    onDemandLinuxHr: 0.716,
    onDemandWindowsHr: 0.716,
  },
  "r5n.4xlarge": {
    onDemandLinuxHr: 1.432,
    onDemandWindowsHr: 1.432,
  },
  "r5n.8xlarge": {
    onDemandLinuxHr: 2.864,
    onDemandWindowsHr: 2.864,
  },
  "r5n.large": {
    onDemandLinuxHr: 0.179,
    onDemandWindowsHr: 0.271,
  },
  "r5n.metal": {
    onDemandLinuxHr: 8.592,
    onDemandWindowsHr: 13.008,
  },
  "r5n.xlarge": {
    onDemandLinuxHr: 0.358,
    onDemandWindowsHr: 0.358,
  },
  "r6g.12xlarge": {
    onDemandLinuxHr: 2.8992,
    onDemandWindowsHr: 0,
  },
  "r6g.16xlarge": {
    onDemandLinuxHr: 3.8656,
    onDemandWindowsHr: 0,
  },
  "r6g.2xlarge": {
    onDemandLinuxHr: 0.4832,
    onDemandWindowsHr: 0,
  },
  "r6g.4xlarge": {
    onDemandLinuxHr: 0.9664,
    onDemandWindowsHr: 0,
  },
  "r6g.8xlarge": {
    onDemandLinuxHr: 1.9328,
    onDemandWindowsHr: 0,
  },
  "r6g.large": {
    onDemandLinuxHr: 0.1208,
    onDemandWindowsHr: 0,
  },
  "r6g.medium": {
    onDemandLinuxHr: 0.0604,
    onDemandWindowsHr: 0,
  },
  "r6g.metal": {
    onDemandLinuxHr: 3.8656,
    onDemandWindowsHr: 0,
  },
  "r6g.xlarge": {
    onDemandLinuxHr: 0.2416,
    onDemandWindowsHr: 0,
  },
  "r6gd.12xlarge": {
    onDemandLinuxHr: 3.3216,
    onDemandWindowsHr: 0,
  },
  "r6gd.16xlarge": {
    onDemandLinuxHr: 4.4288,
    onDemandWindowsHr: 0,
  },
  "r6gd.2xlarge": {
    onDemandLinuxHr: 0.5536,
    onDemandWindowsHr: 0,
  },
  "r6gd.4xlarge": {
    onDemandLinuxHr: 1.1072,
    onDemandWindowsHr: 0,
  },
  "r6gd.8xlarge": {
    onDemandLinuxHr: 2.2144,
    onDemandWindowsHr: 0,
  },
  "r6gd.large": {
    onDemandLinuxHr: 0.1384,
    onDemandWindowsHr: 0,
  },
  "r6gd.medium": {
    onDemandLinuxHr: 0.0692,
    onDemandWindowsHr: 0,
  },
  "r6gd.metal": {
    onDemandLinuxHr: 4.4288,
    onDemandWindowsHr: 0,
  },
  "r6gd.xlarge": {
    onDemandLinuxHr: 0.2768,
    onDemandWindowsHr: 0,
  },
  "r6i.12xlarge": {
    onDemandLinuxHr: 3.624,
    onDemandWindowsHr: 5.832,
  },
  "r6i.16xlarge": {
    onDemandLinuxHr: 4.832,
    onDemandWindowsHr: 4.832,
  },
  "r6i.24xlarge": {
    onDemandLinuxHr: 7.248,
    onDemandWindowsHr: 11.664,
  },
  "r6i.2xlarge": {
    onDemandLinuxHr: 0.604,
    onDemandWindowsHr: 0.604,
  },
  "r6i.32xlarge": {
    onDemandLinuxHr: 9.664,
    onDemandWindowsHr: 15.552,
  },
  "r6i.4xlarge": {
    onDemandLinuxHr: 1.208,
    onDemandWindowsHr: 1.944,
  },
  "r6i.8xlarge": {
    onDemandLinuxHr: 2.416,
    onDemandWindowsHr: 2.416,
  },
  "r6i.large": {
    onDemandLinuxHr: 0.151,
    onDemandWindowsHr: 0.243,
  },
  "r6i.metal": {
    onDemandLinuxHr: 9.664,
    onDemandWindowsHr: 15.552,
  },
  "r6i.xlarge": {
    onDemandLinuxHr: 0.302,
    onDemandWindowsHr: 0.486,
  },
  "r7g.12xlarge": {
    onDemandLinuxHr: 3.0806,
    onDemandWindowsHr: 0,
  },
  "r7g.16xlarge": {
    onDemandLinuxHr: 4.1075,
    onDemandWindowsHr: 0,
  },
  "r7g.2xlarge": {
    onDemandLinuxHr: 0.5134,
    onDemandWindowsHr: 0,
  },
  "r7g.4xlarge": {
    onDemandLinuxHr: 1.0269,
    onDemandWindowsHr: 0,
  },
  "r7g.8xlarge": {
    onDemandLinuxHr: 2.0538,
    onDemandWindowsHr: 0,
  },
  "r7g.large": {
    onDemandLinuxHr: 0.1284,
    onDemandWindowsHr: 0,
  },
  "r7g.medium": {
    onDemandLinuxHr: 0.0642,
    onDemandWindowsHr: 0,
  },
  "r7g.metal": {
    onDemandLinuxHr: 4.1075,
    onDemandWindowsHr: 0,
  },
  "r7g.xlarge": {
    onDemandLinuxHr: 0.2567,
    onDemandWindowsHr: 0,
  },
  "r7gd.12xlarge": {
    onDemandLinuxHr: 3.9235,
    onDemandWindowsHr: 0,
  },
  "r7gd.16xlarge": {
    onDemandLinuxHr: 5.2314,
    onDemandWindowsHr: 0,
  },
  "r7gd.2xlarge": {
    onDemandLinuxHr: 0.6539,
    onDemandWindowsHr: 0,
  },
  "r7gd.4xlarge": {
    onDemandLinuxHr: 1.3078,
    onDemandWindowsHr: 0,
  },
  "r7gd.8xlarge": {
    onDemandLinuxHr: 2.6157,
    onDemandWindowsHr: 0,
  },
  "r7gd.large": {
    onDemandLinuxHr: 0.1635,
    onDemandWindowsHr: 0,
  },
  "r7gd.medium": {
    onDemandLinuxHr: 0.0817,
    onDemandWindowsHr: 0,
  },
  "r7gd.metal": {
    onDemandLinuxHr: 5.2314,
    onDemandWindowsHr: 0,
  },
  "r7gd.xlarge": {
    onDemandLinuxHr: 0.327,
    onDemandWindowsHr: 0,
  },
  "r7i.12xlarge": {
    onDemandLinuxHr: 3.8052,
    onDemandWindowsHr: 6.0132,
  },
  "r7i.16xlarge": {
    onDemandLinuxHr: 5.0736,
    onDemandWindowsHr: 5.0736,
  },
  "r7i.24xlarge": {
    onDemandLinuxHr: 7.6104,
    onDemandWindowsHr: 12.0264,
  },
  "r7i.2xlarge": {
    onDemandLinuxHr: 0.6342,
    onDemandWindowsHr: 1.0022,
  },
  "r7i.48xlarge": {
    onDemandLinuxHr: 15.2208,
    onDemandWindowsHr: 15.2208,
  },
  "r7i.4xlarge": {
    onDemandLinuxHr: 1.2684,
    onDemandWindowsHr: 2.0044,
  },
  "r7i.8xlarge": {
    onDemandLinuxHr: 2.5368,
    onDemandWindowsHr: 4.0088,
  },
  "r7i.large": {
    onDemandLinuxHr: 0.15855,
    onDemandWindowsHr: 0.15855,
  },
  "r7i.metal-24xl": {
    onDemandLinuxHr: 7.6104,
    onDemandWindowsHr: 12.0264,
  },
  "r7i.metal-48xl": {
    onDemandLinuxHr: 15.2208,
    onDemandWindowsHr: 24.0528,
  },
  "r7i.xlarge": {
    onDemandLinuxHr: 0.3171,
    onDemandWindowsHr: 0.5011,
  },
  "r8g.12xlarge": {
    onDemandLinuxHr: 3.3888,
    onDemandWindowsHr: 0,
  },
  "r8g.16xlarge": {
    onDemandLinuxHr: 4.5184,
    onDemandWindowsHr: 0,
  },
  "r8g.24xlarge": {
    onDemandLinuxHr: 6.7776,
    onDemandWindowsHr: 0,
  },
  "r8g.2xlarge": {
    onDemandLinuxHr: 0.5648,
    onDemandWindowsHr: 0,
  },
  "r8g.48xlarge": {
    onDemandLinuxHr: 13.5552,
    onDemandWindowsHr: 0,
  },
  "r8g.4xlarge": {
    onDemandLinuxHr: 1.1296,
    onDemandWindowsHr: 0,
  },
  "r8g.8xlarge": {
    onDemandLinuxHr: 2.2592,
    onDemandWindowsHr: 0,
  },
  "r8g.large": {
    onDemandLinuxHr: 0.1412,
    onDemandWindowsHr: 0,
  },
  "r8g.medium": {
    onDemandLinuxHr: 0.0706,
    onDemandWindowsHr: 0,
  },
  "r8g.metal-24xl": {
    onDemandLinuxHr: 6.7776,
    onDemandWindowsHr: 0,
  },
  "r8g.metal-48xl": {
    onDemandLinuxHr: 13.5552,
    onDemandWindowsHr: 0,
  },
  "r8g.xlarge": {
    onDemandLinuxHr: 0.2824,
    onDemandWindowsHr: 0,
  },
  "r8gd.12xlarge": {
    onDemandLinuxHr: 4.23744,
    onDemandWindowsHr: 0,
  },
  "r8gd.16xlarge": {
    onDemandLinuxHr: 5.64992,
    onDemandWindowsHr: 0,
  },
  "r8gd.24xlarge": {
    onDemandLinuxHr: 8.47488,
    onDemandWindowsHr: 0,
  },
  "r8gd.2xlarge": {
    onDemandLinuxHr: 0.70624,
    onDemandWindowsHr: 0,
  },
  "r8gd.48xlarge": {
    onDemandLinuxHr: 16.94976,
    onDemandWindowsHr: 0,
  },
  "r8gd.4xlarge": {
    onDemandLinuxHr: 1.41248,
    onDemandWindowsHr: 0,
  },
  "r8gd.8xlarge": {
    onDemandLinuxHr: 2.82496,
    onDemandWindowsHr: 0,
  },
  "r8gd.large": {
    onDemandLinuxHr: 0.17656,
    onDemandWindowsHr: 0,
  },
  "r8gd.medium": {
    onDemandLinuxHr: 0.08828,
    onDemandWindowsHr: 0,
  },
  "r8gd.metal-24xl": {
    onDemandLinuxHr: 8.47488,
    onDemandWindowsHr: 0,
  },
  "r8gd.metal-48xl": {
    onDemandLinuxHr: 16.94976,
    onDemandWindowsHr: 0,
  },
  "r8gd.xlarge": {
    onDemandLinuxHr: 0.35312,
    onDemandWindowsHr: 0,
  },
  "r8i-flex.12xlarge": {
    onDemandLinuxHr: 3.79584,
    onDemandWindowsHr: 3.79584,
  },
  "r8i-flex.16xlarge": {
    onDemandLinuxHr: 5.06112,
    onDemandWindowsHr: 5.06112,
  },
  "r8i-flex.2xlarge": {
    onDemandLinuxHr: 0.63264,
    onDemandWindowsHr: 0.63264,
  },
  "r8i-flex.4xlarge": {
    onDemandLinuxHr: 1.26528,
    onDemandWindowsHr: 1.96448,
  },
  "r8i-flex.8xlarge": {
    onDemandLinuxHr: 2.53056,
    onDemandWindowsHr: 3.92896,
  },
  "r8i-flex.large": {
    onDemandLinuxHr: 0.15816,
    onDemandWindowsHr: 0.15816,
  },
  "r8i-flex.xlarge": {
    onDemandLinuxHr: 0.31632,
    onDemandWindowsHr: 0.31632,
  },
  "r8i.12xlarge": {
    onDemandLinuxHr: 3.99552,
    onDemandWindowsHr: 3.99552,
  },
  "r8i.16xlarge": {
    onDemandLinuxHr: 5.32736,
    onDemandWindowsHr: 5.32736,
  },
  "r8i.24xlarge": {
    onDemandLinuxHr: 7.99104,
    onDemandWindowsHr: 7.99104,
  },
  "r8i.2xlarge": {
    onDemandLinuxHr: 0.66592,
    onDemandWindowsHr: 1.03392,
  },
  "r8i.32xlarge": {
    onDemandLinuxHr: 10.65472,
    onDemandWindowsHr: 16.54272,
  },
  "r8i.48xlarge": {
    onDemandLinuxHr: 15.98208,
    onDemandWindowsHr: 24.81408,
  },
  "r8i.4xlarge": {
    onDemandLinuxHr: 1.33184,
    onDemandWindowsHr: 2.06784,
  },
  "r8i.8xlarge": {
    onDemandLinuxHr: 2.66368,
    onDemandWindowsHr: 4.13568,
  },
  "r8i.96xlarge": {
    onDemandLinuxHr: 31.96416,
    onDemandWindowsHr: 31.96416,
  },
  "r8i.large": {
    onDemandLinuxHr: 0.16648,
    onDemandWindowsHr: 0.16648,
  },
  "r8i.metal-48xl": {
    onDemandLinuxHr: 15.98208,
    onDemandWindowsHr: 24.81408,
  },
  "r8i.metal-96xl": {
    onDemandLinuxHr: 31.96416,
    onDemandWindowsHr: 49.62816,
  },
  "r8i.xlarge": {
    onDemandLinuxHr: 0.33296,
    onDemandWindowsHr: 0.51696,
  },
  "t3.2xlarge": {
    onDemandLinuxHr: 0.3904,
    onDemandWindowsHr: 0.3904,
  },
  "t3.large": {
    onDemandLinuxHr: 0.0976,
    onDemandWindowsHr: 0.1252,
  },
  "t3.medium": {
    onDemandLinuxHr: 0.0488,
    onDemandWindowsHr: 0.0672,
  },
  "t3.micro": {
    onDemandLinuxHr: 0.0122,
    onDemandWindowsHr: 0.0122,
  },
  "t3.nano": {
    onDemandLinuxHr: 0.0061,
    onDemandWindowsHr: 0.0107,
  },
  "t3.small": {
    onDemandLinuxHr: 0.0244,
    onDemandWindowsHr: 0.0244,
  },
  "t3.xlarge": {
    onDemandLinuxHr: 0.1952,
    onDemandWindowsHr: 0.2688,
  },
  "t3a.2xlarge": {
    onDemandLinuxHr: 0.3514,
    onDemandWindowsHr: 0.4986,
  },
  "t3a.large": {
    onDemandLinuxHr: 0.0878,
    onDemandWindowsHr: 0.0878,
  },
  "t3a.medium": {
    onDemandLinuxHr: 0.0439,
    onDemandWindowsHr: 0.0623,
  },
  "t3a.micro": {
    onDemandLinuxHr: 0.011,
    onDemandWindowsHr: 0.0202,
  },
  "t3a.nano": {
    onDemandLinuxHr: 0.0055,
    onDemandWindowsHr: 0.0055,
  },
  "t3a.small": {
    onDemandLinuxHr: 0.022,
    onDemandWindowsHr: 0.0404,
  },
  "t3a.xlarge": {
    onDemandLinuxHr: 0.1757,
    onDemandWindowsHr: 0.2493,
  },
  "t4g.2xlarge": {
    onDemandLinuxHr: 0.3136,
    onDemandWindowsHr: 0,
  },
  "t4g.large": {
    onDemandLinuxHr: 0.0784,
    onDemandWindowsHr: 0,
  },
  "t4g.medium": {
    onDemandLinuxHr: 0.0392,
    onDemandWindowsHr: 0,
  },
  "t4g.micro": {
    onDemandLinuxHr: 0.0098,
    onDemandWindowsHr: 0,
  },
  "t4g.nano": {
    onDemandLinuxHr: 0.0049,
    onDemandWindowsHr: 0,
  },
  "t4g.small": {
    onDemandLinuxHr: 0.0196,
    onDemandWindowsHr: 0,
  },
  "t4g.xlarge": {
    onDemandLinuxHr: 0.1568,
    onDemandWindowsHr: 0,
  },
  "u-12tb1.112xlarge": {
    onDemandLinuxHr: 130.867,
    onDemandWindowsHr: 151.475,
  },
  "u-24tb1.112xlarge": {
    onDemandLinuxHr: 261.73,
    onDemandWindowsHr: 282.338,
  },
  "u-6tb1.112xlarge": {
    onDemandLinuxHr: 65.433,
    onDemandWindowsHr: 65.433,
  },
  "u-6tb1.56xlarge": {
    onDemandLinuxHr: 55.61075,
    onDemandWindowsHr: 65.91475,
  },
  "u-6tb1.metal": {
    onDemandLinuxHr: 0,
    onDemandWindowsHr: 20.608,
  },
  "u-9tb1.112xlarge": {
    onDemandLinuxHr: 98.15,
    onDemandWindowsHr: 118.758,
  },
  "u7i-12tb.224xlarge": {
    onDemandLinuxHr: 150.49696,
    onDemandWindowsHr: 150.49696,
  },
  "u7i-6tb.112xlarge": {
    onDemandLinuxHr: 75.24795,
    onDemandWindowsHr: 75.24795,
  },
  "u7in-16tb.224xlarge": {
    onDemandLinuxHr: 216.28384,
    onDemandWindowsHr: 257.49984,
  },
  "u7in-24tb.224xlarge": {
    onDemandLinuxHr: 324.44368,
    onDemandWindowsHr: 365.65968,
  },
  "x1.16xlarge": {
    onDemandLinuxHr: 8.003,
    onDemandWindowsHr: 8.003,
  },
  "x1.32xlarge": {
    onDemandLinuxHr: 16.006,
    onDemandWindowsHr: 21.894,
  },
  "x1e.16xlarge": {
    onDemandLinuxHr: 16,
    onDemandWindowsHr: 16,
  },
  "x1e.2xlarge": {
    onDemandLinuxHr: 2,
    onDemandWindowsHr: 2.368,
  },
  "x1e.32xlarge": {
    onDemandLinuxHr: 32,
    onDemandWindowsHr: 37.888,
  },
  "x1e.4xlarge": {
    onDemandLinuxHr: 4,
    onDemandWindowsHr: 4.736,
  },
  "x1e.8xlarge": {
    onDemandLinuxHr: 8,
    onDemandWindowsHr: 8,
  },
  "x1e.xlarge": {
    onDemandLinuxHr: 1,
    onDemandWindowsHr: 1.184,
  },
  "x2idn.16xlarge": {
    onDemandLinuxHr: 8.003,
    onDemandWindowsHr: 8.003,
  },
  "x2idn.24xlarge": {
    onDemandLinuxHr: 12.0045,
    onDemandWindowsHr: 12.0045,
  },
  "x2idn.32xlarge": {
    onDemandLinuxHr: 16.006,
    onDemandWindowsHr: 16.006,
  },
  "x2idn.metal": {
    onDemandLinuxHr: 16.006,
    onDemandWindowsHr: 21.894,
  },
  "x2iedn.16xlarge": {
    onDemandLinuxHr: 16.006,
    onDemandWindowsHr: 16.006,
  },
  "x2iedn.24xlarge": {
    onDemandLinuxHr: 24.009,
    onDemandWindowsHr: 28.425,
  },
  "x2iedn.2xlarge": {
    onDemandLinuxHr: 2.00075,
    onDemandWindowsHr: 2.36875,
  },
  "x2iedn.32xlarge": {
    onDemandLinuxHr: 32.012,
    onDemandWindowsHr: 32.012,
  },
  "x2iedn.4xlarge": {
    onDemandLinuxHr: 4.0015,
    onDemandWindowsHr: 4.0015,
  },
  "x2iedn.8xlarge": {
    onDemandLinuxHr: 8.003,
    onDemandWindowsHr: 8.003,
  },
  "x2iedn.metal": {
    onDemandLinuxHr: 32.012,
    onDemandWindowsHr: 37.9,
  },
  "x2iedn.xlarge": {
    onDemandLinuxHr: 1.00038,
    onDemandWindowsHr: 1.18438,
  },
};
