#!/usr/bin/env node
/*
 * split-data.js — splits each monolithic js/{provider}/{provider}-data.js into
 * per-region files (js/{provider}/regions/<regionKey>.js) and rewrites the
 * original file as a small manifest.
 *
 * Data-update workflow:
 *   1. Drop the freshly generated monolithic {provider}-data.js in place
 *      (same format as produced from instances.vantage.sh).
 *   2. Run: node tools/split-data.js
 *   3. Commit the regenerated regions/ files and the manifest.
 *
 * Idempotent: a file that is already a manifest (contains _REGION_KEYS) is
 * skipped, so running the tool twice is safe.
 *
 * Hard-fails if the number of extracted region blocks does not match the key
 * list in the makeXRegionsGlobal({...}) call — protects against a format
 * drift in the upstream generator silently dropping regions.
 */

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const ROOT = path.join(__dirname, "..");

const PROVIDERS = [
  { name: "aws", prefix: "AWS" },
  { name: "azure", prefix: "AZURE" },
  { name: "gcp", prefix: "GCP" },
];

function splitProvider({ name, prefix }) {
  const dataPath = path.join(ROOT, "js", name, `${name}-data.js`);
  if (!fs.existsSync(dataPath)) {
    console.log(`[${name}] ${dataPath} not found — skipping`);
    return { name, skipped: true };
  }

  // Normalize CRLF so the exact-line matching below works regardless of
  // how git checked the file out
  const content = fs.readFileSync(dataPath, "utf8").replace(/\r\n/g, "\n");

  if (content.includes("_REGION_KEYS")) {
    console.log(`[${name}] already a manifest — skipping (idempotency guard)`);
    return { name, skipped: true };
  }

  // Header comments (first lines starting with //) — preserved in manifest
  const headerLines = [];
  for (const line of content.split("\n")) {
    if (line.startsWith("//")) headerLines.push(line);
    else break;
  }

  const dateMatch = content.match(
    new RegExp(`window\\.${prefix}_DATA_DATE = "([^"]+)";`),
  );
  if (!dateMatch) {
    throw new Error(`[${name}] window.${prefix}_DATA_DATE not found`);
  }
  const dataDate = dateMatch[1];

  // Extract region blocks: column-0 `const <key> = {` ... column-0 `};`
  const lines = content.split("\n");
  const regions = []; // { key, body: [lines between braces] }
  let current = null;
  for (const line of lines) {
    if (current === null) {
      const m = line.match(/^const ([A-Za-z_][A-Za-z0-9_]*) = \{$/);
      if (m) current = { key: m[1], body: [] };
    } else if (line === "};") {
      regions.push(current);
      current = null;
    } else {
      current.body.push(line);
    }
  }
  if (current !== null) {
    throw new Error(`[${name}] unterminated region block: ${current.key}`);
  }

  // Cross-check against the makeXRegionsGlobal({...}) key list
  const callMatch = content.match(/make\w*RegionsGlobal\(\{([\s\S]*?)\}\)/);
  if (!callMatch) {
    throw new Error(`[${name}] makeRegionsGlobal call not found`);
  }
  const declaredKeys = callMatch[1]
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
  const extractedKeys = regions.map((r) => r.key);

  if (declaredKeys.length !== extractedKeys.length) {
    throw new Error(
      `[${name}] extracted ${extractedKeys.length} region blocks but ` +
        `makeRegionsGlobal declares ${declaredKeys.length} keys — aborting`,
    );
  }
  const extractedSet = new Set(extractedKeys);
  const missing = declaredKeys.filter((k) => !extractedSet.has(k));
  if (missing.length) {
    throw new Error(
      `[${name}] declared but not extracted: ${missing.join(", ")}`,
    );
  }

  // Build per-region files and syntax-validate each BEFORE any disk write.
  // A mis-split block (e.g. upstream formatting drift closing a region
  // early) necessarily leaves unbalanced braces, which fails compilation
  // here instead of producing silently truncated data.
  const files = regions.map(({ key, body }) => {
    const fileContent =
      `// ${prefix} instance data for region key: ${key} (updated ${dataDate})\n` +
      `// Auto-generated by tools/split-data.js — do not edit by hand\n` +
      `window.${key} = {\n${body.join("\n")}\n};\n`;
    try {
      new vm.Script(fileContent, { filename: `${key}.js` });
    } catch (err) {
      throw new Error(
        `[${name}] region ${key} did not split cleanly (${err.message}) — aborting`,
      );
    }
    return { key, fileContent };
  });

  // Write the new region files FIRST, then prune stale ones not in the new
  // key set — a write-time failure (disk full, interruption) can then never
  // leave regions/ with deleted-but-unreplaced files
  const regionsDir = path.join(ROOT, "js", name, "regions");
  fs.mkdirSync(regionsDir, { recursive: true });
  const newFileNames = new Set(files.map(({ key }) => `${key}.js`));
  for (const { key, fileContent } of files) {
    fs.writeFileSync(path.join(regionsDir, `${key}.js`), fileContent, "utf8");
  }
  const pruned = [];
  for (const stale of fs.readdirSync(regionsDir)) {
    if (stale.endsWith(".js") && !newFileNames.has(stale)) {
      fs.unlinkSync(path.join(regionsDir, stale));
      pruned.push(stale);
    }
  }

  // Rewrite the data file as a manifest
  const manifest =
    headerLines.join("\n") +
    (headerLines.length ? "\n" : "") +
    `// Manifest generated by tools/split-data.js — region data lives in js/${name}/regions/\n` +
    `window.${prefix}_DATA_DATE = "${dataDate}";\n` +
    `window.${prefix}_REGION_KEYS = [\n` +
    extractedKeys.map((k) => `  "${k}",`).join("\n") +
    `\n];\n` +
    `window.${prefix}_DATA_READY = true;\n`;
  fs.writeFileSync(dataPath, manifest, "utf8");

  console.log(
    `[${name}] split ${regions.length} regions into js/${name}/regions/ and rewrote manifest`,
  );
  // A pruned region stays in users' runtime cache: stale-while-revalidate keeps
  // serving the cached copy because revalidating a deleted file 404s. Bumping
  // CACHE in sw.js is the only thing that evicts it — so say so, loudly.
  if (pruned.length) {
    console.log(
      `[${name}] removed ${pruned.length} region file(s) no longer upstream: ${pruned.join(", ")}`,
    );
    console.log(
      `[${name}] ⚠ regions were removed — bump CACHE in sw.js so clients drop the stale copies`,
    );
  }
  return { name, count: regions.length, pruned };
}

let failed = false;
for (const provider of PROVIDERS) {
  try {
    splitProvider(provider);
  } catch (err) {
    failed = true;
    console.error(String(err.message || err));
  }
}
process.exit(failed ? 1 : 0);
