// AZURE instance prices for region key: eastasia (updated 2026-08-30)
// Auto-generated by tools/split-data.js — do not edit by hand
// Specs for these types live in js/azure/azure-data.js as AZURE_SPECS.compute
window.eastasia = {
  "a0": {
    linuxPrice: 0.018,
    windowsPrice: 0.02,
  },
  "a1": {
    linuxPrice: 0.06,
    windowsPrice: 0.09,
  },
  "a1v2": {
    linuxPrice: 0.05,
    windowsPrice: 0.076,
  },
  "a2": {
    linuxPrice: 0.12,
    windowsPrice: 0.157,
  },
  "a2mv2": {
    linuxPrice: 0.138,
    windowsPrice: 0.23,
  },
  "a2v2": {
    linuxPrice: 0.105,
    windowsPrice: 0.159,
  },
  "a3": {
    linuxPrice: 0.232,
    windowsPrice: 0.348,
  },
  "a4": {
    linuxPrice: 0.464,
    windowsPrice: 0.696,
  },
  "a4mv2": {
    linuxPrice: 0.276,
    windowsPrice: 0.46,
  },
  "a4v2": {
    linuxPrice: 0.222,
    windowsPrice: 0.333,
  },
  "a5": {
    linuxPrice: 0.294,
    windowsPrice: 0.36,
  },
  "a6": {
    linuxPrice: 0.588,
    windowsPrice: 0.72,
  },
  "a7": {
    linuxPrice: 1.176,
    windowsPrice: 1.44,
  },
  "a8mv2": {
    linuxPrice: 0.552,
    windowsPrice: 0.92,
  },
  "a8v2": {
    linuxPrice: 0.464,
    windowsPrice: 0.7,
  },
  "b12ms": {
    linuxPrice: 0.701,
    windowsPrice: 0.749,
  },
  "b16alsv2": {
    linuxPrice: 0.745,
    windowsPrice: 0.818,
  },
  "b16asv2": {
    linuxPrice: 0.841,
    windowsPrice: 0.915,
  },
  "b16lsv2": {
    linuxPrice: 0.901,
    windowsPrice: 0.901,
  },
  "b16ms": {
    linuxPrice: 0.934,
    windowsPrice: 0.998,
  },
  "b16plsv2": {
    linuxPrice: 0.731,
    windowsPrice: 0.731,
  },
  "b16psv2": {
    linuxPrice: 0.816,
    windowsPrice: 0.816,
  },
  "b16sv2": {
    linuxPrice: 1.008,
    windowsPrice: 1.008,
  },
  "b1ls": {
    linuxPrice: 0.0073,
    windowsPrice: 0.0113,
  },
  "b1ms": {
    linuxPrice: 0.0292,
    windowsPrice: 0.0332,
  },
  "b1s": {
    linuxPrice: 0.0146,
    windowsPrice: 0.0186,
  },
  "b20ms": {
    linuxPrice: 1.168,
    windowsPrice: 1.248,
  },
  "b2alsv2": {
    linuxPrice: 0.0618,
    windowsPrice: 0.0618,
  },
  "b2asv2": {
    linuxPrice: 0.105,
    windowsPrice: 0.114,
  },
  "b2atsv2": {
    linuxPrice: 0.0223,
    windowsPrice: 0.0223,
  },
  "b2lsv2": {
    linuxPrice: 0.0584,
    windowsPrice: 0.0676,
  },
  "b2ms": {
    linuxPrice: 0.117,
    windowsPrice: 0.125,
  },
  "b2plsv2": {
    linuxPrice: 0.0464,
    windowsPrice: 0.0556,
  },
  "b2psv2": {
    linuxPrice: 0.0928,
    windowsPrice: 0.102,
  },
  "b2ptsv2": {
    linuxPrice: 0.0208,
    windowsPrice: 0.0208,
  },
  "b2s": {
    linuxPrice: 0.0584,
    windowsPrice: 0.0664,
  },
  "b2sv2": {
    linuxPrice: 0.117,
    windowsPrice: 0.126,
  },
  "b2tsv2": {
    linuxPrice: 0.0146,
    windowsPrice: 0.0238,
  },
  "b32alsv2": {
    linuxPrice: 1.489,
    windowsPrice: 1.637,
  },
  "b32asv2": {
    linuxPrice: 1.829,
    windowsPrice: 1.829,
  },
  "b32lsv2": {
    linuxPrice: 1.655,
    windowsPrice: 1.802,
  },
  "b32sv2": {
    linuxPrice: 2.016,
    windowsPrice: 2.016,
  },
  "b4alsv2": {
    linuxPrice: 0.205,
    windowsPrice: 0.205,
  },
  "b4asv2": {
    linuxPrice: 0.229,
    windowsPrice: 0.229,
  },
  "b4lsv2": {
    linuxPrice: 0.207,
    windowsPrice: 0.225,
  },
  "b4ms": {
    linuxPrice: 0.234,
    windowsPrice: 0.25,
  },
  "b4plsv2": {
    linuxPrice: 0.164,
    windowsPrice: 0.183,
  },
  "b4psv2": {
    linuxPrice: 0.204,
    windowsPrice: 0.204,
  },
  "b4sv2": {
    linuxPrice: 0.252,
    windowsPrice: 0.252,
  },
  "b8alsv2": {
    linuxPrice: 0.372,
    windowsPrice: 0.409,
  },
  "b8asv2": {
    linuxPrice: 0.457,
    windowsPrice: 0.457,
  },
  "b8lsv2": {
    linuxPrice: 0.451,
    windowsPrice: 0.451,
  },
  "b8ms": {
    linuxPrice: 0.467,
    windowsPrice: 0.499,
  },
  "b8plsv2": {
    linuxPrice: 0.329,
    windowsPrice: 0.365,
  },
  "b8psv2": {
    linuxPrice: 0.371,
    windowsPrice: 0.408,
  },
  "b8sv2": {
    linuxPrice: 0.504,
    windowsPrice: 0.504,
  },
  "d1": {
    linuxPrice: 0.113,
    windowsPrice: 0.185,
  },
  "d11": {
    linuxPrice: 0.242,
    windowsPrice: 0.352,
  },
  "d11s": {
    linuxPrice: 0.242,
    windowsPrice: 0.352,
  },
  "d11v2": {
    linuxPrice: 0.229,
    windowsPrice: 0.352,
  },
  "d12": {
    linuxPrice: 0.483,
    windowsPrice: 0.703,
  },
  "d128adsv7": {
    linuxPrice: 10.099,
    windowsPrice: 15.987,
  },
  "d128aldsv7": {
    linuxPrice: 8.435,
    windowsPrice: 14.323,
  },
  "d128alsv7": {
    linuxPrice: 7.117,
    windowsPrice: 13.005,
  },
  "d128asv7": {
    linuxPrice: 8.038,
    windowsPrice: 13.926,
  },
  "d128dsv6": {
    linuxPrice: 10.963,
    windowsPrice: 16.851,
  },
  "d128ldsv6": {
    linuxPrice: 9.709,
    windowsPrice: 15.597,
  },
  "d128lsv6": {
    linuxPrice: 7.855,
    windowsPrice: 13.743,
  },
  "d128ndsv6": {
    linuxPrice: 15.785,
    windowsPrice: 21.673,
  },
  "d128nldsv6": {
    linuxPrice: 11.868,
    windowsPrice: 17.756,
  },
  "d128nlsv6": {
    linuxPrice: 9.61,
    windowsPrice: 15.498,
  },
  "d128nsv6": {
    linuxPrice: 13.812,
    windowsPrice: 19.7,
  },
  "d128sv6": {
    linuxPrice: 8.87,
    windowsPrice: 14.758,
  },
  "d12s": {
    linuxPrice: 0.483,
    windowsPrice: 0.703,
  },
  "d12v2": {
    linuxPrice: 0.459,
    windowsPrice: 0.704,
  },
  "d13": {
    linuxPrice: 0.966,
    windowsPrice: 1.407,
  },
  "d13s": {
    linuxPrice: 0.966,
    windowsPrice: 1.407,
  },
  "d13v2": {
    linuxPrice: 0.918,
    windowsPrice: 1.407,
  },
  "d14": {
    linuxPrice: 1.932,
    windowsPrice: 2.814,
  },
  "d14s": {
    linuxPrice: 1.932,
    windowsPrice: 2.814,
  },
  "d14v2": {
    linuxPrice: 1.835,
    windowsPrice: 2.814,
  },
  "d15iv2": {
    linuxPrice: 2.294,
    windowsPrice: 3.518,
  },
  "d15v2": {
    linuxPrice: 2.294,
    windowsPrice: 3.518,
  },
  "d160adsv7": {
    linuxPrice: 12.624,
    windowsPrice: 19.984,
  },
  "d160aldsv7": {
    linuxPrice: 10.544,
    windowsPrice: 17.904,
  },
  "d160alsv7": {
    linuxPrice: 8.896,
    windowsPrice: 16.256,
  },
  "d160asv7": {
    linuxPrice: 10.048,
    windowsPrice: 17.408,
  },
  "d16adsv5": {
    linuxPrice: 1.136,
    windowsPrice: 1.872,
  },
  "d16adsv6": {
    linuxPrice: 1.262,
    windowsPrice: 1.998,
  },
  "d16adsv7": {
    linuxPrice: 1.262,
    windowsPrice: 1.998,
  },
  "d16aldsv6": {
    linuxPrice: 1.054,
    windowsPrice: 1.79,
  },
  "d16aldsv7": {
    linuxPrice: 1.054,
    windowsPrice: 1.79,
  },
  "d16alsv6": {
    linuxPrice: 0.89,
    windowsPrice: 1.626,
  },
  "d16alsv7": {
    linuxPrice: 0.89,
    windowsPrice: 1.626,
  },
  "d16asv4": {
    linuxPrice: 1.056,
    windowsPrice: 1.792,
  },
  "d16asv5": {
    linuxPrice: 1.688,
    windowsPrice: 1.688,
  },
  "d16asv6": {
    linuxPrice: 1.005,
    windowsPrice: 1.741,
  },
  "d16asv7": {
    linuxPrice: 1.005,
    windowsPrice: 1.741,
  },
  "d16av4": {
    linuxPrice: 1.056,
    windowsPrice: 1.792,
  },
  "d16dsv4": {
    linuxPrice: 1.24,
    windowsPrice: 1.976,
  },
  "d16dsv5": {
    linuxPrice: 1.24,
    windowsPrice: 1.976,
  },
  "d16dsv6": {
    linuxPrice: 1.37,
    windowsPrice: 2.106,
  },
  "d16dv4": {
    linuxPrice: 1.24,
    windowsPrice: 1.976,
  },
  "d16dv5": {
    linuxPrice: 1.24,
    windowsPrice: 1.976,
  },
  "d16ldsv5": {
    linuxPrice: 0.984,
    windowsPrice: 1.72,
  },
  "d16ldsv6": {
    linuxPrice: 1.214,
    windowsPrice: 1.95,
  },
  "d16lsv5": {
    linuxPrice: 0.864,
    windowsPrice: 1.6,
  },
  "d16lsv6": {
    linuxPrice: 0.982,
    windowsPrice: 1.718,
  },
  "d16ndsv6": {
    linuxPrice: 1.973,
    windowsPrice: 2.709,
  },
  "d16nldsv6": {
    linuxPrice: 1.483,
    windowsPrice: 2.219,
  },
  "d16nlsv6": {
    linuxPrice: 1.201,
    windowsPrice: 1.937,
  },
  "d16nsv6": {
    linuxPrice: 1.726,
    windowsPrice: 2.462,
  },
  "d16pdsv5": {
    linuxPrice: 0.996,
    windowsPrice: 0,
  },
  "d16pdsv6": {
    linuxPrice: 1.011,
    windowsPrice: 0,
  },
  "d16pldsv5": {
    linuxPrice: 0.784,
    windowsPrice: 0,
  },
  "d16pldsv6": {
    linuxPrice: 0.859,
    windowsPrice: 0,
  },
  "d16plsv5": {
    linuxPrice: 0.688,
    windowsPrice: 0,
  },
  "d16plsv6": {
    linuxPrice: 0.683,
    windowsPrice: 0,
  },
  "d16psv5": {
    linuxPrice: 0.848,
    windowsPrice: 0,
  },
  "d16psv6": {
    linuxPrice: 0.773,
    windowsPrice: 0,
  },
  "d16sv3": {
    linuxPrice: 1.056,
    windowsPrice: 1.792,
  },
  "d16sv4": {
    linuxPrice: 1.056,
    windowsPrice: 1.792,
  },
  "d16sv5": {
    linuxPrice: 1.056,
    windowsPrice: 1.792,
  },
  "d16sv6": {
    linuxPrice: 1.109,
    windowsPrice: 1.845,
  },
  "d16v3": {
    linuxPrice: 1.056,
    windowsPrice: 1.792,
  },
  "d16v4": {
    linuxPrice: 1.056,
    windowsPrice: 1.792,
  },
  "d16v5": {
    linuxPrice: 1.056,
    windowsPrice: 1.792,
  },
  "d192dsv6": {
    linuxPrice: 16.445,
    windowsPrice: 25.277,
  },
  "d192sv6": {
    linuxPrice: 13.306,
    windowsPrice: 22.138,
  },
  "d1s": {
    linuxPrice: 0.113,
    windowsPrice: 0.185,
  },
  "d1v2": {
    linuxPrice: 0.107,
    windowsPrice: 0.167,
  },
  "d2": {
    linuxPrice: 0.225,
    windowsPrice: 0.37,
  },
  "d2adsv5": {
    linuxPrice: 0.234,
    windowsPrice: 0.234,
  },
  "d2adsv6": {
    linuxPrice: 0.158,
    windowsPrice: 0.25,
  },
  "d2adsv7": {
    linuxPrice: 0.158,
    windowsPrice: 0.25,
  },
  "d2aldsv6": {
    linuxPrice: 0.132,
    windowsPrice: 0.224,
  },
  "d2aldsv7": {
    linuxPrice: 0.132,
    windowsPrice: 0.224,
  },
  "d2alsv6": {
    linuxPrice: 0.111,
    windowsPrice: 0.203,
  },
  "d2alsv7": {
    linuxPrice: 0.111,
    windowsPrice: 0.203,
  },
  "d2asv4": {
    linuxPrice: 0.132,
    windowsPrice: 0.224,
  },
  "d2asv5": {
    linuxPrice: 0.211,
    windowsPrice: 0.211,
  },
  "d2asv6": {
    linuxPrice: 0.126,
    windowsPrice: 0.218,
  },
  "d2asv7": {
    linuxPrice: 0.126,
    windowsPrice: 0.218,
  },
  "d2av4": {
    linuxPrice: 0.132,
    windowsPrice: 0.224,
  },
  "d2dsv4": {
    linuxPrice: 0.155,
    windowsPrice: 0.247,
  },
  "d2dsv5": {
    linuxPrice: 0.155,
    windowsPrice: 0.247,
  },
  "d2dsv6": {
    linuxPrice: 0.171,
    windowsPrice: 0.263,
  },
  "d2dv4": {
    linuxPrice: 0.155,
    windowsPrice: 0.247,
  },
  "d2dv5": {
    linuxPrice: 0.155,
    windowsPrice: 0.247,
  },
  "d2ldsv5": {
    linuxPrice: 0.123,
    windowsPrice: 0.215,
  },
  "d2ldsv6": {
    linuxPrice: 0.152,
    windowsPrice: 0.244,
  },
  "d2lsv5": {
    linuxPrice: 0.108,
    windowsPrice: 0.2,
  },
  "d2lsv6": {
    linuxPrice: 0.123,
    windowsPrice: 0.215,
  },
  "d2ndsv6": {
    linuxPrice: 0.247,
    windowsPrice: 0.339,
  },
  "d2nldsv6": {
    linuxPrice: 0.185,
    windowsPrice: 0.277,
  },
  "d2nlsv6": {
    linuxPrice: 0.15,
    windowsPrice: 0.242,
  },
  "d2nsv6": {
    linuxPrice: 0.216,
    windowsPrice: 0.308,
  },
  "d2pdsv5": {
    linuxPrice: 0.125,
    windowsPrice: 0,
  },
  "d2pdsv6": {
    linuxPrice: 0.126,
    windowsPrice: 0,
  },
  "d2pldsv5": {
    linuxPrice: 0.098,
    windowsPrice: 0,
  },
  "d2pldsv6": {
    linuxPrice: 0.107,
    windowsPrice: 0,
  },
  "d2plsv5": {
    linuxPrice: 0.086,
    windowsPrice: 0,
  },
  "d2plsv6": {
    linuxPrice: 0.0854,
    windowsPrice: 0,
  },
  "d2psv5": {
    linuxPrice: 0.106,
    windowsPrice: 0,
  },
  "d2psv6": {
    linuxPrice: 0.0966,
    windowsPrice: 0,
  },
  "d2s": {
    linuxPrice: 0.225,
    windowsPrice: 0.37,
  },
  "d2sv3": {
    linuxPrice: 0.132,
    windowsPrice: 0.224,
  },
  "d2sv4": {
    linuxPrice: 0.132,
    windowsPrice: 0.224,
  },
  "d2sv5": {
    linuxPrice: 0.132,
    windowsPrice: 0.224,
  },
  "d2sv6": {
    linuxPrice: 0.139,
    windowsPrice: 0.231,
  },
  "d2v2": {
    linuxPrice: 0.214,
    windowsPrice: 0.333,
  },
  "d2v3": {
    linuxPrice: 0.132,
    windowsPrice: 0.224,
  },
  "d2v4": {
    linuxPrice: 0.132,
    windowsPrice: 0.224,
  },
  "d2v5": {
    linuxPrice: 0.132,
    windowsPrice: 0.224,
  },
  "d3": {
    linuxPrice: 0.451,
    windowsPrice: 0.741,
  },
  "d32adsv5": {
    linuxPrice: 3.744,
    windowsPrice: 3.744,
  },
  "d32adsv6": {
    linuxPrice: 2.525,
    windowsPrice: 3.997,
  },
  "d32adsv7": {
    linuxPrice: 2.525,
    windowsPrice: 3.997,
  },
  "d32aldsv6": {
    linuxPrice: 2.109,
    windowsPrice: 3.581,
  },
  "d32aldsv7": {
    linuxPrice: 2.109,
    windowsPrice: 3.581,
  },
  "d32alsv6": {
    linuxPrice: 1.779,
    windowsPrice: 3.251,
  },
  "d32alsv7": {
    linuxPrice: 1.779,
    windowsPrice: 3.251,
  },
  "d32asv4": {
    linuxPrice: 2.112,
    windowsPrice: 3.584,
  },
  "d32asv5": {
    linuxPrice: 3.376,
    windowsPrice: 3.376,
  },
  "d32asv6": {
    linuxPrice: 2.01,
    windowsPrice: 3.482,
  },
  "d32asv7": {
    linuxPrice: 2.01,
    windowsPrice: 3.482,
  },
  "d32av4": {
    linuxPrice: 2.112,
    windowsPrice: 3.584,
  },
  "d32dsv4": {
    linuxPrice: 2.48,
    windowsPrice: 3.952,
  },
  "d32dsv5": {
    linuxPrice: 2.48,
    windowsPrice: 3.952,
  },
  "d32dsv6": {
    linuxPrice: 2.741,
    windowsPrice: 4.213,
  },
  "d32dv4": {
    linuxPrice: 2.48,
    windowsPrice: 3.952,
  },
  "d32dv5": {
    linuxPrice: 2.48,
    windowsPrice: 3.952,
  },
  "d32ldsv5": {
    linuxPrice: 1.968,
    windowsPrice: 3.44,
  },
  "d32ldsv6": {
    linuxPrice: 2.427,
    windowsPrice: 3.899,
  },
  "d32lsv5": {
    linuxPrice: 1.728,
    windowsPrice: 3.2,
  },
  "d32lsv6": {
    linuxPrice: 1.964,
    windowsPrice: 3.436,
  },
  "d32ndsv6": {
    linuxPrice: 3.946,
    windowsPrice: 5.418,
  },
  "d32nldsv6": {
    linuxPrice: 2.967,
    windowsPrice: 4.439,
  },
  "d32nlsv6": {
    linuxPrice: 2.402,
    windowsPrice: 3.874,
  },
  "d32nsv6": {
    linuxPrice: 3.453,
    windowsPrice: 4.925,
  },
  "d32pdsv5": {
    linuxPrice: 1.992,
    windowsPrice: 0,
  },
  "d32pdsv6": {
    linuxPrice: 2.022,
    windowsPrice: 0,
  },
  "d32pldsv5": {
    linuxPrice: 1.568,
    windowsPrice: 0,
  },
  "d32pldsv6": {
    linuxPrice: 1.718,
    windowsPrice: 0,
  },
  "d32plsv5": {
    linuxPrice: 1.376,
    windowsPrice: 0,
  },
  "d32plsv6": {
    linuxPrice: 1.366,
    windowsPrice: 0,
  },
  "d32psv5": {
    linuxPrice: 1.696,
    windowsPrice: 0,
  },
  "d32psv6": {
    linuxPrice: 1.546,
    windowsPrice: 0,
  },
  "d32sv3": {
    linuxPrice: 2.112,
    windowsPrice: 3.584,
  },
  "d32sv4": {
    linuxPrice: 2.112,
    windowsPrice: 3.584,
  },
  "d32sv5": {
    linuxPrice: 2.112,
    windowsPrice: 3.584,
  },
  "d32sv6": {
    linuxPrice: 2.218,
    windowsPrice: 3.69,
  },
  "d32v3": {
    linuxPrice: 2.112,
    windowsPrice: 3.584,
  },
  "d32v4": {
    linuxPrice: 2.112,
    windowsPrice: 3.584,
  },
  "d32v5": {
    linuxPrice: 2.112,
    windowsPrice: 3.584,
  },
  "d3s": {
    linuxPrice: 0.451,
    windowsPrice: 0.741,
  },
  "d3v2": {
    linuxPrice: 0.428,
    windowsPrice: 0.667,
  },
  "d4": {
    linuxPrice: 0.902,
    windowsPrice: 1.481,
  },
  "d48adsv5": {
    linuxPrice: 3.408,
    windowsPrice: 5.616,
  },
  "d48adsv6": {
    linuxPrice: 3.787,
    windowsPrice: 5.995,
  },
  "d48adsv7": {
    linuxPrice: 3.787,
    windowsPrice: 5.995,
  },
  "d48aldsv6": {
    linuxPrice: 3.163,
    windowsPrice: 5.371,
  },
  "d48aldsv7": {
    linuxPrice: 3.163,
    windowsPrice: 5.371,
  },
  "d48alsv6": {
    linuxPrice: 2.669,
    windowsPrice: 4.877,
  },
  "d48alsv7": {
    linuxPrice: 2.669,
    windowsPrice: 4.877,
  },
  "d48asv4": {
    linuxPrice: 3.168,
    windowsPrice: 5.376,
  },
  "d48asv5": {
    linuxPrice: 2.856,
    windowsPrice: 5.064,
  },
  "d48asv6": {
    linuxPrice: 3.014,
    windowsPrice: 5.222,
  },
  "d48asv7": {
    linuxPrice: 3.014,
    windowsPrice: 5.222,
  },
  "d48av4": {
    linuxPrice: 3.168,
    windowsPrice: 5.376,
  },
  "d48dsv4": {
    linuxPrice: 3.72,
    windowsPrice: 5.928,
  },
  "d48dsv5": {
    linuxPrice: 3.72,
    windowsPrice: 5.928,
  },
  "d48dsv6": {
    linuxPrice: 4.111,
    windowsPrice: 6.319,
  },
  "d48dv4": {
    linuxPrice: 3.72,
    windowsPrice: 5.928,
  },
  "d48dv5": {
    linuxPrice: 3.72,
    windowsPrice: 5.928,
  },
  "d48ldsv5": {
    linuxPrice: 2.952,
    windowsPrice: 5.16,
  },
  "d48ldsv6": {
    linuxPrice: 3.641,
    windowsPrice: 5.849,
  },
  "d48lsv5": {
    linuxPrice: 2.592,
    windowsPrice: 4.8,
  },
  "d48lsv6": {
    linuxPrice: 2.946,
    windowsPrice: 5.154,
  },
  "d48ndsv6": {
    linuxPrice: 5.919,
    windowsPrice: 8.127,
  },
  "d48nldsv6": {
    linuxPrice: 4.45,
    windowsPrice: 6.658,
  },
  "d48nlsv6": {
    linuxPrice: 3.604,
    windowsPrice: 5.812,
  },
  "d48nsv6": {
    linuxPrice: 5.179,
    windowsPrice: 7.387,
  },
  "d48pdsv5": {
    linuxPrice: 2.988,
    windowsPrice: 0,
  },
  "d48pdsv6": {
    linuxPrice: 3.034,
    windowsPrice: 0,
  },
  "d48pldsv5": {
    linuxPrice: 2.352,
    windowsPrice: 0,
  },
  "d48pldsv6": {
    linuxPrice: 2.578,
    windowsPrice: 0,
  },
  "d48plsv5": {
    linuxPrice: 2.064,
    windowsPrice: 0,
  },
  "d48plsv6": {
    linuxPrice: 2.05,
    windowsPrice: 0,
  },
  "d48psv5": {
    linuxPrice: 2.544,
    windowsPrice: 0,
  },
  "d48psv6": {
    linuxPrice: 2.318,
    windowsPrice: 0,
  },
  "d48sv3": {
    linuxPrice: 3.168,
    windowsPrice: 5.376,
  },
  "d48sv4": {
    linuxPrice: 3.168,
    windowsPrice: 5.376,
  },
  "d48sv5": {
    linuxPrice: 3.168,
    windowsPrice: 5.376,
  },
  "d48sv6": {
    linuxPrice: 3.326,
    windowsPrice: 5.534,
  },
  "d48v3": {
    linuxPrice: 3.168,
    windowsPrice: 5.376,
  },
  "d48v4": {
    linuxPrice: 3.168,
    windowsPrice: 5.376,
  },
  "d48v5": {
    linuxPrice: 3.168,
    windowsPrice: 5.376,
  },
  "d4adsv5": {
    linuxPrice: 0.468,
    windowsPrice: 0.468,
  },
  "d4adsv6": {
    linuxPrice: 0.316,
    windowsPrice: 0.5,
  },
  "d4adsv7": {
    linuxPrice: 0.316,
    windowsPrice: 0.5,
  },
  "d4aldsv6": {
    linuxPrice: 0.264,
    windowsPrice: 0.448,
  },
  "d4aldsv7": {
    linuxPrice: 0.264,
    windowsPrice: 0.448,
  },
  "d4alsv6": {
    linuxPrice: 0.222,
    windowsPrice: 0.406,
  },
  "d4alsv7": {
    linuxPrice: 0.222,
    windowsPrice: 0.406,
  },
  "d4asv4": {
    linuxPrice: 0.264,
    windowsPrice: 0.448,
  },
  "d4asv5": {
    linuxPrice: 0.238,
    windowsPrice: 0.422,
  },
  "d4asv6": {
    linuxPrice: 0.251,
    windowsPrice: 0.435,
  },
  "d4asv7": {
    linuxPrice: 0.251,
    windowsPrice: 0.435,
  },
  "d4av4": {
    linuxPrice: 0.264,
    windowsPrice: 0.448,
  },
  "d4dsv4": {
    linuxPrice: 0.31,
    windowsPrice: 0.494,
  },
  "d4dsv5": {
    linuxPrice: 0.31,
    windowsPrice: 0.494,
  },
  "d4dsv6": {
    linuxPrice: 0.343,
    windowsPrice: 0.527,
  },
  "d4dv4": {
    linuxPrice: 0.31,
    windowsPrice: 0.494,
  },
  "d4dv5": {
    linuxPrice: 0.31,
    windowsPrice: 0.494,
  },
  "d4ldsv5": {
    linuxPrice: 0.246,
    windowsPrice: 0.43,
  },
  "d4ldsv6": {
    linuxPrice: 0.303,
    windowsPrice: 0.487,
  },
  "d4lsv5": {
    linuxPrice: 0.216,
    windowsPrice: 0.4,
  },
  "d4lsv6": {
    linuxPrice: 0.245,
    windowsPrice: 0.429,
  },
  "d4ndsv6": {
    linuxPrice: 0.454,
    windowsPrice: 0.638,
  },
  "d4nldsv6": {
    linuxPrice: 0.371,
    windowsPrice: 0.555,
  },
  "d4nlsv6": {
    linuxPrice: 0.3,
    windowsPrice: 0.484,
  },
  "d4nsv6": {
    linuxPrice: 0.432,
    windowsPrice: 0.616,
  },
  "d4pdsv5": {
    linuxPrice: 0.249,
    windowsPrice: 0,
  },
  "d4pdsv6": {
    linuxPrice: 0.253,
    windowsPrice: 0,
  },
  "d4pldsv5": {
    linuxPrice: 0.196,
    windowsPrice: 0,
  },
  "d4pldsv6": {
    linuxPrice: 0.215,
    windowsPrice: 0,
  },
  "d4plsv5": {
    linuxPrice: 0.172,
    windowsPrice: 0,
  },
  "d4plsv6": {
    linuxPrice: 0.171,
    windowsPrice: 0,
  },
  "d4psv5": {
    linuxPrice: 0.212,
    windowsPrice: 0,
  },
  "d4psv6": {
    linuxPrice: 0.193,
    windowsPrice: 0,
  },
  "d4s": {
    linuxPrice: 0.902,
    windowsPrice: 1.481,
  },
  "d4sv3": {
    linuxPrice: 0.264,
    windowsPrice: 0.448,
  },
  "d4sv4": {
    linuxPrice: 0.264,
    windowsPrice: 0.448,
  },
  "d4sv5": {
    linuxPrice: 0.264,
    windowsPrice: 0.448,
  },
  "d4sv6": {
    linuxPrice: 0.277,
    windowsPrice: 0.461,
  },
  "d4v2": {
    linuxPrice: 0.857,
    windowsPrice: 1.333,
  },
  "d4v3": {
    linuxPrice: 0.264,
    windowsPrice: 0.448,
  },
  "d4v4": {
    linuxPrice: 0.264,
    windowsPrice: 0.448,
  },
  "d4v5": {
    linuxPrice: 0.264,
    windowsPrice: 0.448,
  },
  "d5v2": {
    linuxPrice: 1.714,
    windowsPrice: 2.666,
  },
  "d64adsv5": {
    linuxPrice: 4.544,
    windowsPrice: 7.488,
  },
  "d64adsv6": {
    linuxPrice: 5.05,
    windowsPrice: 7.994,
  },
  "d64adsv7": {
    linuxPrice: 5.05,
    windowsPrice: 7.994,
  },
  "d64aldsv6": {
    linuxPrice: 4.218,
    windowsPrice: 7.162,
  },
  "d64aldsv7": {
    linuxPrice: 4.218,
    windowsPrice: 7.162,
  },
  "d64alsv6": {
    linuxPrice: 3.558,
    windowsPrice: 6.502,
  },
  "d64alsv7": {
    linuxPrice: 3.558,
    windowsPrice: 6.502,
  },
  "d64asv4": {
    linuxPrice: 4.224,
    windowsPrice: 7.168,
  },
  "d64asv5": {
    linuxPrice: 3.808,
    windowsPrice: 6.752,
  },
  "d64asv6": {
    linuxPrice: 4.019,
    windowsPrice: 6.963,
  },
  "d64asv7": {
    linuxPrice: 4.019,
    windowsPrice: 6.963,
  },
  "d64av4": {
    linuxPrice: 4.224,
    windowsPrice: 7.168,
  },
  "d64dsv4": {
    linuxPrice: 4.96,
    windowsPrice: 7.904,
  },
  "d64dsv5": {
    linuxPrice: 4.96,
    windowsPrice: 7.904,
  },
  "d64dsv6": {
    linuxPrice: 5.482,
    windowsPrice: 8.426,
  },
  "d64dv4": {
    linuxPrice: 4.96,
    windowsPrice: 7.904,
  },
  "d64dv5": {
    linuxPrice: 4.96,
    windowsPrice: 7.904,
  },
  "d64ldsv5": {
    linuxPrice: 3.936,
    windowsPrice: 6.88,
  },
  "d64ldsv6": {
    linuxPrice: 4.854,
    windowsPrice: 7.798,
  },
  "d64lsv5": {
    linuxPrice: 3.456,
    windowsPrice: 6.4,
  },
  "d64lsv6": {
    linuxPrice: 3.928,
    windowsPrice: 6.872,
  },
  "d64ndsv6": {
    linuxPrice: 7.892,
    windowsPrice: 10.836,
  },
  "d64nldsv6": {
    linuxPrice: 5.934,
    windowsPrice: 8.878,
  },
  "d64nlsv6": {
    linuxPrice: 4.805,
    windowsPrice: 7.749,
  },
  "d64nsv6": {
    linuxPrice: 6.906,
    windowsPrice: 9.85,
  },
  "d64pdsv5": {
    linuxPrice: 3.984,
    windowsPrice: 0,
  },
  "d64pdsv6": {
    linuxPrice: 4.045,
    windowsPrice: 0,
  },
  "d64pldsv5": {
    linuxPrice: 3.136,
    windowsPrice: 0,
  },
  "d64pldsv6": {
    linuxPrice: 3.437,
    windowsPrice: 0,
  },
  "d64plsv5": {
    linuxPrice: 2.752,
    windowsPrice: 0,
  },
  "d64plsv6": {
    linuxPrice: 2.733,
    windowsPrice: 0,
  },
  "d64psv5": {
    linuxPrice: 3.392,
    windowsPrice: 0,
  },
  "d64psv6": {
    linuxPrice: 3.091,
    windowsPrice: 0,
  },
  "d64sv3": {
    linuxPrice: 4.224,
    windowsPrice: 7.168,
  },
  "d64sv4": {
    linuxPrice: 4.224,
    windowsPrice: 7.168,
  },
  "d64sv5": {
    linuxPrice: 4.224,
    windowsPrice: 7.168,
  },
  "d64sv6": {
    linuxPrice: 4.435,
    windowsPrice: 7.379,
  },
  "d64v3": {
    linuxPrice: 4.224,
    windowsPrice: 7.168,
  },
  "d64v4": {
    linuxPrice: 4.224,
    windowsPrice: 7.168,
  },
  "d64v5": {
    linuxPrice: 4.224,
    windowsPrice: 7.168,
  },
  "d8adsv5": {
    linuxPrice: 0.936,
    windowsPrice: 0.936,
  },
  "d8adsv6": {
    linuxPrice: 0.631,
    windowsPrice: 0.999,
  },
  "d8adsv7": {
    linuxPrice: 0.631,
    windowsPrice: 0.999,
  },
  "d8aldsv6": {
    linuxPrice: 0.527,
    windowsPrice: 0.895,
  },
  "d8aldsv7": {
    linuxPrice: 0.527,
    windowsPrice: 0.895,
  },
  "d8alsv6": {
    linuxPrice: 0.445,
    windowsPrice: 0.813,
  },
  "d8alsv7": {
    linuxPrice: 0.445,
    windowsPrice: 0.813,
  },
  "d8asv4": {
    linuxPrice: 0.528,
    windowsPrice: 0.896,
  },
  "d8asv5": {
    linuxPrice: 0.844,
    windowsPrice: 0.844,
  },
  "d8asv6": {
    linuxPrice: 0.502,
    windowsPrice: 0.87,
  },
  "d8asv7": {
    linuxPrice: 0.502,
    windowsPrice: 0.87,
  },
  "d8av4": {
    linuxPrice: 0.528,
    windowsPrice: 0.896,
  },
  "d8dsv4": {
    linuxPrice: 0.62,
    windowsPrice: 0.988,
  },
  "d8dsv5": {
    linuxPrice: 0.62,
    windowsPrice: 0.988,
  },
  "d8dsv6": {
    linuxPrice: 0.685,
    windowsPrice: 1.053,
  },
  "d8dv4": {
    linuxPrice: 0.62,
    windowsPrice: 0.988,
  },
  "d8dv5": {
    linuxPrice: 0.62,
    windowsPrice: 0.988,
  },
  "d8ldsv5": {
    linuxPrice: 0.492,
    windowsPrice: 0.86,
  },
  "d8ldsv6": {
    linuxPrice: 0.607,
    windowsPrice: 0.975,
  },
  "d8lsv5": {
    linuxPrice: 0.432,
    windowsPrice: 0.8,
  },
  "d8lsv6": {
    linuxPrice: 0.491,
    windowsPrice: 0.859,
  },
  "d8ndsv6": {
    linuxPrice: 0.987,
    windowsPrice: 1.355,
  },
  "d8nldsv6": {
    linuxPrice: 0.742,
    windowsPrice: 1.11,
  },
  "d8nlsv6": {
    linuxPrice: 0.601,
    windowsPrice: 0.969,
  },
  "d8nsv6": {
    linuxPrice: 0.863,
    windowsPrice: 1.231,
  },
  "d8pdsv5": {
    linuxPrice: 0.498,
    windowsPrice: 0,
  },
  "d8pdsv6": {
    linuxPrice: 0.506,
    windowsPrice: 0,
  },
  "d8pldsv5": {
    linuxPrice: 0.392,
    windowsPrice: 0,
  },
  "d8pldsv6": {
    linuxPrice: 0.43,
    windowsPrice: 0,
  },
  "d8plsv5": {
    linuxPrice: 0.344,
    windowsPrice: 0,
  },
  "d8plsv6": {
    linuxPrice: 0.342,
    windowsPrice: 0,
  },
  "d8psv5": {
    linuxPrice: 0.424,
    windowsPrice: 0,
  },
  "d8psv6": {
    linuxPrice: 0.386,
    windowsPrice: 0,
  },
  "d8sv3": {
    linuxPrice: 0.528,
    windowsPrice: 0.896,
  },
  "d8sv4": {
    linuxPrice: 0.528,
    windowsPrice: 0.896,
  },
  "d8sv5": {
    linuxPrice: 0.528,
    windowsPrice: 0.896,
  },
  "d8sv6": {
    linuxPrice: 0.554,
    windowsPrice: 0.922,
  },
  "d8v3": {
    linuxPrice: 0.528,
    windowsPrice: 0.896,
  },
  "d8v4": {
    linuxPrice: 0.528,
    windowsPrice: 0.896,
  },
  "d8v5": {
    linuxPrice: 0.528,
    windowsPrice: 0.896,
  },
  "d96adsv5": {
    linuxPrice: 6.816,
    windowsPrice: 11.232,
  },
  "d96adsv6": {
    linuxPrice: 7.574,
    windowsPrice: 11.99,
  },
  "d96adsv7": {
    linuxPrice: 7.574,
    windowsPrice: 11.99,
  },
  "d96aldsv6": {
    linuxPrice: 6.326,
    windowsPrice: 10.742,
  },
  "d96aldsv7": {
    linuxPrice: 6.326,
    windowsPrice: 10.742,
  },
  "d96alsv6": {
    linuxPrice: 5.338,
    windowsPrice: 9.754,
  },
  "d96alsv7": {
    linuxPrice: 5.338,
    windowsPrice: 9.754,
  },
  "d96asv4": {
    linuxPrice: 6.336,
    windowsPrice: 10.752,
  },
  "d96asv5": {
    linuxPrice: 5.712,
    windowsPrice: 10.128,
  },
  "d96asv6": {
    linuxPrice: 6.029,
    windowsPrice: 10.445,
  },
  "d96asv7": {
    linuxPrice: 6.029,
    windowsPrice: 10.445,
  },
  "d96av4": {
    linuxPrice: 6.336,
    windowsPrice: 10.752,
  },
  "d96dsv5": {
    linuxPrice: 7.44,
    windowsPrice: 11.856,
  },
  "d96dsv6": {
    linuxPrice: 8.222,
    windowsPrice: 12.638,
  },
  "d96dv5": {
    linuxPrice: 7.44,
    windowsPrice: 11.856,
  },
  "d96ldsv5": {
    linuxPrice: 5.904,
    windowsPrice: 10.32,
  },
  "d96ldsv6": {
    linuxPrice: 7.282,
    windowsPrice: 11.698,
  },
  "d96lsv5": {
    linuxPrice: 5.184,
    windowsPrice: 9.6,
  },
  "d96lsv6": {
    linuxPrice: 5.892,
    windowsPrice: 10.308,
  },
  "d96ndsv6": {
    linuxPrice: 11.839,
    windowsPrice: 16.255,
  },
  "d96nldsv6": {
    linuxPrice: 8.901,
    windowsPrice: 13.317,
  },
  "d96nlsv6": {
    linuxPrice: 7.207,
    windowsPrice: 11.623,
  },
  "d96nsv6": {
    linuxPrice: 10.359,
    windowsPrice: 14.775,
  },
  "d96pdsv6": {
    linuxPrice: 6.067,
    windowsPrice: 0,
  },
  "d96pldsv6": {
    linuxPrice: 5.155,
    windowsPrice: 0,
  },
  "d96plsv6": {
    linuxPrice: 4.099,
    windowsPrice: 0,
  },
  "d96psv6": {
    linuxPrice: 4.637,
    windowsPrice: 0,
  },
  "d96sv5": {
    linuxPrice: 6.336,
    windowsPrice: 10.752,
  },
  "d96sv6": {
    linuxPrice: 6.653,
    windowsPrice: 11.069,
  },
  "d96v5": {
    linuxPrice: 6.336,
    windowsPrice: 10.752,
  },
  "dc16adsv5": {
    linuxPrice: 1.136,
    windowsPrice: 1.872,
  },
  "dc16adsv6": {
    linuxPrice: 1.262,
    windowsPrice: 1.998,
  },
  "dc16asv5": {
    linuxPrice: 0.952,
    windowsPrice: 1.688,
  },
  "dc16asv6": {
    linuxPrice: 1.005,
    windowsPrice: 1.741,
  },
  "dc2adsv5": {
    linuxPrice: 0.142,
    windowsPrice: 0.234,
  },
  "dc2adsv6": {
    linuxPrice: 0.158,
    windowsPrice: 0.25,
  },
  "dc2asv5": {
    linuxPrice: 0.119,
    windowsPrice: 0.211,
  },
  "dc2asv6": {
    linuxPrice: 0.126,
    windowsPrice: 0.218,
  },
  "dc32adsv5": {
    linuxPrice: 2.272,
    windowsPrice: 3.744,
  },
  "dc32adsv6": {
    linuxPrice: 2.525,
    windowsPrice: 3.997,
  },
  "dc32asv5": {
    linuxPrice: 1.904,
    windowsPrice: 3.376,
  },
  "dc32asv6": {
    linuxPrice: 2.01,
    windowsPrice: 3.482,
  },
  "dc48adsv5": {
    linuxPrice: 3.408,
    windowsPrice: 5.616,
  },
  "dc48adsv6": {
    linuxPrice: 3.787,
    windowsPrice: 5.995,
  },
  "dc48asv5": {
    linuxPrice: 2.856,
    windowsPrice: 5.064,
  },
  "dc48asv6": {
    linuxPrice: 3.014,
    windowsPrice: 5.222,
  },
  "dc4adsv5": {
    linuxPrice: 0.284,
    windowsPrice: 0.468,
  },
  "dc4adsv6": {
    linuxPrice: 0.316,
    windowsPrice: 0.5,
  },
  "dc4asv5": {
    linuxPrice: 0.238,
    windowsPrice: 0.422,
  },
  "dc4asv6": {
    linuxPrice: 0.251,
    windowsPrice: 0.435,
  },
  "dc64adsv5": {
    linuxPrice: 4.544,
    windowsPrice: 7.488,
  },
  "dc64adsv6": {
    linuxPrice: 5.05,
    windowsPrice: 7.994,
  },
  "dc64asv5": {
    linuxPrice: 3.808,
    windowsPrice: 6.752,
  },
  "dc64asv6": {
    linuxPrice: 4.019,
    windowsPrice: 6.963,
  },
  "dc8adsv5": {
    linuxPrice: 0.568,
    windowsPrice: 0.936,
  },
  "dc8adsv6": {
    linuxPrice: 0.631,
    windowsPrice: 0.999,
  },
  "dc8asv5": {
    linuxPrice: 0.476,
    windowsPrice: 0.844,
  },
  "dc8asv6": {
    linuxPrice: 0.502,
    windowsPrice: 0.87,
  },
  "dc96adsv5": {
    linuxPrice: 6.816,
    windowsPrice: 11.232,
  },
  "dc96adsv6": {
    linuxPrice: 7.574,
    windowsPrice: 11.99,
  },
  "dc96asv5": {
    linuxPrice: 5.712,
    windowsPrice: 10.128,
  },
  "dc96asv6": {
    linuxPrice: 6.029,
    windowsPrice: 10.445,
  },
  "ds11": {
    linuxPrice: 0.242,
    windowsPrice: 0.352,
  },
  "ds11v2": {
    linuxPrice: 0.229,
    windowsPrice: 0.352,
  },
  "ds12": {
    linuxPrice: 0.483,
    windowsPrice: 0.703,
  },
  "ds12v2": {
    linuxPrice: 0.459,
    windowsPrice: 0.704,
  },
  "ds13": {
    linuxPrice: 0.966,
    windowsPrice: 1.407,
  },
  "ds13v2": {
    linuxPrice: 0.918,
    windowsPrice: 1.407,
  },
  "ds14": {
    linuxPrice: 1.932,
    windowsPrice: 2.814,
  },
  "ds14v2": {
    linuxPrice: 1.835,
    windowsPrice: 2.814,
  },
  "ds15iv2": {
    linuxPrice: 2.294,
    windowsPrice: 3.518,
  },
  "ds15v2": {
    linuxPrice: 2.294,
    windowsPrice: 3.518,
  },
  "ds1v2": {
    linuxPrice: 0.107,
    windowsPrice: 0.167,
  },
  "ds2v2": {
    linuxPrice: 0.214,
    windowsPrice: 0.333,
  },
  "ds3v2": {
    linuxPrice: 0.428,
    windowsPrice: 0.667,
  },
  "ds4v2": {
    linuxPrice: 0.857,
    windowsPrice: 1.333,
  },
  "ds5v2": {
    linuxPrice: 1.714,
    windowsPrice: 2.666,
  },
  "e104idsv5": {
    linuxPrice: 10.01,
    windowsPrice: 14.794,
  },
  "e104idv5": {
    linuxPrice: 10.01,
    windowsPrice: 14.794,
  },
  "e104isv5": {
    linuxPrice: 9.552,
    windowsPrice: 14.336,
  },
  "e104iv5": {
    linuxPrice: 9.552,
    windowsPrice: 14.336,
  },
  "e112bdsv5": {
    linuxPrice: 13.675,
    windowsPrice: 18.827,
  },
  "e112bsv5": {
    linuxPrice: 12.258,
    windowsPrice: 17.41,
  },
  "e128": {
    linuxPrice: 11.643,
    windowsPrice: 18.739,
  },
  "e128adsv7": {
    linuxPrice: 12.851,
    windowsPrice: 18.739,
  },
  "e128asv7": {
    linuxPrice: 10.56,
    windowsPrice: 16.448,
  },
  "e128bdsv6": {
    linuxPrice: 19.021,
    windowsPrice: 24.909,
  },
  "e128bsv6": {
    linuxPrice: 16.977,
    windowsPrice: 22.865,
  },
  "e128dsv6": {
    linuxPrice: 14.39,
    windowsPrice: 20.278,
  },
  "e128ndsv6": {
    linuxPrice: 19.383,
    windowsPrice: 25.271,
  },
  "e128nsv6": {
    linuxPrice: 17.294,
    windowsPrice: 23.182,
  },
  "e128sv6": {
    linuxPrice: 11.643,
    windowsPrice: 17.531,
  },
  "e16": {
    linuxPrice: 1.336,
    windowsPrice: 2.136,
  },
  "e160adsv7": {
    linuxPrice: 16.064,
    windowsPrice: 23.424,
  },
  "e160asv7": {
    linuxPrice: 13.2,
    windowsPrice: 20.56,
  },
  "e16adsv5": {
    linuxPrice: 1.388,
    windowsPrice: 2.124,
  },
  "e16adsv6": {
    linuxPrice: 1.606,
    windowsPrice: 2.342,
  },
  "e16adsv7": {
    linuxPrice: 1.606,
    windowsPrice: 2.342,
  },
  "e16asv4": {
    linuxPrice: 1.336,
    windowsPrice: 2.072,
  },
  "e16asv5": {
    linuxPrice: 1.204,
    windowsPrice: 1.94,
  },
  "e16asv6": {
    linuxPrice: 1.32,
    windowsPrice: 2.056,
  },
  "e16asv7": {
    linuxPrice: 1.32,
    windowsPrice: 2.056,
  },
  "e16av4": {
    linuxPrice: 1.336,
    windowsPrice: 2.072,
  },
  "e16bdsv5": {
    linuxPrice: 1.776,
    windowsPrice: 2.512,
  },
  "e16bdsv6": {
    linuxPrice: 2.378,
    windowsPrice: 3.114,
  },
  "e16bsv5": {
    linuxPrice: 1.592,
    windowsPrice: 2.328,
  },
  "e16bsv6": {
    linuxPrice: 2.122,
    windowsPrice: 2.858,
  },
  "e16dsv4": {
    linuxPrice: 1.4,
    windowsPrice: 2.136,
  },
  "e16dsv5": {
    linuxPrice: 1.4,
    windowsPrice: 2.136,
  },
  "e16dsv6": {
    linuxPrice: 1.799,
    windowsPrice: 2.535,
  },
  "e16dv4": {
    linuxPrice: 1.4,
    windowsPrice: 2.136,
  },
  "e16dv5": {
    linuxPrice: 1.4,
    windowsPrice: 2.136,
  },
  "e16ndsv6": {
    linuxPrice: 2.423,
    windowsPrice: 3.159,
  },
  "e16nsv6": {
    linuxPrice: 2.162,
    windowsPrice: 2.898,
  },
  "e16pdsv5": {
    linuxPrice: 1.124,
    windowsPrice: 0,
  },
  "e16pdsv6": {
    linuxPrice: 1.288,
    windowsPrice: 0,
  },
  "e16psv5": {
    linuxPrice: 1.072,
    windowsPrice: 0,
  },
  "e16psv6": {
    linuxPrice: 1.014,
    windowsPrice: 0,
  },
  "e16sv3": {
    linuxPrice: 1.336,
    windowsPrice: 2.072,
  },
  "e16sv4": {
    linuxPrice: 1.336,
    windowsPrice: 2.072,
  },
  "e16sv5": {
    linuxPrice: 1.336,
    windowsPrice: 2.072,
  },
  "e16sv6": {
    linuxPrice: 1.455,
    windowsPrice: 2.191,
  },
  "e16v3": {
    linuxPrice: 1.336,
    windowsPrice: 2.072,
  },
  "e16v4": {
    linuxPrice: 1.336,
    windowsPrice: 2.072,
  },
  "e16v5": {
    linuxPrice: 1.336,
    windowsPrice: 2.072,
  },
  "e192ibdsv6": {
    linuxPrice: 31.385,
    windowsPrice: 40.217,
  },
  "e192ibsv6": {
    linuxPrice: 28.012,
    windowsPrice: 36.844,
  },
  "e192idsv6": {
    linuxPrice: 23.743,
    windowsPrice: 32.575,
  },
  "e20adsv5": {
    linuxPrice: 2.655,
    windowsPrice: 2.655,
  },
  "e20adsv6": {
    linuxPrice: 2.008,
    windowsPrice: 2.928,
  },
  "e20asv4": {
    linuxPrice: 1.67,
    windowsPrice: 2.59,
  },
  "e20asv5": {
    linuxPrice: 1.505,
    windowsPrice: 2.425,
  },
  "e20asv6": {
    linuxPrice: 1.65,
    windowsPrice: 2.57,
  },
  "e20av4": {
    linuxPrice: 1.67,
    windowsPrice: 2.59,
  },
  "e20dsv4": {
    linuxPrice: 1.75,
    windowsPrice: 2.67,
  },
  "e20dsv5": {
    linuxPrice: 1.75,
    windowsPrice: 2.67,
  },
  "e20dsv6": {
    linuxPrice: 2.248,
    windowsPrice: 3.168,
  },
  "e20dv4": {
    linuxPrice: 1.75,
    windowsPrice: 2.67,
  },
  "e20dv5": {
    linuxPrice: 1.75,
    windowsPrice: 2.67,
  },
  "e20pdsv5": {
    linuxPrice: 1.405,
    windowsPrice: 0,
  },
  "e20psv5": {
    linuxPrice: 1.34,
    windowsPrice: 0,
  },
  "e20sv3": {
    linuxPrice: 1.67,
    windowsPrice: 2.59,
  },
  "e20sv4": {
    linuxPrice: 1.67,
    windowsPrice: 2.59,
  },
  "e20sv5": {
    linuxPrice: 1.67,
    windowsPrice: 2.59,
  },
  "e20sv6": {
    linuxPrice: 1.819,
    windowsPrice: 2.739,
  },
  "e20v3": {
    linuxPrice: 1.67,
    windowsPrice: 2.59,
  },
  "e20v4": {
    linuxPrice: 1.67,
    windowsPrice: 2.59,
  },
  "e20v5": {
    linuxPrice: 1.67,
    windowsPrice: 2.59,
  },
  "e2adsv5": {
    linuxPrice: 0.266,
    windowsPrice: 0.266,
  },
  "e2adsv6": {
    linuxPrice: 0.201,
    windowsPrice: 0.293,
  },
  "e2adsv7": {
    linuxPrice: 0.201,
    windowsPrice: 0.293,
  },
  "e2asv4": {
    linuxPrice: 0.167,
    windowsPrice: 0.259,
  },
  "e2asv5": {
    linuxPrice: 0.15,
    windowsPrice: 0.242,
  },
  "e2asv6": {
    linuxPrice: 0.165,
    windowsPrice: 0.257,
  },
  "e2asv7": {
    linuxPrice: 0.165,
    windowsPrice: 0.257,
  },
  "e2av4": {
    linuxPrice: 0.167,
    windowsPrice: 0.259,
  },
  "e2bdsv5": {
    linuxPrice: 0.222,
    windowsPrice: 0.314,
  },
  "e2bdsv6": {
    linuxPrice: 0.297,
    windowsPrice: 0.389,
  },
  "e2bsv5": {
    linuxPrice: 0.199,
    windowsPrice: 0.291,
  },
  "e2bsv6": {
    linuxPrice: 0.265,
    windowsPrice: 0.357,
  },
  "e2dsv4": {
    linuxPrice: 0.175,
    windowsPrice: 0.267,
  },
  "e2dsv5": {
    linuxPrice: 0.175,
    windowsPrice: 0.267,
  },
  "e2dsv6": {
    linuxPrice: 0.225,
    windowsPrice: 0.317,
  },
  "e2dv4": {
    linuxPrice: 0.175,
    windowsPrice: 0.267,
  },
  "e2dv5": {
    linuxPrice: 0.175,
    windowsPrice: 0.267,
  },
  "e2ndsv6": {
    linuxPrice: 0.303,
    windowsPrice: 0.395,
  },
  "e2nsv6": {
    linuxPrice: 0.27,
    windowsPrice: 0.362,
  },
  "e2pdsv5": {
    linuxPrice: 0.141,
    windowsPrice: 0,
  },
  "e2pdsv6": {
    linuxPrice: 0.161,
    windowsPrice: 0,
  },
  "e2psv5": {
    linuxPrice: 0.134,
    windowsPrice: 0,
  },
  "e2psv6": {
    linuxPrice: 0.127,
    windowsPrice: 0,
  },
  "e2sv3": {
    linuxPrice: 0.167,
    windowsPrice: 0.259,
  },
  "e2sv4": {
    linuxPrice: 0.167,
    windowsPrice: 0.259,
  },
  "e2sv5": {
    linuxPrice: 0.167,
    windowsPrice: 0.259,
  },
  "e2sv6": {
    linuxPrice: 0.182,
    windowsPrice: 0.274,
  },
  "e2v3": {
    linuxPrice: 0.167,
    windowsPrice: 0.259,
  },
  "e2v4": {
    linuxPrice: 0.167,
    windowsPrice: 0.259,
  },
  "e2v5": {
    linuxPrice: 0.167,
    windowsPrice: 0.259,
  },
  "e32": {
    linuxPrice: 2.776,
    windowsPrice: 4.383,
  },
  "e32adsv5": {
    linuxPrice: 4.248,
    windowsPrice: 4.248,
  },
  "e32adsv6": {
    linuxPrice: 3.213,
    windowsPrice: 4.685,
  },
  "e32adsv7": {
    linuxPrice: 3.213,
    windowsPrice: 4.685,
  },
  "e32asv4": {
    linuxPrice: 2.672,
    windowsPrice: 4.144,
  },
  "e32asv5": {
    linuxPrice: 3.88,
    windowsPrice: 3.88,
  },
  "e32asv6": {
    linuxPrice: 2.64,
    windowsPrice: 4.112,
  },
  "e32asv7": {
    linuxPrice: 2.64,
    windowsPrice: 4.112,
  },
  "e32av4": {
    linuxPrice: 2.672,
    windowsPrice: 4.144,
  },
  "e32bdsv5": {
    linuxPrice: 3.552,
    windowsPrice: 5.024,
  },
  "e32bdsv6": {
    linuxPrice: 4.755,
    windowsPrice: 6.227,
  },
  "e32bsv5": {
    linuxPrice: 3.184,
    windowsPrice: 4.656,
  },
  "e32bsv6": {
    linuxPrice: 4.244,
    windowsPrice: 5.716,
  },
  "e32dsv4": {
    linuxPrice: 2.8,
    windowsPrice: 4.272,
  },
  "e32dsv5": {
    linuxPrice: 2.8,
    windowsPrice: 4.272,
  },
  "e32dsv6": {
    linuxPrice: 3.597,
    windowsPrice: 5.069,
  },
  "e32dv4": {
    linuxPrice: 2.8,
    windowsPrice: 4.272,
  },
  "e32dv5": {
    linuxPrice: 2.8,
    windowsPrice: 4.272,
  },
  "e32ndsv6": {
    linuxPrice: 4.846,
    windowsPrice: 6.318,
  },
  "e32nsv6": {
    linuxPrice: 4.323,
    windowsPrice: 5.795,
  },
  "e32pdsv5": {
    linuxPrice: 2.248,
    windowsPrice: 0,
  },
  "e32pdsv6": {
    linuxPrice: 2.576,
    windowsPrice: 0,
  },
  "e32psv5": {
    linuxPrice: 2.144,
    windowsPrice: 0,
  },
  "e32psv6": {
    linuxPrice: 2.029,
    windowsPrice: 0,
  },
  "e32sv3": {
    linuxPrice: 2.672,
    windowsPrice: 4.144,
  },
  "e32sv4": {
    linuxPrice: 2.672,
    windowsPrice: 4.144,
  },
  "e32sv5": {
    linuxPrice: 2.672,
    windowsPrice: 4.144,
  },
  "e32sv6": {
    linuxPrice: 2.911,
    windowsPrice: 4.383,
  },
  "e32v3": {
    linuxPrice: 2.672,
    windowsPrice: 4.144,
  },
  "e32v4": {
    linuxPrice: 2.672,
    windowsPrice: 4.144,
  },
  "e32v5": {
    linuxPrice: 2.672,
    windowsPrice: 4.144,
  },
  "e4": {
    linuxPrice: 0.35,
    windowsPrice: 0.548,
  },
  "e48adsv5": {
    linuxPrice: 4.164,
    windowsPrice: 6.372,
  },
  "e48adsv6": {
    linuxPrice: 4.819,
    windowsPrice: 7.027,
  },
  "e48adsv7": {
    linuxPrice: 4.819,
    windowsPrice: 7.027,
  },
  "e48asv4": {
    linuxPrice: 4.008,
    windowsPrice: 6.216,
  },
  "e48asv5": {
    linuxPrice: 5.82,
    windowsPrice: 5.82,
  },
  "e48asv6": {
    linuxPrice: 3.96,
    windowsPrice: 6.168,
  },
  "e48asv7": {
    linuxPrice: 3.96,
    windowsPrice: 6.168,
  },
  "e48av4": {
    linuxPrice: 4.008,
    windowsPrice: 6.216,
  },
  "e48bdsv5": {
    linuxPrice: 5.328,
    windowsPrice: 7.536,
  },
  "e48bdsv6": {
    linuxPrice: 7.133,
    windowsPrice: 9.341,
  },
  "e48bsv5": {
    linuxPrice: 4.776,
    windowsPrice: 6.984,
  },
  "e48bsv6": {
    linuxPrice: 6.366,
    windowsPrice: 8.574,
  },
  "e48dsv4": {
    linuxPrice: 4.2,
    windowsPrice: 6.408,
  },
  "e48dsv5": {
    linuxPrice: 4.2,
    windowsPrice: 6.408,
  },
  "e48dsv6": {
    linuxPrice: 5.396,
    windowsPrice: 7.604,
  },
  "e48dv4": {
    linuxPrice: 4.2,
    windowsPrice: 6.408,
  },
  "e48dv5": {
    linuxPrice: 4.2,
    windowsPrice: 6.408,
  },
  "e48ndsv6": {
    linuxPrice: 7.268,
    windowsPrice: 9.476,
  },
  "e48nsv6": {
    linuxPrice: 6.485,
    windowsPrice: 8.693,
  },
  "e48pdsv6": {
    linuxPrice: 3.864,
    windowsPrice: 0,
  },
  "e48psv6": {
    linuxPrice: 3.043,
    windowsPrice: 0,
  },
  "e48sv3": {
    linuxPrice: 4.008,
    windowsPrice: 6.216,
  },
  "e48sv4": {
    linuxPrice: 4.008,
    windowsPrice: 6.216,
  },
  "e48sv5": {
    linuxPrice: 4.008,
    windowsPrice: 6.216,
  },
  "e48sv6": {
    linuxPrice: 4.366,
    windowsPrice: 6.574,
  },
  "e48v3": {
    linuxPrice: 4.008,
    windowsPrice: 6.216,
  },
  "e48v4": {
    linuxPrice: 4.008,
    windowsPrice: 6.216,
  },
  "e48v5": {
    linuxPrice: 4.008,
    windowsPrice: 6.216,
  },
  "e4adsv5": {
    linuxPrice: 0.347,
    windowsPrice: 0.531,
  },
  "e4adsv6": {
    linuxPrice: 0.402,
    windowsPrice: 0.586,
  },
  "e4adsv7": {
    linuxPrice: 0.402,
    windowsPrice: 0.586,
  },
  "e4asv4": {
    linuxPrice: 0.334,
    windowsPrice: 0.518,
  },
  "e4asv5": {
    linuxPrice: 0.301,
    windowsPrice: 0.485,
  },
  "e4asv6": {
    linuxPrice: 0.33,
    windowsPrice: 0.514,
  },
  "e4asv7": {
    linuxPrice: 0.33,
    windowsPrice: 0.514,
  },
  "e4av4": {
    linuxPrice: 0.334,
    windowsPrice: 0.518,
  },
  "e4bdsv5": {
    linuxPrice: 0.444,
    windowsPrice: 0.628,
  },
  "e4bdsv6": {
    linuxPrice: 0.594,
    windowsPrice: 0.778,
  },
  "e4bsv5": {
    linuxPrice: 0.398,
    windowsPrice: 0.582,
  },
  "e4bsv6": {
    linuxPrice: 0.531,
    windowsPrice: 0.715,
  },
  "e4dsv4": {
    linuxPrice: 0.35,
    windowsPrice: 0.534,
  },
  "e4dsv5": {
    linuxPrice: 0.35,
    windowsPrice: 0.534,
  },
  "e4dsv6": {
    linuxPrice: 0.45,
    windowsPrice: 0.634,
  },
  "e4dv4": {
    linuxPrice: 0.35,
    windowsPrice: 0.534,
  },
  "e4dv5": {
    linuxPrice: 0.35,
    windowsPrice: 0.534,
  },
  "e4ndsv6": {
    linuxPrice: 0.606,
    windowsPrice: 0.79,
  },
  "e4nsv6": {
    linuxPrice: 0.54,
    windowsPrice: 0.724,
  },
  "e4pdsv5": {
    linuxPrice: 0.281,
    windowsPrice: 0,
  },
  "e4pdsv6": {
    linuxPrice: 0.322,
    windowsPrice: 0,
  },
  "e4psv5": {
    linuxPrice: 0.268,
    windowsPrice: 0,
  },
  "e4psv6": {
    linuxPrice: 0.254,
    windowsPrice: 0,
  },
  "e4sv3": {
    linuxPrice: 0.334,
    windowsPrice: 0.518,
  },
  "e4sv4": {
    linuxPrice: 0.334,
    windowsPrice: 0.518,
  },
  "e4sv5": {
    linuxPrice: 0.334,
    windowsPrice: 0.518,
  },
  "e4sv6": {
    linuxPrice: 0.364,
    windowsPrice: 0.548,
  },
  "e4v3": {
    linuxPrice: 0.334,
    windowsPrice: 0.518,
  },
  "e4v4": {
    linuxPrice: 0.334,
    windowsPrice: 0.518,
  },
  "e4v5": {
    linuxPrice: 0.334,
    windowsPrice: 0.518,
  },
  "e64": {
    linuxPrice: 4.81,
    windowsPrice: 7.76,
  },
  "e64adsv5": {
    linuxPrice: 5.552,
    windowsPrice: 8.496,
  },
  "e64adsv6": {
    linuxPrice: 6.426,
    windowsPrice: 9.37,
  },
  "e64adsv7": {
    linuxPrice: 6.426,
    windowsPrice: 9.37,
  },
  "e64asv4": {
    linuxPrice: 5.344,
    windowsPrice: 8.288,
  },
  "e64asv5": {
    linuxPrice: 4.816,
    windowsPrice: 7.76,
  },
  "e64asv6": {
    linuxPrice: 5.28,
    windowsPrice: 8.224,
  },
  "e64asv7": {
    linuxPrice: 5.28,
    windowsPrice: 8.224,
  },
  "e64av4": {
    linuxPrice: 5.344,
    windowsPrice: 8.288,
  },
  "e64bdsv5": {
    linuxPrice: 7.104,
    windowsPrice: 10.048,
  },
  "e64bdsv6": {
    linuxPrice: 9.511,
    windowsPrice: 12.455,
  },
  "e64bsv5": {
    linuxPrice: 6.368,
    windowsPrice: 9.312,
  },
  "e64bsv6": {
    linuxPrice: 8.488,
    windowsPrice: 11.432,
  },
  "e64dsv4": {
    linuxPrice: 5.6,
    windowsPrice: 8.544,
  },
  "e64dsv5": {
    linuxPrice: 5.6,
    windowsPrice: 8.544,
  },
  "e64dsv6": {
    linuxPrice: 7.195,
    windowsPrice: 10.139,
  },
  "e64dv4": {
    linuxPrice: 5.6,
    windowsPrice: 8.544,
  },
  "e64dv5": {
    linuxPrice: 5.6,
    windowsPrice: 8.544,
  },
  "e64isv3": {
    linuxPrice: 4.81,
    windowsPrice: 7.754,
  },
  "e64iv3": {
    linuxPrice: 4.81,
    windowsPrice: 7.754,
  },
  "e64ndsv6": {
    linuxPrice: 9.691,
    windowsPrice: 12.635,
  },
  "e64nsv6": {
    linuxPrice: 8.647,
    windowsPrice: 11.591,
  },
  "e64pdsv6": {
    linuxPrice: 5.152,
    windowsPrice: 0,
  },
  "e64psv6": {
    linuxPrice: 4.058,
    windowsPrice: 0,
  },
  "e64sv3": {
    linuxPrice: 4.81,
    windowsPrice: 7.754,
  },
  "e64sv4": {
    linuxPrice: 5.344,
    windowsPrice: 8.288,
  },
  "e64sv5": {
    linuxPrice: 5.344,
    windowsPrice: 8.288,
  },
  "e64sv6": {
    linuxPrice: 5.821,
    windowsPrice: 8.765,
  },
  "e64v3": {
    linuxPrice: 4.81,
    windowsPrice: 7.754,
  },
  "e64v4": {
    linuxPrice: 5.344,
    windowsPrice: 8.288,
  },
  "e64v5": {
    linuxPrice: 5.344,
    windowsPrice: 8.288,
  },
  "e8": {
    linuxPrice: 0.7,
    windowsPrice: 1.036,
  },
  "e80idsv4": {
    linuxPrice: 7,
    windowsPrice: 10.68,
  },
  "e80isv4": {
    linuxPrice: 6.68,
    windowsPrice: 10.36,
  },
  "e8adsv5": {
    linuxPrice: 0.694,
    windowsPrice: 1.062,
  },
  "e8adsv6": {
    linuxPrice: 0.803,
    windowsPrice: 1.171,
  },
  "e8adsv7": {
    linuxPrice: 0.803,
    windowsPrice: 1.171,
  },
  "e8asv4": {
    linuxPrice: 0.668,
    windowsPrice: 1.036,
  },
  "e8asv5": {
    linuxPrice: 0.97,
    windowsPrice: 0.97,
  },
  "e8asv6": {
    linuxPrice: 0.66,
    windowsPrice: 1.028,
  },
  "e8asv7": {
    linuxPrice: 0.66,
    windowsPrice: 1.028,
  },
  "e8av4": {
    linuxPrice: 0.668,
    windowsPrice: 1.036,
  },
  "e8bdsv5": {
    linuxPrice: 0.888,
    windowsPrice: 1.256,
  },
  "e8bdsv6": {
    linuxPrice: 1.189,
    windowsPrice: 1.557,
  },
  "e8bsv5": {
    linuxPrice: 0.796,
    windowsPrice: 1.164,
  },
  "e8bsv6": {
    linuxPrice: 1.061,
    windowsPrice: 1.429,
  },
  "e8dsv4": {
    linuxPrice: 0.7,
    windowsPrice: 1.068,
  },
  "e8dsv5": {
    linuxPrice: 0.7,
    windowsPrice: 1.068,
  },
  "e8dsv6": {
    linuxPrice: 0.899,
    windowsPrice: 1.267,
  },
  "e8dv4": {
    linuxPrice: 0.7,
    windowsPrice: 1.068,
  },
  "e8dv5": {
    linuxPrice: 0.7,
    windowsPrice: 1.068,
  },
  "e8ndsv6": {
    linuxPrice: 1.211,
    windowsPrice: 1.579,
  },
  "e8nsv6": {
    linuxPrice: 1.081,
    windowsPrice: 1.449,
  },
  "e8pdsv5": {
    linuxPrice: 0.562,
    windowsPrice: 0,
  },
  "e8pdsv6": {
    linuxPrice: 0.644,
    windowsPrice: 0,
  },
  "e8psv5": {
    linuxPrice: 0.536,
    windowsPrice: 0,
  },
  "e8psv6": {
    linuxPrice: 0.507,
    windowsPrice: 0,
  },
  "e8sv3": {
    linuxPrice: 0.668,
    windowsPrice: 1.036,
  },
  "e8sv4": {
    linuxPrice: 0.668,
    windowsPrice: 1.036,
  },
  "e8sv5": {
    linuxPrice: 0.668,
    windowsPrice: 1.036,
  },
  "e8sv6": {
    linuxPrice: 0.728,
    windowsPrice: 1.096,
  },
  "e8v3": {
    linuxPrice: 0.668,
    windowsPrice: 1.036,
  },
  "e8v4": {
    linuxPrice: 0.668,
    windowsPrice: 1.036,
  },
  "e8v5": {
    linuxPrice: 0.668,
    windowsPrice: 1.036,
  },
  "e96": {
    linuxPrice: 9.638,
    windowsPrice: 12.336,
  },
  "e96adsv5": {
    linuxPrice: 12.744,
    windowsPrice: 12.744,
  },
  "e96adsv6": {
    linuxPrice: 9.638,
    windowsPrice: 14.054,
  },
  "e96adsv7": {
    linuxPrice: 9.638,
    windowsPrice: 14.054,
  },
  "e96asv4": {
    linuxPrice: 8.016,
    windowsPrice: 12.432,
  },
  "e96asv5": {
    linuxPrice: 11.64,
    windowsPrice: 11.64,
  },
  "e96asv6": {
    linuxPrice: 7.92,
    windowsPrice: 12.336,
  },
  "e96asv7": {
    linuxPrice: 7.92,
    windowsPrice: 12.336,
  },
  "e96av4": {
    linuxPrice: 8.016,
    windowsPrice: 12.432,
  },
  "e96bdsv5": {
    linuxPrice: 10.656,
    windowsPrice: 15.072,
  },
  "e96bdsv6": {
    linuxPrice: 14.266,
    windowsPrice: 18.682,
  },
  "e96bsv5": {
    linuxPrice: 9.552,
    windowsPrice: 13.968,
  },
  "e96bsv6": {
    linuxPrice: 12.733,
    windowsPrice: 17.149,
  },
  "e96dsv5": {
    linuxPrice: 8.4,
    windowsPrice: 12.816,
  },
  "e96dsv6": {
    linuxPrice: 10.792,
    windowsPrice: 15.208,
  },
  "e96dv5": {
    linuxPrice: 8.4,
    windowsPrice: 12.816,
  },
  "e96ndsv6": {
    linuxPrice: 14.537,
    windowsPrice: 18.953,
  },
  "e96nsv6": {
    linuxPrice: 12.97,
    windowsPrice: 17.386,
  },
  "e96pdsv6": {
    linuxPrice: 7.728,
    windowsPrice: 0,
  },
  "e96psv6": {
    linuxPrice: 6.086,
    windowsPrice: 0,
  },
  "e96sv5": {
    linuxPrice: 8.016,
    windowsPrice: 12.432,
  },
  "e96sv6": {
    linuxPrice: 8.732,
    windowsPrice: 13.148,
  },
  "e96v5": {
    linuxPrice: 8.016,
    windowsPrice: 12.432,
  },
  "ec16adsv5": {
    linuxPrice: 1.388,
    windowsPrice: 2.124,
  },
  "ec16adsv6": {
    linuxPrice: 1.606,
    windowsPrice: 2.342,
  },
  "ec16asv5": {
    linuxPrice: 1.204,
    windowsPrice: 1.94,
  },
  "ec16asv6": {
    linuxPrice: 1.32,
    windowsPrice: 2.056,
  },
  "ec20adsv5": {
    linuxPrice: 1.735,
    windowsPrice: 2.655,
  },
  "ec20asv5": {
    linuxPrice: 1.505,
    windowsPrice: 2.425,
  },
  "ec2adsv5": {
    linuxPrice: 0.174,
    windowsPrice: 0.266,
  },
  "ec2adsv6": {
    linuxPrice: 0.201,
    windowsPrice: 0.293,
  },
  "ec2asv5": {
    linuxPrice: 0.151,
    windowsPrice: 0.243,
  },
  "ec2asv6": {
    linuxPrice: 0.165,
    windowsPrice: 0.257,
  },
  "ec32adsv5": {
    linuxPrice: 2.776,
    windowsPrice: 4.248,
  },
  "ec32adsv6": {
    linuxPrice: 3.213,
    windowsPrice: 4.685,
  },
  "ec32asv5": {
    linuxPrice: 2.408,
    windowsPrice: 3.88,
  },
  "ec32asv6": {
    linuxPrice: 2.64,
    windowsPrice: 4.112,
  },
  "ec48adsv5": {
    linuxPrice: 4.164,
    windowsPrice: 6.372,
  },
  "ec48adsv6": {
    linuxPrice: 4.819,
    windowsPrice: 7.027,
  },
  "ec48asv5": {
    linuxPrice: 3.612,
    windowsPrice: 5.82,
  },
  "ec48asv6": {
    linuxPrice: 3.96,
    windowsPrice: 6.168,
  },
  "ec4adsv5": {
    linuxPrice: 0.347,
    windowsPrice: 0.531,
  },
  "ec4adsv6": {
    linuxPrice: 0.402,
    windowsPrice: 0.586,
  },
  "ec4asv5": {
    linuxPrice: 0.301,
    windowsPrice: 0.485,
  },
  "ec4asv6": {
    linuxPrice: 0.33,
    windowsPrice: 0.514,
  },
  "ec64adsv5": {
    linuxPrice: 5.552,
    windowsPrice: 8.496,
  },
  "ec64adsv6": {
    linuxPrice: 6.426,
    windowsPrice: 9.37,
  },
  "ec64asv5": {
    linuxPrice: 4.816,
    windowsPrice: 7.76,
  },
  "ec64asv6": {
    linuxPrice: 5.28,
    windowsPrice: 8.224,
  },
  "ec8adsv5": {
    linuxPrice: 0.694,
    windowsPrice: 1.062,
  },
  "ec8adsv6": {
    linuxPrice: 0.803,
    windowsPrice: 1.171,
  },
  "ec8asv5": {
    linuxPrice: 0.602,
    windowsPrice: 0.97,
  },
  "ec8asv6": {
    linuxPrice: 0.66,
    windowsPrice: 1.028,
  },
  "ec96adsv5": {
    linuxPrice: 8.328,
    windowsPrice: 12.744,
  },
  "ec96adsv6": {
    linuxPrice: 9.638,
    windowsPrice: 14.054,
  },
  "ec96asv5": {
    linuxPrice: 7.224,
    windowsPrice: 11.64,
  },
  "ec96asv6": {
    linuxPrice: 7.92,
    windowsPrice: 12.336,
  },
  "ec96iadsv5": {
    linuxPrice: 9.161,
    windowsPrice: 13.577,
  },
  "ec96iasv5": {
    linuxPrice: 7.946,
    windowsPrice: 12.362,
  },
  "f1": {
    linuxPrice: 0.072,
    windowsPrice: 0.129,
  },
  "f16": {
    linuxPrice: 1.155,
    windowsPrice: 2.072,
  },
  "f16adsv7": {
    linuxPrice: 1.898,
    windowsPrice: 2.634,
  },
  "f16aldsv7": {
    linuxPrice: 1.584,
    windowsPrice: 2.32,
  },
  "f16alsv6": {
    linuxPrice: 1.339,
    windowsPrice: 2.075,
  },
  "f16alsv7": {
    linuxPrice: 1.339,
    windowsPrice: 2.075,
  },
  "f16amdsv7": {
    linuxPrice: 2.413,
    windowsPrice: 3.149,
  },
  "f16amsv6": {
    linuxPrice: 1.981,
    windowsPrice: 2.717,
  },
  "f16amsv7": {
    linuxPrice: 1.981,
    windowsPrice: 2.717,
  },
  "f16asv6": {
    linuxPrice: 1.512,
    windowsPrice: 2.248,
  },
  "f16asv7": {
    linuxPrice: 1.512,
    windowsPrice: 2.248,
  },
  "f16s": {
    linuxPrice: 1.155,
    windowsPrice: 2.072,
  },
  "f16sv2": {
    linuxPrice: 0.864,
    windowsPrice: 1.6,
  },
  "f1adsv7": {
    linuxPrice: 0.119,
    windowsPrice: 0.165,
  },
  "f1aldsv7": {
    linuxPrice: 0.099,
    windowsPrice: 0.145,
  },
  "f1alsv7": {
    linuxPrice: 0.0837,
    windowsPrice: 0.13,
  },
  "f1amdsv7": {
    linuxPrice: 0.151,
    windowsPrice: 0.197,
  },
  "f1amsv7": {
    linuxPrice: 0.124,
    windowsPrice: 0.17,
  },
  "f1asv7": {
    linuxPrice: 0.0945,
    windowsPrice: 0.141,
  },
  "f1s": {
    linuxPrice: 0.072,
    windowsPrice: 0.129,
  },
  "f2": {
    linuxPrice: 0.144,
    windowsPrice: 0.259,
  },
  "f2adsv7": {
    linuxPrice: 0.237,
    windowsPrice: 0.329,
  },
  "f2aldsv7": {
    linuxPrice: 0.198,
    windowsPrice: 0.29,
  },
  "f2alsv6": {
    linuxPrice: 0.167,
    windowsPrice: 0.259,
  },
  "f2alsv7": {
    linuxPrice: 0.167,
    windowsPrice: 0.259,
  },
  "f2amdsv7": {
    linuxPrice: 0.302,
    windowsPrice: 0.394,
  },
  "f2amsv6": {
    linuxPrice: 0.248,
    windowsPrice: 0.34,
  },
  "f2amsv7": {
    linuxPrice: 0.248,
    windowsPrice: 0.34,
  },
  "f2asv6": {
    linuxPrice: 0.189,
    windowsPrice: 0.281,
  },
  "f2asv7": {
    linuxPrice: 0.189,
    windowsPrice: 0.281,
  },
  "f2s": {
    linuxPrice: 0.144,
    windowsPrice: 0.259,
  },
  "f2sv2": {
    linuxPrice: 0.108,
    windowsPrice: 0.2,
  },
  "f32": {
    linuxPrice: 4.826,
    windowsPrice: 5.434,
  },
  "f32adsv7": {
    linuxPrice: 3.797,
    windowsPrice: 5.269,
  },
  "f32aldsv7": {
    linuxPrice: 3.167,
    windowsPrice: 4.639,
  },
  "f32alsv6": {
    linuxPrice: 2.678,
    windowsPrice: 4.15,
  },
  "f32alsv7": {
    linuxPrice: 2.678,
    windowsPrice: 4.15,
  },
  "f32amdsv7": {
    linuxPrice: 4.826,
    windowsPrice: 6.298,
  },
  "f32amsv6": {
    linuxPrice: 3.962,
    windowsPrice: 5.434,
  },
  "f32amsv7": {
    linuxPrice: 3.962,
    windowsPrice: 5.434,
  },
  "f32asv6": {
    linuxPrice: 3.024,
    windowsPrice: 4.496,
  },
  "f32asv7": {
    linuxPrice: 3.024,
    windowsPrice: 4.496,
  },
  "f32sv2": {
    linuxPrice: 1.728,
    windowsPrice: 3.2,
  },
  "f4": {
    linuxPrice: 0.289,
    windowsPrice: 0.518,
  },
  "f48adsv7": {
    linuxPrice: 5.695,
    windowsPrice: 7.903,
  },
  "f48aldsv7": {
    linuxPrice: 4.751,
    windowsPrice: 6.959,
  },
  "f48alsv6": {
    linuxPrice: 4.018,
    windowsPrice: 6.226,
  },
  "f48alsv7": {
    linuxPrice: 4.018,
    windowsPrice: 6.226,
  },
  "f48amdsv7": {
    linuxPrice: 7.238,
    windowsPrice: 9.446,
  },
  "f48amsv6": {
    linuxPrice: 5.942,
    windowsPrice: 8.15,
  },
  "f48amsv7": {
    linuxPrice: 5.942,
    windowsPrice: 8.15,
  },
  "f48asv6": {
    linuxPrice: 4.536,
    windowsPrice: 6.744,
  },
  "f48asv7": {
    linuxPrice: 4.536,
    windowsPrice: 6.744,
  },
  "f48sv2": {
    linuxPrice: 2.592,
    windowsPrice: 4.8,
  },
  "f4adsv7": {
    linuxPrice: 0.475,
    windowsPrice: 0.659,
  },
  "f4aldsv7": {
    linuxPrice: 0.396,
    windowsPrice: 0.58,
  },
  "f4alsv6": {
    linuxPrice: 0.335,
    windowsPrice: 0.519,
  },
  "f4alsv7": {
    linuxPrice: 0.335,
    windowsPrice: 0.519,
  },
  "f4amdsv7": {
    linuxPrice: 0.603,
    windowsPrice: 0.787,
  },
  "f4amsv6": {
    linuxPrice: 0.495,
    windowsPrice: 0.679,
  },
  "f4amsv7": {
    linuxPrice: 0.495,
    windowsPrice: 0.679,
  },
  "f4asv6": {
    linuxPrice: 0.378,
    windowsPrice: 0.562,
  },
  "f4asv7": {
    linuxPrice: 0.378,
    windowsPrice: 0.562,
  },
  "f4s": {
    linuxPrice: 0.289,
    windowsPrice: 0.518,
  },
  "f4sv2": {
    linuxPrice: 0.216,
    windowsPrice: 0.4,
  },
  "f64": {
    linuxPrice: 7.923,
    windowsPrice: 12.595,
  },
  "f64adsv7": {
    linuxPrice: 7.593,
    windowsPrice: 10.537,
  },
  "f64aldsv7": {
    linuxPrice: 6.335,
    windowsPrice: 9.279,
  },
  "f64alsv6": {
    linuxPrice: 5.357,
    windowsPrice: 8.301,
  },
  "f64alsv7": {
    linuxPrice: 5.357,
    windowsPrice: 8.301,
  },
  "f64amdsv7": {
    linuxPrice: 9.651,
    windowsPrice: 12.595,
  },
  "f64amsv6": {
    linuxPrice: 7.923,
    windowsPrice: 10.867,
  },
  "f64amsv7": {
    linuxPrice: 7.923,
    windowsPrice: 10.867,
  },
  "f64asv6": {
    linuxPrice: 6.048,
    windowsPrice: 8.992,
  },
  "f64asv7": {
    linuxPrice: 6.048,
    windowsPrice: 8.992,
  },
  "f64sv2": {
    linuxPrice: 3.456,
    windowsPrice: 6.4,
  },
  "f72sv2": {
    linuxPrice: 3.888,
    windowsPrice: 7.2,
  },
  "f8": {
    linuxPrice: 0.578,
    windowsPrice: 1.036,
  },
  "f80adsv7": {
    linuxPrice: 9.492,
    windowsPrice: 13.172,
  },
  "f80aldsv7": {
    linuxPrice: 7.919,
    windowsPrice: 11.599,
  },
  "f80alsv7": {
    linuxPrice: 6.696,
    windowsPrice: 10.376,
  },
  "f80amdsv7": {
    linuxPrice: 12.064,
    windowsPrice: 15.744,
  },
  "f80amsv7": {
    linuxPrice: 9.904,
    windowsPrice: 13.584,
  },
  "f80asv7": {
    linuxPrice: 7.56,
    windowsPrice: 11.24,
  },
  "f8adsv7": {
    linuxPrice: 0.949,
    windowsPrice: 1.317,
  },
  "f8aldsv7": {
    linuxPrice: 0.792,
    windowsPrice: 1.16,
  },
  "f8alsv6": {
    linuxPrice: 0.67,
    windowsPrice: 1.038,
  },
  "f8alsv7": {
    linuxPrice: 0.67,
    windowsPrice: 1.038,
  },
  "f8amdsv7": {
    linuxPrice: 1.206,
    windowsPrice: 1.574,
  },
  "f8amsv6": {
    linuxPrice: 0.99,
    windowsPrice: 1.358,
  },
  "f8amsv7": {
    linuxPrice: 0.99,
    windowsPrice: 1.358,
  },
  "f8asv6": {
    linuxPrice: 0.756,
    windowsPrice: 1.124,
  },
  "f8asv7": {
    linuxPrice: 0.756,
    windowsPrice: 1.124,
  },
  "f8s": {
    linuxPrice: 0.578,
    windowsPrice: 1.036,
  },
  "f8sv2": {
    linuxPrice: 0.432,
    windowsPrice: 0.8,
  },
  "l12aosv4": {
    linuxPrice: 1.788,
    windowsPrice: 2.34,
  },
  "l16aosv4": {
    linuxPrice: 2.384,
    windowsPrice: 3.12,
  },
  "l16asv3": {
    linuxPrice: 1.648,
    windowsPrice: 2.384,
  },
  "l16asv4": {
    linuxPrice: 1.813,
    windowsPrice: 2.549,
  },
  "l16sv3": {
    linuxPrice: 1.84,
    windowsPrice: 2.576,
  },
  "l16sv4": {
    linuxPrice: 2.158,
    windowsPrice: 2.894,
  },
  "l24aosv4": {
    linuxPrice: 3.576,
    windowsPrice: 4.68,
  },
  "l2aosv4": {
    linuxPrice: 0.298,
    windowsPrice: 0.39,
  },
  "l2asv4": {
    linuxPrice: 0.227,
    windowsPrice: 0.319,
  },
  "l2sv4": {
    linuxPrice: 0.27,
    windowsPrice: 0.362,
  },
  "l32aosv4": {
    linuxPrice: 4.768,
    windowsPrice: 6.24,
  },
  "l32asv3": {
    linuxPrice: 3.296,
    windowsPrice: 4.768,
  },
  "l32asv4": {
    linuxPrice: 3.626,
    windowsPrice: 5.098,
  },
  "l32sv3": {
    linuxPrice: 3.68,
    windowsPrice: 5.152,
  },
  "l32sv4": {
    linuxPrice: 4.315,
    windowsPrice: 5.787,
  },
  "l48asv3": {
    linuxPrice: 4.944,
    windowsPrice: 7.152,
  },
  "l48asv4": {
    linuxPrice: 5.438,
    windowsPrice: 7.646,
  },
  "l48sv3": {
    linuxPrice: 5.52,
    windowsPrice: 7.728,
  },
  "l48sv4": {
    linuxPrice: 6.473,
    windowsPrice: 8.681,
  },
  "l4aosv4": {
    linuxPrice: 0.596,
    windowsPrice: 0.78,
  },
  "l4asv4": {
    linuxPrice: 0.453,
    windowsPrice: 0.637,
  },
  "l4sv4": {
    linuxPrice: 0.539,
    windowsPrice: 0.723,
  },
  "l64asv3": {
    linuxPrice: 6.592,
    windowsPrice: 9.536,
  },
  "l64asv4": {
    linuxPrice: 7.251,
    windowsPrice: 10.195,
  },
  "l64sv3": {
    linuxPrice: 7.36,
    windowsPrice: 10.304,
  },
  "l64sv4": {
    linuxPrice: 8.63,
    windowsPrice: 11.574,
  },
  "l80asv3": {
    linuxPrice: 8.24,
    windowsPrice: 11.92,
  },
  "l80asv4": {
    linuxPrice: 9.064,
    windowsPrice: 12.744,
  },
  "l80sv3": {
    linuxPrice: 9.2,
    windowsPrice: 12.88,
  },
  "l80sv4": {
    linuxPrice: 10.788,
    windowsPrice: 14.468,
  },
  "l8aosv4": {
    linuxPrice: 1.192,
    windowsPrice: 1.56,
  },
  "l8asv3": {
    linuxPrice: 0.824,
    windowsPrice: 1.192,
  },
  "l8asv4": {
    linuxPrice: 0.906,
    windowsPrice: 1.274,
  },
  "l8sv3": {
    linuxPrice: 0.92,
    windowsPrice: 1.288,
  },
  "l8sv4": {
    linuxPrice: 1.079,
    windowsPrice: 1.447,
  },
  "l96asv4": {
    linuxPrice: 10.877,
    windowsPrice: 15.293,
  },
  "l96sv4": {
    linuxPrice: 12.946,
    windowsPrice: 17.362,
  },
  "m128": {
    linuxPrice: 24.1775,
    windowsPrice: 27.168,
  },
  "m128bds3v3": {
    linuxPrice: 71.238,
    windowsPrice: 77.126,
  },
  "m128bdsv3": {
    linuxPrice: 18.1505,
    windowsPrice: 24.0385,
  },
  "m128bsv3": {
    linuxPrice: 17.298,
    windowsPrice: 23.186,
  },
  "m128dmsv2": {
    linuxPrice: 42.704,
    windowsPrice: 48.592,
  },
  "m128dsv2": {
    linuxPrice: 21.344,
    windowsPrice: 27.232,
  },
  "m128m": {
    linuxPrice: 48.37625,
    windowsPrice: 48.458,
  },
  "m128ms": {
    linuxPrice: 48.37625,
    windowsPrice: 48.458,
  },
  "m128msv2": {
    linuxPrice: 42.031,
    windowsPrice: 47.919,
  },
  "m128s": {
    linuxPrice: 24.1775,
    windowsPrice: 27.168,
  },
  "m128sv2": {
    linuxPrice: 20.671,
    windowsPrice: 26.559,
  },
  "m12dsv3": {
    linuxPrice: 2.5296,
    windowsPrice: 3.0816,
  },
  "m12sv3": {
    linuxPrice: 2.3808,
    windowsPrice: 2.9328,
  },
  "m16": {
    linuxPrice: 5.569875,
    windowsPrice: 5.636,
  },
  "m16bdsv3": {
    linuxPrice: 2.263,
    windowsPrice: 2.999,
  },
  "m16bsv3": {
    linuxPrice: 2.17,
    windowsPrice: 2.906,
  },
  "m16ms": {
    linuxPrice: 5.569875,
    windowsPrice: 5.636,
  },
  "m176": {
    linuxPrice: 24.9705,
    windowsPrice: 31.873,
  },
  "m176bds4v3": {
    linuxPrice: 97.3865,
    windowsPrice: 105.4825,
  },
  "m176bdsv3": {
    linuxPrice: 24.9705,
    windowsPrice: 33.0665,
  },
  "m176bsv3": {
    linuxPrice: 23.777,
    windowsPrice: 31.873,
  },
  "m176ds3v3": {
    linuxPrice: 29.44876,
    windowsPrice: 37.54476,
  },
  "m176ds4v3": {
    linuxPrice: 41.02168,
    windowsPrice: 49.11768,
  },
  "m176s3v3": {
    linuxPrice: 27.71648,
    windowsPrice: 35.81248,
  },
  "m176s4v3": {
    linuxPrice: 38.60864,
    windowsPrice: 46.70464,
  },
  "m192idmsv2": {
    linuxPrice: 51.302,
    windowsPrice: 60.134,
  },
  "m192idsv2": {
    linuxPrice: 25.651,
    windowsPrice: 34.483,
  },
  "m192imsv2": {
    linuxPrice: 50.629,
    windowsPrice: 59.461,
  },
  "m192isv2": {
    linuxPrice: 24.978,
    windowsPrice: 33.81,
  },
  "m208msv2": {
    linuxPrice: 69.161,
    windowsPrice: 78.729,
  },
  "m208sv2": {
    linuxPrice: 34.58,
    windowsPrice: 44.148,
  },
  "m24dsv3": {
    linuxPrice: 5.0592,
    windowsPrice: 6.1632,
  },
  "m24sv3": {
    linuxPrice: 4.7616,
    windowsPrice: 5.8656,
  },
  "m32": {
    linuxPrice: 11.139625,
    windowsPrice: 11.272,
  },
  "m32bdsv3": {
    linuxPrice: 4.5415,
    windowsPrice: 6.0135,
  },
  "m32bsv3": {
    linuxPrice: 4.3245,
    windowsPrice: 5.7965,
  },
  "m32dmsv2": {
    linuxPrice: 9.834,
    windowsPrice: 11.306,
  },
  "m32ls": {
    linuxPrice: 3.806725,
    windowsPrice: 5.278725,
  },
  "m32ms": {
    linuxPrice: 11.139625,
    windowsPrice: 11.272,
  },
  "m32msv2": {
    linuxPrice: 9.665,
    windowsPrice: 11.137,
  },
  "m32ts": {
    linuxPrice: 3.586775,
    windowsPrice: 5.058775,
  },
  "m416msv2": {
    linuxPrice: 153.68,
    windowsPrice: 172.82,
  },
  "m416s8v2": {
    linuxPrice: 102.47,
    windowsPrice: 121.61,
  },
  "m416sv2": {
    linuxPrice: 76.849,
    windowsPrice: 95.985,
  },
  "m48bdsv3": {
    linuxPrice: 6.8045,
    windowsPrice: 9.0125,
  },
  "m48bsv3": {
    linuxPrice: 6.479,
    windowsPrice: 8.687,
  },
  "m48ds1v3": {
    linuxPrice: 10.26596,
    windowsPrice: 12.47396,
  },
  "m48s1v3": {
    linuxPrice: 9.66208,
    windowsPrice: 11.87008,
  },
  "m64": {
    linuxPrice: 12.08875,
    windowsPrice: 13.584,
  },
  "m6432bds1v3": {
    linuxPrice: 35.619,
    windowsPrice: 38.563,
  },
  "m64bds1v3": {
    linuxPrice: 35.619,
    windowsPrice: 38.563,
  },
  "m64bdsv3": {
    linuxPrice: 9.083,
    windowsPrice: 12.027,
  },
  "m64bsv3": {
    linuxPrice: 8.649,
    windowsPrice: 11.593,
  },
  "m64dmsv2": {
    linuxPrice: 16.544,
    windowsPrice: 19.488,
  },
  "m64dsv2": {
    linuxPrice: 10.67,
    windowsPrice: 13.614,
  },
  "m64ls": {
    linuxPrice: 7.174875,
    windowsPrice: 10.118875,
  },
  "m64m": {
    linuxPrice: 18.7375,
    windowsPrice: 19.434,
  },
  "m64ms": {
    linuxPrice: 18.7375,
    windowsPrice: 19.434,
  },
  "m64msv2": {
    linuxPrice: 16.207,
    windowsPrice: 19.151,
  },
  "m64s": {
    linuxPrice: 12.08875,
    windowsPrice: 13.584,
  },
  "m64sv2": {
    linuxPrice: 10.334,
    windowsPrice: 13.278,
  },
  "m8": {
    linuxPrice: 2.784875,
    windowsPrice: 2.818,
  },
  "m8ms": {
    linuxPrice: 2.784875,
    windowsPrice: 2.818,
  },
  "m96": {
    linuxPrice: 53.4285,
    windowsPrice: 0,
  },
  "m96bds2v3": {
    linuxPrice: 53.4285,
    windowsPrice: 57.8445,
  },
  "m96bdsv3": {
    linuxPrice: 13.6245,
    windowsPrice: 18.0405,
  },
  "m96bsv3": {
    linuxPrice: 12.9735,
    windowsPrice: 17.3895,
  },
  "m96ds1v3": {
    linuxPrice: 15.3884,
    windowsPrice: 19.8044,
  },
  "m96ds2v3": {
    linuxPrice: 20.51084,
    windowsPrice: 24.92684,
  },
  "m96s1v3": {
    linuxPrice: 14.4832,
    windowsPrice: 18.8992,
  },
  "m96s2v3": {
    linuxPrice: 19.30432,
    windowsPrice: 23.72032,
  },
  "nc12sv3": {
    linuxPrice: 9.486,
    windowsPrice: 10.038,
  },
  "nc24rsv3": {
    linuxPrice: 20.869,
    windowsPrice: 21.973,
  },
  "nc24sv3": {
    linuxPrice: 18.972,
    windowsPrice: 20.076,
  },
  "nc6sv3": {
    linuxPrice: 4.743,
    windowsPrice: 5.019,
  },
  "nv12adsv5": {
    linuxPrice: 1.407,
    windowsPrice: 1.959,
  },
  "nv18adsv5": {
    linuxPrice: 2.48,
    windowsPrice: 3.308,
  },
  "nv36admsv5": {
    linuxPrice: 7.006,
    windowsPrice: 8.662,
  },
  "nv36adsv5": {
    linuxPrice: 4.96,
    windowsPrice: 6.616,
  },
  "nv6adsv5": {
    linuxPrice: 0.704,
    windowsPrice: 0.98,
  },
  "nv72adsv5": {
    linuxPrice: 10.106,
    windowsPrice: 13.418,
  },
};
